import type { TFunction } from "i18next";
export function currencyWorkspaceLabels(t: TFunction) {
  return {
    needsCheck: t("currencyWorkspaceUx.needsCheck"),
    eyebrow: t("currencyWorkspaceUx.eyebrow"),
    title: t("currencyWorkspaceUx.title"),
    description: t("currencyWorkspaceUx.description"),
    current: t("currencyWorkspaceUx.current"),
    choose: t("currencyWorkspaceUx.choose"),
    sar: t("currencyWorkspaceUx.sar"),
    usd: t("currencyWorkspaceUx.usd"),
    example: t("currencyWorkspaceUx.example"),
    exampleHint: t("currencyWorkspaceUx.exampleHint"),
    impactTitle: t("currencyWorkspaceUx.impactTitle"),
    impactDisplay: t("currencyWorkspaceUx.impactDisplay"),
    impactAmounts: t("currencyWorkspaceUx.impactAmounts"),
    impactRecords: t("currencyWorkspaceUx.impactRecords"),
    readonly: t("currencyWorkspaceUx.readonly"),
    unknown: t("currencyWorkspaceUx.unknown"),
    unknownShort: t("currencyWorkspaceUx.unknownShort"),
    save: t("currencyWorkspaceUx.save"),
    saving: t("currencyWorkspaceUx.saving"),
    dirty: t("currencyWorkspaceUx.dirty"),
    inSync: t("currencyWorkspaceUx.inSync"),
    refresh: t("currencyWorkspaceUx.refresh"),
    discard: t("currencyWorkspaceUx.discard"),
    check: t("currencyWorkspaceUx.check"),
    saved: t("currencyWorkspaceUx.saved"),
    noChanges: t("currencyWorkspaceUx.noChanges"),
    verified: t("currencyWorkspaceUx.verified"),
    different: t("currencyWorkspaceUx.different"),
    conflict: t("currencyWorkspaceUx.conflict"),
    uncertain: t("currencyWorkspaceUx.uncertain"),
    failedRead: t("currencyWorkspaceUx.failedRead"),
  };
}
