import type { TFunction } from "i18next";
export const notificationPreferenceLabels = (t: TFunction) => ({
  unsavedDefaults: t("notificationPreferenceUx.unsavedDefaults"),
  title: t("notificationPreferenceUx.title"),
  help: t("notificationPreferenceUx.help"),
  method: t("notificationPreferenceUx.method"),
  methodHelp: t("notificationPreferenceUx.methodHelp"),
  push: t("notificationPreferenceUx.push"),
  email: t("notificationPreferenceUx.email"),
  both: t("notificationPreferenceUx.both"),
  types: t("notificationPreferenceUx.types"),
  newOrdersEnabled: t("notificationPreferenceUx.newOrdersEnabled"),
  newMessagesEnabled: t("notificationPreferenceUx.newMessagesEnabled"),
  appointmentsEnabled: t("notificationPreferenceUx.appointmentsEnabled"),
  orderStatusEnabled: t("notificationPreferenceUx.orderStatusEnabled"),
  missedMessagesEnabled: t("notificationPreferenceUx.missedMessagesEnabled"),
  whatsappDisconnectEnabled: t(
    "notificationPreferenceUx.whatsappDisconnectEnabled"
  ),
  quiet: t("notificationPreferenceUx.quiet"),
  quietHoursEnabled: t("notificationPreferenceUx.quietHoursEnabled"),
  quietHoursStart: t("notificationPreferenceUx.quietHoursStart"),
  quietHoursEnd: t("notificationPreferenceUx.quietHoursEnd"),
  zone: t("notificationPreferenceUx.zone"),
  quietHelp: t("notificationPreferenceUx.quietHelp"),
  overnight: t("notificationPreferenceUx.overnight"),
  save: t("notificationPreferenceUx.save"),
  saving: t("notificationPreferenceUx.saving"),
  saved: t("notificationPreferenceUx.saved"),
  noChanges: t("notificationPreferenceUx.noChanges"),
  dirty: t("notificationPreferenceUx.dirty"),
  current: t("notificationPreferenceUx.current"),
  defaults: t("notificationPreferenceUx.defaults"),
  readonly: t("notificationPreferenceUx.readonly"),
  invalid: t("notificationPreferenceUx.invalid"),
  unknown: t("notificationPreferenceUx.unknown"),
  fieldError: t("notificationPreferenceUx.fieldError"),
  duplicate: t("notificationPreferenceUx.duplicate"),
  legacy: t("notificationPreferenceUx.legacy"),
  legacyHelp: t("notificationPreferenceUx.legacyHelp"),
  instantNotifications: t("notificationPreferenceUx.instantNotifications"),
  batchNotifications: t("notificationPreferenceUx.batchNotifications"),
  batchInterval: t("notificationPreferenceUx.batchInterval"),
  on: t("notificationPreferenceUx.on"),
  off: t("notificationPreferenceUx.off"),
  unknownShort: t("notificationPreferenceUx.unknownShort"),
  refresh: t("notificationPreferenceUx.refresh"),
  discard: t("notificationPreferenceUx.discard"),
  check: t("notificationPreferenceUx.check"),
  uncertain: t("notificationPreferenceUx.uncertain"),
  conflict: t("notificationPreferenceUx.conflict"),
  different: t("notificationPreferenceUx.different"),
  checking: t("notificationPreferenceUx.checking"),
  failedRead: t("notificationPreferenceUx.failedRead"),
});
