import {promotionWorkspaceInput,promotionWorkspaceSchema,promotionStates,promotionTypes,promotionScopes,type PromotionSelection,type PromotionWorkspaceRow} from '@shared/promotion-workspace';
import {promotionActionTarget,promotionActionReview,promotionActionResult,promotionCancelledReceipt,type PromotionActionTarget} from '@shared/promotion-actions';
export const promotionSelectionKey=(s:PromotionSelection)=>JSON.stringify([s.query,s.state,s.type,s.scope,s.page]);
export function promotionNavigation(search:string){const p=new URLSearchParams(search),page=p.get('page');return promotionWorkspaceInput.parse({query:(p.get('q')??'').trim().slice(0,100),state:promotionStates.includes(p.get('state') as any)?p.get('state'):'all',type:promotionTypes.includes(p.get('type') as any)?p.get('type'):'all',scope:promotionScopes.includes(p.get('scope') as any)?p.get('scope'):'any',page:page&&/^[1-9]\d*$/.test(page)&&Number(page)<=1000000?Number(page):1});}
export function scopedPromotionWorkspace(raw:unknown,a:number,m:number,s:PromotionSelection){const p=promotionWorkspaceSchema.safeParse(raw);return p.success&&p.data.actorId===a&&p.data.merchantId===m&&promotionSelectionKey(p.data.selection)===promotionSelectionKey(s)?p.data:null;}
export function scopedPromotionReview(raw:unknown,a:number,m:number,target:PromotionActionTarget){const p=promotionActionReview.safeParse(raw),t=promotionActionTarget.parse(target);return p.success&&p.data.actorId===a&&p.data.merchantId===m&&JSON.stringify(p.data.target)===JSON.stringify(t)&&(t.action==='create'||p.data.before?.id===(t.action==='update'?t.data.id:t.id))?p.data:null;}
export function scopedPromotionResult(raw:unknown,a:number,m:number,requestKey:string,target?:PromotionActionTarget){const p=promotionActionResult.safeParse(raw);return p.success&&p.data.actorId===a&&p.data.merchantId===m&&p.data.requestKey===requestKey&&(!target||p.data.action===target.action&&(target.action==='create'||p.data.id===(target.action==='update'?target.data.id:target.id))&&(target.action!=='toggle'||p.data.active===target.enabled))?p.data:null;}
export const promotionDefinitionKey=(r:PromotionWorkspaceRow)=>JSON.stringify(Object.entries(r).filter(([k])=>!['revision','viewCount','clickCount','updatedAt','state','issues'].includes(k)));
export const promotionLocalTime=(v:string|null)=>v?new Date(Date.parse(v)+10800000).toISOString().slice(0,19):'';
export const promotionFormFields=['title','description','type','value','scope','productIds','categoryIds','minOrderAmount','minQuantity','startsAt','expiresAt','bannerImageUrl','autoCodeType','autoCodeValue'] as const;
export type PromotionForm=Record<typeof promotionFormFields[number],string>&{autoGenerateCode:boolean};
export function promotionForm(row?:PromotionWorkspaceRow):PromotionForm{
 const ids=(raw:string|null|undefined,parsed:number[]|null|undefined)=>parsed?parsed.join(', '):raw??'';
 return {title:row?.title??'',description:row?.description??'',type:row?row.type??'':'percentage',value:row?.value?.toString()??'',scope:row?row.scope??'':'all',productIds:ids(row?.productIds,row?.productIdsParsed),categoryIds:ids(row?.categoryIds,row?.categoryIdsParsed),minOrderAmount:row?.minOrderAmount?.toString()??'',minQuantity:row?.minQuantity?.toString()??'',startsAt:promotionLocalTime(row?.startsAt??null),expiresAt:promotionLocalTime(row?.expiresAt??null),bannerImageUrl:row?.bannerImageUrl??'',autoGenerateCode:false,autoCodeType:'percentage',autoCodeValue:''};
}
export function promotionFormTarget(form:PromotionForm,row?:PromotionWorkspaceRow){
 const original=form;
 form={...form};for(const k of ['value','minOrderAmount','minQuantity','autoCodeValue','productIds','categoryIds'] as const)form[k]=form[k].replace(/[٠-٩]/g,v=>String(v.charCodeAt(0)-1632)).replace(/[۰-۹]/g,v=>String(v.charCodeAt(0)-1776));
 const errors:Partial<Record<keyof PromotionForm,'fieldRequired'|'fieldNumber'|'fieldIds'|'fieldDates'|'fieldUrl'|'fieldInvalid'>>={},data:any={},initial=promotionForm(row);
 data.title=form.title.trim();if(!data.title||data.title.length>255)errors.title='fieldRequired';
 data.description=form.description||null;if(form.description.length>65535)errors.description='fieldInvalid';
 data.type=form.type;data.scope=form.scope;if(!promotionTypes.includes(form.type as any))errors.type='fieldRequired';if(!promotionScopes.includes(form.scope as any))errors.scope='fieldRequired';
 for(const [key,min,max] of [['value',form.type==='percentage'||form.type==='fixed'?1:0,form.type==='percentage'?100:100000],['minOrderAmount',0,1000000],['minQuantity',1,10000]] as const){const s=form[key].trim();data[key]=s===''?null:Number(s);if(s!==''&&(!/^\d+$/.test(s)||!Number.isInteger(data[key])||data[key]<min||data[key]>max)||key==='value'&&['percentage','fixed'].includes(form.type)&&s==='')errors[key]='fieldNumber';}
 for(const key of ['productIds','categoryIds'] as const){const s=form[key].trim(),parts=s?s.split(/[,،\s]+/).filter(Boolean):[],ids=parts.map(Number);if(parts.some(v=>!/^\d+$/.test(v))||ids.some(n=>!Number.isInteger(n)||n<=0||n>2147483647)||new Set(ids).size!==ids.length||ids.length>1000||!ids.length&&form.scope===(key==='productIds'?'products':'categories'))errors[key]='fieldIds';data[key]=s?JSON.stringify(ids):null;}
 for(const key of ['startsAt','expiresAt'] as const){const s=form[key];data[key]=null;if(s){const iso=new Date(s+'+03:00');if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2})?$/.test(s)||!Number.isFinite(iso.getTime())||promotionLocalTime(iso.toISOString()).slice(0,s.length)!==s||iso.getUTCFullYear()<1971||iso.getUTCFullYear()>2037)errors[key]='fieldInvalid';else data[key]=iso.toISOString();}}
 if(data.startsAt&&data.expiresAt&&data.startsAt>=data.expiresAt)errors.expiresAt='fieldDates';
 data.bannerImageUrl=form.bannerImageUrl.trim()||null;if(data.bannerImageUrl){try{const u=new URL(data.bannerImageUrl);if(data.bannerImageUrl.length>500||u.protocol!=='https:'||u.username||u.password||u.hash||u.port&&u.port!=='443'||!u.hostname.includes('.')||/[\[\]:]/.test(u.hostname)||/^[\d.]+$/.test(u.hostname)||/(?:\.local|\.localhost|\.internal|\.test)$/.test(u.hostname))errors.bannerImageUrl='fieldUrl';}catch{errors.bannerImageUrl='fieldUrl';}}
 if(!row&&form.autoGenerateCode){data.autoGenerateCode=true;data.autoCodeType=form.autoCodeType;data.autoCodeValue=Number(form.autoCodeValue);if(!['percentage','fixed'].includes(form.autoCodeType))errors.autoCodeType='fieldInvalid';if(!/^\d+$/.test(form.autoCodeValue)||data.autoCodeValue<1||data.autoCodeValue>(form.autoCodeType==='percentage'?100:100000))errors.autoCodeValue='fieldNumber';}
 if(!row&&form.autoGenerateCode){if(form.scope!=='all')errors.scope='fieldInvalid';if(data.startsAt&&Date.parse(data.startsAt)>Date.now())errors.startsAt='fieldInvalid';if(data.minQuantity!==null&&data.minQuantity>1)errors.minQuantity='fieldInvalid';if(data.expiresAt&&Date.parse(data.expiresAt)<=Date.now())errors.expiresAt='fieldInvalid';}
 if(Object.keys(errors).length)return {target:null,errors};
 if(row){for(const k of Object.keys(data))if(original[k as keyof PromotionForm]===initial[k as keyof PromotionForm])delete data[k];if(!Object.keys(data).length)return {target:null,errors,noChanges:true};data.id=row.id;}
 const result=promotionActionTarget.safeParse({action:row?'update':'create',data});return result.success?{target:result.data,errors}:{target:null,errors:{title:'fieldInvalid' as const}};
}
export const promotionReceiptStorageKey=(actorId:number,merchantId:number)=>`sary:promotion-pending:${actorId}:${merchantId}`;
export function scopedPromotionCancellation(raw:unknown,actorId:number,merchantId:number,requestKey:string){const p=promotionCancelledReceipt.safeParse(raw);return p.success&&p.data.actorId===actorId&&p.data.merchantId===merchantId&&p.data.requestKey===requestKey?p.data:null;}
