import { useEffect, useState } from 'react';
import { Link, useLocation, useSearch } from 'wouter';
import { useTranslation } from 'react-i18next';
import { CalendarDays, Plus, RefreshCw } from 'lucide-react';
import { trpc } from '@/lib/trpc';
import { bookingWorkspaceSchema, bookingDetailsSchema, bookingWorkspaceInput } from '@shared/booking-workspace';
import { bookingNavigation, bookingHref } from '@/lib/booking-workspace';
import { bookingWorkspaceLabels } from '@/lib/booking-workspace-labels';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { BookingOperations } from '@/components/BookingOperations';
import { BookingPaymentLinkRenewal } from '@/components/BookingPaymentLinkRenewal';
import { BookingCheckoutAttempts } from '@/components/BookingCheckoutAttempts';
import { BookingCreateWorkspace } from './BookingCreateWorkspace';
import { WorkspaceState, workspaceFailureKind } from './WorkspaceState';
import '@/styles/service-catalog-workspace.css';
import '@/styles/service-editor-workspace.css';
import '@/styles/booking-workspace.css';

export function BookingWorkspace({actorId,merchantId}:{actorId:number;merchantId:number}) {
  const {t,i18n}=useTranslation(),text=bookingWorkspaceLabels(t),[path,navigate]=useLocation(),search=useSearch(),nav=bookingNavigation(search),selection=nav.selection;
  const [filters,setFilters]=useState({q:selection?.search??'',status:selection?.status??'all',payment:selection?.payment??'all',from:selection?.startDate??'',to:selection?.endDate??''}),[filterError,setFilterError]=useState(false);
  useEffect(()=>{const parsed=bookingNavigation(search).selection;if(parsed)setFilters({q:parsed.search,status:parsed.status,payment:parsed.payment,from:parsed.startDate??'',to:parsed.endDate??''});setFilterError(false);},[search]);
  const query=trpc.bookings.workspace.useQuery(selection??{}, {enabled:!!selection&&(nav.view==='list'||nav.view==='new'),retry:false,staleTime:0,refetchOnMount:'always'});
  const parsed=bookingWorkspaceSchema.safeParse(query.data),data=!query.error&&parsed.success&&parsed.data.actorId===actorId&&parsed.data.merchantId===merchantId&&JSON.stringify(parsed.data.selection)===JSON.stringify(selection)?parsed.data:null;
  const change=(patch:Record<string,string|number|null>)=>navigate(bookingHref(path,search,patch)),reset=()=>change({q:null,status:null,payment:null,from:null,to:null,service:null,staff:null,page:null,booking:null});
  if(!selection||nav.view==='invalid')return <WorkspaceState kind="error" onRetry={reset}/>;
  if(typeof nav.view==='number')return <BookingDetail key={`${actorId}:${merchantId}:${nav.view}`} actorId={actorId} merchantId={merchantId} id={nav.view} back={()=>change({booking:null})}/>;
  if(nav.view==='new')return <BookingCreateWorkspace key={`${actorId}:${merchantId}:new`} actorId={actorId} merchantId={merchantId} canManage={!!data?.canManage} current={!!data&&!query.isFetching} refresh={()=>{void query.refetch();}} leave={()=>change({booking:null})} saved={id=>change({booking:id})}/>;
  if(query.error)return <WorkspaceState kind={workspaceFailureKind(query.error)} onRetry={()=>{void query.refetch();}}/>;
  if(!data)return <WorkspaceState kind={query.isFetching?'loading':'error'} onRetry={()=>{void query.refetch();}}/>;
  const number=(n:number)=>new Intl.NumberFormat(i18n.language).format(n),money=(n:number|null)=>n===null?text('missingAmount'):new Intl.NumberFormat(i18n.language,{style:'currency',currency:'SAR'}).format(n/100),s=data.summary;
  return <div className="service-catalog booking-workspace" dir={i18n.language.startsWith('ar')?'rtl':'ltr'}>
    <header className="sc-header"><div><p className="sc-eyebrow">{text('eyebrow')}</p><h1>{text('title')}</h1><p>{text('description')}</p></div><div className="sc-actions"><Button variant="outline" disabled={query.isFetching} onClick={()=>{void query.refetch();}}><RefreshCw aria-hidden="true"/>{text('refresh')}</Button>{data.canManage&&<Button onClick={()=>change({booking:'new'})}><Plus aria-hidden="true"/>{text('create')}</Button>}</div></header>
    <nav className="sc-nav"><Link href="/merchant/services">{text('services')}</Link><Link href="/merchant/staff">{text('providers')}</Link><Link href="/merchant/calendar">{text('calendar')}</Link></nav>
    {!data.canManage&&<p className="sc-feedback">{text('readOnly')}</p>}
    <div><dl className="sc-summary"><div><dt>{text('total')}</dt><dd>{number(s.total)}</dd></div><div><dt>{text('active')}</dt><dd>{number(s.counts.pending+s.counts.confirmed)}</dd></div><div><dt>{text('paidValue')}</dt><dd className="bw-amount">{money(s.paidValue.minor)}</dd></div></dl><p className="sc-muted bw-summary-hint">{text('summaryHint')}</p>{s.paidValue.invalid>0&&<p className="sc-feedback">{text('invalidAmounts',{count:number(s.paidValue.invalid)})}</p>}</div>
    <section className="sc-list"><form className="sc-filters bw-filters" onSubmit={event=>{event.preventDefault();const checked=bookingWorkspaceInput.safeParse({search:filters.q,status:filters.status,payment:filters.payment,startDate:filters.from||undefined,endDate:filters.to||undefined});if(!checked.success){setFilterError(true);return;}change({...filters,page:null});}}>
      <label className="sc-search"><span>{text('search')}</span><input value={filters.q} maxLength={200} placeholder={text('searchHint')} onChange={event=>setFilters(f=>({...f,q:event.target.value}))}/></label>
      <label><span>{text('status')}</span><select value={filters.status} onChange={event=>setFilters(f=>({...f,status:event.target.value as typeof f.status}))}>{(['all','pending','confirmed','in_progress','completed','cancelled','no_show','unknown'] as const).map(key=><option key={key} value={key}>{text(key)}</option>)}</select></label>
      <label><span>{text('payment')}</span><select value={filters.payment} onChange={event=>setFilters(f=>({...f,payment:event.target.value as typeof f.payment}))}>{(['all','unpaid','paid','refunded','unknown'] as const).map(key=><option key={key} value={key}>{text(key)}</option>)}</select></label>
      {(['from','to'] as const).map(key=><label key={key}><span>{text(key)}</span><input type="date" value={filters[key]} onInput={event=>{const value=event.currentTarget.value;setFilters(f=>({...f,[key]:value}));}} aria-invalid={filterError} onChange={event=>{setFilterError(false);setFilters(f=>({...f,[key]:event.target.value}));}}/></label>)}<Button type="submit">{text('searchAction')}</Button><Button type="button" variant="ghost" onClick={reset}>{text('clear')}</Button>
    </form>{filterError&&<p role="alert" className="sc-feedback">{text('filterError')}</p>}
    {(selection.serviceId||selection.staffId)&&<p className="sc-feedback">{selection.serviceId&&<span>{text('service')} #{selection.serviceId}</span>}{selection.staffId&&<span>{text('staff')} #{selection.staffId}</span>}</p>}
    <p role="status" className="sc-results">{query.isFetching?text('loadingUpdate'):text('results',{count:number(s.total)})}</p>
    {!data.rows.length?<div className="sc-empty"><CalendarDays aria-hidden="true"/><h2>{text(selection.page>1?'outOfRange':'empty')}</h2><p>{text('emptyHint')}</p>{selection.page>1&&<Button onClick={()=>change({page:null})}>{text('first')}</Button>}</div>:<ul className="sc-records">{data.rows.map(row=><li key={row.id} className="sc-record" data-booking-id={row.id}><div className="sc-record-title"><div><p className="sc-muted">{text('bookingNumber',{id:row.id})}</p><h2>{row.customerName||row.customerPhone||text('none')}</h2></div><Badge>{text(row.status)}</Badge></div><p>{row.service.name??text('unavailable')}</p><dl className="sc-facts bw-facts"><div><dt>{text('bookingDate')}</dt><dd dir="ltr">{row.date??text('unknown')}<br/>{row.startTime??'—'} – {row.endTime??'—'}</dd></div><div><dt>{text('finalPrice')}</dt><dd>{money(row.finalPrice)}<br/><span className="sc-muted">{text(row.paymentStatus)}</span></dd></div><div><dt>{text('staff')}</dt><dd>{row.staff?row.staff.name??text('unavailable'):text('none')}</dd></div><div><dt>{text('customerPhone')}</dt><dd dir="ltr">{row.customerPhone??text('none')}</dd></div></dl>{row.issues.length>0&&<p className="sc-repair">{text('issues')}</p>}<div className="sc-record-actions"><Button variant="outline" onClick={()=>change({booking:row.id})}>{text('view')}</Button></div></li>)}</ul>}
    {data.pagination.pages>0&&<nav className="sc-pagination" aria-label={text('title')}><Button variant="outline" disabled={selection.page<=1||query.isFetching} onClick={()=>change({page:selection.page-1})}>{text('previous')}</Button><span>{text('page',{page:number(selection.page),pages:number(data.pagination.pages)})}</span><Button variant="outline" disabled={selection.page>=data.pagination.pages||query.isFetching} onClick={()=>change({page:selection.page+1})}>{text('next')}</Button></nav>}</section>
  </div>;
}

function BookingDetail({actorId,merchantId,id,back}:{actorId:number;merchantId:number;id:number;back:()=>void}) {
  const {t,i18n}=useTranslation(),text=bookingWorkspaceLabels(t),utils=trpc.useUtils(),[operations,setOperations]=useState(false),[payments,setPayments]=useState(false);
  const query=trpc.bookings.details.useQuery({bookingId:id},{retry:false,staleTime:0,refetchOnMount:'always'}),parsed=bookingDetailsSchema.safeParse(query.data);
  const data=!query.error&&parsed.success&&parsed.data.actorId===actorId&&parsed.data.merchantId===merchantId&&parsed.data.selection.bookingId===id?parsed.data:null;
  const refresh=async(deleted=false)=>{await utils.bookings.workspace.invalidate();await utils.bookings.getPaymentLinkRenewal.invalidate({bookingId:id});await utils.bookings.getCheckoutAttempts.invalidate({bookingId:id});if(deleted){back();return;}const result=await query.refetch();if(result.error)throw Error('Booking refresh unavailable');};
  if(query.error)return <WorkspaceState kind={workspaceFailureKind(query.error)} onRetry={()=>{void query.refetch();}}/>;
  if(!data)return <WorkspaceState kind={query.isFetching?'loading':'error'} onRetry={()=>{void query.refetch();}}/>;
  const b=data.booking,money=(n:number|null)=>n===null?text('missingAmount'):new Intl.NumberFormat(i18n.language,{style:'currency',currency:'SAR'}).format(n/100),date=(n:string|null)=>n?new Intl.DateTimeFormat(i18n.language,{dateStyle:'medium',timeStyle:'short'}).format(new Date(n)):text('none');
  const fact=(key:Parameters<typeof text>[0],value:React.ReactNode)=><div key={key}><dt>{text(key)}</dt><dd>{value??text('none')}</dd></div>;
  return <div className="service-catalog booking-workspace" dir={i18n.language.startsWith('ar')?'rtl':'ltr'}><header className="sc-header"><div><Button variant="ghost" onClick={back}>{text('back')}</Button><p className="sc-eyebrow">{text('detailsTitle')}</p><h1>{text('bookingNumber',{id})}</h1><div className="sc-actions"><Badge>{text(b.status)}</Badge><Badge variant="secondary">{text(b.paymentStatus)}</Badge></div></div><Button disabled={query.isFetching} variant="outline" onClick={()=>{void query.refetch();}}><RefreshCw aria-hidden="true"/>{text('refresh')}</Button></header>
    {!data.canManage&&<p className="sc-feedback">{text('readOnly')}</p>}{b.issues.length>0&&<p role="status" className="sc-feedback">{text('issues')}</p>}
    <section className="bw-panel"><h2>{text('customerSection')}</h2><dl className="bw-detail-facts">{fact('service',b.service.name??text('unavailable'))}{fact('staff',b.staff?b.staff.name??text('unavailable'):null)}{fact('customerName',b.customerName)}{fact('customerPhone',<bdi>{b.customerPhone}</bdi>)}{fact('customerEmail',<bdi>{b.customerEmail||text('none')}</bdi>)}{fact('bookingDate',b.date)}{fact('startTime',b.startTime)}{fact('endTime',b.endTime)}{fact('durationMinutes',b.durationMinutes)}{fact('bookingSource',text(b.bookingSource))}</dl></section>
    <section className="bw-panel"><h2>{text('priceSection')}</h2><dl className="bw-detail-facts">{fact('basePrice',money(b.basePrice))}{fact('discountAmount',money(b.discountAmount))}{fact('finalPrice',money(b.finalPrice))}{fact('payment',text(b.paymentStatus))}</dl><p className="sc-muted">{text('detailAmountHint')}</p></section>
    <section className="bw-panel"><h2>{text('notes')}</h2><p className="bw-notes">{b.notes||text('none')}</p>{(b.cancellationReason||b.cancelledBy)&&<dl className="bw-detail-facts">{fact('cancellationReason',b.cancellationReason)}{fact('cancelledBy',b.cancelledBy?text(b.cancelledBy):null)}</dl>}</section>
    {data.canManage&&<><details className="bw-panel" open={operations} onToggle={event=>setOperations(event.currentTarget.open)}><summary>{text('operations')}</summary><p className="sc-muted">{text('operationsHint')}</p>{operations&&(b.status==='unknown'||b.paymentStatus==='unknown'?<p>{text('issues')}</p>:<BookingOperations key={`${id}:${b.updatedAt}`} booking={{id,status:b.status,paymentStatus:b.paymentStatus}} onChanged={refresh}/>)}</details><details className="bw-panel" open={payments} onToggle={event=>setPayments(event.currentTarget.open)}><summary>{text('paymentTools')}</summary>{payments&&<div className="bw-tools"><BookingPaymentLinkRenewal bookingId={id} onRenewed={()=>refresh()}/><BookingCheckoutAttempts bookingId={id} onReviewed={()=>refresh()}/></div>}</details></>}
    <details className="bw-panel"><summary>{text('advanced')}</summary><p className="sc-muted">{text('storedHint')}</p><dl className="bw-detail-facts">{fact('customerAgreementId',b.customerAgreementId)}{fact('googleEventId',b.googleEventId)}{(['reminder24hSent','reminder1hSent'] as const).map(key=>fact(key,b[key]===null?text('unknown'):text(b[key]?'yes':'no')))}{(['createdAt','updatedAt','confirmedAt','completedAt','cancelledAt'] as const).map(key=>fact(key,date(b[key])))}</dl></details>
  </div>;
}
