import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { trpc } from '@/lib/trpc';
import { catalogEditorContextSchema } from '@shared/service-catalog-workspace';
import { emptyBookingDraft, parseBookingDraft, bookingEndTime, bookingMoney, type BookingDraft } from '@/lib/booking-workspace';
import { bookingWorkspaceLabels } from '@/lib/booking-workspace-labels';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { CatalogChoicePicker } from './CatalogChoicePicker';

export function BookingCreateWorkspace({actorId,merchantId,canManage,current,refresh,leave,saved}:{actorId:number;merchantId:number;canManage:boolean;current:boolean;refresh:()=>void;leave:()=>void;saved:(id:number)=>void}) {
  const {t,i18n}=useTranslation(),text=bookingWorkspaceLabels(t),[draft,setDraft]=useState({...emptyBookingDraft}),[errors,setErrors]=useState<Record<string,boolean>>({}),[names,setNames]=useState<{service:Record<number,string>;staff:Record<number,string>}>({service:{},staff:{}});
  const [dialog,setDialog]=useState<'review'|'leave'|null>(null),[busy,setBusy]=useState(false),[failure,setFailure]=useState<'error'|'conflict'|null>(null),[uncertain,setUncertain]=useState(false),[attempted,setAttempted]=useState(false);
  const live=useRef(true),lock=useRef(false),seeded=useRef<number|null>(null),heading=useRef<HTMLHeadingElement>(null),opener=useRef<HTMLElement|null>(null),reviewed=useRef('');
  const create=trpc.bookings.create.useMutation(),serviceQuery=trpc.services.catalogEditor.useQuery({entity:'service',id:draft.serviceId||undefined},{enabled:draft.serviceId>0,retry:false,staleTime:0,refetchOnMount:'always'});
  const parsedService=catalogEditorContextSchema.safeParse(serviceQuery.data),service=!serviceQuery.error&&parsedService.success&&parsedService.data.actorId===actorId&&parsedService.data.merchantId===merchantId&&parsedService.data.selection.id===draft.serviceId&&parsedService.data.record?.entity==='service'?parsedService.data.record:null;
  const settingsValid=!!service&&service.fields.isActive===true&&Number.isInteger(service.fields.durationMinutes)&&service.fields.durationMinutes!>=1&&service.fields.durationMinutes!<=1439;
  const dirty=JSON.stringify(draft)!==JSON.stringify(emptyBookingDraft),canSave=current&&canManage&&settingsValid&&!serviceQuery.isFetching&&!busy&&!uncertain;
  useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
  useEffect(()=>{if(!service||!settingsValid||seeded.current===draft.serviceId)return;seeded.current=draft.serviceId;setNames(previous=>({...previous,service:{...previous.service,[service.id]:service.fields.name}}));setDraft(previous=>({...previous,durationMinutes:String(service.fields.durationMinutes),endTime:bookingEndTime(previous.startTime,String(service.fields.durationMinutes)),basePrice:service.fields.priceType==='fixed'&&service.fields.basePrice!==null&&service.fields.basePrice>=0?(service.fields.basePrice/100).toFixed(2):'',discountAmount:'0'}));},[draft.serviceId,service?.definition,settingsValid]);
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  const patch=(key:keyof BookingDraft,value:string|number)=>{setDraft(previous=>{const next={...previous,[key]:value};if(key==='startTime'||key==='durationMinutes')next.endTime=bookingEndTime(next.startTime,next.durationMinutes);if(key==='endTime'&&next.startTime&&next.endTime>next.startTime){const minutes=(time:string)=>Number(time.slice(0,2))*60+Number(time.slice(3));next.durationMinutes=String(minutes(next.endTime)-minutes(next.startTime));}return next;});setErrors(previous=>({...previous,[key]:false}));};
  const open=(value:'review'|'leave')=>{opener.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setDialog(value);};
  const review=()=>{setAttempted(true);const checked=parseBookingDraft(draft),next={...checked.errors,...(!settingsValid?{serviceId:true}:{})};setErrors(next);if(!checked.data||Object.keys(next).length){queueMicrotask(()=>document.querySelector<HTMLElement>('.bw-form [aria-invalid="true"]')?.focus());return;}if(!canSave)return;reviewed.current=JSON.stringify(checked.data);open('review');};
  const confirm=async()=>{const checked=parseBookingDraft(draft);if(!canSave||!checked.data||reviewed.current!==JSON.stringify(checked.data)||lock.current)return;lock.current=true;setBusy(true);setFailure(null);try{const result=await create.mutateAsync(checked.data);if(result.success!==true||!Number.isInteger(result.bookingId)||result.bookingId<=0||result.bookingId>2147483647)throw Error('Invalid booking receipt');if(live.current){setDialog(null);saved(result.bookingId);}}catch(error){if(live.current){const code=(error as {data?:{code?:string}})?.data?.code;setFailure(code==='CONFLICT'?'conflict':'error');setUncertain(true);}}finally{lock.current=false;if(live.current)setBusy(false);}};
  const field=(key:Exclude<keyof BookingDraft,'serviceId'|'staffId'|'bookingSource'>,required=false)=>{
    const numeric=['durationMinutes','basePrice','discountAmount'].includes(key),invalid=!!errors[key],type=key==='bookingDate'?'date':key==='startTime'||key==='endTime'?'time':key==='customerEmail'?'email':key==='customerPhone'?'tel':'text';
    const error=text(key==='customerPhone'?'phoneError':key==='customerEmail'?'emailError':['startTime','endTime','durationMinutes'].includes(key)?'timeError':'invalid');
    const props={id:`bw-${key}`,value:draft[key],required,'aria-invalid':invalid,'aria-describedby':invalid?`bw-error-${key}`:undefined,onChange:(event:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>patch(key,event.target.value),onBlur:()=>{if(attempted)setErrors(parseBookingDraft(draft).errors);},maxLength:key==='notes'?2000:key==='customerName'||key==='customerEmail'?255:key==='customerPhone'?20:30};
    return <label className="bw-field" key={key}><span>{text(key)} {required?<span aria-hidden="true">*</span>:<small>{text('optional')}</small>}</span>{key==='notes'?<textarea {...props} rows={4}/>:<input {...props} type={type} onInput={type==='date'||type==='time'?event=>patch(key,event.currentTarget.value):undefined} inputMode={numeric?key==='durationMinutes'?'numeric':'decimal':key==='customerPhone'?'tel':undefined} dir={numeric||type!=='text'?'ltr':undefined}/ >}{invalid&&<span id={`bw-error-${key}`} role="alert" className="bw-error">{error}</span>}</label>;
  };
  const choose=(kind:'service'|'staff',ids:number[])=>{const id=ids.at(-1)??0;if(kind==='service'){seeded.current=null;setDraft(previous=>({...previous,serviceId:id,staffId:0}));}else patch('staffId',id);setErrors(previous=>({...previous,[kind+'Id']:false}));};
  const picker=(kind:'service'|'staff')=><div className="bw-field" tabIndex={-1} id={`bw-${kind}Id`} aria-invalid={!!errors[kind+'Id']}><h3>{text(kind)} {kind==='service'?'*':text('optional')}</h3><p className="sc-muted">{text(kind==='service'?'serviceHint':'staffHint')}</p><CatalogChoicePicker single actorId={actorId} merchantId={merchantId} kind={kind} selected={draft[kind+'Id' as 'serviceId'|'staffId']?[draft[kind+'Id' as 'serviceId'|'staffId']]:[]} names={names[kind]} disabled={!canManage||busy||uncertain} onChange={ids=>choose(kind,ids)} onNames={rows=>setNames(previous=>({...previous,[kind]:{...previous[kind],...Object.fromEntries(rows.map(row=>[row.id,row.name]))}}))}/>{errors[kind+'Id']&&<p role="alert" className="bw-error">{text('invalid')}</p>}</div>;
  const base=bookingMoney(draft.basePrice),discount=bookingMoney(draft.discountAmount),amount=base!==null&&discount!==null&&discount<=base?base-discount:null,money=amount===null?text('missingAmount'):new Intl.NumberFormat(i18n.language,{style:'currency',currency:'SAR'}).format(amount/100);
  const summary=<dl className="bw-detail-facts">{([['service',names.service[draft.serviceId]??text('none')],['staff',draft.staffId?names.staff[draft.staffId]??text('unavailable'):text('none')],['customerName',draft.customerName||text('none')],['customerPhone',draft.customerPhone],['customerEmail',draft.customerEmail||text('none')],['bookingDate',draft.bookingDate],['startTime',draft.startTime],['endTime',draft.endTime],['durationMinutes',draft.durationMinutes],['basePrice',draft.basePrice],['discountAmount',draft.discountAmount],['finalPrice',money],['bookingSource',text(draft.bookingSource as 'walk_in')],['notes',draft.notes||text('none')]] as const).map(([key,value])=><div key={key}><dt>{text(key)}</dt><dd>{value}</dd></div>)}</dl>;
  return <div className="service-catalog booking-workspace" dir={i18n.language.startsWith('ar')?'rtl':'ltr'}><header className="sc-header"><div><Button variant="ghost" disabled={busy} onClick={()=>dirty?open('leave'):leave()}>{text('back')}</Button><p className="sc-eyebrow">{text('eyebrow')}</p><h1>{text('create')}</h1><p>{text('createHint')}</p></div><Button variant="outline" disabled={busy||serviceQuery.isFetching} onClick={()=>{refresh();if(draft.serviceId)void serviceQuery.refetch();}}>{text('refresh')}</Button></header>
    {!current&&<p role="alert" className="sc-feedback">{text('sourceError')}</p>}{current&&!canManage&&<p className="sc-feedback">{text('readOnly')}</p>}{draft.serviceId>0&&!settingsValid&&!serviceQuery.isFetching&&<p className="sc-feedback" role="alert">{text('selectedServiceError')}</p>}
    {failure&&<p className="sc-feedback" role="alert">{text(failure)} <Button variant="outline" onClick={()=>open('leave')}>{text('checkList')}</Button></p>}
    <form className="bw-form" noValidate onSubmit={event=>{event.preventDefault();review();}}><fieldset disabled={!canManage||busy||uncertain}><section className="bw-panel"><h2>{text('service')}</h2>{picker('service')}{picker('staff')}</section><section className="bw-panel"><h2>{text('customerSection')}</h2><div className="bw-form-grid">{field('customerPhone',true)}{field('customerName')}{field('customerEmail')}{field('bookingDate',true)}{field('startTime',true)}{field('durationMinutes',true)}{field('endTime',true)}</div><p className="sc-muted">{text('timeError')}</p></section><section className="bw-panel"><h2>{text('priceSection')}</h2><p className="sc-muted">{text('priceHint')}</p><div className="bw-form-grid">{field('basePrice',true)}{field('discountAmount',true)}</div><dl className="bw-detail-facts"><div><dt>{text('finalPrice')}</dt><dd>{money}</dd></div></dl></section><section className="bw-panel"><h2>{text('notes')}</h2>{field('notes')}<label className="bw-field"><span>{text('bookingSource')}</span><select value={draft.bookingSource} onChange={event=>patch('bookingSource',event.target.value)}>{(['whatsapp','website','phone','walk_in'] as const).map(key=><option key={key} value={key}>{text(key)}</option>)}</select></label><p className="sc-muted">{text('sourceHint')}</p></section></fieldset><footer className="bw-save"><p role="status">{text(busy?'saving':uncertain?'error':'unsaved')}</p>{canManage&&<Button type="submit" disabled={!current||busy||uncertain||serviceQuery.isFetching}>{text('review')}</Button>}</footer></form>
    <Dialog open={!!dialog} onOpenChange={open=>{if(!open&&!busy)setDialog(null);}}><DialogContent className="sc-dialog booking-dialog" closeLabel={text('cancel')} showCloseButton={!busy} dir={i18n.language.startsWith('ar')?'rtl':'ltr'} onOpenAutoFocus={event=>{event.preventDefault();heading.current?.focus();}} onCloseAutoFocus={event=>{event.preventDefault();if(opener.current?.isConnected)opener.current.focus();}}><DialogHeader><DialogTitle ref={heading} tabIndex={-1}>{text(dialog==='review'?'reviewTitle':'leaveTitle')}</DialogTitle><DialogDescription>{text(dialog==='review'?'reviewHint':'leaveHint')}</DialogDescription></DialogHeader>{dialog==='review'&&<>{summary}{failure&&<p className="sc-feedback" role="alert">{text(failure)}</p>}{!current&&<p role="alert">{text('sourceError')}</p>}</>}<DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setDialog(null)}>{text('cancel')}</Button><Button disabled={busy||dialog==='review'&&!canSave} onClick={()=>{if(dialog==='review')void confirm();else leave();}}>{text(busy?'saving':dialog==='review'?'save':'leave')}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
