import {useRef,useState} from 'react';
import {trpc} from '@/lib/trpc';
import {Button} from '@/components/ui/button';
import {WorkspaceState,workspaceFailureKind} from './WorkspaceState';
import {calendlyFresh} from './CalendlyOperationPanel';
import {calendlyAppointmentsInput,calendlyReceiptsInput,calendlyAppointmentStates,calendlyReceiptStates,type CalendlyAppointments,type CalendlyReceipts} from '@shared/calendly-workspace';
import {scopedCalendlyAppointments,scopedCalendlyReceipts,scopedCalendlyLinks,calendlyDate} from '@/lib/calendly-workspace';
import type {CalendlyCopy} from '@/lib/calendly-workspace-labels';
type Props={actorId:number;merchantId:number;copy:CalendlyCopy;locale:'ar'|'en'};
function Pagination({value,c,locale,busy,change}:{value:{page:number;pages:number;total:number};c:CalendlyCopy;locale:string;busy:boolean;change:(page:number)=>void}){
 return <div className="cl-pagination"><p>{c.results}: {value.total.toLocaleString(locale)} · {c.page} {value.page.toLocaleString(locale)} {c.of} {Math.max(1,value.pages).toLocaleString(locale)}</p><div className="sc-actions"><Button variant="outline" disabled={busy||value.page<=1} onClick={()=>change(value.page-1)}>{c.previous}</Button><Button variant="outline" disabled={busy||value.page>=value.pages} onClick={()=>change(value.page+1)}>{c.next}</Button></div></div>;
}
export function CalendlyAppointmentsList({actorId,merchantId,copy:c,locale}:Props){
 const [input,setInput]=useState(()=>calendlyAppointmentsInput.parse({})),[draft,setDraft]=useState({search:'',state:'all',period:'all',startDate:'',endDate:''}),[error,setError]=useState<'invalidRange'|'searchTooLong'|null>(null);
 const form=useRef<HTMLFormElement>(null),heading=useRef<HTMLHeadingElement>(null),query=trpc.calendly.getAppointmentsWorkspace.useQuery(input,calendlyFresh),data=query.error?null:scopedCalendlyAppointments(query.data,actorId,merchantId,input);
 const date=(v:string|null)=>calendlyDate(v,locale,c.none);
 function apply(){const parsed=calendlyAppointmentsInput.safeParse({...draft,startDate:draft.startDate||undefined,endDate:draft.endDate||undefined,page:1});if(!parsed.success){const field=parsed.error.issues.some(i=>i.path[0]==='search')?'search':'startDate';setError(field==='search'?'searchTooLong':'invalidRange');form.current?.querySelector<HTMLInputElement>(`[name=${field}]`)?.focus();return;}setError(null);setInput(parsed.data);heading.current?.focus();}
 const change=(page:number)=>{setInput({...input,page});heading.current?.focus();};
 return <section className="cl-panel" aria-labelledby="cl-appointments"><h2 id="cl-appointments" ref={heading} tabIndex={-1}>{c.appointments}</h2><p className="sc-muted" id="cl-date-hint">{c.dateHint}</p><form ref={form} className="cl-form" noValidate onSubmit={e=>{e.preventDefault();apply();}}><label>{c.search}<input name="search" type="search" value={draft.search} maxLength={100} placeholder={c.searchAppointments} onChange={e=>setDraft({...draft,search:e.target.value})}/></label><div className="cl-dates"><label>{c.state}<select value={draft.state} onChange={e=>setDraft({...draft,state:e.target.value})}>{(['all',...calendlyAppointmentStates] as const).map(v=><option key={v} value={v}>{c[v]}</option>)}</select></label><label>{c.period}<select value={draft.period} onChange={e=>setDraft({...draft,period:e.target.value})}>{(['all','upcoming','past'] as const).map(v=><option key={v} value={v}>{c[v]}</option>)}</select></label>{(['startDate','endDate'] as const).map(field=><label key={field}>{field==='startDate'?c.start:c.end}<input name={field} type="date" value={draft[field]} aria-invalid={error==='invalidRange'} aria-describedby={error==='invalidRange'?'cl-filter-error':'cl-date-hint'} onChange={e=>{setDraft({...draft,[field]:e.target.value});setError(null);}}/></label>)}</div>{error&&<p className="cl-error" role="alert" id="cl-filter-error">{c[error]}</p>}<div className="sc-actions"><Button type="submit" disabled={query.isFetching}>{c.apply}</Button><Button variant="outline" type="button" disabled={query.isFetching} onClick={()=>{setDraft({search:'',state:'all',period:'all',startDate:'',endDate:''});setInput(calendlyAppointmentsInput.parse({}));setError(null);heading.current?.focus();}}>{c.reset}</Button><Button type="button" variant="outline" disabled={query.isFetching} onClick={()=>void query.refetch()}>{c.refresh}</Button></div></form>
 {query.isLoading?<WorkspaceState inline kind="loading"/>:!data?<WorkspaceState inline kind={workspaceFailureKind(query.error)} onRetry={()=>void query.refetch()}/>:<><div className="cl-groups"><span>{c.stored}: {data.summary.stored.toLocaleString(locale)}</span>{data.summary.groups.map(g=><span key={g.key}>{c[g.key]}: {g.count.toLocaleString(locale)}</span>)}</div>{!data.rows.length?<div className="cl-notice"><h3>{c.empty}</h3><p>{c.emptyHint}</p></div>:<ul className="cl-records">{data.rows.map(row=><Appointment key={row.id} row={row} c={c} date={date}/>)}</ul>}<Pagination value={data.pagination} c={c} locale={locale} busy={query.isFetching} change={change}/></>}
 </section>;
}
function Appointment({row:r,c,date}:{row:CalendlyAppointments['rows'][number];c:CalendlyCopy;date:(v:string|null)=>string}){
 return <li data-calendly-appointment={r.id}><header><h3>{r.eventName??c.none}</h3><span>{c[r.state]}</span></header><p>{r.customerName??c.none}</p><p>{date(r.startAt)} · UTC</p>{r.invalidData&&<p className="cl-notice">{c.invalidData}</p>}<details><summary>{c.details}</summary><dl className="cl-facts"><div><dt>{c.email}</dt><dd><bdi>{r.customerEmail??c.none}</bdi></dd></div><div><dt>{c.phone}</dt><dd><bdi>{r.customerPhone??c.none}</bdi></dd></div><div><dt>{c.location}</dt><dd>{r.location??c.none}</dd></div>{(['startAt','endAt','cancelledAt','providerUpdatedAt'] as const).map(key=><div key={key}><dt>{c[key]}</dt><dd>{date(r[key])}</dd></div>)}<div><dt>{c.confirmations}</dt><dd>{r.confirmationAcceptedAt?`${c.confirmationAccepted} · ${date(r.confirmationAcceptedAt)}`:c.confirmationNotAccepted}</dd></div></dl><p className="sc-muted">{c.acceptedHint}</p></details></li>;
}
export function CalendlyReceiptsList({actorId,merchantId,copy:c,locale}:Props){
 const [input,setInput]=useState(()=>calendlyReceiptsInput.parse({})),[draft,setDraft]=useState({search:'',state:'all',event:'all'}),[error,setError]=useState(false),heading=useRef<HTMLHeadingElement>(null),search=useRef<HTMLInputElement>(null);
 const query=trpc.calendly.getReceiptsWorkspace.useQuery(input,calendlyFresh),data=query.error?null:scopedCalendlyReceipts(query.data,actorId,merchantId,input),date=(v:string|null)=>calendlyDate(v,locale,c.none);
 return <section className="cl-panel"><h2 ref={heading} tabIndex={-1}>{c.receipts}</h2><p className="sc-muted">{c.utc}</p><form className="cl-form" onSubmit={e=>{e.preventDefault();const p=calendlyReceiptsInput.safeParse({...draft,page:1});if(!p.success){setError(true);search.current?.focus();return;}setError(false);setInput(p.data);heading.current?.focus();}}><label>{c.search}<input ref={search} type="search" value={draft.search} maxLength={100} placeholder={c.searchReceipts} aria-invalid={error} aria-describedby={error?'cl-receipt-error':undefined} onChange={e=>{setDraft({...draft,search:e.target.value});setError(false);}}/></label><div className="cl-dates"><label>{c.state}<select value={draft.state} onChange={e=>setDraft({...draft,state:e.target.value})}>{(['all',...calendlyReceiptStates] as const).map(v=><option key={v} value={v}>{c[v]}</option>)}</select></label><label>{c.event}<select value={draft.event} onChange={e=>setDraft({...draft,event:e.target.value})}>{(['all','created','cancelled','unknown'] as const).map(v=><option key={v} value={v}>{c[v]}</option>)}</select></label></div>{error&&<p id="cl-receipt-error" role="alert">{c.searchTooLong}</p>}<div className="sc-actions"><Button disabled={query.isFetching} type="submit">{c.apply}</Button><Button variant="outline" disabled={query.isFetching} type="button" onClick={()=>{setDraft({search:'',state:'all',event:'all'});setInput(calendlyReceiptsInput.parse({}));setError(false);heading.current?.focus();}}>{c.reset}</Button><Button variant="outline" disabled={query.isFetching} type="button" onClick={()=>void query.refetch()}>{c.refresh}</Button></div></form>
 {query.isLoading?<WorkspaceState inline kind="loading"/>:!data?<WorkspaceState inline kind={workspaceFailureKind(query.error)} onRetry={()=>void query.refetch()}/>:<><div className="cl-groups"><span>{c.stored}: {data.summary.stored.toLocaleString(locale)}</span>{data.summary.groups.map(g=><span key={g.key}>{c[g.key]}: {g.count.toLocaleString(locale)}</span>)}</div>{!data.rows.length?<div className="cl-notice"><h3>{c.empty}</h3><p>{c.emptyHint}</p></div>:<ul className="cl-records">{data.rows.map(row=><Receipt key={row.id} row={row} c={c} date={date}/>)}</ul>}<Pagination value={data.pagination} c={c} locale={locale} busy={query.isFetching} change={page=>{setInput({...input,page});heading.current?.focus();}}/></>}
 </section>;
}
function Receipt({row:r,c,date}:{row:CalendlyReceipts['rows'][number];c:CalendlyCopy;date:(v:string|null)=>string}){const bool=(v:boolean|null)=>v===null?c.unknown:v?c.yes:c.no;return <li data-calendly-receipt={r.id}><header><h3>{c[r.event]} · <bdi>{r.id}</bdi></h3><span>{c[r.state]}</span></header><p>{date(r.createdAt)} · UTC</p>{r.invalidData&&<p>{c.invalidData}</p>}{r.hasError&&<p className="cl-notice">{c.receiptError}</p>}<details><summary>{c.details}</summary><dl className="cl-facts"><div><dt>{c.attempts}</dt><dd>{r.attempts??c.none}</dd></div><div><dt>{c.effectApplied}</dt><dd>{bool(r.effectApplied)}</dd></div><div><dt>{c.notificationRequired}</dt><dd>{bool(r.notificationRequired)}</dd></div>{(['availableAt','claimedAt','processedAt'] as const).map(key=><div key={key}><dt>{c[key]}</dt><dd>{date(r[key])}</dd></div>)}</dl></details></li>;}
export function CalendlyBookingLinks({actorId,merchantId,copy:c,locale,revision,ready}:Props&{revision:string;ready:boolean}){
 const query=trpc.calendly.getBookingLinksWorkspace.useQuery(undefined,{...calendlyFresh,enabled:ready}),data=query.error?null:scopedCalendlyLinks(query.data,actorId,merchantId,revision);
 return <section className="cl-panel"><h2>{c.links}</h2><p>{c.linksHint}</p>{!ready?<p>{c.notReady}</p>:query.isLoading?<WorkspaceState inline kind="loading"/>:!data?<WorkspaceState inline kind={workspaceFailureKind(query.error)} onRetry={()=>void query.refetch()}/>:<><p className="sc-muted">{c.checked}: {calendlyDate(data.checkedAt,locale,c.none)} · UTC</p>{!data.rows.length?<div className="cl-notice"><h3>{c.empty}</h3><p>{c.emptyHint}</p></div>:<ul className="cl-records">{data.rows.map((r,i)=><li key={i}><h3>{r.name??c.none}</h3><p>{r.duration===null?c.none:`${r.duration.toLocaleString(locale)} ${c.minutes}`}</p>{r.schedulingUrl?<Button variant="outline" asChild><a href={r.schedulingUrl} target="_blank" rel="noopener noreferrer">{c.openBooking}<span className="sr-only"> · {r.name??c.none}</span></a></Button>:<p>{c.linkUnavailable}</p>}</li>)}</ul>}<Button variant="outline" disabled={query.isFetching} onClick={()=>void query.refetch()}>{c.refresh}</Button></>}</section>;
}
