import {useEffect,useRef,useState} from 'react';
import {useLocation,useSearch} from 'wouter';
import {useTranslation} from 'react-i18next';
import {RefreshCw} from 'lucide-react';
import {trpc} from '@/lib/trpc';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {WorkspaceState,workspaceFailureKind} from './WorkspaceState';
import {CartSummary} from './CartSummary';
import {CartDiscountPicker} from './CartDiscountPicker';
import {cartWorkspaceLabels} from '@/lib/cart-workspace-labels';
import {cartNavigation,cartSelectionKey,scopedCartWorkspace,scopedCartReminder,scopedCartRecovery,scopedCartHistory,scopedCartReceipt,cartStamp,readCartTracking,saveCartTracking,clearCartTracking,type CartTracking} from '@/lib/cart-workspace';
import {catalogHref} from '@/lib/service-catalog-navigation';
import type {CartWorkspaceRow} from '@shared/abandoned-cart-workspace';
import type {CartReminderReview,CartReminderReceipt} from '@shared/abandoned-cart-reminder';
import type {DiscountWorkspaceRow} from '@shared/discount-workspace';
import '@/styles/service-catalog-workspace.css';
import '@/styles/discount-workspace.css';
import '@/styles/cart-workspace.css';
type Action={kind:'details'|'recover'|'remind';row:CartWorkspaceRow;recoveryReady?:boolean};
const emptyKey='00000000-0000-4000-8000-000000000000';
export function CartWorkspace({actorId,merchantId}:{actorId:number;merchantId:number}){
 const {t,i18n}=useTranslation(),c=cartWorkspaceLabels(t),locale=i18n.language.startsWith('ar')?'ar':'en';
 const [path,navigate]=useLocation(),search=useSearch(),params=new URLSearchParams(search),tab=params.get('tab')==='reminders'?'reminders':'carts',selection=cartNavigation(search),selectionKey=cartSelectionKey(selection),historyPage=/^[1-9]\d*$/.test(params.get('historyPage')??'')&&Number(params.get('historyPage'))<=1000000?Number(params.get('historyPage')):1;
 const query=trpc.abandonedCarts.workspace.useQuery(selection,{retry:false,staleTime:0,refetchOnMount:'always'}),historyQuery=trpc.abandonedCarts.reminderHistory.useQuery({page:historyPage},{retry:false,staleTime:0,refetchOnMount:'always',enabled:tab==='reminders'});
 const data=query.error?null:scopedCartWorkspace(query.data,actorId,merchantId,selection),history=historyQuery.error?null:scopedCartHistory(historyQuery.data,actorId,merchantId,historyPage);
 const reviewRecovery=trpc.abandonedCarts.reviewRecovery.useMutation({retry:false}),record=trpc.abandonedCarts.recordRecovery.useMutation({retry:false}),reviewMessage=trpc.abandonedCarts.reviewReminder.useMutation({retry:false}),send=trpc.abandonedCarts.sendReviewedReminder.useMutation({retry:false});
 const [initial]=useState(()=>{try{return {tracking:readCartTracking(localStorage,actorId,merchantId),error:false};}catch{return {tracking:null,error:true};}}),[tracking,setTracking]=useState<CartTracking|null>(initial.tracking),[storedReceipt,setStoredReceipt]=useState<CartReminderReceipt|null>(null),[storageFailed,setStorageFailed]=useState(initial.error);
 const receiptQuery=trpc.abandonedCarts.reminderReceipt.useQuery({operationKey:tracking?.operationKey??emptyKey},{enabled:!!tracking,retry:false,staleTime:0,refetchOnMount:'always'});
 const fetchedReceipt=tracking&&!receiptQuery.error?scopedCartReceipt(receiptQuery.data,merchantId,tracking):null,mutationReceipt=tracking&&!receiptQuery.error?scopedCartReceipt(storedReceipt,merchantId,tracking):null;
 const receipt=mutationReceipt&&(!fetchedReceipt||Date.parse(mutationReceipt.updatedAt)>=Date.parse(fetchedReceipt.updatedAt))?mutationReceipt:fetchedReceipt,missingReceipt=(receiptQuery.error as any)?.data?.code==='NOT_FOUND';
 const [editSearch,setEditSearch]=useState<string|null>(null),[action,setAction]=useState<Action|null>(null),[review,setReview]=useState<CartReminderReview|null>(null),[pickDiscount,setPickDiscount]=useState(false),[discount,setDiscount]=useState<DiscountWorkspaceRow|null>(null),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[failure,setFailure]=useState(''),[notice,setNotice]=useState('');
 const live=useRef(true),locked=useRef(false),scope=useRef(''),title=useRef<HTMLHeadingElement>(null),results=useRef<HTMLHeadingElement>(null),outcome=useRef<HTMLElement|null>(null),opener=useRef<HTMLElement|null>(null),returnToTitle=useRef(false),focusResults=useRef(false),focusOutcome=useRef(false);
 scope.current=`${actorId}:${merchantId}:${selectionKey}:${locale}:${tab}`;
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 useEffect(()=>{setAction(null);setReview(null);setAck(false);setEditSearch(null);},[search,locale]);
 useEffect(()=>{if(focusResults.current&&data&&!query.isFetching){results.current?.focus();focusResults.current=false;}},[selectionKey,data,query.isFetching]);
 useEffect(()=>{if(focusOutcome.current&&tracking&&!action){outcome.current?.focus();focusOutcome.current=false;}},[tracking,action,receipt]);
 const same=!action||!!data?.rows.some(r=>r.id===action.row.id&&r.revision===action.row.revision),writable=!!data?.canManage&&same&&!query.isFetching&&!busy&&!blocked;
 const change=(patch:Record<string,string|number|null>)=>{focusResults.current=true;navigate(catalogHref(path,search,patch));};
 const open=(next:Action)=>{opener.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setFailure('');setAck(false);setReview(null);setDiscount(null);setPickDiscount(false);setAction(next);};
 async function refresh(){const view=scope.current,result=await query.refetch();if(!live.current||view!==scope.current)return;if(!result.error&&scopedCartWorkspace(result.data,actorId,merchantId,selection)){setBlocked(false);setFailure('');setAction(null);setReview(null);}if(tab==='reminders')void historyQuery.refetch();}
 async function prepare(kind:'recover'|'remind',row:CartWorkspaceRow){
  if(!writable||locked.current)return;const view=scope.current;locked.current=true;setBusy(true);setFailure('');setAck(false);
  try{if(kind==='recover'){const raw=await reviewRecovery.mutateAsync({cartId:row.id});if(!live.current||view!==scope.current)return;const checked=scopedCartRecovery(raw,actorId,merchantId,row.id,row.revision);if(!checked||!checked.eligible)throw Error();setAction({kind,row:checked.row,recoveryReady:true});}
   else{const raw=await reviewMessage.mutateAsync({cartId:row.id,discountId:pickDiscount?discount?.id??null:null,locale});if(!live.current||view!==scope.current)return;const checked=scopedCartReminder(raw,actorId,merchantId,row.id,row.revision,pickDiscount?discount?.id??null:null,locale);if(!checked)throw Error();setReview(checked);}}
  catch{if(live.current&&view===scope.current){setFailure(c.reviewFailed);setReview(null);}}
  finally{locked.current=false;if(live.current)setBusy(false);}
 }
 async function save(){
  if(!action||action.kind==='details'||!writable||locked.current||!ack)return;if(action.kind==='recover'&&!action.recoveryReady)return;if(action.kind==='remind'&&(!review?.eligible||tracking))return;
  const submitted=action,view=scope.current;locked.current=true;setBusy(true);setFailure('');
  try{if(submitted.kind==='recover'){const result=await record.mutateAsync({cartId:submitted.row.id,expectedRevision:submitted.row.revision,recordOnly:true});if(result?.success!==true||result.cartId!==submitted.row.id||result.effect!=='record_only'||result.salesVerified!==false)throw Error();if(!live.current||view!==scope.current)return;returnToTitle.current=true;setAction(null);setNotice(c.saved);setBlocked(true);await refresh();}
   else{let saved:CartTracking;try{saved=saveCartTracking(localStorage,actorId,merchantId,{operationKey:crypto.randomUUID(),cartId:submitted.row.id});setStorageFailed(false);}catch{setStorageFailed(true);setFailure(c.storageFailed);return;}setTracking(saved);setStoredReceipt(null);const result=await send.mutateAsync({cartId:submitted.row.id,discountId:review!.selection.discountId,locale,expectedRevision:review!.expectedRevision,operationKey:saved.operationKey,confirm:true});if(!live.current||view!==scope.current)return;const checked=scopedCartReceipt(result,merchantId,saved);if(!checked)throw Error();setStoredReceipt(checked);returnToTitle.current=true;focusOutcome.current=true;setAction(null);setBlocked(true);await refresh();}
  }catch(error){if(live.current&&view===scope.current){setFailure((error as any)?.data?.code==='CONFLICT'?c.conflict:c.uncertain);setBlocked(true);if(submitted.kind==='remind'){setAction(null);focusOutcome.current=true;}}}
  finally{locked.current=false;if(live.current)setBusy(false);}
 }
 async function restore(){if(!tracking)return;const view=scope.current,current=tracking;const result=await receiptQuery.refetch();if(!live.current||scope.current!==view)return;const checked=result.error?null:scopedCartReceipt(result.data,merchantId,current);if(checked){setStoredReceipt(checked);setFailure('');await refresh();}}
 function dismiss(){if(!tracking||!receipt&&!missingReceipt)return;try{clearCartTracking(localStorage,actorId,merchantId,tracking.operationKey);setTracking(null);setStoredReceipt(null);setFailure('');setStorageFailed(false);title.current?.focus();}catch{setStorageFailed(true);}}
 function selectReceipt(row:CartReminderReceipt){if(busy)return;try{const saved=saveCartTracking(localStorage,actorId,merchantId,{operationKey:row.operationKey,cartId:row.cartId});setTracking(saved);setStoredReceipt(row);setStorageFailed(false);focusOutcome.current=true;}catch{setStorageFailed(true);}}
 const number=(n:number)=>n.toLocaleString(locale),receiptState=(r:CartReminderReceipt)=>r.state==='unknown'?c.unknownResult:c[r.state],heading=(row:CartWorkspaceRow)=>row.customerName||row.customerPhone||`#${row.id}`;
 return <div className="service-catalog cart-workspace" dir={locale==='ar'?'rtl':'ltr'}>
  <header className="sc-header"><div><p className="sc-eyebrow">{c.eyebrow}</p><h1 ref={title} tabIndex={-1}>{c.title}</h1><p>{c.description}</p></div><Button variant="outline" disabled={busy||query.isFetching} onClick={()=>void refresh()}><RefreshCw aria-hidden="true"/>{c.refresh}</Button></header>
  {storageFailed&&<p role="alert" className="sc-feedback">{c.storageFailed}</p>}{notice&&<p role="status" className="sc-feedback">{notice}</p>}
  {tracking&&<section ref={outcome} className="cw-receipt" tabIndex={-1} aria-live="polite"><h2>{c.cartId} #{tracking.cartId} · {c.receiptId}</h2><p>{c.receiptHelp}</p>{receipt?<><p className="cw-status">{receiptState(receipt)}</p><p>{cartStamp(receipt.updatedAt,c.unknown)} · #{receipt.id}</p></>:<p role={receiptQuery.error?'alert':'status'}>{missingReceipt?c.notFound:receiptQuery.error?c.restoreFailed:c.reviewing}</p>}{failure&&<p role="alert">{failure}</p>}<div className="sc-actions"><Button variant="outline" disabled={busy||receiptQuery.isFetching} onClick={()=>void restore()}>{c.restore}</Button>{(receipt||missingReceipt)&&<Button variant="outline" disabled={busy} onClick={dismiss}>{c.dismiss}</Button>}</div></section>}
  {query.error?<WorkspaceState inline kind={workspaceFailureKind(query.error)} onRetry={()=>void refresh()}/>:!data?<WorkspaceState inline kind={query.isLoading||query.isFetching?'loading':'error'} onRetry={()=>void refresh()}/>:<>
   {!data.canManage&&<p>{c.readonly}</p>}{blocked&&!action&&!tracking&&<p role="alert" className="sc-feedback">{failure||c.uncertain}</p>}
   <dl className="sc-summary">{(['waiting','reminded','recovered','invalid'] as const).map(state=><div key={state}><dt>{c[state]}</dt><dd>{number(data.counts[state])}</dd></div>)}</dl><p className="sc-muted">{c.evidence}</p><p className="sc-muted">{c.automatic}</p><details className="cw-stats"><summary>{c.storedStats}</summary><dl className="dc-summary">{[[c.reminderFlag,data.recorded.reminded],[c.recoveryFlag,data.recorded.recovered],[c.unknownFlags,data.recorded.flagsUnknown],[c.recoveredAmount,data.recorded.recoveredAmount],[c.excludedAmounts,data.recorded.amountRowsExcluded],[c.withoutReminder,data.recorded.recoveredWithoutReminder]].map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{value===null?c.unknown:number(Number(value))}</dd></div>)}</dl><p>{c.unitUnknown}</p></details>
   <div className="cw-tabs" role="group" aria-label={c.title}><Button variant={tab==='carts'?'default':'outline'} aria-pressed={tab==='carts'} disabled={busy} onClick={()=>change({tab:null})}>{c.carts} ({number(data.total)})</Button><Button variant={tab==='reminders'?'default':'outline'} aria-pressed={tab==='reminders'} disabled={busy} onClick={()=>change({tab:'reminders'})}>{c.history}</Button></div>
   {tab==='reminders'?<section className="sc-list" aria-busy={historyQuery.isFetching}><h2>{c.history}</h2><p>{c.historyHelp}</p>{historyQuery.error?<WorkspaceState inline kind={workspaceFailureKind(historyQuery.error)} onRetry={()=>void historyQuery.refetch()}/>:!history?<WorkspaceState inline kind={historyQuery.isLoading||historyQuery.isFetching?'loading':'error'} onRetry={()=>void historyQuery.refetch()}/>:<>{!history.rows.length?<p>{history.total===0?c.historyEmpty:c.outOfRange}</p>:<div className="dc-codes">{history.rows.map(r=><article key={r.id} className="dc-code"><h3>{c.cartId} #{r.cartId}</h3><p>{receiptState(r)}</p><p className="sc-muted">{cartStamp(r.createdAt,c.unknown)}</p><Button variant="outline" disabled={busy} onClick={()=>selectReceipt(r)}>{c.restore}<span className="sr-only"> #{r.id}</span></Button></article>)}</div>}{history.pages>1&&<nav className="sc-pagination" aria-label={c.history}><Button variant="outline" disabled={historyPage<=1||historyQuery.isFetching} onClick={()=>change({historyPage:historyPage-1})}>{c.previous}</Button><span>{c.page} {number(historyPage)} {c.of} {number(history.pages)}</span><Button variant="outline" disabled={historyPage>=history.pages||historyQuery.isFetching} onClick={()=>change({historyPage:historyPage+1})}>{c.next}</Button></nav>}{historyPage>1&&!history.rows.length&&<Button variant="outline" onClick={()=>change({historyPage:null})}>{c.first}</Button>}</>}</section>:<section className="sc-list" aria-busy={query.isFetching}>
    <form className="sc-filters" onSubmit={e=>{e.preventDefault();change({q:(editSearch??selection.query).trim(),page:null});}}><label className="sc-search"><span>{c.search}</span><input value={editSearch??selection.query} maxLength={100} disabled={busy} onChange={e=>setEditSearch(e.target.value)}/></label><Button type="submit" variant="outline" disabled={busy}>{c.searchAction}</Button><label><span>{c.state}</span><select value={selection.state} disabled={busy} onChange={e=>change({state:e.target.value,page:null})}>{(['all','waiting','reminded','recovered','invalid'] as const).map(s=><option key={s} value={s}>{c[s]}</option>)}</select></label>{(selection.query||selection.state!=='all')&&<Button type="button" variant="ghost" disabled={busy} onClick={()=>change({q:null,state:null,page:null})}>{c.clear}</Button>}</form>
    <h2 className="dc-results" ref={results} tabIndex={-1}>{c.matches} · {number(data.matched)}</h2>
    {!data.rows.length?<div className="sc-empty"><p>{data.total===0?c.empty:data.matched===0?c.noResults:c.outOfRange}</p>{selection.page>1&&<Button variant="outline" onClick={()=>change({page:null})}>{c.first}</Button>}</div>:<div className="dc-codes">{data.rows.map(row=><article className="dc-code" key={row.id}><div className="dc-code-heading"><div><p className="sc-muted">#{row.id}</p><h3><bdi>{heading(row)}</bdi></h3></div><Badge variant="secondary">{c[row.state]}</Badge></div><p><bdi>{row.customerPhone||c.unknown}</bdi></p><p className="sc-muted">{cartStamp(row.createdAt,c.unknown)}</p><div className="sc-actions"><Button variant="outline" disabled={busy} onClick={()=>open({kind:'details',row})}>{c.details}<span className="sr-only"> {heading(row)} #{row.id}</span></Button>{data.canManage&&row.state==='waiting'&&<Button disabled={!writable||!!tracking} onClick={()=>open({kind:'remind',row})}>{c.remind}<span className="sr-only"> #{row.id}</span></Button>}{data.canManage&&(row.state==='waiting'||row.state==='reminded')&&<Button variant="outline" disabled={!writable} onClick={()=>{open({kind:'recover',row});void prepare('recover',row);}}>{c.recover}<span className="sr-only"> #{row.id}</span></Button>}</div></article>)}</div>}
    {data.pages>1&&<nav className="sc-pagination" aria-label={c.page}><Button variant="outline" disabled={selection.page<=1||query.isFetching||busy} onClick={()=>change({page:selection.page-1})}>{c.previous}</Button><span>{c.page} {number(selection.page)} {c.of} {number(data.pages)}</span><Button variant="outline" disabled={selection.page>=data.pages||query.isFetching||busy} onClick={()=>change({page:selection.page+1})}>{c.next}</Button></nav>}
   </section>}
  </>}
  <Dialog open={!!action&&!!data&&!query.error} onOpenChange={v=>{if(!v&&!busy)setAction(null);}}><DialogContent className="sc-dialog dc-dialog cw-dialog" closeLabel={c.close} dir={locale==='ar'?'rtl':'ltr'} showCloseButton={!busy} onEscapeKeyDown={e=>{if(busy)e.preventDefault();}} onInteractOutside={e=>{if(busy)e.preventDefault();}} onCloseAutoFocus={e=>{e.preventDefault();(returnToTitle.current?(tracking?outcome.current:title.current):opener.current?.isConnected?opener.current:title.current)?.focus();returnToTitle.current=false;}}><DialogHeader><DialogTitle>{action?.kind==='remind'?c.remind:action?.kind==='recover'?c.recover:c.details}</DialogTitle><DialogDescription>{action?.kind==='remind'?c.sendHelp:action?.kind==='recover'?c.recoverHelp:c.evidence}</DialogDescription></DialogHeader>
   {failure&&<p role="alert" className="sc-feedback">{failure}</p>}{!same&&<p role="alert">{c.reviewStale}</p>}{action?.row.issues.length?<p className="sc-feedback">{c.invalidHelp}</p>:null}
   {action?.kind==='details'&&<CartSummary row={action.row}/>}
   {action?.kind==='recover'&&<><p>{c.cartId} #{action.row.id} · <bdi>{heading(action.row)}</bdi></p><p><bdi>{action.row.customerPhone||c.unknown}</bdi></p><details><summary>{c.details}</summary><CartSummary row={action.row}/></details></>}
   {action?.kind==='recover'&&<label className="cw-check"><input type="checkbox" checked={ack} disabled={busy||!action.recoveryReady||!same||blocked} onChange={e=>setAck(e.target.checked)}/><span>{c.recoverAck}</span></label>}
   {action?.kind==='remind'&&<div className="cw-review"><p>{c.name}: <bdi>{heading(action.row)}</bdi> · {c.cartId} #{action.row.id}</p><label className="dc-field"><span>{c.discount}</span><select value={pickDiscount?'choose':'none'} disabled={busy} onChange={e=>{setPickDiscount(e.target.value==='choose');setReview(null);setAck(false);}}><option value="none">{c.noDiscount}</option><option value="choose">{c.chooseDiscount}</option></select></label>{pickDiscount&&<fieldset disabled={busy}><CartDiscountPicker actorId={actorId} merchantId={merchantId} selected={discount} onSelect={row=>{setDiscount(row);setReview(null);setAck(false);}}/></fieldset>}<Button variant="outline" disabled={!writable||pickDiscount&&!discount} onClick={()=>void prepare('remind',action.row)}>{busy?c.reviewing:c.review}</Button>
    {review&&<><dl className="dc-summary"><div><dt>{c.recipient}</dt><dd><bdi>{review.recipient||c.unknown}</bdi></dd></div><div><dt>{c.channel}</dt><dd>{review.channel?`${review.channel.provider} · #${review.channel.id}`:c.unknown}</dd></div><div><dt>{c.quota}</dt><dd>{review.quotaUnlimited?c.unlimited:review.quotaRemaining===null?c.unknown:number(review.quotaRemaining)}</dd></div></dl>{review.text&&<><h3>{c.message}</h3><pre className="cw-message">{review.text}</pre></>}{review.blockers.length>0&&<ul className="cw-blockers" role="alert">{review.blockers.map(reason=><li key={reason}>{c[`blocker_${reason}`]}</li>)}</ul>}{review.latest&&<p>{c.receiptId} #{review.latest.id}: {receiptState(review.latest)}</p>}<label className="cw-check"><input type="checkbox" checked={ack} disabled={busy||!review.eligible||!same||blocked} onChange={e=>setAck(e.target.checked)}/><span>{c.sendAck}</span></label></>}
   </div>}
   <div className="sc-actions"><Button variant="outline" disabled={busy} onClick={()=>setAction(null)}>{action?.kind==='details'?c.close:c.cancel}</Button>{action&&action.kind!=='details'&&<Button disabled={!writable||!ack||(action.kind==='recover'?!action.recoveryReady:!review?.eligible||!!tracking)} onClick={()=>void save()}>{busy?c.sending:action.kind==='recover'?c.recoverConfirm:c.send}</Button>}</div>{(blocked||!same)&&<Button variant="outline" disabled={busy||query.isFetching} onClick={()=>void refresh()}>{c.refresh}</Button>}
  </DialogContent></Dialog>
 </div>;
}
