import { useTranslation } from 'react-i18next';
import type { DiscountWorkspaceRow } from '@shared/discount-workspace';
import type { DiscountDraft } from '@/lib/discount-workspace';
import { discountWorkspaceLabels } from '@/lib/discount-workspace-labels';
export function DiscountSummary({ row, draft }: { row?: DiscountWorkspaceRow; draft?: DiscountDraft }) {
  const { t, i18n } = useTranslation(), c = discountWorkspaceLabels(t), locale = i18n.language.startsWith('ar') ? 'ar' : 'en';
  const number = (n: number | null | undefined) => n == null ? c.unknown : n.toLocaleString(locale);
  const date = (iso: string | null | undefined) => iso ? new Date(iso).toLocaleString(locale, { timeZone: 'UTC' }) + ' UTC' : c.unknown;
  const pairs = row ? [
    [c.code, row.code], [c.type, row.type ? c[row.type] : c.unknown], [c.value, number(row.value)], [c.minimum, row.minOrderAmount === null ? row.issues.includes('minimum') ? c.unknown : c.noMinimum : number(row.minOrderAmount)],
    [c.maxUses, row.maxUses === null ? row.issues.includes('limit') ? c.unknown : c.unlimited : number(row.maxUses)], [c.uses, number(row.usedCount)], [c.expiry, row.expiresAt ? date(row.expiresAt) : row.issues.includes('expiry') ? c.unknown : c.noExpiry],
    [c.customer, row.customerPhone || c.allCustomers], [c.origin, row.isAutoGenerated === null ? c.unknown : row.isAutoGenerated ? c.automatic : c.manual], [c.created, date(row.createdAt)], [c.updated, date(row.updatedAt)],
  ] : [[c.code, draft!.code.trim().toUpperCase()], [c.type, c[draft!.type]], [c.value, draft!.value], [c.minimum, draft!.minOrderAmount || c.noMinimum], [c.maxUses, draft!.maxUses || c.unlimited], [c.expiry, draft!.expiresAt ? draft!.expiresAt + ' 00:00 UTC' : c.noExpiry]];
  return <dl className="dc-summary">{pairs.map(([label, value]) => <div key={label}><dt>{label}</dt><dd><bdi>{value}</bdi></dd></div>)}</dl>;
}
