import {useEffect,useRef,useState} from 'react';
import {useLocation,useSearch,Link} from 'wouter';
import {useTranslation} from 'react-i18next';
import {RefreshCw,Plus} from 'lucide-react';
import {trpc} from '@/lib/trpc';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {WorkspaceState,workspaceFailureKind} from './WorkspaceState';
import {PromotionRecord,promotionStamp} from './PromotionRecord';
import {PromotionForm} from './PromotionForm';
import {promotionWorkspaceLabels} from '@/lib/promotion-workspace-labels';
import {promotionWriteError} from '@/lib/promotion-write-error';
import {promotionNavigation,promotionSelectionKey,scopedPromotionWorkspace,scopedPromotionReview,scopedPromotionResult,promotionDefinitionKey,promotionForm,promotionFormTarget,promotionReceiptStorageKey,scopedPromotionCancellation} from '@/lib/promotion-workspace';
import {catalogHref} from '@/lib/service-catalog-navigation';
import {promotionTypes,promotionScopes,promotionStates,type PromotionWorkspaceRow} from '@shared/promotion-workspace';
import type {PromotionActionTarget,PromotionActionReview} from '@shared/promotion-actions';
import '@/styles/service-catalog-workspace.css';
import '@/styles/promotion-workspace.css';
type Modal={kind:'details';row:PromotionWorkspaceRow}|{kind:'edit';row?:PromotionWorkspaceRow}|{kind:'review';target:PromotionActionTarget;row?:PromotionWorkspaceRow};
export function PromotionWorkspace({actorId,merchantId}:{actorId:number;merchantId:number}){
 const {t,i18n}=useTranslation(),c=promotionWorkspaceLabels(t),locale=i18n.language.startsWith('ar')?'ar':'en',utils=trpc.useUtils();
 const [path,navigate]=useLocation(),search=useSearch(),selection=promotionNavigation(search),key=promotionSelectionKey(selection),storageKey=promotionReceiptStorageKey(actorId,merchantId);
 const query=trpc.promotions.workspace.useQuery(selection,{retry:false,staleTime:0,refetchOnMount:'always'}),data=query.error?null:scopedPromotionWorkspace(query.data,actorId,merchantId,selection);
 const reviewMutation=trpc.promotions.reviewAction.useMutation({retry:false}),apply=trpc.promotions.applyAction.useMutation({retry:false});
 const resolveMutation=trpc.promotions.resolveActionReceipt.useMutation({retry:false});
 const [modal,setModal]=useState<Modal|null>(null),[form,setForm]=useState(()=>promotionForm()),[errors,setErrors]=useState<any>({}),[review,setReview]=useState<PromotionActionReview|null>(null),[busy,setBusy]=useState(false),[failure,setFailure]=useState(''),[notice,setNotice]=useState(''),[editSearch,setEditSearch]=useState<string|null>(null);
 const [pending,setPending]=useState<string|null>(()=>{try{const k=sessionStorage.getItem(storageKey);return k&&/^[a-f0-9-]{36}$/i.test(k)?k:null;}catch{return null;}});
 const live=useRef(true),locked=useRef(false),scope=useRef(''),heading=useRef<HTMLHeadingElement>(null),opener=useRef<HTMLElement|null>(null),focusHeading=useRef(false);scope.current=`${actorId}:${merchantId}:${key}:${locale}`;
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 useEffect(()=>{setModal(null);setReview(null);setEditSearch(null);setFailure('');},[search,locale]);
 useEffect(()=>{if(query.error){setModal(null);setReview(null);}},[query.error]);
 const same=!modal?.row||!!data?.rows.some(r=>r.id===modal.row!.id&&promotionDefinitionKey(r)===promotionDefinitionKey(modal.row!));
 const writable=!!data?.canManage&&!query.isFetching&&!busy&&!pending&&same;
 const number=(v:number)=>v.toLocaleString(locale),stamp=(v:string|null)=>promotionStamp(v,c,locale);
 const change=(patch:Record<string,string|number|null>)=>navigate(catalogHref(path,search,patch));
 async function refresh(){await query.refetch();}
 function open(value:Modal){opener.current=document.activeElement as HTMLElement;setErrors({});setFailure('');setReview(null);if(value.kind==='edit')setForm(promotionForm(value.row));setModal(value);}
 async function prepare(target:PromotionActionTarget,row?:PromotionWorkspaceRow){if(!writable||locked.current)return;const view=scope.current;locked.current=true;setBusy(true);setFailure('');setReview(null);setModal({kind:'review',target,row});try{const raw=await reviewMutation.mutateAsync(target);if(!live.current||view!==scope.current)return;const checked=scopedPromotionReview(raw,actorId,merchantId,target);if(!checked)throw Error();if(row&&checked.before&&promotionDefinitionKey(row)!==promotionDefinitionKey(checked.before)){setFailure(c.stale);return;}setReview(checked);}catch(e){if(live.current&&view===scope.current)setFailure(promotionWriteError(e,t));}finally{locked.current=false;if(live.current)setBusy(false);}}
 function reviewForm(){if(modal?.kind!=='edit'||!writable)return;const result=promotionFormTarget(form,modal.row);setErrors(result.errors);if(!result.target){setFailure(result.noChanges?c.noChanges:c.validation);return;}void prepare(result.target,modal.row);}
 async function saved(requestKey:string){try{if(sessionStorage.getItem(storageKey)===requestKey)sessionStorage.removeItem(storageKey);}catch{}setPending(null);setModal(null);setReview(null);setFailure('');setNotice(c.saved);focusHeading.current=true;await refresh();}
 async function save(){if(!writable||locked.current||!review||modal?.kind!=='review')return;const view=scope.current,requestKey=crypto.randomUUID(),target=modal.target;locked.current=true;setBusy(true);setFailure('');try{sessionStorage.setItem(storageKey,requestKey);setPending(requestKey);const result=await apply.mutateAsync({target,reviewRevision:review.reviewRevision,checkedAt:review.checkedAt,requestKey});if(!live.current||view!==scope.current)return;if(!scopedPromotionResult(result,actorId,merchantId,requestKey,target))throw Error();await saved(requestKey);}catch(e){if(live.current&&view===scope.current){const code=(e as any)?.data?.code;if(['CONFLICT','BAD_REQUEST','FORBIDDEN','NOT_FOUND','PRECONDITION_FAILED'].includes(code)){try{sessionStorage.removeItem(storageKey);}catch{}setPending(null);setReview(null);setFailure(code==='CONFLICT'?c.stale:promotionWriteError(e,t));}else setFailure(c.pending);}}finally{locked.current=false;if(live.current)setBusy(false);}}
 async function recover(resolve=false){if(!pending||locked.current)return;const view=scope.current,requestKey=pending;locked.current=true;setBusy(true);setFailure('');try{const result=resolve?await resolveMutation.mutateAsync({requestKey}):await utils.promotions.actionReceipt.fetch({requestKey},{staleTime:0});if(!live.current||view!==scope.current)return;if(result.state==='saved'&&scopedPromotionResult(result.result,actorId,merchantId,requestKey))await saved(requestKey);else if(result.state==='cancelled'&&scopedPromotionCancellation(result.result,actorId,merchantId,requestKey)){try{sessionStorage.removeItem(storageKey);}catch{}setPending(null);setModal(null);setReview(null);setFailure('');setNotice(c.cancelledRequest);await refresh();}else setFailure(result.state==='missing'?c.missingReceipt:c.pending);}catch(e){if(live.current&&view===scope.current)setFailure(promotionWriteError(e,t));}finally{locked.current=false;if(live.current)setBusy(false);}}
 const pendingPanel=pending&&<div className="sc-feedback pm-pending" role="status"><p>{c.pending}</p><p className="pm-inline-value">{c.receipt}: {pending}</p><Button variant="outline" disabled={busy} onClick={()=>void recover()}>{c.recover}</Button><p>{c.resolveHelp}</p><Button variant="outline" disabled={busy} onClick={()=>void recover(true)}>{c.resolveRequest}</Button></div>;
 const effect=review?.effect==='create_active'?c.createEffect:review?.effect==='update'?c.updateEffect:review?.effect==='enable'?c.enableEffect:review?.effect==='disable'?c.disableEffect:c.deleteEffect;
 const proposed=review?.proposed;const facts=proposed?[[c.name,proposed.title],[c.description,proposed.description],[c.type,proposed.type?c[proposed.type]:null],[c.value,proposed.value],[c.scope,proposed.scope?c[proposed.scope]:null],[c.productIds,proposed.productIds],[c.categoryIds,proposed.categoryIds],[c.minOrderAmount,proposed.minOrderAmount],[c.minQuantity,proposed.minQuantity],[c.startsAt,stamp(proposed.startsAt??null)],[c.expiresAt,stamp(proposed.expiresAt??null)],[c.bannerImageUrl,proposed.bannerImageUrl]]:[];
 return <div className="service-catalog promotion-workspace" dir={locale==='ar'?'rtl':'ltr'}><header className="sc-header"><div><p className="sc-eyebrow">{c.eyebrow}</p><h1 ref={heading} tabIndex={-1}>{c.title}</h1><p>{c.intro}</p></div><div className="sc-actions"><Button variant="outline" disabled={busy||query.isFetching} onClick={()=>void refresh()}><RefreshCw aria-hidden="true"/>{c.refresh}</Button>{data?.canManage&&<Button disabled={!writable} onClick={()=>open({kind:'edit'})}><Plus aria-hidden="true"/>{c.create}</Button>}</div></header>
  {notice&&<p role="status" className="sc-feedback">{notice}</p>}{!modal&&pendingPanel}{!modal&&failure&&<p role="alert" className="sc-feedback">{failure}</p>}
  {query.error?<WorkspaceState inline kind={workspaceFailureKind(query.error)} onRetry={()=>void refresh()}/>:!data?<WorkspaceState inline kind={query.isLoading||query.isFetching?'loading':'error'} onRetry={()=>void refresh()}/>:<>{!data.canManage&&<p>{c.readonly}</p>}<dl className="sc-summary">{[[c.total,number(data.total)],[c.active,number(data.counts.active)],[c.scheduled,number(data.counts.scheduled)],[c.sales,c.notVerified]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="sc-muted">{c.evidence}</p>
   <section className="sc-list" aria-busy={query.isFetching}><h2>{c.history}</h2><form className="sc-filters" onSubmit={e=>{e.preventDefault();change({q:(editSearch??selection.query).trim(),page:null});}}><label className="sc-search"><span>{c.search}</span><input maxLength={100} value={editSearch??selection.query} disabled={busy} onChange={e=>setEditSearch(e.target.value)}/></label><Button type="submit" variant="outline" disabled={busy}>{c.searchAction}</Button>
    <label><span>{c.state}</span><select disabled={busy} value={selection.state} onChange={e=>change({state:e.target.value==='all'?null:e.target.value,page:null})}><option value="all">{c.allStatuses}</option>{promotionStates.map(v=><option key={v} value={v}>{c[v]}</option>)}</select></label><label><span>{c.type}</span><select disabled={busy} value={selection.type} onChange={e=>change({type:e.target.value==='all'?null:e.target.value,page:null})}><option value="all">{c.allTypes}</option>{promotionTypes.map(v=><option key={v} value={v}>{c[v]}</option>)}</select></label><label><span>{c.scope}</span><select disabled={busy} value={selection.scope} onChange={e=>change({scope:e.target.value==='any'?null:e.target.value,page:null})}><option value="any">{c.anyScope}</option>{promotionScopes.map(v=><option key={v} value={v}>{c[v]}</option>)}</select></label>{(selection.query||selection.state!=='all'||selection.type!=='all'||selection.scope!=='any')&&<Button variant="outline" type="button" disabled={busy} onClick={()=>change({q:null,state:null,type:null,scope:null,page:null})}>{c.clear}</Button>}</form><p className="sc-results" aria-live="polite">{c.matches}: {number(data.matched)}</p>
    {!data.rows.length?<div className="sc-empty"><p>{data.total===0?c.empty:data.matched===0?c.noResults:c.outOfRange}</p>{selection.page>1&&<Button variant="outline" onClick={()=>change({page:null})}>{c.first}</Button>}</div>:<div className="pm-grid">{data.rows.map(row=><article className="pm-record" key={row.id}><div className="pm-heading"><h3>{row.title??c.unknown}</h3><Badge variant="outline">{c[row.state]}</Badge></div><p className="sc-description">{row.description??c.notRecorded}</p><dl className="pm-facts"><div><dt>{c.type}</dt><dd>{row.type?c[row.type]:c.unknown}{row.value!==null?' · '+number(row.value)+(row.type==='percentage'?'%':''):''}</dd></div><div><dt>{c.scope}</dt><dd>{row.scope?c[row.scope]:c.unknown}</dd></div><div><dt>{c.expiresAt}</dt><dd>{stamp(row.expiresAt)}</dd></div><div><dt>{c.code}</dt><dd>{row.linkedDiscount?.code??(row.autoDiscountCodeId?c.unknown:c.notRecorded)}</dd></div></dl><div className="sc-actions"><Button variant="outline" disabled={busy} onClick={()=>open({kind:'details',row})}>{c.details}<span className="sr-only"> #{row.id}</span></Button>{data.canManage&&<><Button variant="outline" disabled={!writable} onClick={()=>open({kind:'edit',row})}>{c.edit}<span className="sr-only"> #{row.id}</span></Button>{row.isActive!==null&&<Button variant="outline" disabled={!writable} onClick={()=>{opener.current=document.activeElement as HTMLElement;void prepare({action:'toggle',id:row.id,enabled:!row.isActive},row);}}>{row.isActive?c.disable:c.enable}<span className="sr-only"> #{row.id}</span></Button>}<Button variant="outline" disabled={!writable} onClick={()=>{opener.current=document.activeElement as HTMLElement;void prepare({action:'delete',id:row.id},row);}}>{c.delete}<span className="sr-only"> #{row.id}</span></Button></>}</div></article>)}</div>}
    {data.pages>1&&<nav className="sc-pagination" aria-label={c.history}><Button variant="outline" disabled={busy||query.isFetching||selection.page<=1} onClick={()=>change({page:selection.page-1})}>{c.previous}</Button><span>{c.page} {number(selection.page)} {c.of} {number(data.pages)}</span><Button variant="outline" disabled={busy||query.isFetching||selection.page>=data.pages} onClick={()=>change({page:selection.page+1})}>{c.next}</Button></nav>}
   </section><Link className="sc-muted" href="/merchant/discounts">{c.discounts}</Link>
  </>}
  <Dialog open={!!modal&&!!data} onOpenChange={value=>{if(!value&&!busy){setModal(null);setReview(null);}}}><DialogContent showCloseButton={!busy} closeLabel={c.close} className="sc-dialog pm-dialog" dir={locale==='ar'?'rtl':'ltr'} onInteractOutside={e=>{if(busy)e.preventDefault();}} onEscapeKeyDown={e=>{if(busy)e.preventDefault();}} onCloseAutoFocus={e=>{e.preventDefault();if(focusHeading.current){heading.current?.focus();focusHeading.current=false;}else if(opener.current?.isConnected)opener.current.focus();else heading.current?.focus();}}><DialogHeader><DialogTitle>{modal?.kind==='details'?c.details:modal?.kind==='edit'?modal.row?c.edit:c.create:c.reviewTitle}</DialogTitle><DialogDescription>{modal?.kind==='review'?c.reviewIntro:modal?.kind==='details'?'#'+modal.row.id:c.intro}</DialogDescription></DialogHeader>
   {modal?.kind==='details'?<PromotionRecord row={modal.row} c={c} locale={locale}/>:modal?.kind==='edit'?<PromotionForm form={form} setForm={setForm} errors={errors} c={c} busy={busy} editing={!!modal.row} codeHelp={t('merchantUx.promotionWrites.codeHelp')}/>:<>{busy&&!review&&<p role="status">{c.reviewing}</p>}{review&&<div className="pm-review"><p className="pm-effect">{effect}</p><p>{c.state}: {review.candidateState==='deleted'?c.delete:c[review.candidateState]}</p>{facts.length>0&&<dl className="pm-facts">{facts.map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd className="pm-inline-value">{value===null||value===undefined?c.notRecorded:String(value)}</dd></div>)}</dl>}{review.newDiscount&&<p className="sc-feedback">{c.newCode}: {review.newDiscount.value}{review.newDiscount.type==='percentage'?'%':''} · {c.minOrderAmount}: {review.newDiscount.minOrderAmount} · {c.expiresAt}: {stamp(review.newDiscount.expiresAt)}</p>}{review.retainsLinkedDiscount&&<p className="sc-feedback">{c.keptCode}</p>}<p className="sc-muted">{c.currency}</p><p className="sc-muted">{c.reviewExpires}: {stamp(review.expiresAt)}</p>{review.before&&<details><summary>{c.before}</summary><PromotionRecord row={review.before} c={c} locale={locale}/></details>}</div>}</>}
   {!same&&<p role="alert" className="sc-feedback">{c.stale}</p>}{pendingPanel}{failure&&<p role="alert" className="sc-feedback">{failure}</p>}<div className="sc-actions"><Button variant="outline" disabled={busy} onClick={()=>setModal(null)}>{modal?.kind==='details'?c.close:c.cancel}</Button>{modal?.kind==='edit'&&<Button disabled={!writable} onClick={reviewForm}>{c.review}</Button>}{modal?.kind==='review'&&<>{['create','update'].includes(modal.target.action)&&<Button variant="outline" disabled={busy||!!pending} onClick={()=>{setReview(null);setFailure('');setModal({kind:'edit',row:modal.row});}}>{c.back}</Button>}<Button disabled={!writable||!review} onClick={()=>void save()}>{busy?c.saving:c.confirm}</Button>{!review&&!busy&&!pending&&<Button variant="outline" onClick={()=>{setModal(null);void refresh();}}>{c.refresh}</Button>}</>}</div>
  </DialogContent></Dialog>
 </div>;
}
