import {PromotionSavedTargets} from './PromotionTargetNames';
import type {PromotionWorkspaceRow} from '@shared/promotion-workspace';
import type {PromotionLabels} from '@/lib/promotion-workspace-labels';
export function promotionStamp(value:string|null,c:PromotionLabels,locale:string){if(!value)return c.notRecorded;const date=new Date(value.includes('T')?value:value.replace(' ','T')+'Z');return Number.isFinite(date.getTime())?new Intl.DateTimeFormat(locale,{timeZone:'Asia/Riyadh',dateStyle:'medium',timeStyle:'short'}).format(date):c.unknown;}
export function PromotionRecord({actorId,merchantId,row,c,locale}:{actorId:number;merchantId:number;row:PromotionWorkspaceRow;c:PromotionLabels;locale:string}){
 const value=(v:unknown)=>v===null?c.notRecorded:String(v),stamp=(v:string|null)=>promotionStamp(v,c,locale);
 const fields=[[c.id,'#'+row.id],[c.type,row.type?c[row.type]:c.unknown],[c.value,value(row.value)+(row.type==='percentage'?'%':'')],[c.scope,row.scope?c[row.scope]:c.unknown],[c.minOrderAmount,value(row.minOrderAmount)],[c.minQuantity,value(row.minQuantity)],[c.startsAt,stamp(row.startsAt)],[c.expiresAt,stamp(row.expiresAt)],[c.activeFlag,row.isActive===null?c.unknown:row.isActive?c.yes:c.no],[c.code,row.linkedDiscount?row.linkedDiscount.code+' · '+row.linkedDiscount.value+(row.linkedDiscount.type==='percentage'?'%':'')+' · '+(row.linkedDiscount.isActive?c.active:c.inactive):row.autoDiscountCodeId?'#'+row.autoDiscountCodeId+' · '+c.unknown:c.notRecorded],[c.views,value(row.viewCount)],[c.clicks,value(row.clickCount)],[c.created,stamp(row.createdAt)],[c.updated,stamp(row.updatedAt)]];
 return <div className="pm-detail"><h3>{row.title??c.unknown}</h3>{row.issues.length>0&&<p className="sc-feedback">{c.dataHelp}</p>}<p>{row.description??c.notRecorded}</p>{(row.productIds!==null||row.categoryIds!==null||row.scope==='products'||row.scope==='categories')&&<PromotionSavedTargets actorId={actorId} merchantId={merchantId} row={row} c={c} locale={locale}/>}<dl className="pm-facts">{fields.map(([label,text])=><div key={label}><dt>{label}</dt><dd className="pm-inline-value">{text}</dd></div>)}</dl><details><summary>{c.rawTargets}</summary><dl className="pm-facts"><div><dt>{c.productIds}</dt><dd className="pm-inline-value">{value(row.productIds)}</dd></div><div><dt>{c.categoryIds}</dt><dd className="pm-inline-value">{value(row.categoryIds)}</dd></div></dl></details><div><h3>{c.bannerImageUrl}</h3><p className="pm-inline-value">{row.bannerImageUrl??c.notRecorded}</p></div><p className="sc-muted">{c.currency}</p><p className="sc-muted">{c.evidence}</p>{row.autoDiscountCodeId!==null&&<p className="sc-feedback">{c.keptCode}</p>}</div>;
}
