import {useEffect,useRef} from 'react';
import {promotionTypes,promotionScopes} from '@shared/promotion-workspace';
import type {PromotionLabels} from '@/lib/promotion-workspace-labels';
import type {PromotionForm as Form} from '@/lib/promotion-workspace';
export function PromotionForm({form,setForm,errors,c,busy,editing,codeHelp}:{form:Form;setForm:(v:Form)=>void;errors:Partial<Record<keyof Form,keyof PromotionLabels>>;c:PromotionLabels;busy:boolean;editing:boolean;codeHelp:string}){
 const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const first=Object.keys(errors)[0];if(first){const input=root.current?.querySelector<HTMLElement>('#pm-'+first);let ancestor=input?.parentElement;while(ancestor){if(ancestor instanceof HTMLDetailsElement)ancestor.open=true;ancestor=ancestor.parentElement;}input?.focus();}},[errors]);
 const label=(key:keyof Form)=>key==='title'?c.name:key==='autoCodeType'?c.codeType:key==='autoCodeValue'?c.codeValue:c[key as keyof PromotionLabels]??key;
 const change=(key:keyof Form,value:string|boolean)=>setForm({...form,[key]:value});
 function field(key:Exclude<keyof Form,'autoGenerateCode'>,type='text',options?:readonly string[]){const props={id:'pm-'+key,value:form[key],disabled:busy,'aria-invalid':!!errors[key],'aria-describedby':errors[key]?'pm-error-'+key:undefined,onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>change(key,e.target.value)};return <label><span>{label(key)}{key==='title'||key==='type'?' *':''}</span>{options?<select {...props}>{!options.includes(form[key])&&<option value="">{c.unknown}</option>}{options.map(o=><option key={o} value={o}>{c[o as keyof PromotionLabels]}</option>)}</select>:type==='textarea'?<textarea {...props} maxLength={65535}/>:<input {...props} type={type} step={type==='datetime-local'?1:undefined} inputMode={['value','minOrderAmount','minQuantity','autoCodeValue'].includes(key)?'numeric':undefined} maxLength={key==='title'?255:key==='bannerImageUrl'?500:undefined}/>} {errors[key]&&<span id={'pm-error-'+key} className="pm-field-error">{c[errors[key]!]}</span>}</label>;}
 return <div ref={root} className="pm-form">{field('title')}{field('description','textarea')}<div className="pm-grid">{field('type','text',promotionTypes)}{field('value')}</div><p className="sc-muted">{c.currency}</p>
  <details open={editing||undefined}><summary>{c.advanced}</summary><div className="pm-form">{field('scope','text',promotionScopes)}{(form.scope==='products'||!!form.productIds)&&field('productIds')}{(form.scope==='categories'||!!form.categoryIds)&&field('categoryIds')}{form.scope!=='all'&&<p className="sc-muted">{c.idsHelp}</p>}<div className="pm-grid">{field('minOrderAmount')}{field('minQuantity')}{field('startsAt','datetime-local')}{field('expiresAt','datetime-local')}</div><p className="sc-muted">{c.dateHelp}</p>{field('bannerImageUrl','url')}<p className="sc-muted">{c.bannerHelp}</p></div></details>
  {!editing&&<div><label className="pm-check"><input type="checkbox" checked={form.autoGenerateCode} disabled={busy} onChange={e=>change('autoGenerateCode',e.target.checked)}/><span>{c.autoCode}</span></label><p className="sc-muted">{codeHelp}</p>{form.autoGenerateCode&&<div className="pm-grid">{field('autoCodeType','text',['percentage','fixed'])}{field('autoCodeValue')}</div>}</div>}
 </div>;
}
