import {serviceEditorLabels} from '@/lib/service-editor-labels';
import {useEffect,useRef,useState} from 'react';
import {Link,useLocation,useSearch} from 'wouter';
import {useTranslation} from 'react-i18next';
import {RefreshCw,Check,Eye} from 'lucide-react';
import {trpc} from '@/lib/trpc';
import {catalogEditorContextSchema,type CatalogEditorContext} from '@shared/service-catalog-workspace';
import {newServiceDraft,serviceDraftFromRecord,parseServiceDraft,type ServiceDraft} from '@/lib/service-editor-form';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {WorkspaceState,workspaceFailureKind} from './WorkspaceState';
import {CatalogChoicePicker} from './CatalogChoicePicker';
import '@/styles/service-catalog-workspace.css';
import '@/styles/service-editor-workspace.css';

export function ServiceEditorWorkspace({actorId,merchantId,serviceId}:{actorId:number;merchantId:number;serviceId?:number}){
 const query=trpc.services.catalogEditor.useQuery({entity:'service',id:serviceId},{retry:false,staleTime:0,refetchOnMount:'always'}),parsed=catalogEditorContextSchema.safeParse(query.data);
 const current=!query.error&&parsed.success&&parsed.data.actorId===actorId&&parsed.data.merchantId===merchantId&&parsed.data.selection.entity==='service'&&parsed.data.selection.id===serviceId?parsed.data:null;
 const [seed,setSeed]=useState<CatalogEditorContext|null>(null),[version,setVersion]=useState(0);
 useEffect(()=>{if(current&&!seed&&!query.isFetching)setSeed(current);},[current,seed,query.isFetching]);
 const refresh=()=>{void query.refetch();};
 if(!seed){if(query.error)return <WorkspaceState kind={workspaceFailureKind(query.error)} onRetry={refresh}/>;return <WorkspaceState kind={query.isLoading||query.isFetching||current?'loading':'error'} onRetry={refresh}/>;}
 return <ServiceEditorForm key={version} seed={seed} current={current} refreshing={query.isFetching} refresh={refresh} reload={()=>{if(current&&!query.isFetching){setSeed(current);setVersion(value=>value+1);}}}/>;
}
function ServiceEditorForm({seed,current,refreshing,refresh,reload}:{seed:CatalogEditorContext;current:CatalogEditorContext|null;refreshing:boolean;refresh:()=>void;reload:()=>void}){
 const {t,i18n}=useTranslation(),[path,navigate]=useLocation(),search=useSearch(),label=serviceEditorLabels(t);
 const record=seed.record?.entity==='service'?seed.record:null,id=record?.id,rtl=i18n.language.startsWith('ar'),locale=rtl?'ar-SA':'en-US';
 const [draft,setDraft]=useState<ServiceDraft>(()=>record?serviceDraftFromRecord(record):{...newServiceDraft,staffIds:[]});
 const initialDraft=useRef(JSON.stringify(draft)),dirty=JSON.stringify(draft)!==initialDraft.current;
 const [names,setNames]=useState<Record<string,Record<number,string>>>(()=>Object.fromEntries(['category','staff'].map(kind=>[kind,Object.fromEntries((record?.references??[]).filter(row=>row.kind===kind).map(row=>[row.id,row.name]))])));
 const [attempted,setAttempted]=useState(false),[touched,setTouched]=useState<string[]>([]),[advanced,setAdvanced]=useState(false),[focusField,setFocusField]=useState<string|null>(null);
 const [dialog,setDialog]=useState<'review'|'reload'|null>(null),[reviewed,setReviewed]=useState(''),[busy,setBusy]=useState(false),[failure,setFailure]=useState(''),[uncertain,setUncertain]=useState(false),[conflict,setConflict]=useState(false);
 const live=useRef(true),lock=useRef(false),scope=useRef(''),opener=useRef<HTMLElement|null>(null),heading=useRef<HTMLHeadingElement|null>(null);scope.current=`${seed.actorId}:${seed.merchantId}:${id??'new'}:${path}:${search}`;
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 useEffect(()=>{setDialog(null);},[path,search]);
 useEffect(()=>{if(focusField){const element=document.getElementById(`se-${focusField}`);element?.focus();setFocusField(null);}},[focusField,advanced]);
 const create=trpc.services.create.useMutation(),update=trpc.services.update.useMutation(),utils=trpc.useUtils();
 const parsed=parseServiceDraft(draft),errors={...parsed.errors},latest=current?.record?.entity==='service'?current.record:null;
 if(draft.categoryId!==null&&(!names.category[draft.categoryId]||latest?.fields.categoryId===draft.categoryId&&!latest.references.some(row=>row.kind==='category'&&row.id===draft.categoryId)))errors.categoryId='reference';
 if(draft.staffIds?.some(value=>!names.staff[value]||latest?.fields.staffIds?.includes(value)&&!latest.references.some(row=>row.kind==='staff'&&row.id===value)))errors.staffIds='reference';
 const stale=conflict||!!current&&current.record?.definition!==record?.definition,canManage=!!current?.canManage&&seed.canManage,canSave=canManage&&!refreshing&&!!current&&!stale&&!uncertain&&!!parsed.value&&!Object.keys(errors).length;
 const disabled=busy||uncertain||!seed.canManage,patch=<K extends keyof ServiceDraft>(key:K,value:ServiceDraft[K])=>{setDraft(previous=>({...previous,[key]:value}));setFailure('');};
 const errorText=(key:keyof ServiceDraft)=>errors[key]==='reference'?label('referencesUnavailable'):errors[key]==='range'?label('rangeError'):['basePrice','minPrice','maxPrice'].includes(key)?label('moneyError'):key==='name'?label('nameError'):key==='description'?label('descriptionError'):key==='durationMinutes'?label('durationError'):key==='bufferTimeMinutes'?label('bufferError'):key==='maxBookingsPerDay'?label('positiveError'):['advanceBookingDays','displayOrder'].includes(key)?label('integerError'):key==='staffIds'?label('repairSelection'):label('fieldError');
 const fieldError=(key:keyof ServiceDraft)=>(attempted||touched.includes(key))&&errors[key]?errorText(key):'';
 const blur=(key:string)=>setTouched(values=>values.includes(key)?values:[...values,key]);
 const input=(key:'name'|'description'|'category'|'basePrice'|'minPrice'|'maxPrice'|'durationMinutes'|'bufferTimeMinutes'|'maxBookingsPerDay'|'advanceBookingDays'|'displayOrder',options:{hint?:string;multiline?:boolean;required?:boolean}={})=>{
  const error=fieldError(key),numeric=!['name','description','category'].includes(key),props={id:`se-${key}`,value:draft[key],disabled,onChange:(event:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>patch(key,event.target.value),onBlur:()=>blur(key),'aria-invalid':!!error,'aria-describedby':[error?`se-${key}-error`:'',options.hint?`se-${key}-hint`:''].filter(Boolean).join(' ')||undefined,'aria-required':options.required,maxLength:key==='name'?255:key==='description'?8000:key==='category'?100:30};
  return <div className="se-field"><label htmlFor={props.id}>{label(key==='description'?'descriptionField':key)}{options.required&&<span aria-hidden="true"> *</span>}</label>{options.multiline?<textarea {...props} rows={4}/>:<input {...props} inputMode={numeric?['basePrice','minPrice','maxPrice'].includes(key)?'decimal':'numeric':undefined}/ >}{options.hint&&<p id={`se-${key}-hint`} className="sc-muted">{options.hint}</p>}{error&&<p id={`se-${key}-error`} className="se-error">{error}</p>}</div>;
 };
 const boolean=(key:'isActive'|'requiresAppointment')=><div className="se-field"><label htmlFor={`se-${key}`}>{label(key)}</label><select id={`se-${key}`} value={draft[key]===null?'':String(draft[key])} disabled={disabled} onBlur={()=>blur(key)} onChange={event=>patch(key,event.target.value===''?null:event.target.value==='true')} aria-invalid={!!fieldError(key)} aria-describedby={fieldError(key)?`se-${key}-error`:undefined}><option value="" disabled>{label('unknown')}</option><option value="true">{label(key==='isActive'?'active':'yes')}</option><option value="false">{label(key==='isActive'?'inactive':'no')}</option></select>{fieldError(key)&&<p className="se-error" id={`se-${key}-error`}>{fieldError(key)}</p>}</div>;
 const picker=(kind:'category'|'staff')=>{const key=kind==='category'?'categoryId':'staffIds';return <div className="se-field" id={`se-${key}`} tabIndex={-1} role="group" aria-labelledby={`se-${key}-label`} aria-describedby={fieldError(key)?`se-${key}-error`:undefined}><h3 id={`se-${key}-label`}>{label(key)}</h3><CatalogChoicePicker actorId={seed.actorId} merchantId={seed.merchantId} kind={kind} selected={kind==='category'?draft.categoryId===null?[]:[draft.categoryId]:draft.staffIds} names={names[kind]} disabled={disabled||!canManage} onNames={values=>setNames(previous=>({...previous,[kind]:{...previous[kind],...Object.fromEntries(values.map(value=>[value.id,value.name]))}}))} onChange={values=>{if(kind==='category')patch('categoryId',values[0]??null);else patch('staffIds',values);blur(key);}}/>{fieldError(key)&&<p className="se-error" id={`se-${key}-error`}>{fieldError(key)}</p>}</div>;};
 const open=(mode:'review'|'reload')=>{opener.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setDialog(mode);};
 const review=()=>{setAttempted(true);if(!canSave){const order: (keyof ServiceDraft)[]=['name','description','priceType','basePrice','minPrice','maxPrice','durationMinutes','isActive','categoryId','staffIds','bufferTimeMinutes','requiresAppointment','maxBookingsPerDay','advanceBookingDays','displayOrder','category'];const key=order.find(field=>errors[field]);if(key){if(!['name','description','priceType','basePrice','minPrice','maxPrice','durationMinutes','isActive'].includes(key))setAdvanced(true);setFocusField(key);}return;}setReviewed(JSON.stringify(parsed.value));open('review');};
 const save=async()=>{
  if(!canSave||!parsed.value||busy||lock.current||dialog!=='review'||reviewed!==JSON.stringify(parsed.value))return;
  const submitted=scope.current;lock.current=true;setBusy(true);setFailure('');
  try{const result=id?await update.mutateAsync({...parsed.value,serviceId:id,expectedDefinition:record!.definition}):await create.mutateAsync(parsed.value);
   if(!live.current||scope.current!==submitted)return;const saved=id??(result as {serviceId?:number}).serviceId;
   if(result.success!==true||!Number.isInteger(saved)||!saved||saved<1||saved>2147483647)throw Error('Unverified service result');
   setDialog(null);void utils.services.catalogWorkspace.invalidate().catch(()=>{});void utils.services.catalogEditor.invalidate().catch(()=>{});void utils.services.catalogRecord.invalidate().catch(()=>{});void utils.services.catalogChoices.invalidate().catch(()=>{});navigate(`/merchant/services/${saved}`);
  }catch(error){if(!live.current||scope.current!==submitted)return;const code=(error as {data?:{code?:string}})?.data?.code;if(code==='CONFLICT'){setConflict(true);setFailure(label('stale'));refresh();}else if(code==='BAD_REQUEST'||code==='NOT_FOUND'){setFailure(label('rejected'));setDialog(null);setAttempted(true);refresh();}else if(code==='FORBIDDEN'||code==='UNAUTHORIZED'){setFailure(label('forbidden'));refresh();}else{setUncertain(true);setFailure(label('saveError'));}}
  finally{lock.current=false;if(live.current)setBusy(false);}
 };
 const formattedPrice=()=>{const value=parseServiceDraft({...newServiceDraft,name:'preview',priceType:draft.priceType,basePrice:draft.basePrice,minPrice:draft.minPrice,maxPrice:draft.maxPrice}).value,format=(amount:number)=>new Intl.NumberFormat(locale,{style:'currency',currency:'SAR'}).format(amount/100);return !value?label('noPrice'):value.priceType==='custom'?label('custom'):value.priceType==='fixed'?format(value.basePrice!):`${format(value.minPrice!)} – ${format(value.maxPrice!)}`;};
 const summary=<dl className="se-summary"><div><dt>{label('name')}</dt><dd>{draft.name.trim()||label('noName')}</dd></div><div><dt>{label('priceType')}</dt><dd>{label(draft.priceType==='fixed'||draft.priceType==='variable'||draft.priceType==='custom'?draft.priceType:'unknown')}</dd></div><div><dt>{label('basePrice')}</dt><dd>{formattedPrice()}</dd></div><div><dt>{label('durationMinutes')}</dt><dd>{draft.durationMinutes?label('minutes',{value:draft.durationMinutes}):'—'}</dd></div><div><dt>{label('isActive')}</dt><dd>{label(draft.isActive===true?'active':draft.isActive===false?'inactive':'unknown')}</dd></div></dl>;
 return <div className="service-catalog service-editor" dir={rtl?'rtl':'ltr'}>
  <Link className="se-back" href="/merchant/services">{label('back')}</Link><header className="sc-header"><div><h1>{label(id?'editTitle':'title')}</h1><p>{label('description')}</p></div><Button variant="outline" disabled={busy||refreshing} onClick={refresh}><RefreshCw aria-hidden="true"/>{label('refresh')}</Button></header>
  {!canManage&&<p className="sc-feedback">{label('readOnly')}</p>}{!current&&<p className="sc-feedback" role="alert">{label('sourceError')}</p>}{stale&&<div className="sc-feedback" role="alert"><span>{label('stale')}</span><Button variant="outline" disabled={!current||refreshing||busy} onClick={()=>open('reload')}>{label('reload')}</Button></div>}{record&&(record.issues.length>0||record.unavailableReferences>0)&&<p className="sc-feedback">{label('savedInvalid')}</p>}{failure&&!dialog&&failure!==label('stale')&&<p className="sc-feedback" role="alert">{failure}</p>}{uncertain&&<Button asChild variant="outline"><Link href="/merchant/services">{label('viewList')}</Link></Button>}
  <div className="se-layout"><form noValidate onSubmit={event=>{event.preventDefault();review();}}><section className="se-panel"><h2>{label('basics')}</h2>{input('name',{required:true})}{input('description',{multiline:true})}<div className="se-field"><label htmlFor="se-priceType">{label('priceType')}</label><select id="se-priceType" disabled={disabled} value={draft.priceType} onBlur={()=>blur('priceType')} onChange={event=>patch('priceType',event.target.value)} aria-invalid={!!fieldError('priceType')} aria-describedby={fieldError('priceType')?'se-priceType-error':undefined}>{!['fixed','variable','custom'].includes(draft.priceType)&&<option value={draft.priceType}>{label('unknown')}</option>}{(['fixed','variable','custom'] as const).map(value=><option key={value} value={value}>{label(value)}</option>)}</select>{fieldError('priceType')&&<p className="se-error" id="se-priceType-error">{fieldError('priceType')}</p>}</div>{draft.priceType==='fixed'&&input('basePrice',{required:true})}{draft.priceType==='variable'&&<div className="se-columns">{input('minPrice',{required:true})}{input('maxPrice',{required:true})}</div>}{input('durationMinutes',{required:true})}{boolean('isActive')}</section>
   <details className="se-panel" open={advanced} onToggle={event=>setAdvanced(event.currentTarget.open)}><summary><strong>{label('advanced')}</strong><span>{label('advancedHint')}</span></summary><div className="se-advanced">{picker('category')}{picker('staff')}{input('bufferTimeMinutes',{hint:label('bufferError')})}{boolean('requiresAppointment')}<div className="se-columns">{input('maxBookingsPerDay',{hint:label('maxHint')})}{input('advanceBookingDays',{hint:label('advanceHint')})}</div>{input('displayOrder')}{input('category',{hint:label('categoryHint')})}</div></details>
   <div className="se-save"><p className="sc-muted">{label(busy?'saving':uncertain?'saveError':!current?'sourceError':stale?'stale':!canManage?'viewOnly':id&&!dirty?'unchanged':'unsaved')}</p><Button type="submit" disabled={busy||!canManage||refreshing||!current||stale||uncertain}><Eye aria-hidden="true"/>{label('review')}</Button></div></form><aside className="se-panel se-preview"><h2>{label('preview')}</h2>{summary}</aside></div>
  <Dialog open={!!dialog} onOpenChange={open=>{if(!open&&!busy)setDialog(null);}}><DialogContent className="sc-dialog se-dialog" dir={rtl?'rtl':'ltr'} closeLabel={label('cancel')} onOpenAutoFocus={event=>{event.preventDefault();heading.current?.focus();}} onCloseAutoFocus={event=>{event.preventDefault();if(opener.current?.isConnected)opener.current.focus();}}><DialogHeader><DialogTitle ref={heading} tabIndex={-1}>{label(dialog==='reload'?'reloadTitle':'reviewTitle')}</DialogTitle><DialogDescription>{label(dialog==='reload'?'reloadHint':'reviewHint')}</DialogDescription></DialogHeader>{dialog==='review'&&<>{summary}<dl className="se-summary"><div><dt>{label('descriptionField')}</dt><dd>{draft.description||'—'}</dd></div><div><dt>{label('categoryId')}</dt><dd>{draft.categoryId===null?label('noSelection'):names.category[draft.categoryId]}</dd></div><div><dt>{label('staffIds')}</dt><dd>{draft.staffIds?.length?draft.staffIds.map(value=>names.staff[value]).join('، '):label('noSelection')}</dd></div><div><dt>{label('requiresAppointment')}</dt><dd>{label(draft.requiresAppointment?'yes':'no')}</dd></div>{(['bufferTimeMinutes','maxBookingsPerDay','advanceBookingDays','displayOrder','category'] as const).map(key=><div key={key}><dt>{label(key)}</dt><dd>{draft[key]||label(key==='maxBookingsPerDay'?'unlimited':'noSelection')}</dd></div>)}</dl></>}{failure&&<p className="sc-feedback" role="alert">{failure}</p>}{stale&&dialog==='review'&&!failure&&<p role="alert">{label('stale')}</p>}<DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setDialog(null)}>{label('cancel')}</Button><Button disabled={dialog==='reload'?!current||refreshing||busy:!canSave||busy||reviewed!==JSON.stringify(parsed.value)} onClick={()=>{if(dialog==='reload')reload();else void save();}}><Check aria-hidden="true"/>{label(dialog==='reload'?'reload':'confirm')}</Button></DialogFooter></DialogContent></Dialog>
 </div>;
}
