import {useEffect,useRef,useState} from 'react';
import {Link,useLocation,useSearch} from 'wouter';
import {useTranslation} from 'react-i18next';
import {RefreshCw,Eye,Check} from 'lucide-react';
import {trpc} from '@/lib/trpc';
import {serviceCollectionLabels} from '@/lib/service-collection-labels';
import {newCollectionDraft,collectionDraftFromRecord,parseCollectionDraft,type CollectionEntity,type CollectionDraft} from '@/lib/service-collection-form';
import {catalogEditorContextSchema,type CatalogEditorContext} from '@shared/service-catalog-workspace';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {WorkspaceState,workspaceFailureKind} from './WorkspaceState';
import {CatalogChoicePicker} from './CatalogChoicePicker';
import '@/styles/service-catalog-workspace.css';
import '@/styles/service-editor-workspace.css';
export function ServiceCollectionEditor({actorId,merchantId,entity,id,backHref}:{actorId:number;merchantId:number;entity:CollectionEntity;id?:number;backHref:string}){
 const query=trpc.services.catalogEditor.useQuery({entity,id},{retry:false,staleTime:0,refetchOnMount:'always'}),parsed=catalogEditorContextSchema.safeParse(query.data);
 const current=!query.error&&parsed.success&&parsed.data.actorId===actorId&&parsed.data.merchantId===merchantId&&parsed.data.selection.entity===entity&&parsed.data.selection.id===id?parsed.data:null;
 const [seed,setSeed]=useState<CatalogEditorContext|null>(null),[version,setVersion]=useState(0);
 useEffect(()=>{if(current&&!seed&&!query.isFetching)setSeed(current);},[current,seed,query.isFetching]);
 const refresh=()=>{void query.refetch();};
 if(!seed){if(query.error)return <WorkspaceState kind={workspaceFailureKind(query.error)} onRetry={refresh}/>;return <WorkspaceState kind={query.isLoading||query.isFetching||current?'loading':'error'} onRetry={refresh}/>;}
 return <CollectionForm key={version} entity={entity} seed={seed} current={current} backHref={backHref} refreshing={query.isFetching} refresh={refresh} reload={()=>{if(current&&!query.isFetching){setSeed(current);setVersion(v=>v+1);}}}/>;
}
function CollectionForm({entity,seed,current,backHref,refreshing,refresh,reload}:{entity:CollectionEntity;seed:CatalogEditorContext;current:CatalogEditorContext|null;backHref:string;refreshing:boolean;refresh:()=>void;reload:()=>void}){
 const {t,i18n}=useTranslation(),label=serviceCollectionLabels(t),[path,navigate]=useLocation(),search=useSearch(),rtl=i18n.language.startsWith('ar');
 const record=seed.record?.entity===entity?seed.record:null,id=record?.id,latest=current?.record?.entity===entity?current.record:null;
 const [draft,setDraft]=useState<CollectionDraft>(()=>record?collectionDraftFromRecord(record):{...newCollectionDraft,serviceIds:[]});
 const initialDraft=useRef(JSON.stringify(draft)),dirty=JSON.stringify(draft)!==initialDraft.current;
 const [names,setNames]=useState<Record<number,string>>(()=>Object.fromEntries((record?.references??[]).filter(r=>r.kind==='service').map(r=>[r.id,r.name])));
 const [attempted,setAttempted]=useState(false),[touched,setTouched]=useState<string[]>([]),[advanced,setAdvanced]=useState(false),[focusField,setFocusField]=useState<string|null>(null);
 const [dialog,setDialog]=useState<'review'|'reload'|null>(null),[reviewed,setReviewed]=useState(''),[busy,setBusy]=useState(false),[failure,setFailure]=useState(''),[uncertain,setUncertain]=useState(false),[conflict,setConflict]=useState(false);
 const live=useRef(true),lock=useRef(false),scope=useRef(''),opener=useRef<HTMLElement|null>(null),heading=useRef<HTMLHeadingElement|null>(null);
 scope.current=`${seed.actorId}:${seed.merchantId}:${entity}:${id??'new'}:${path}:${search}`;
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 useEffect(()=>{setDialog(null);},[path,search]);
 useEffect(()=>{if(focusField){document.getElementById(`scf-${focusField}`)?.focus();setFocusField(null);}},[focusField,advanced]);
 const createCategory=trpc.serviceCategories.create.useMutation(),updateCategory=trpc.serviceCategories.update.useMutation(),createPackage=trpc.servicePackages.create.useMutation(),updatePackage=trpc.servicePackages.update.useMutation(),utils=trpc.useUtils();
 const parsed=parseCollectionDraft(entity,draft),errors={...parsed.errors};
 if(entity==='package'&&draft.serviceIds?.some(value=>!names[value]||latest?.entity==='package'&&latest.fields.serviceIds?.includes(value)&&!latest.references.some(r=>r.kind==='service'&&r.id===value)))errors.serviceIds='reference';
 const stale=conflict||!!current&&current.record?.definition!==record?.definition,canManage=!!current?.canManage&&seed.canManage,canSave=canManage&&!refreshing&&!!current&&!stale&&!uncertain&&!!parsed.result&&!Object.keys(errors).length;
 const disabled=busy||uncertain||!canManage,patch=<K extends keyof CollectionDraft>(key:K,value:CollectionDraft[K])=>{setDraft(d=>({...d,[key]:value}));setFailure('');},blur=(key:string)=>setTouched(keys=>keys.includes(key)?keys:[...keys,key]);
 const errorText=(key:keyof CollectionDraft)=>errors[key]==='reference'?label('referencesUnavailable'):errors[key]==='range'?label('packageRange'):key==='serviceIds'?label('servicesError'):key==='name'?label('nameError'):key==='description'?label('descriptionError'):key==='color'?label('colorError'):key==='displayOrder'?label('orderHint'):key==='originalPrice'||key==='packagePrice'?label('moneyError'):label('fieldError');
 const fieldError=(key:keyof CollectionDraft)=>(attempted||touched.includes(key))&&errors[key]?errorText(key):'';
 const input=(key:'name'|'description'|'nameEn'|'icon'|'color'|'displayOrder'|'originalPrice'|'packagePrice',hint?:string)=>{
  const error=fieldError(key),numeric=['originalPrice','packagePrice','displayOrder'].includes(key),required=['name','originalPrice','packagePrice'].includes(key),props={id:`scf-${key}`,value:draft[key],disabled,onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>patch(key,e.target.value),onBlur:()=>blur(key),'aria-invalid':!!error,'aria-required':required,'aria-describedby':[error?`scf-${key}-error`:'',hint?`scf-${key}-hint`:''].filter(Boolean).join(' ')||undefined,maxLength:key==='name'||key==='nameEn'?255:key==='description'?8000:key==='icon'?100:30};
  return <div className="se-field"><label htmlFor={props.id}>{label(key==='description'?'descriptionField':key)}{required&&<span aria-hidden="true"> *</span>}</label>{key==='description'?<textarea {...props} rows={3}/>:<input {...props} dir={key==='color'?'ltr':undefined} inputMode={numeric?key==='displayOrder'?'numeric':'decimal':undefined}/>}{hint&&<p className="sc-muted" id={`scf-${key}-hint`}>{hint}</p>}{error&&<p className="se-error" id={`scf-${key}-error`}>{error}</p>}</div>;
 };
 const status=<div className="se-field"><label htmlFor="scf-isActive">{label('isActive')}</label><select id="scf-isActive" value={draft.isActive===null?'':String(draft.isActive)} disabled={disabled} onChange={e=>patch('isActive',e.target.value===''?null:e.target.value==='true')} onBlur={()=>blur('isActive')} aria-invalid={!!fieldError('isActive')} aria-describedby={fieldError('isActive')?'scf-isActive-error':undefined}><option value="" disabled>{label('unknown')}</option><option value="true">{label('active')}</option><option value="false">{label('inactive')}</option></select>{fieldError('isActive')&&<p className="se-error" id="scf-isActive-error">{fieldError('isActive')}</p>}</div>;
 const open=(mode:'review'|'reload')=>{opener.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setDialog(mode);};
 const review=()=>{setAttempted(true);if(!canSave){const order:(keyof CollectionDraft)[]=entity==='category'?['name','description','isActive','nameEn','icon','color','displayOrder']:['name','description','serviceIds','originalPrice','packagePrice','isActive'];const field=order.find(k=>errors[k]);if(field){if(['nameEn','icon','color','displayOrder'].includes(field))setAdvanced(true);setFocusField(field);}return;}setReviewed(JSON.stringify(parsed.result));open('review');};
 const save=async()=>{
  if(!canSave||!parsed.result||busy||lock.current||dialog!=='review'||reviewed!==JSON.stringify(parsed.result))return;
  const submitted=scope.current;lock.current=true;setBusy(true);setFailure('');
  try{
   const result=parsed.result.entity==='category'?(id?await updateCategory.mutateAsync({...parsed.result.value,categoryId:id,expectedDefinition:record!.definition}):await createCategory.mutateAsync(parsed.result.value)):(id?await updatePackage.mutateAsync({...parsed.result.value,packageId:id,expectedDefinition:record!.definition}):await createPackage.mutateAsync(parsed.result.value));
   if(!live.current||scope.current!==submitted)return;
   const saved=id??(result as {categoryId?:number;packageId?:number})[entity==='category'?'categoryId':'packageId'];
   if(result.success!==true||!Number.isInteger(saved)||!saved||saved<1||saved>2147483647)throw Error('Unverified catalog save');
   setDialog(null);void utils.services.catalogWorkspace.invalidate().catch(()=>{});void utils.services.catalogEditor.invalidate().catch(()=>{});void utils.services.catalogRecord.invalidate().catch(()=>{});void utils.services.catalogChoices.invalidate().catch(()=>{});navigate(backHref);
  }catch(error){if(!live.current||scope.current!==submitted)return;const code=(error as {data?:{code?:string}})?.data?.code;if(code==='CONFLICT'){setConflict(true);setFailure(label('stale'));refresh();}else if(code==='BAD_REQUEST'||code==='NOT_FOUND'){setFailure(label('rejected'));setDialog(null);setAttempted(true);refresh();}else if(code==='FORBIDDEN'||code==='UNAUTHORIZED'){setFailure(label('forbidden'));refresh();}else{setUncertain(true);setFailure(label('saveError'));}}
  finally{lock.current=false;if(live.current)setBusy(false);}
 };
 // Price preview stays useful while the name and selections are still incomplete.
 const preview=parseCollectionDraft('package',{...newCollectionDraft,name:'preview',serviceIds:[1],originalPrice:draft.originalPrice,packagePrice:draft.packagePrice}).result;
 const amounts=preview?.entity==='package'?preview.value:null,money=(value:number)=>new Intl.NumberFormat(rtl?'ar-SA':'en-US',{style:'currency',currency:'SAR'}).format(value/100);
 const summary=<dl className="se-summary"><div><dt>{label('name')}</dt><dd>{draft.name.trim()||label('noName')}</dd></div><div><dt>{label('isActive')}</dt><dd>{label(draft.isActive===true?'active':draft.isActive===false?'inactive':'unknown')}</dd></div>{entity==='package'?<><div><dt>{label('originalPrice')}</dt><dd>{amounts?money(amounts.originalPrice):label('noPrice')}</dd></div><div><dt>{label('packagePrice')}</dt><dd>{amounts?money(amounts.packagePrice):label('noPrice')}</dd></div><div><dt>{label('discount')}</dt><dd>{amounts?label('discountValue',{value:amounts.discountPercentage}):'—'}</dd></div><div><dt>{label('saving')}</dt><dd>{amounts?money(amounts.originalPrice-amounts.packagePrice):'—'}</dd></div><div><dt>{label('serviceIds')}</dt><dd>{draft.serviceIds===null?label('repairSelection'):draft.serviceIds.map(value=>names[value]??label('unavailableSelection',{id:value})).join('، ')||label('noSelection')}</dd></div></>:<>{(['nameEn','icon','color','displayOrder'] as const).map(key=><div key={key}><dt>{label(key)}</dt><dd>{draft[key]||label('emptyValue')}</dd></div>)}</>}</dl>;
 return <div className="service-catalog service-editor" dir={rtl?'rtl':'ltr'}><Link className="se-back" href={backHref}>{label('back')}</Link><header className="sc-header"><div><h1>{label(entity==='category'?id?'categoryEdit':'categoryCreate':id?'packageEdit':'packageCreate')}</h1><p>{label('description')}</p></div><Button variant="outline" disabled={busy||refreshing} onClick={refresh}><RefreshCw aria-hidden="true"/>{label('refresh')}</Button></header>
  {!canManage&&<p className="sc-feedback">{label('readOnly')}</p>}{!current&&<p className="sc-feedback" role="alert">{label('sourceError')}</p>}{stale&&<div className="sc-feedback" role="alert"><span>{label('stale')}</span><Button variant="outline" disabled={!current||refreshing||busy} onClick={()=>open('reload')}>{label('reload')}</Button></div>}{record&&(record.issues.length>0||record.unavailableReferences>0)&&<p className="sc-feedback">{label('savedInvalid')}</p>}{failure&&!dialog&&failure!==label('stale')&&<p className="sc-feedback" role="alert">{failure}</p>}{uncertain&&<Button asChild variant="outline"><Link href={backHref}>{label('viewList')}</Link></Button>}
  <div className="se-layout"><form noValidate onSubmit={e=>{e.preventDefault();review();}}><section className="se-panel"><h2>{label('basics')}</h2>{input('name')}{input('description')}{entity==='package'&&<><div className="se-field" id="scf-serviceIds" tabIndex={-1} role="group" aria-labelledby="scf-serviceIds-label" aria-describedby={fieldError('serviceIds')?'scf-serviceIds-error':'scf-serviceIds-hint'}><h3 id="scf-serviceIds-label">{label('serviceIds')}</h3><p className="sc-muted" id="scf-serviceIds-hint">{label('selectionNote')}</p><CatalogChoicePicker actorId={seed.actorId} merchantId={seed.merchantId} kind="service" selected={draft.serviceIds} names={names} disabled={disabled} onNames={values=>setNames(previous=>({...previous,...Object.fromEntries(values.map(v=>[v.id,v.name]))}))} onChange={values=>{patch('serviceIds',values);blur('serviceIds');}}/>{fieldError('serviceIds')&&<p id="scf-serviceIds-error" className="se-error">{fieldError('serviceIds')}</p>}</div><div className="se-columns">{input('originalPrice')}{input('packagePrice')}</div><p className="sc-muted">{label('calculated')}</p></>}{status}</section>
   {entity==='category'&&<details className="se-panel" open={advanced} onToggle={e=>setAdvanced(e.currentTarget.open)}><summary><strong>{label('advanced')}</strong><span>{label('advancedHint')}</span></summary><div className="se-advanced">{input('nameEn')}{input('icon',label('iconHint'))}{input('color',label('colorHint'))}{input('displayOrder',label('orderHint'))}</div></details>}
   <div className="se-save"><p className="sc-muted">{label(busy?'saving':uncertain?'saveError':!current?'sourceError':stale?'stale':!canManage?'viewOnly':id&&!dirty?'unchanged':'unsaved')}</p><Button type="submit" disabled={busy||!canManage||refreshing||!current||stale||uncertain}><Eye aria-hidden="true"/>{label('review')}</Button></div></form><aside className="se-panel se-preview"><h2>{label('preview')}</h2>{summary}</aside></div>
  <Dialog open={!!dialog} onOpenChange={open=>{if(!open&&!busy)setDialog(null);}}><DialogContent className="sc-dialog se-dialog" dir={rtl?'rtl':'ltr'} closeLabel={label('cancel')} onOpenAutoFocus={e=>{e.preventDefault();heading.current?.focus();}} onCloseAutoFocus={e=>{e.preventDefault();if(opener.current?.isConnected)opener.current.focus();}}><DialogHeader><DialogTitle ref={heading} tabIndex={-1}>{label(dialog==='reload'?'reloadTitle':'reviewTitle')}</DialogTitle><DialogDescription>{label(dialog==='reload'?'reloadHint':'reviewHint')}</DialogDescription></DialogHeader>{dialog==='review'&&<>{summary}<dl className="se-summary"><div><dt>{label('descriptionField')}</dt><dd>{draft.description||label('emptyValue')}</dd></div></dl></>}{failure&&<p className="sc-feedback" role="alert">{failure}</p>}{stale&&dialog==='review'&&!failure&&<p role="alert">{label('stale')}</p>}<DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setDialog(null)}>{label('cancel')}</Button><Button disabled={dialog==='reload'?!current||refreshing||busy:!canSave||busy||reviewed!==JSON.stringify(parsed.result)} onClick={()=>{if(dialog==='reload')reload();else void save();}}><Check aria-hidden="true"/>{label(dialog==='reload'?'reload':'confirm')}</Button></DialogFooter></DialogContent></Dialog>
 </div>;
}
