import {serviceCollectionLabels,serviceCollectionListLabels} from '@/lib/service-collection-labels';
import type {CollectionEntity} from '@/lib/service-collection-form';
import {serviceCatalogLabels} from '@/lib/service-catalog-labels';
import {useEffect,useRef,useState} from 'react';
import {Link,useLocation,useSearch} from 'wouter';
import {useTranslation} from 'react-i18next';
import {Plus,RefreshCw,Layers,Folder,Search,Clock3,CalendarCheck,AlertCircle,ArrowUpRight,Pause} from 'lucide-react';
import {trpc} from '@/lib/trpc';
import {catalogWorkspaceSchema,type CatalogRecord} from '@shared/service-catalog-workspace';
import {catalogNavigation,catalogHref,catalogSelectionKey} from '@/lib/service-catalog-navigation';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {WorkspaceState,workspaceFailureKind} from './WorkspaceState';
import '@/styles/service-catalog-workspace.css';

type Service=Extract<CatalogRecord,{entity:'service'}>;
type Scope={actorId:number;merchantId:number};
export function ServiceCatalogList(props:Scope){const archive=trpc.services.delete.useMutation();return <CatalogList {...props} entity="service" archiveRow={row=>archive.mutateAsync({serviceId:row.id,expectedDefinition:row.definition})}/>;}
export function ServiceCollectionList(props:Scope&{entity:CollectionEntity}){const category=trpc.serviceCategories.delete.useMutation(),pkg=trpc.servicePackages.delete.useMutation();return <CatalogList {...props} archiveRow={row=>props.entity==='category'?category.mutateAsync({categoryId:row.id,expectedDefinition:row.definition}):pkg.mutateAsync({packageId:row.id,expectedDefinition:row.definition})}/>;}
function CatalogList({actorId,merchantId,entity,archiveRow}:Scope&{entity:'service'|CollectionEntity;archiveRow:(row:CatalogRecord)=>Promise<{success:boolean}>}){
 const {t,i18n}=useTranslation(),[path,navigate]=useLocation(),search=useSearch(),selection=catalogNavigation(search,entity);
 const text=entity==='service'?serviceCatalogLabels(t):serviceCollectionListLabels(t,entity),collection=serviceCollectionLabels(t);
 const createHref=entity==='service'?'/merchant/services/new':catalogHref(path,search,{edit:'new'}),editHref=(id:number)=>entity==='service'?`/merchant/services/${id}/edit`:catalogHref(path,search,{edit:id});
 const [searchEdit,setSearchEdit]=useState<{source:string;value:string}|null>(null),[action,setAction]=useState<{row:CatalogRecord;view:string}|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[failure,setFailure]=useState(''),[needsRefresh,setNeedsRefresh]=useState(false);
 const view=useRef(''),live=useRef(true),lock=useRef(false),opener=useRef<HTMLElement|null>(null);view.current=`${actorId}:${merchantId}:${path}:${search}`;
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 useEffect(()=>{setAction(null);setSearchEdit(null);setNotice('');setFailure('');},[search]);
 const query=trpc.services.catalogWorkspace.useQuery(selection,{retry:false,staleTime:0,refetchOnMount:'always'});
 const parsed=catalogWorkspaceSchema.safeParse(query.data),key=catalogSelectionKey(selection);
 const matches=parsed.success&&parsed.data.actorId===actorId&&parsed.data.merchantId===merchantId&&catalogSelectionKey(parsed.data.selection)===key;
 const data=!query.error&&matches?parsed.data:undefined;
 const change=(patch:Record<string,string|number|null>)=>navigate(catalogHref(path,search,patch));
 const refresh=async()=>{const scope=view.current;const result=await query.refetch();if(!live.current||scope!==view.current)return;const checked=catalogWorkspaceSchema.safeParse(result.data);if(!result.error&&checked.success&&checked.data.actorId===actorId&&checked.data.merchantId===merchantId&&catalogSelectionKey(checked.data.selection)===key){setNeedsRefresh(false);setFailure('');setAction(null);}};
 const current=action&&data?.rows.find(row=>row.id===action.row.id),unchanged=!!action&&action.view===view.current&&current?.definition===action.row.definition;
 const canConfirm=!!data?.canManage&&unchanged&&!query.isFetching&&!busy&&!needsRefresh;
 const confirm=async()=>{
  if(!action||!canConfirm||lock.current)return;const submitted=action;lock.current=true;setBusy(true);setFailure('');
  try{const result=await archiveRow(submitted.row);if(result?.success!==true)throw Error('Unverified catalog operation');if(live.current&&submitted.view===view.current){setAction(null);setNotice(text('archiveSuccess'));setNeedsRefresh(true);await refresh();}}
  catch(error){if(live.current&&submitted.view===view.current){setFailure(text((error as {data?:{code?:string}})?.data?.code==='CONFLICT'?'conflict':'actionError'));setNeedsRefresh(true);}}
  finally{lock.current=false;if(live.current)setBusy(false);}
 };
 if(query.error)return <WorkspaceState kind={workspaceFailureKind(query.error)} onRetry={()=>{void refresh();}}/>;
 if(!data)return <WorkspaceState kind={query.isLoading||query.isFetching?'loading':'error'} onRetry={()=>{void refresh();}}/>;
 const locale=i18n.language.startsWith('ar')?'ar-SA':'en-US',number=(value:number)=>value.toLocaleString(locale),money=(value:number)=>new Intl.NumberFormat(locale,{style:'currency',currency:'SAR'}).format(value/100);
 const price=(row:Service)=>{const f=row.fields;if(row.issues.some(issue=>['priceType','basePrice','minPrice','maxPrice'].includes(issue)))return text('unavailable');if(f.priceType==='custom')return text('customPrice');if(f.priceType==='fixed'&&f.basePrice!==null&&f.basePrice>=0)return money(f.basePrice);if(f.priceType==='variable'&&f.minPrice!==null&&f.maxPrice!==null&&f.minPrice>=0&&f.maxPrice>=f.minPrice)return text('range',{min:money(f.minPrice),max:money(f.maxPrice)});return text('unavailable');};
 const filtered=!!selection.search||selection.status!=='all',name=(row:CatalogRecord)=>row.fields.name.trim()||text('unnamed');
 return <div className="service-catalog" dir={i18n.language.startsWith('ar')?'rtl':'ltr'}>
  <header className="sc-header"><div><p className="sc-eyebrow">{text('eyebrow')}</p><h1>{text('title')}</h1><p>{text('description')}</p></div><div className="sc-actions"><Button variant="outline" disabled={query.isFetching||busy} onClick={()=>{void refresh();}}><RefreshCw aria-hidden="true"/>{text('refresh')}</Button>{data.canManage&&<Button asChild><Link href={createHref}><Plus aria-hidden="true"/>{text('create')}</Link></Button>}</div></header>
  <nav className="sc-nav" aria-label={text('title')}>{entity!=='service'&&<Link href="/merchant/services">{t('merchantUx.serviceEditor.back')}</Link>}<Link href="/merchant/service-categories"><Folder aria-hidden="true"/>{text('categories')}<ArrowUpRight aria-hidden="true"/></Link><Link href="/merchant/service-packages"><Layers aria-hidden="true"/>{text('packages')}<ArrowUpRight aria-hidden="true"/></Link></nav>
  {!data.canManage&&<p className="sc-muted">{text('readOnly')}</p>}{notice&&<p role="status" className="sc-feedback">{notice}</p>}{needsRefresh&&!action&&<p role="alert" className="sc-feedback"><span>{failure||text('actionError')}</span><Button variant="outline" disabled={busy||query.isFetching} onClick={()=>{void refresh();}}>{text('reviewState')}</Button></p>}
  <dl className="sc-summary"><div><dt>{text('total')}</dt><dd>{number(data.summary.total)}</dd></div><div><dt>{text('active')}</dt><dd>{number(data.summary.active)}</dd></div><div><dt>{text('inactive')}</dt><dd>{number(data.summary.inactive)}</dd></div>{data.summary.unknown>0&&<div><dt>{text('unknown')}</dt><dd>{number(data.summary.unknown)}</dd></div>}</dl>
  {data.summary.unknown>0&&<p className="sc-feedback"><AlertCircle aria-hidden="true"/>{text('unknownHint')}</p>}
  <section className="sc-list" aria-busy={query.isFetching}>
   <form className="sc-filters" onSubmit={event=>{event.preventDefault();change({q:searchEdit?.source===search?searchEdit.value.trim():selection.search,page:null});}}><label className="sc-search"><span>{text('search')}</span><div><Search aria-hidden="true"/><input value={searchEdit?.source===search?searchEdit.value:selection.search} maxLength={200} placeholder={text('searchHint')} onChange={event=>setSearchEdit({source:search,value:event.target.value})}/></div></label><Button type="submit" variant="outline">{text('searchAction')}</Button><label><span>{text('status')}</span><select value={selection.status} onChange={event=>change({status:event.target.value,page:null})}>{(['all','active','inactive','unknown'] as const).map(status=><option key={status} value={status}>{text(status)}</option>)}</select></label>{filtered&&<Button variant="ghost" type="button" onClick={()=>change({q:null,status:null,page:null})}>{text('clear')}</Button>}</form>
   <p className="sc-results" role="status">{query.isFetching?text('loadingUpdate'):text('results',{total:number(data.pagination.total)})}</p>
   {!data.rows.length?<div className="sc-empty"><Layers aria-hidden="true"/><h2>{text(selection.page>1?'outOfRange':filtered?'noResults':'empty')}</h2><p>{text(filtered?'noResultsHint':'emptyHint')}</p>{selection.page>1?<Button onClick={()=>change({page:null})}>{text('first')}</Button>:filtered?<Button variant="outline" onClick={()=>change({q:null,status:null,page:null})}>{text('clear')}</Button>:data.canManage?<Button asChild><Link href={createHref}>{text('create')}</Link></Button>:null}</div>:
    <ul className="sc-records">{data.rows.map(row=>{const f=row.fields,repair=row.issues.length>0||row.unavailableReferences>0;return <li key={row.id} className="sc-record" data-service-id={row.id}>
     <div className="sc-record-title"><div>{row.entity==='service'&&<p className="sc-muted">{row.categoryName??text(row.fields.categoryId===null?'uncategorized':'categoryUnavailable')}</p>}<Link href={row.entity==='service'?'/merchant/services/'+row.id:editHref(row.id)}><h2>{name(row)}</h2></Link>{row.entity==='category'&&row.fields.nameEn&&<p className="sc-muted" lang="en" dir="ltr">{row.fields.nameEn}</p>}</div><Badge variant={f.isActive===true?'default':'secondary'}>{text(f.isActive===true?'active':f.isActive===false?'inactive':'unknown')}</Badge></div>
     {f.description&&<p className="sc-description">{f.description}</p>}
     {row.entity==='service'?<><dl className="sc-facts"><div><dt>{text('price')}</dt><dd>{price(row)}</dd></div><div><dt><Clock3 aria-hidden="true"/>{text('duration')}</dt><dd>{row.fields.durationMinutes!==null&&!row.issues.includes('durationMinutes')?text('minutes',{value:number(row.fields.durationMinutes)}):text('unavailable')}</dd></div></dl><p className="sc-appointment"><CalendarCheck aria-hidden="true"/>{text(row.fields.requiresAppointment===true?'appointment':row.fields.requiresAppointment===false?'noAppointment':'unavailable')}</p></>:
      row.entity==='category'?<dl className="sc-facts"><div><dt>{collection('icon')}</dt><dd>{row.fields.icon||collection('emptyValue')}</dd></div><div><dt>{collection('color')}</dt><dd>{row.fields.color&&!row.issues.includes('color')?<span className="sc-color"><i aria-hidden="true" style={{backgroundColor:row.fields.color}}/>{row.fields.color}</span>:collection('emptyValue')}</dd></div><div><dt>{collection('displayOrder')}</dt><dd>{row.fields.displayOrder!==null&&!row.issues.includes('displayOrder')?number(row.fields.displayOrder):text('unavailable')}</dd></div></dl>:
      <dl className="sc-facts"><div><dt>{collection('serviceIds')}</dt><dd>{row.fields.serviceIds===null?text('unavailable'):row.fields.serviceIds.map(id=>row.references.find(r=>r.kind==='service'&&r.id===id)?.name??collection('unavailableSelection',{id})).join('، ')||collection('noSelection')}</dd></div><div><dt>{collection('originalPrice')}</dt><dd>{row.fields.originalPrice!==null&&!row.issues.includes('originalPrice')?money(row.fields.originalPrice):text('unavailable')}</dd></div><div><dt>{collection('packagePrice')}</dt><dd>{row.fields.packagePrice!==null&&!row.issues.includes('packagePrice')?money(row.fields.packagePrice):text('unavailable')}</dd></div><div><dt>{collection('discount')}</dt><dd>{row.fields.discountPercentage!==null&&!row.issues.some(key=>['discountPercentage','originalPrice','packagePrice'].includes(key))?collection('discountValue',{value:number(row.fields.discountPercentage)}):text('unavailable')}</dd></div></dl>}
     {repair&&<div className="sc-repair"><AlertCircle aria-hidden="true"/><div><strong>{text('repair')}</strong><p>{text('repairHint')}</p></div></div>}
     <div className="sc-record-actions">{row.entity==='service'&&<Button asChild variant="outline"><Link href={'/merchant/services/'+row.id}>{text('details')}</Link></Button>}{(data.canManage||row.entity!=='service')&&<Button asChild variant="ghost"><Link href={editHref(row.id)}>{text(data.canManage?'edit':'details')}</Link></Button>}{data.canManage&&f.isActive!==false&&<Button variant="ghost" disabled={busy||query.isFetching||needsRefresh} aria-label={text('archiveNamed',{name:name(row)})} onClick={()=>{opener.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setFailure('');setAction({row,view:view.current});}}><Pause aria-hidden="true"/>{text('archive')}</Button>}</div>
    </li>;})}</ul>}
   {data.pagination.pages>0&&<nav className="sc-pagination" aria-label={text('title')}><Button variant="outline" disabled={selection.page<=1||busy} onClick={()=>change({page:selection.page-1})}>{text('previous')}</Button><span>{text('page',{page:number(selection.page),pages:number(data.pagination.pages)})}</span><Button variant="outline" disabled={selection.page>=data.pagination.pages||busy} onClick={()=>change({page:selection.page+1})}>{text('next')}</Button></nav>}
  </section>
  <Dialog open={!!action} onOpenChange={open=>{if(!open&&!busy)setAction(null);}}><DialogContent className="sc-dialog" closeLabel={text('cancel')} dir={i18n.language.startsWith('ar')?'rtl':'ltr'} onCloseAutoFocus={event=>{event.preventDefault();if(opener.current?.isConnected)opener.current.focus();}}><DialogHeader><DialogTitle>{text('archiveTitle',{name:action?name(action.row):''})}</DialogTitle><DialogDescription>{text('archiveHint')}</DialogDescription></DialogHeader>{!unchanged&&<p role="alert" className="sc-feedback">{text('changed')}</p>}{failure&&<p role="alert" className="sc-feedback">{failure}</p>}{needsRefresh&&<Button variant="outline" disabled={busy||query.isFetching} onClick={()=>{void refresh();}}>{text('reviewState')}</Button>}<DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setAction(null)}>{text('cancel')}</Button><Button disabled={!canConfirm} onClick={()=>{void confirm();}}>{text('confirmArchive')}</Button></DialogFooter></DialogContent></Dialog>
 </div>;
}
