import {Link} from 'wouter';
import {useTranslation} from 'react-i18next';
import {RefreshCw,Edit,Calendar,Star} from 'lucide-react';
import {trpc} from '@/lib/trpc';
import {serviceDetailsSchema,serviceBookingStatus} from '@shared/service-details-workspace';
import {serviceDetailsLabels} from '@/lib/service-details-labels';
import {serviceEditorLabels} from '@/lib/service-editor-labels';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {WorkspaceState,workspaceFailureKind} from './WorkspaceState';
import '@/styles/service-catalog-workspace.css';
import '@/styles/service-editor-workspace.css';
import '@/styles/service-details-workspace.css';
export function ServiceDetailsWorkspace({actorId,merchantId,serviceId}:{actorId:number;merchantId:number;serviceId:number}){
 const {t,i18n}=useTranslation(),text=serviceDetailsLabels(t),field=serviceEditorLabels(t),rtl=i18n.language.startsWith('ar'),locale=rtl?'ar-SA':'en-US';
 const query=trpc.services.detailsWorkspace.useQuery({serviceId},{retry:false,staleTime:0,refetchOnMount:'always'}),parsed=serviceDetailsSchema.safeParse(query.data);
 const data=!query.error&&parsed.success&&parsed.data.actorId===actorId&&parsed.data.merchantId===merchantId&&parsed.data.selection.serviceId===serviceId?parsed.data:null;
 const refresh=()=>{void query.refetch();};
 if(query.error)return <WorkspaceState kind={workspaceFailureKind(query.error)} onRetry={refresh}/>;
 if(!data)return <WorkspaceState kind={query.isLoading||query.isFetching?'loading':'error'} onRetry={refresh}/>;
 const {service,bookings,recent,ratings}=data,f=service.fields,number=(n:number,digits=0)=>n.toLocaleString(locale,{maximumFractionDigits:digits,minimumFractionDigits:digits}),money=(n:number)=>new Intl.NumberFormat(locale,{style:'currency',currency:'SAR'}).format(n/100);
 const price=()=>{if(service.issues.some(key=>['priceType','basePrice','minPrice','maxPrice'].includes(key)))return text('unavailable');if(f.priceType==='custom')return field('custom');if(f.priceType==='fixed'&&f.basePrice!==null&&f.basePrice>=0)return money(f.basePrice);if(f.priceType==='variable'&&f.minPrice!==null&&f.maxPrice!==null&&f.minPrice>=0&&f.maxPrice>=f.minPrice)return `${money(f.minPrice)} – ${money(f.maxPrice)}`;return text('unavailable');};
 const status=(value:typeof serviceBookingStatus.enum[keyof typeof serviceBookingStatus.enum])=>text(value==='unknown'?'unknownStatus':value);
 const validNumber=(key:'durationMinutes'|'bufferTimeMinutes'|'maxBookingsPerDay'|'advanceBookingDays'|'displayOrder')=>service.issues.includes(key)?text('unavailable'):f[key]===null?key==='maxBookingsPerDay'?field('unlimited'):text('unavailable'):number(f[key]!);
 const ratingEntries=[['five',5],['four',4],['three',3],['two',2],['one',1]] as const,average=ratings.total?ratingEntries.reduce((sum,[key,weight])=>sum+ratings.distribution[key]*weight,0)/ratings.total:null;
 const date=(value:string|null)=>value?new Intl.DateTimeFormat(locale,{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(value+'T00:00:00Z')):text('unavailable');
 return <div className="service-catalog service-details" dir={rtl?'rtl':'ltr'} aria-busy={query.isFetching}>
  <Link className="se-back" href="/merchant/services">{text('back')}</Link><header className="sc-header"><div><p className="sc-eyebrow">{text('title')}</p><h1>{f.name.trim()||field('noName')}</h1><p>{f.description||text('description')}</p><Badge variant={f.isActive===true?'default':'secondary'}>{f.isActive===null?text('unknown'):field(f.isActive?'active':'inactive')}</Badge></div><div className="sc-actions"><Button variant="outline" disabled={query.isFetching} onClick={refresh}><RefreshCw aria-hidden="true"/>{text('refresh')}</Button>{data.canManage&&<Button asChild><Link href={`/merchant/services/${serviceId}/edit`}><Edit aria-hidden="true"/>{text('edit')}</Link></Button>}</div></header>
  {!data.canManage&&<p className="sc-muted">{text('readOnly')}</p>}{(service.issues.length>0||service.unavailableReferences>0)&&<p className="sc-feedback">{text('repair')}</p>}
  <dl className="sd-overview"><div><dt>{text('price')}</dt><dd>{price()}</dd></div><div><dt>{text('duration')}</dt><dd>{service.issues.includes('durationMinutes')||f.durationMinutes===null?text('unavailable'):field('minutes',{value:number(f.durationMinutes)})}</dd></div><div><dt>{text('category')}</dt><dd>{service.categoryName??text(f.categoryId===null?'noCategory':'unavailable')}</dd></div><div><dt>{text('rating')}</dt><dd>{average===null?text('noRating'):text('outOfFive',{value:number(average,1)})}</dd>{average!==null&&<p>{text('sample',{count:number(ratings.total)})}</p>}</div></dl>
  <section className="se-panel"><div className="sd-heading"><div><h2>{text('bookings')}</h2><p className="sc-muted">{text('allTime')}</p></div><Button asChild variant="outline"><Link href="/merchant/bookings"><Calendar aria-hidden="true"/>{text('bookingsLink')}</Link></Button></div><dl className="sd-counts"><div><dt>{text('total')}</dt><dd>{number(bookings.total)}</dd></div>{serviceBookingStatus.options.filter(key=>key!=='unknown'||bookings.counts.unknown>0).map(key=><div key={key}><dt>{status(key)}</dt><dd>{number(bookings.counts[key])}</dd></div>)}</dl><div className="sd-values"><div><h3>{text('paidValue')}</h3><strong>{bookings.paidValue.minor===null?text('unavailable'):money(bookings.paidValue.minor)}</strong><p className="sc-muted">{text('paidHint',{count:number(bookings.paidValue.eligible)})}</p>{bookings.paidValue.invalid>0&&<p className="sc-feedback">{text('invalidValue',{count:number(bookings.paidValue.invalid)})}</p>}</div><div><h3>{text('completion')}</h3><strong>{bookings.total?text('percent',{value:number(bookings.counts.completed/bookings.total*100,1)}):'—'}</strong><p className="sc-muted">{text('completionHint')}</p></div></div></section>
  <section className="se-panel"><h2>{text('recent')}</h2><p className="sc-muted">{text('recentHint',{count:number(recent.length),total:number(bookings.total)})}</p>{!recent.length?<p className="sd-empty">{text('emptyBookings')}</p>:<ul className="sd-bookings">{recent.map(booking=><li key={booking.id}><div className="sd-booking-title"><div><p className="sc-muted">{text('bookingNumber',{id:booking.id})}</p><h3>{booking.customerName?.trim()||booking.customerPhone?.trim()||text('customer')}</h3></div><Badge variant={booking.status==='completed'?'default':'secondary'}>{status(booking.status)}</Badge></div><dl className="sd-booking-facts"><div><dt>{text('date')}</dt><dd>{date(booking.date)}</dd></div><div><dt>{text('time')}</dt><dd><bdi>{booking.startTime&&booking.endTime?`${booking.startTime} – ${booking.endTime}`:text('unavailable')}</bdi></dd></div><div><dt>{text('duration')}</dt><dd>{booking.durationMinutes===null?text('unavailable'):field('minutes',{value:number(booking.durationMinutes)})}</dd></div><div><dt>{text('finalPrice')}</dt><dd>{booking.finalPrice===null?text('unavailable'):money(booking.finalPrice)}</dd></div><div><dt>{text('payment')}</dt><dd>{text(booking.paymentStatus)}</dd></div></dl></li>)}</ul>}</section>
  <section className="se-panel"><h2>{text('ratings')}</h2><p className="sc-muted">{text('ratingsHint')}</p>{ratings.excluded>0&&<p className="sc-feedback">{text('excluded',{count:number(ratings.excluded)})}</p>}{average===null?<p className="sd-empty">{text('noRating')}</p>:<><p>{text('sample',{count:number(ratings.total)})}</p><ul className="sd-ratings">{ratingEntries.map(([key,weight])=>{const count=ratings.distribution[key];return <li key={key}><span><Star aria-hidden="true"/>{text('stars',{value:number(weight)})}</span><meter min={0} max={ratings.total} value={count} aria-label={text('stars',{value:number(weight)})}>{count}</meter><span>{text('ratingCount',{count:number(count)})}</span></li>;})}</ul></>}</section>
  <details className="se-panel"><summary><strong>{text('settings')}</strong><span>{text('settingsHint')}</span></summary><dl className="se-summary sd-settings"><div><dt>{field('priceType')}</dt><dd>{f.priceType==='fixed'||f.priceType==='variable'||f.priceType==='custom'?field(f.priceType):text('unknown')}</dd></div><div><dt>{field('requiresAppointment')}</dt><dd>{f.requiresAppointment===null?text('unknown'):field(f.requiresAppointment?'yes':'no')}</dd></div>{(['bufferTimeMinutes','maxBookingsPerDay','advanceBookingDays','displayOrder'] as const).map(key=><div key={key}><dt>{field(key)}</dt><dd>{validNumber(key)}</dd></div>)}<div><dt>{field('staffIds')}</dt><dd>{f.staffIds===null?text('unavailable'):f.staffIds.map(id=>service.references.find(r=>r.kind==='staff'&&r.id===id)?.name??field('unavailableSelection',{id})).join('، ')||field('noSelection')}</dd></div><div><dt>{field('category')}</dt><dd>{f.category||field('noSelection')}</dd></div></dl></details>
  <p className="sc-muted">{text('checked',{value:new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short'}).format(new Date(data.checkedAt))})}</p>
 </div>;
}
