import { useEffect, useRef, useState } from 'react';
import { Link, useLocation, useSearch } from 'wouter';
import { useTranslation } from 'react-i18next';
import { Plus, RefreshCw, UserRound, Pause, Play, ArrowLeft } from 'lucide-react';
import { trpc } from '@/lib/trpc';
import { staffWorkspaceSnapshot, type StaffWorkspaceRecord } from '@shared/staff-workspace';
import { staffDraft, parseStaffDraft, staffNavigation, staffHref, staffWeekdays, type StaffDraft } from '@/lib/staff-workspace';
import { staffWorkspaceLabels } from '@/lib/staff-workspace-labels';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { WorkspaceState, workspaceFailureKind } from './WorkspaceState';
import '@/styles/service-catalog-workspace.css';
import '@/styles/staff-workspace.css';

export function StaffWorkspace({ actorId, merchantId }: { actorId:number; merchantId:number }) {
  const {t,i18n}=useTranslation(),text=staffWorkspaceLabels(t),[path,navigate]=useLocation(),search=useSearch(),selection=staffNavigation(search);
  const [searchInput,setSearchInput]=useState(selection.q),[action,setAction]=useState<StaffWorkspaceRecord|null>(null),[busy,setBusy]=useState(false),[failure,setFailure]=useState(''),[notice,setNotice]=useState(''),[uncertain,setUncertain]=useState(false);
  const heading=useRef<HTMLHeadingElement>(null),opener=useRef<HTMLElement|null>(null);
  const live=useRef(true),lock=useRef(false),view=useRef(''),trusted=useRef<ReturnType<typeof staffWorkspaceSnapshot.parse>|null>(null);view.current=`${actorId}:${merchantId}:${search}`;
  const query=trpc.staff.list.useQuery({}, {retry:false,staleTime:0,refetchOnMount:'always'}),update=trpc.staff.update.useMutation(),archive=trpc.staff.delete.useMutation();
  const parsed=staffWorkspaceSnapshot.safeParse(query.data),matches=parsed.success&&parsed.data.actorUserId===actorId&&parsed.data.merchantId===merchantId;
  const data=!query.error&&matches?parsed.data:undefined;if(data)trusted.current=data;
  useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
  useEffect(()=>{setSearchInput(selection.q);setAction(null);setFailure('');setNotice('');},[search]);
  const change=(patch:Record<string,string|number|null>)=>navigate(staffHref(path,search,patch));
  const refresh=async()=>{const source=view.current,result=await query.refetch(),checked=staffWorkspaceSnapshot.safeParse(result.data);if(!live.current||source!==view.current)return false;if(!result.error&&checked.success&&checked.data.actorUserId===actorId&&checked.data.merchantId===merchantId){setUncertain(false);setFailure('');setAction(null);return true;}return false;};
  const current=action&&data?.staff.find(row=>row.id===action.id),canConfirm=!!data?.canManage&&!!current&&current.definition===action?.definition&&!query.isFetching&&!busy&&!uncertain;
  const confirm=async()=>{if(!action||!canConfirm||lock.current)return;const source=view.current;lock.current=true;setBusy(true);setFailure('');try{const result=action.isActive===1?await archive.mutateAsync({staffId:action.id,expectedDefinition:action.definition}):await update.mutateAsync({staffId:action.id,isActive:true,expectedDefinition:action.definition});if(result.success!==true)throw Error('Invalid receipt');if(live.current&&source===view.current){setAction(null);setNotice(text('success'));setUncertain(true);await refresh();}}catch(error){if(live.current&&source===view.current){setFailure(text((error as any)?.data?.code==='CONFLICT'?'conflict':'error'));setUncertain(true);}}finally{lock.current=false;if(live.current)setBusy(false);}};
  if(selection.edit==='invalid')return <WorkspaceState kind="missing" onRetry={()=>change({edit:null})}/>;
  const snapshot=data??trusted.current;
  if(selection.edit!==null&&snapshot){const row=typeof selection.edit==='number'?snapshot.staff.find(r=>r.id===selection.edit):undefined;if(selection.edit!=='new'&&!row)return <WorkspaceState kind="missing" onRetry={()=>change({edit:null})}/>;return <StaffEditor key={`${actorId}:${merchantId}:${selection.edit}`} row={row} canManage={!!data?.canManage} sourceCurrent={!!data&&!query.isFetching} refresh={refresh} leave={()=>change({edit:null})} saved={()=>{void refresh();change({edit:null});}}/>;}
  if(query.error)return <WorkspaceState kind={workspaceFailureKind(query.error)} onRetry={()=>{void refresh();}}/>;
  if(!data)return <WorkspaceState kind={query.isLoading||query.isFetching?'loading':'error'} onRetry={()=>{void refresh();}}/>;
  const state=(row:StaffWorkspaceRecord)=>row.isActive===1?'active':row.isActive===0?'inactive':'unknown';
  const filtered=data.staff.filter(row=>(selection.status==='all'||state(row)===selection.status)&&[row.name,row.phone,row.email,row.role].some(value=>value?.toLocaleLowerCase().includes(selection.q.toLocaleLowerCase()))),pages=Math.ceil(filtered.length/24),rows=filtered.slice((selection.page-1)*24,selection.page*24),format=(value:number)=>value.toLocaleString(i18n.language.startsWith('ar')?'ar-SA':'en-US');
  return <div className="service-catalog staff-workspace" dir={i18n.language.startsWith('ar')?'rtl':'ltr'}>
    <header className="sc-header"><div><p className="sc-eyebrow">{text('eyebrow')}</p><h1>{text('title')}</h1><p>{text('description')}</p></div><div className="sc-actions"><Button variant="outline" disabled={query.isFetching||busy} onClick={()=>{void refresh();}}><RefreshCw aria-hidden="true"/>{text('refresh')}</Button>{data.canManage&&<Button onClick={()=>change({edit:'new'})}><Plus aria-hidden="true"/>{text('create')}</Button>}</div></header>
    <nav className="sc-nav" aria-label={text('eyebrow')}><Link href="/merchant/services">{text('services')}</Link><Link href="/merchant/bookings">{text('bookings')}</Link></nav>
    {!data.canManage&&<p className="sc-muted">{text('readOnly')}</p>}{notice&&<p role="status" className="sc-feedback">{notice}</p>}{uncertain&&!action&&<p role="alert" className="sc-feedback">{failure||text('error')}</p>}
    <dl className="sc-summary">{(['total','active','inactive','unknown'] as const).map(key=><div key={key}><dt>{text(key)}</dt><dd>{format(key==='total'?data.staff.length:data.staff.filter(row=>state(row)===key).length)}</dd></div>)}</dl>
    <section className="sc-list" aria-busy={query.isFetching}>
      <form className="sc-filters" onSubmit={event=>{event.preventDefault();change({q:searchInput.trim(),page:null});}}><label className="sc-search"><span>{text('search')}</span><input value={searchInput} maxLength={200} placeholder={text('searchHint')} onChange={event=>setSearchInput(event.target.value)}/></label><Button variant="outline" type="submit">{text('searchAction')}</Button><label><span>{text('status')}</span><select value={selection.status} onChange={event=>change({status:event.target.value,page:null})}>{(['all','active','inactive','unknown'] as const).map(key=><option key={key} value={key}>{text(key)}</option>)}</select></label>{(selection.q||selection.status!=='all')&&<Button type="button" variant="ghost" onClick={()=>change({q:null,status:null,page:null})}>{text('clear')}</Button>}</form>
      <p className="sc-results" role="status">{query.isFetching?text('loadingUpdate'):text('results',{count:format(filtered.length)})}</p>
      {!rows.length?<div className="sc-empty"><UserRound aria-hidden="true"/><h2>{text(selection.page>1?'outOfRange':data.staff.length?'noResults':'empty')}</h2><p>{text('emptyHint')}</p>{selection.page>1&&<Button onClick={()=>change({page:null})}>{text('first')}</Button>}</div>:<ul className="sc-records">{rows.map(row=><li className="sc-record" key={row.id} data-staff-id={row.id}><div className="sc-record-title"><div><p className="sc-muted">{row.role||text('none')}</p><h2>{row.name||text('unknown')}</h2></div><Badge variant={row.isActive===1?'default':'secondary'}>{text(state(row))}</Badge></div><dl className="sc-facts"><div><dt>{text('phone')}</dt><dd dir="ltr">{row.phone||text('none')}</dd></div><div><dt>{text('email')}</dt><dd dir="ltr">{row.email||text('none')}</dd></div></dl><div className="sc-record-actions"><Button variant="outline" onClick={()=>change({edit:row.id})}>{text(data.canManage?'edit':'view')}</Button>{data.canManage&&<Button variant="ghost" disabled={busy||query.isFetching||uncertain} onClick={()=>{opener.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setFailure('');setAction(row);}}>{row.isActive===1?<Pause aria-hidden="true"/>:<Play aria-hidden="true"/>}{text(row.isActive===1?'archive':'activate')}</Button>}</div></li>)}</ul>}
      {pages>0&&<nav className="sc-pagination" aria-label={text('title')}><Button variant="outline" disabled={selection.page<=1||busy} onClick={()=>change({page:selection.page-1})}>{text('previous')}</Button><span>{text('page',{page:format(selection.page),pages:format(pages)})}</span><Button variant="outline" disabled={selection.page>=pages||busy} onClick={()=>change({page:selection.page+1})}>{text('next')}</Button></nav>}
    </section>
    <Dialog open={!!action} onOpenChange={open=>{if(!open&&!busy)setAction(null);}}><DialogContent onOpenAutoFocus={event=>{event.preventDefault();heading.current?.focus();}} onCloseAutoFocus={event=>{event.preventDefault();if(opener.current?.isConnected)opener.current.focus();}} closeLabel={text('cancel')} showCloseButton={!busy} className="sc-dialog staff-dialog" dir={i18n.language.startsWith('ar')?'rtl':'ltr'}><DialogHeader><DialogTitle ref={heading} tabIndex={-1}>{text(action?.isActive===1?'archiveTitle':'activateTitle')}</DialogTitle><DialogDescription>{text(action?.isActive===1?'archiveHint':'activateHint')}</DialogDescription></DialogHeader><p>{action?.name}</p>{failure&&<p role="alert" className="sc-feedback">{failure}</p>}{action&&current?.definition!==action.definition&&<p role="alert">{text('changed')}</p>}{uncertain&&<Button variant="outline" disabled={busy||query.isFetching} onClick={()=>{void refresh();}}>{text('refresh')}</Button>}<DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setAction(null)}>{text('cancel')}</Button><Button disabled={!canConfirm} onClick={()=>{void confirm();}}>{text(busy?'saving':'confirm')}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function StaffEditor({row,canManage,sourceCurrent,refresh,leave,saved}:{row?:StaffWorkspaceRecord;canManage:boolean;sourceCurrent:boolean;refresh:()=>Promise<boolean>;leave:()=>void;saved:(id:number)=>void}){
  const {t,i18n}=useTranslation(),text=staffWorkspaceLabels(t),[draft,setDraft]=useState(()=>staffDraft(row)),[baseline,setBaseline]=useState(()=>({draft:JSON.stringify(staffDraft(row)),definition:row?.definition})),[dialog,setDialog]=useState<'save'|'reload'|'leave'|null>(null),[errors,setErrors]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(false),[failure,setFailure]=useState(''),[uncertain,setUncertain]=useState(false);
  const heading=useRef<HTMLHeadingElement>(null),opener=useRef<HTMLElement|null>(null);
  const openDialog=(mode:'save'|'reload'|'leave')=>{opener.current=document.activeElement instanceof HTMLElement?document.activeElement:null;setDialog(mode);};
  const live=useRef(true),lock=useRef(false),create=trpc.staff.create.useMutation(),update=trpc.staff.update.useMutation();
  useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
  const dirty=JSON.stringify(draft)!==baseline.draft,stale=row?.definition!==baseline.definition,editable=canManage&&!busy,canSave=editable&&sourceCurrent&&!stale&&!uncertain;
  useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
  const set=(key:keyof StaffDraft,value:any)=>{setDraft(current=>({...current,[key]:value}));setErrors(current=>({...current,[key]:false}));};
  const review=()=>{const parsed=parseStaffDraft(draft);setErrors(parsed.errors);if(!parsed.data){queueMicrotask(()=>document.querySelector<HTMLElement>('.staff-editor [aria-invalid="true"]')?.focus());return;}openDialog('save');};
  const confirm=async()=>{if(!canSave||lock.current)return;const parsed=parseStaffDraft(draft);if(!parsed.data)return;lock.current=true;setBusy(true);setFailure('');try{const result=row?await update.mutateAsync({staffId:row.id,expectedDefinition:baseline.definition,...parsed.data}):await create.mutateAsync(parsed.data);if(result.success!==true||!row&&(!('staffId' in result)||!Number.isSafeInteger(result.staffId)||Number(result.staffId)<=0))throw Error('Unverified receipt');if(live.current){setDialog(null);setUncertain(true);saved(row?.id??Number('staffId' in result?result.staffId:NaN));}}catch(error){if(live.current){setFailure(text((error as any)?.data?.code==='CONFLICT'?'conflict':'error'));setUncertain(true);}}finally{lock.current=false;if(live.current)setBusy(false);}};
  const reset=()=>{const next=staffDraft(row);setDraft(next);setBaseline({draft:JSON.stringify(next),definition:row?.definition});setErrors({});setFailure('');setUncertain(false);setDialog(null);};
  const field=(key:'name'|'phone'|'email'|'role'|'googleCalendarId',required=false)=><label className="sw-field" key={key}><span>{text(key)} {required?'*':<small>{text('optional')}</small>}</span><input id={'sw-'+key} value={draft[key]} type={key==='email'?'email':'text'} inputMode={key==='phone'?'tel':undefined} dir={['phone','email','googleCalendarId'].includes(key)?'ltr':undefined} maxLength={key==='phone'?20:key==='role'?100:255} required={required} aria-invalid={!!errors[key]} aria-describedby={errors[key]?'sw-error-'+key:undefined} onChange={event=>set(key,event.target.value)}/>{errors[key]&&<span id={'sw-error-'+key} role="alert" className="sw-error">{text('invalid')}</span>}</label>;
  const hours=<dl className="sw-review">{staffWeekdays.filter(day=>draft.hours[day]).map(day=><div key={day}><dt>{text(day)}</dt><dd dir="ltr">{draft.hours[day].start} – {draft.hours[day].end}</dd></div>)}</dl>;
  return <div className="service-catalog staff-workspace staff-editor" dir={i18n.language.startsWith('ar')?'rtl':'ltr'}>
    <header className="sc-header"><div><Button variant="ghost" disabled={busy} onClick={()=>dirty?openDialog('leave'):leave()}><ArrowLeft aria-hidden="true"/>{text('back')}</Button><p className="sc-eyebrow">{text('eyebrow')}</p><h1>{text(row?canManage?'edit':'view':'create')}</h1><p>{text('description')}</p></div><div className="sc-actions"><Button variant="outline" disabled={busy} onClick={()=>{void refresh();}}><RefreshCw aria-hidden="true"/>{text('refresh')}</Button>{row&&<Button variant="outline" disabled={busy||!sourceCurrent} onClick={()=>openDialog('reload')}>{text('reload')}</Button>}</div></header>
    {!canManage&&<p className="sc-feedback">{text('readOnly')}</p>}{!sourceCurrent&&<p className="sc-feedback" role="alert">{text('error')}</p>}{stale&&<p className="sc-feedback" role="alert">{text('changed')}</p>}{failure&&<p className="sc-feedback" role="alert">{failure}</p>}
    <form noValidate onSubmit={event=>{event.preventDefault();if(canSave)review();}}>
      <fieldset disabled={!editable} className="sw-sections"><section className="sw-panel"><h2>{text('basics')}</h2><div className="sw-grid">{field('name',true)}{field('role')}{field('phone')}{field('email')}<label className="sw-field"><span>{text('isActive')}</span><select value={draft.isActive} aria-invalid={!!errors.isActive} onChange={event=>set('isActive',event.target.value)}>{draft.isActive==='unknown'&&<option value="unknown">{text('unknown')}</option>}<option value="active">{text('active')}</option><option value="inactive">{text('inactive')}</option></select>{errors.isActive&&<span role="alert" className="sw-error">{text('invalidStatus')}</span>}</label></div></section>
      <details className="sw-panel" open={errors.workingHours||!draft.hoursValid||undefined}><summary>{text('hours')}</summary><p className="sc-muted">{text('hoursHint')}</p>{!draft.hoursValid?<div className="sc-feedback"><p>{text('hoursInvalid')}</p><Button type="button" variant="outline" onClick={()=>setDraft(d=>({...d,hours:{},hoursValid:true}))}>{text('resetHours')}</Button></div>:<div className="sw-hours">{staffWeekdays.map(day=><div className="sw-day" key={day}><label><input type="checkbox" checked={!!draft.hours[day]} onChange={event=>{const next={...draft.hours};if(event.target.checked)next[day]={start:'09:00',end:'17:00'};else delete next[day];set('hours',next);}}/>{text(day)}</label>{draft.hours[day]&&(['start','end'] as const).map(key=><label key={key}><span>{text(key)}</span><input type="time" value={draft.hours[day][key]} aria-label={text(day)+' · '+text(key)} aria-invalid={!!errors.workingHours} onChange={event=>set('hours',{...draft.hours,[day]:{...draft.hours[day],[key]:event.target.value}})}/></label>)}</div>)}</div>}{errors.workingHours&&<p className="sw-error" role="alert">{text('invalid')}</p>}</details>
      <details className="sw-panel"><summary>{text('advanced')}</summary>{field('googleCalendarId')}<p className="sc-muted">{text('calendarHint')}</p></details></fieldset>
      {row&&['specialization','bio','avatar','serviceIds'].some(key=>row[key as keyof typeof row])&&<details className="sw-panel"><summary>{text('legacy')}</summary><p className="sc-muted">{text('legacyHint')}</p><dl className="sw-review">{(['specialization','bio','avatar','serviceIds'] as const).filter(key=>row[key]).map(key=><div key={key}><dt>{text(key)}</dt><dd>{row[key]}</dd></div>)}</dl></details>}
      <footer className="sw-save"><p role="status">{text(busy?'saving':uncertain?'error':!canManage?'readOnly':stale?'changed':row&&!dirty?'saved':'unsaved')}</p>{canManage&&<Button type="submit" disabled={!canSave}>{text('review')}</Button>}</footer>
    </form>
    <Dialog open={!!dialog} onOpenChange={open=>{if(!open&&!busy)setDialog(null);}}><DialogContent onOpenAutoFocus={event=>{event.preventDefault();heading.current?.focus();}} onCloseAutoFocus={event=>{event.preventDefault();if(opener.current?.isConnected)opener.current.focus();}} closeLabel={text('cancel')} showCloseButton={!busy} className="sc-dialog staff-dialog" dir={i18n.language.startsWith('ar')?'rtl':'ltr'}><DialogHeader><DialogTitle ref={heading} tabIndex={-1}>{text(dialog==='save'?'reviewTitle':dialog==='reload'?'reloadTitle':'leaveTitle')}</DialogTitle><DialogDescription>{text(dialog==='save'?'reviewHint':dialog==='reload'?'reloadHint':'leaveHint')}</DialogDescription></DialogHeader>{dialog==='save'&&<><dl className="sw-review">{(['name','role','phone','email','googleCalendarId'] as const).map(key=><div key={key}><dt>{text(key)}</dt><dd>{draft[key]||text('none')}</dd></div>)}<div><dt>{text('status')}</dt><dd>{text(draft.isActive==='active'?'active':'inactive')}</dd></div></dl><h3>{text('hours')}</h3>{hours}{!Object.keys(draft.hours).length&&<p>{text('none')}</p>}{failure&&<p role="alert" className="sc-feedback">{failure}</p>}{stale&&<p role="alert">{text('changed')}</p>}</>}<DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setDialog(null)}>{text('cancel')}</Button><Button disabled={busy||(dialog==='save'?!canSave:dialog==='reload'?!sourceCurrent:false)} onClick={()=>{if(dialog==='save')void confirm();else if(dialog==='reload')reset();else leave();}}>{text(busy?'saving':dialog==='save'?'save':dialog==='reload'?'reload':'leave')}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
