import {useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {trpc} from '@/lib/trpc';
import {Button} from '@/components/ui/button';
import {wooAnalyticsInput,type WooAnalyticsWorkspace as Snapshot} from '@shared/woocommerce-analytics-workspace';
import {scopedWooAnalytics,wooMoneyLabel,wooDefaultPeriod,wooRevenuePoints} from '@/lib/woocommerce-workspace';
import {wooWorkspaceLabels,type WooCopy} from '@/lib/woocommerce-workspace-labels';
import {WorkspaceState,workspaceFailureKind} from './WorkspaceState';
import {WooWorkspaceShell} from './WooWorkspaceShell';
import {wooFresh} from './WooOperationPanel';
function CurrencyReport({group:g,copy:c,locale}:{group:Snapshot['currencies'][number];copy:WooCopy;locale:'ar'|'en'}){
 const values=g.timeline.map(row=>row.revenue),points=wooRevenuePoints(values),money=(value:string)=>wooMoneyLabel(value,g.currency,c.none);
 return <section className="wc-panel" data-woo-currency={g.currency}><h2>{c.currency} · <bdi>{g.currency}</bdi></h2><dl className="wc-facts"><div><dt>{c.revenue}</dt><dd className="wc-amount"><bdi>{money(g.revenue)}</bdi></dd></div><div><dt>{c.averageOrderValue}</dt><dd><bdi>{money(g.averageOrderValue)}</bdi></dd></div><div><dt>{c.completed}</dt><dd>{g.orders.toLocaleString(locale)}</dd></div></dl><h3>{c.timeline}</h3><svg className="wc-sparkline" viewBox="0 0 1000 180" preserveAspectRatio="none" aria-hidden="true" focusable="false"><path d="M0 170 H1000" className="wc-chart-baseline"/>{points.length===1?<circle cx="500" cy={points[0][1]} r="5"/>:<polyline points={points.map(row=>row.join(',')).join(' ')} fill="none" strokeWidth="3" vectorEffect="non-scaling-stroke"/>}</svg><p className="sc-muted"><bdi>{g.timeline[0]?.date}</bdi> — <bdi>{g.timeline.at(-1)?.date}</bdi></p><details className="wc-help"><summary>{c.timelineDetails}</summary><div className="wc-table-scroll" tabIndex={0} role="region" aria-label={c.timeline}><table><caption className="sr-only">{c.timeline} · {g.currency}</caption><thead><tr><th scope="col">{c.period}</th><th scope="col">{c.orders}</th><th scope="col">{c.revenue}</th></tr></thead><tbody>{g.timeline.map(row=><tr key={row.date}><th scope="row"><bdi>{row.date}</bdi></th><td>{row.orders.toLocaleString(locale)}</td><td><bdi>{money(row.revenue)}</bdi></td></tr>)}</tbody></table></div></details>
  <h3>{c.topProducts}</h3><p className="sc-muted">{c.productRevenueHint}</p>{!g.products.rows.length?<p>{c.empty}</p>:<ol className="wc-ranking">{g.products.rows.map(row=><li key={row.key}><div><strong>{row.name}</strong><span>{c.quantity}: {row.quantity.toLocaleString(locale)}</span></div><bdi>{money(row.revenue)}</bdi>{row.identity==='name'&&<small>{c.fallbackIdentity}</small>}</li>)}</ol>}<details className="wc-help"><summary>{c.dataQuality}</summary><dl className="wc-facts">{(['distinct','validLines','excludedLines','invalidArrays','fallbackIdentityLines'] as const).map(key=><div key={key}><dt>{c[key==='distinct'?'distinctProducts':key==='validLines'?'validLines':key==='fallbackIdentityLines'?'fallbackIdentity':key]}</dt><dd>{g.products[key].toLocaleString(locale)}</dd></div>)}</dl></details>
 </section>;
}
export function WooAnalyticsWorkspace({actorId,merchantId,integrationsManage}:{actorId:number;merchantId:number;integrationsManage:boolean}){
 const {t,i18n}=useTranslation(),c=wooWorkspaceLabels(t),locale=i18n.language.startsWith('ar')?'ar':'en';
 const [selection,setSelection]=useState(()=>wooDefaultPeriod()),[draft,setDraft]=useState(selection),[invalid,setInvalid]=useState(false),start=useRef<HTMLInputElement>(null);
 const query=trpc.woocommerce.getAnalyticsWorkspace.useQuery(selection,wooFresh),data=query.error?null:scopedWooAnalytics(query.data,actorId,merchantId,selection),rate=(value:number|null)=>value===null?c.none:value.toLocaleString(locale)+'%';
 return <WooWorkspaceShell view="analytics" copy={c} locale={locale} integrationsManage={integrationsManage} analyticsRead busy={query.isFetching} refresh={()=>void query.refetch()}><section className="wc-panel"><h2>{c.reportPeriod}</h2><p className="sc-muted" id="wc-date-hint">{c.dateHint}</p><form className="sc-filters" noValidate onSubmit={event=>{event.preventDefault();const parsed=wooAnalyticsInput.safeParse(draft);setInvalid(!parsed.success);if(parsed.success)setSelection(parsed.data);else start.current?.focus();}}><label><span>{c.start}</span><input ref={start} type="date" value={draft.startDate} aria-invalid={invalid} aria-describedby={invalid?'wc-range-error':'wc-date-hint'} onInput={event=>{setDraft({...draft,startDate:event.currentTarget.value});setInvalid(false);}} onChange={event=>{setDraft({...draft,startDate:event.target.value});setInvalid(false);}}/></label><label><span>{c.end}</span><input type="date" value={draft.endDate} aria-invalid={invalid} aria-describedby={invalid?'wc-range-error':'wc-date-hint'} onInput={event=>{setDraft({...draft,endDate:event.currentTarget.value});setInvalid(false);}} onChange={event=>{setDraft({...draft,endDate:event.target.value});setInvalid(false);}}/></label><label><span>{c.period}</span><select value={draft.period} onChange={event=>setDraft({...draft,period:event.target.value as typeof draft.period})}>{(['daily','weekly','monthly'] as const).map(value=><option key={value} value={value}>{c[value]}</option>)}</select></label><Button type="submit" disabled={query.isFetching}>{c.apply}</Button><Button type="button" variant="outline" onClick={()=>{const next=wooDefaultPeriod();setDraft(next);setSelection(next);setInvalid(false);}}>{c.reset}</Button></form>{invalid&&<p className="wc-error" role="alert" id="wc-range-error">{c.invalidRange}</p>}</section>
  {query.isLoading||query.isFetching&&!data?<WorkspaceState inline kind="loading"/>:!data?<WorkspaceState inline kind={workspaceFailureKind(query.error)} onRetry={()=>void query.refetch()}/>:<><p className="sc-muted">{c.reportPeriod}: <bdi>{data.selection.startDate}</bdi> — <bdi>{data.selection.endDate}</bdi> · UTC · {c[data.selection.period]} · {c.checked}: {new Date(data.checkedAt).toLocaleString(locale)}</p><dl className="sc-summary"><div><dt>{c.orders}</dt><dd>{data.summary.orders.toLocaleString(locale)}</dd></div><div><dt>{c.completed}</dt><dd>{data.summary.completed.toLocaleString(locale)}</dd></div><div><dt>{c.completionRate}</dt><dd>{rate(data.summary.completionRate)}</dd></div></dl><div className="wc-groups">{data.summary.statuses.map(group=><span key={group.key}>{c[group.key]}: {group.count.toLocaleString(locale)}</span>)}</div><p className="wc-notice">{c.excludedCompleted}: {data.summary.excludedCompleted.toLocaleString(locale)}</p>{!data.currencies.length?<section className="wc-panel"><h2>{c.noSales}</h2><p>{c.noSalesHint}</p></section>:<div className="wc-grid">{data.currencies.map(group=><CurrencyReport key={group.currency} group={group} copy={c} locale={locale}/>)}</div>}<div className="wc-grid"><section className="wc-panel"><h2>{c.customers}</h2><p className="sc-muted">{c.customerHint}</p><dl className="wc-facts">{(['identities','singleOrder','repeat','unidentifiedOrders'] as const).map(key=><div key={key}><dt>{c[key]}</dt><dd>{data.customers[key].toLocaleString(locale)}</dd></div>)}<div><dt>{c.repeatRate}</dt><dd>{rate(data.customers.repeatRate)}</dd></div></dl></section><section className="wc-panel"><h2>{c.conversations}</h2><strong className="wc-amount">{data.conversations.createdInRange.toLocaleString(locale)}</strong><p>{c.attributionUnavailable}</p></section></div></>}
 </WooWorkspaceShell>;
}
