import {useRef,useState} from 'react';
import {trpc} from '@/lib/trpc';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {wooLogsInput,wooLogStates,wooLogKinds,wooLogDirections} from '@shared/woocommerce-workspace';
import {wooIncidentsInput,wooReceiptStates,type WooIncidentRow} from '@shared/woocommerce-incidents';
import {scopedWooLogs,scopedWooIncidents} from '@/lib/woocommerce-workspace';
import type {WooCopy} from '@/lib/woocommerce-workspace-labels';
import {WorkspaceState,workspaceFailureKind} from './WorkspaceState';
import {wooFresh,type WooOperationController} from './WooOperationPanel';
const topicLabel=(topic:WooIncidentRow['topic'],c:WooCopy)=>c[({'product.created':'productCreated','product.updated':'productUpdated','product.deleted':'productDeleted','order.created':'orderCreated','order.updated':'orderUpdated','order.deleted':'orderDeleted',unknown:'unknown'} as const)[topic]];
type Scope={actorId:number;merchantId:number;copy:WooCopy;locale:'ar'|'en'};
const stamp=(value:string|null,locale:string,none:string)=>value?new Date(value).toLocaleString(locale):none;
export function WooPagination({page,pages,total,change,disabled,copy:c}:{page:number;pages:number;total:number;change:(page:number)=>void;disabled:boolean;copy:WooCopy}){return <nav className="wc-pagination" aria-label={c.page}><span>{c.results}: {total} · {c.page} {page} {c.of} {Math.max(1,pages)}</span><div className="sc-actions"><Button variant="outline" disabled={disabled||page<=1} onClick={()=>change(page-1)}>{c.previous}</Button><Button variant="outline" disabled={disabled||page>=pages} onClick={()=>change(page+1)}>{c.next}</Button></div></nav>;}
export function WooLogList({actorId,merchantId,copy:c,locale}:Scope){
 const [selection,setSelection]=useState(()=>wooLogsInput.parse({})),[search,setSearch]=useState('');
 const query=trpc.woocommerce.getLogsWorkspace.useQuery(selection,wooFresh),data=query.error?null:scopedWooLogs(query.data,actorId,merchantId,selection);
 return <section className="wc-panel"><h2>{c.history}</h2><p className="sc-muted">{c.logHint}</p><form className="sc-filters" onSubmit={event=>{event.preventDefault();setSelection({...selection,search,page:1});}}><label className="sc-search"><span>{c.searchLogs}</span><input value={search} maxLength={100} onChange={event=>setSearch(event.target.value)}/></label>{(['state','kind','direction'] as const).map(key=><label key={key}><span>{c[key==='kind'?'resource':key]}</span><select value={selection[key]} onChange={event=>setSelection(wooLogsInput.parse({...selection,[key]:event.target.value,page:1}))}>{['all',...(key==='state'?wooLogStates:key==='kind'?wooLogKinds:wooLogDirections)].map(value=><option key={value} value={value}>{c[value as keyof WooCopy]}</option>)}</select></label>)}<Button type="submit" disabled={query.isFetching}>{c.apply}</Button><Button type="button" variant="outline" onClick={()=>{setSearch('');setSelection(wooLogsInput.parse({}));}}>{c.reset}</Button></form>
  {query.isLoading||query.isFetching&&!data?<WorkspaceState inline kind="loading"/>:!data?<WorkspaceState inline kind={workspaceFailureKind(query.error)} onRetry={()=>void query.refetch()}/>:<><p className="sc-muted">{c.stored}: {data.summary.stored.toLocaleString(locale)}</p><div className="wc-groups">{data.summary.groups.map(g=><span key={g.key}>{c[g.key]}: {g.count.toLocaleString(locale)}</span>)}</div>{!data.rows.length?<p>{c.empty}</p>:<ul className="wc-records">{data.rows.map(row=><li key={row.id}><header><h3>{c[row.kind]} · <bdi>{row.id}</bdi></h3><span>{c[row.state]}</span></header><dl className="wc-facts">{(['processed','succeeded','failed','durationSeconds'] as const).map(key=><div key={key}><dt>{c[key==='failed'?'failedItems':key==='durationSeconds'?'duration':key]}</dt><dd>{row[key]?.toLocaleString(locale)??c.none}</dd></div>)}<div><dt>{c.createdAt}</dt><dd>{stamp(row.startedAt,locale,c.none)}</dd></div><div><dt>{c.processedAt}</dt><dd>{stamp(row.completedAt,locale,c.none)}</dd></div><div><dt>{c.direction}</dt><dd>{c[row.direction]}</dd></div></dl>{row.invalidData&&<p className="wc-notice">{c.invalidData}</p>}</li>)}</ul>}<WooPagination {...data.pagination} copy={c} disabled={query.isFetching} change={page=>setSelection({...selection,page})}/></>}
 </section>;
}
export function WooIncidentList({actorId,merchantId,copy:c,locale,revision,ready,operation:o}:{revision:string;ready:boolean;operation:WooOperationController}&Scope){
 const [selection,setSelection]=useState(()=>wooIncidentsInput.parse({})),[search,setSearch]=useState(''),[chosen,setChosen]=useState<WooIncidentRow[]>([]),[review,setReview]=useState<{revision:string;rows:WooIncidentRow[]}|null>(null);
 const query=trpc.woocommerce.getIncidentsWorkspace.useQuery(selection,wooFresh),mutation=trpc.woocommerce.requestReviewedReconciliation.useMutation({retry:false}),data=query.error?null:scopedWooIncidents(query.data,actorId,merchantId,selection),opener=useRef<HTMLButtonElement|null>(null),heading=useRef<HTMLHeadingElement>(null);
 const valid=!!data&&chosen.every(row=>data.rows.some(current=>current.id===row.id&&current.revision===row.revision&&current.reviewable));
 function choose(row:WooIncidentRow,checked:boolean){setChosen(current=>checked?[...current,row].slice(0,25):current.filter(value=>value.id!==row.id));}
 const change=(next:unknown)=>{setChosen([]);setSelection(wooIncidentsInput.parse(next));};
 async function execute(){if(!review||!ready||!o.canStart||review.revision!==revision||!valid||query.isFetching)return;await o.execute('reconcile',review.revision,requestId=>mutation.mutateAsync({requestId,revision:review.revision,incidents:review.rows.map(({id,revision})=>({id,revision}))}));setReview(null);setChosen([]);}
 return <section className="wc-panel"><h2 ref={heading} tabIndex={-1}>{c.incidents}</h2><p className="sc-muted">{c.incidentHint}</p><form className="sc-filters" onSubmit={event=>{event.preventDefault();change({...selection,search,page:1});}}><label className="sc-search"><span>{c.searchIncidents}</span><input value={search} maxLength={100} onChange={event=>setSearch(event.target.value)}/></label><label><span>{c.state}</span><select value={selection.state} onChange={event=>change({...selection,state:event.target.value,page:1})}>{['all',...wooReceiptStates].map(value=><option key={value} value={value}>{c[value as keyof WooCopy]}</option>)}</select></label><label><span>{c.resource}</span><select value={selection.resource} onChange={event=>change({...selection,resource:event.target.value,page:1})}>{(['all','product','order'] as const).map(value=><option key={value} value={value}>{c[value]}</option>)}</select></label><Button type="submit" disabled={query.isFetching}>{c.apply}</Button><Button type="button" variant="outline" onClick={()=>{setSearch('');change({});}}>{c.reset}</Button></form>
  {query.isLoading||query.isFetching&&!data?<WorkspaceState inline kind="loading"/>:!data?<WorkspaceState inline kind={workspaceFailureKind(query.error)} onRetry={()=>void query.refetch()}/>:<><p className="sc-muted">{c.stored}: {data.summary.stored.toLocaleString(locale)}</p><div className="wc-groups">{data.summary.groups.map(g=><span key={g.key}>{c[g.key]}: {g.count.toLocaleString(locale)}</span>)}</div>{!data.rows.length?<p>{c.empty}</p>:<ul className="wc-records">{data.rows.map(row=><li key={row.id}><header><h3>{c.topic}: <span>{topicLabel(row.topic,c)}</span></h3><span>{c[row.state]}</span></header>{row.reviewable&&<label className="wc-check"><input type="checkbox" checked={chosen.some(r=>r.id===row.id)} disabled={!ready||!o.canStart||query.isFetching} onChange={event=>choose(row,event.target.checked)}/><span>{c.selectIncident} <bdi>{row.id}</bdi></span></label>}<dl className="wc-facts"><div><dt>{c.providerId}</dt><dd><bdi>{row.resourceId??c.none}</bdi></dd></div><div><dt>{c.attempts}</dt><dd>{row.attempts??c.none}</dd></div><div><dt>{c.createdAt}</dt><dd>{stamp(row.createdAt,locale,c.none)}</dd></div><div><dt>{c.processedAt}</dt><dd>{stamp(row.processedAt,locale,c.none)}</dd></div></dl>{row.invalidData&&<p className="wc-notice">{c.invalidData}</p>}</li>)}</ul>}<div className="sc-actions"><Button ref={opener} disabled={!chosen.length||!valid||!ready||!o.canStart||query.isFetching} onClick={()=>setReview({revision,rows:[...chosen]})}>{c.reconcile} · {chosen.length}</Button></div><WooPagination {...data.pagination} copy={c} disabled={query.isFetching||o.busy} change={page=>change({...selection,page})}/></>}
  <Dialog open={!!review} onOpenChange={open=>{if(!open&&!o.busy)setReview(null);}}><DialogContent className="sc-dialog wc-dialog" closeLabel={c.close} showCloseButton={!o.busy} dir={locale==='ar'?'rtl':'ltr'} onCloseAutoFocus={event=>{event.preventDefault();(opener.current?.isConnected&&!opener.current.disabled?opener.current:heading.current)?.focus();}} onEscapeKeyDown={event=>{if(o.busy)event.preventDefault();}} onInteractOutside={event=>{if(o.busy)event.preventDefault();}}><DialogHeader><DialogTitle>{c.reconcile}</DialogTitle><DialogDescription>{c.incidentHint}</DialogDescription></DialogHeader><ul className="wc-batch">{review?.rows.map(row=><li key={row.id}><bdi>{row.id}</bdi> · <span>{topicLabel(row.topic,c)}</span> · {c.providerId}: <bdi>{row.resourceId}</bdi></li>)}</ul>{review?.revision!==revision||!valid?<p role="alert">{c.changed}</p>:null}<DialogFooter><Button variant="outline" disabled={o.busy} onClick={()=>setReview(null)}>{c.cancel}</Button><Button disabled={o.busy||!o.canStart||!valid||review?.revision!==revision||!ready} onClick={()=>void execute()}>{o.busy?c.working:c.confirm}</Button></DialogFooter></DialogContent></Dialog>
 </section>;
}
