import {useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {trpc} from '@/lib/trpc';
import {Button} from '@/components/ui/button';
import {wooOrdersInput,wooOrderStates} from '@shared/woocommerce-data-workspace';
import {scopedWooOrders,wooMoneyLabel} from '@/lib/woocommerce-workspace';
import {wooWorkspaceLabels} from '@/lib/woocommerce-workspace-labels';
import {WorkspaceState,workspaceFailureKind} from './WorkspaceState';
import {WooWorkspaceShell} from './WooWorkspaceShell';
import {wooFresh,useWooOperation,WooOperationPanel} from './WooOperationPanel';
import {WooPagination} from './WooHistoryPanels';
import {WooQuickSync} from './WooQuickSync';
import {WooOrderDialog} from './WooOrderDialog';
export function WooOrdersWorkspace({actorId,merchantId,integrationsManage,ordersManage,analyticsRead}:{actorId:number;merchantId:number;integrationsManage:boolean;ordersManage:boolean;analyticsRead:boolean}){
 const {t,i18n}=useTranslation(),c=wooWorkspaceLabels(t),locale=i18n.language.startsWith('ar')?'ar':'en';
 const [selection,setSelection]=useState(()=>wooOrdersInput.parse({})),[search,setSearch]=useState(''),[dates,setDates]=useState({startDate:'',endDate:''}),[invalid,setInvalid]=useState(false),[opened,setOpened]=useState<{id:number;mode:'details'|'status'|'notify'}|null>(null);
 const query=trpc.woocommerce.getOrdersWorkspace.useQuery(selection,wooFresh),data=query.error?null:scopedWooOrders(query.data,actorId,merchantId,selection),o=useWooOperation(actorId,merchantId,integrationsManage||ordersManage),opener=useRef<HTMLButtonElement|null>(null),heading=useRef<HTMLHeadingElement>(null),start=useRef<HTMLInputElement>(null);
 function open(id:number,mode:NonNullable<typeof opened>['mode'],button:HTMLButtonElement){opener.current=button;setOpened({id,mode});}
 return <WooWorkspaceShell view="orders" copy={c} locale={locale} integrationsManage={integrationsManage} analyticsRead={analyticsRead} busy={query.isFetching||o.busy} refresh={()=>{void query.refetch();if(integrationsManage||ordersManage)void o.recover();}}>{(integrationsManage||ordersManage)&&<WooOperationPanel operation={o} copy={c} locale={locale}/>} {integrationsManage&&<WooQuickSync actorId={actorId} merchantId={merchantId} resource="orders" copy={c} locale={locale} operation={o}/>} {!ordersManage&&<p className="wc-notice">{c.readOnly}</p>}
  <section className="wc-panel"><h2 ref={heading} tabIndex={-1}>{c.orders}</h2><form className="sc-filters" noValidate onSubmit={event=>{event.preventDefault();const parsed=wooOrdersInput.safeParse({...selection,search:search.trim(),page:1,startDate:dates.startDate||undefined,endDate:dates.endDate||undefined});setInvalid(!parsed.success);if(parsed.success)setSelection(parsed.data);else start.current?.focus();}}><label className="sc-search"><span>{c.searchOrders}</span><input type="search" value={search} maxLength={100} onChange={event=>setSearch(event.target.value)}/></label><label><span>{c.state}</span><select value={selection.state} onChange={event=>setSelection(wooOrdersInput.parse({...selection,state:event.target.value,page:1}))}>{(['all',...wooOrderStates] as const).map(value=><option key={value} value={value}>{c[value]}</option>)}</select></label><label><span>{c.start}</span><input ref={start} type="date" value={dates.startDate} aria-invalid={invalid} aria-describedby={invalid?'wc-order-date-error':'wc-order-date-hint'} onInput={event=>{setDates({...dates,startDate:event.currentTarget.value});setInvalid(false);}} onChange={event=>{setDates({...dates,startDate:event.target.value});setInvalid(false);}}/></label><label><span>{c.end}</span><input type="date" value={dates.endDate} aria-invalid={invalid} aria-describedby={invalid?'wc-order-date-error':'wc-order-date-hint'} onInput={event=>{setDates({...dates,endDate:event.currentTarget.value});setInvalid(false);}} onChange={event=>{setDates({...dates,endDate:event.target.value});setInvalid(false);}}/></label><Button type="submit" disabled={query.isFetching}>{c.apply}</Button><Button type="button" variant="outline" onClick={()=>{setSearch('');setDates({startDate:'',endDate:''});setInvalid(false);setSelection(wooOrdersInput.parse({}));}}>{c.reset}</Button></form><p className="sc-muted" id="wc-order-date-hint">{c.orderDateHint}</p>{invalid&&<p role="alert" className="wc-error" id="wc-order-date-error">{c.invalidRange}</p>}
   {query.isLoading||query.isFetching&&!data?<WorkspaceState inline kind="loading"/>:!data?<WorkspaceState inline kind={workspaceFailureKind(query.error)} onRetry={()=>void query.refetch()}/>:<><p className="sc-muted">{c.stored}: {data.summary.stored.toLocaleString(locale)}{data.selection.startDate?<> · <bdi>{data.selection.startDate}</bdi> — <bdi>{data.selection.endDate}</bdi> · UTC</>:null} · {c.checked}: {new Date(data.checkedAt).toLocaleString(locale)}</p><div className="wc-groups">{data.summary.groups.map(group=><span key={group.key}>{c[group.key as keyof typeof c]}: {group.count.toLocaleString(locale)}</span>)}</div>{!data.rows.length?<div className="sc-empty"><h3>{c.empty}</h3><p>{c.emptyHint}</p></div>:<ul className="wc-records">{data.rows.map(row=><li key={row.id} data-woo-order={row.id}><header><h3>{c.orderNumber} · <bdi>{row.orderNumber}</bdi></h3><span>{c[row.state]}</span></header><dl className="wc-facts"><div><dt>{c.customer}</dt><dd>{row.customerName||c.none}</dd></div><div><dt>{c.total}</dt><dd><bdi>{wooMoneyLabel(row.total,row.currency,c.none)}</bdi></dd></div><div><dt>{c.phone}</dt><dd><bdi>{row.customerPhone||c.none}</bdi></dd></div><div><dt>{c.orderDate}</dt><dd>{row.orderDate?new Date(row.orderDate).toLocaleString(locale):c.none}</dd></div></dl>{row.invalidData&&<p className="wc-notice">{c.invalidData}</p>}<div className="sc-actions"><Button variant="outline" onClick={event=>open(row.id,'details',event.currentTarget)}>{c.details}</Button>{ordersManage&&<><Button variant="outline" disabled={!o.canStart} onClick={event=>open(row.id,'status',event.currentTarget)}>{c.changeStatus}</Button><Button variant="outline" disabled={!o.canStart} onClick={event=>open(row.id,'notify',event.currentTarget)}>{c.notify}</Button></>}</div></li>)}</ul>}<WooPagination {...data.pagination} copy={c} disabled={query.isFetching} change={page=>setSelection({...selection,page})}/></>}
  </section>{opened&&<WooOrderDialog key={opened.id} actorId={actorId} merchantId={merchantId} id={opened.id} initialMode={opened.mode} ordersManage={ordersManage} copy={c} locale={locale} operation={o} onClose={()=>setOpened(null)} opener={opener} fallback={heading}/>}
 </WooWorkspaceShell>;
}
