import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {Store} from 'lucide-react';
import {trpc} from '@/lib/trpc';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {scopedWooWorkspace,validateWooConnection,wooStoreDestination,type WooConnectionDraft} from '@/lib/woocommerce-workspace';
import {wooWorkspaceLabels} from '@/lib/woocommerce-workspace-labels';
import {WorkspaceState,workspaceFailureKind} from './WorkspaceState';
import {WooWorkspaceShell} from './WooWorkspaceShell';
import {wooFresh,useWooOperation,WooOperationPanel} from './WooOperationPanel';
import {WooLogList,WooIncidentList} from './WooHistoryPanels';
type Action='connect'|'verify'|'disconnect'|'sync_products'|'sync_orders';
type Review={action:Action;revision:string;draft?:WooConnectionDraft;changed?:boolean};
export function WooSettingsWorkspace({actorId,merchantId,analyticsRead}:{actorId:number;merchantId:number;analyticsRead:boolean}){
 const {t,i18n}=useTranslation(),c=wooWorkspaceLabels(t),locale=i18n.language.startsWith('ar')?'ar':'en';
 const query=trpc.woocommerce.getWorkspace.useQuery(undefined,wooFresh),connect=trpc.woocommerce.requestReviewedConnection.useMutation({retry:false}),sync=trpc.woocommerce.requestReviewedSync.useMutation({retry:false});
 const data=query.error?null:scopedWooWorkspace(query.data,actorId,merchantId),o=useWooOperation(actorId,merchantId,true);
 const [tab,setTab]=useState<'connection'|'history'|'incidents'>('connection'),[draft,setDraft]=useState<WooConnectionDraft>({storeUrl:'',consumerKey:'',consumerSecret:''}),[draftRevision,setDraftRevision]=useState('');
 const [errors,setErrors]=useState<ReturnType<typeof validateWooConnection>['errors']>({}),[visible,setVisible]=useState({consumerKey:false,consumerSecret:false}),[review,setReview]=useState<Review|null>(null),[consent,setConsent]=useState(false);
 const heading=useRef<HTMLHeadingElement>(null),opener=useRef<HTMLButtonElement|null>(null),form=useRef<HTMLFormElement>(null);
 useEffect(()=>{if(data&&data.revision!==draftRevision){setDraft({storeUrl:data.storeUrl??'',consumerKey:'',consumerSecret:''});setDraftRevision(data.revision);setErrors({});setVisible({consumerKey:false,consumerSecret:false});}},[data?.revision,draftRevision]);
 function open(action:Action,button:HTMLButtonElement){if(!data||!o.canStart||query.isFetching)return;opener.current=button;setConsent(false);setReview({action,revision:data.revision});}
 function reviewConnection(){if(!data||!o.canStart||query.isFetching)return;const check=validateWooConnection(draft,data);setErrors(check.errors);if(!check.valid){const first=Object.keys(check.errors)[0];form.current?.querySelector<HTMLInputElement>(`[name="${first}"]`)?.focus();return;}setConsent(false);setReview({action:'connect',revision:data.revision,draft:{...draft,storeUrl:check.destination!},changed:check.changed});}
 async function execute(){if(!review||!data||query.isFetching||!o.canStart||review.revision!==data.revision||((review.action==='disconnect'||review.changed)&&!consent))return;
  const r=review;await o.execute(r.action,r.revision,requestId=>r.action==='sync_products'||r.action==='sync_orders'?sync.mutateAsync({requestId,revision:r.revision,resource:r.action==='sync_products'?'products':'orders'}):r.action==='connect'?connect.mutateAsync({requestId,revision:r.revision,action:'connect',storeUrl:r.draft!.storeUrl,consumerKey:r.draft!.consumerKey.trim()||undefined,consumerSecret:r.draft!.consumerSecret.trim()||undefined,replaceLocalCopies:!!r.changed}):r.action==='disconnect'?connect.mutateAsync({requestId,revision:r.revision,action:'disconnect',clearLocalCopies:true}):connect.mutateAsync({requestId,revision:r.revision,action:'verify'}));
  setReview(null);setDraft(value=>({...value,consumerKey:'',consumerSecret:''}));setVisible({consumerKey:false,consumerSecret:false});
 }
 const busy=o.busy||query.isFetching,ready=!!data&&data.state==='configured'&&data.hasConsumerKey&&data.hasConsumerSecret,date=(v:string|null)=>v?new Date(v).toLocaleString(locale):c.none;
 return <WooWorkspaceShell view="settings" copy={c} locale={locale} integrationsManage analyticsRead={analyticsRead} busy={busy} refresh={()=>{void query.refetch();void o.recover();}}><WooOperationPanel operation={o} copy={c} locale={locale}/>
  {query.isLoading?<WorkspaceState inline kind="loading"/>:!data?<WorkspaceState inline kind={workspaceFailureKind(query.error)} onRetry={()=>void query.refetch()}/>:<><nav className="wc-tabs" aria-label={c.settings}>{(['connection','history','incidents'] as const).map(value=><button key={value} type="button" aria-current={tab===value?'page':undefined} disabled={o.busy} onClick={()=>setTab(value)}>{c[value]}{value==='incidents'&&data.webhooks.needsReview>0?` · ${data.webhooks.needsReview.toLocaleString(locale)}`:''}</button>)}</nav>
   {tab==='history'?<WooLogList actorId={actorId} merchantId={merchantId} copy={c} locale={locale}/>:tab==='incidents'?<WooIncidentList actorId={actorId} merchantId={merchantId} copy={c} locale={locale} revision={data.revision} ready={ready&&!busy} operation={o}/>:<><dl className="sc-summary">{(['storedProducts','storedOrders','syncLogs'] as const).map(key=><div key={key}><dt>{c[key]}</dt><dd>{data.counts[key].toLocaleString(locale)}</dd></div>)}</dl><div className="wc-grid"><section className="wc-panel"><div className="wc-status"><Store aria-hidden="true"/><h2 ref={heading} tabIndex={-1}>{data.storeName||c.connection}</h2><span>{c[data.state]}</span></div><p className="sc-muted">{c.savedHint}</p><dl className="wc-facts"><div><dt>{c.storeUrl}</dt><dd><bdi dir="ltr">{data.storeUrl??c.none}</bdi></dd></div><div><dt>{c.currency}</dt><dd>{data.storeCurrency??c.none}</dd></div><div><dt>{c.lastSync}</dt><dd>{date(data.lastSyncAt)}</dd></div><div><dt>{c.lastTest}</dt><dd>{date(data.lastTestAt)}</dd></div><div><dt>{c.version}</dt><dd>{data.storeVersion??c.none}</dd></div></dl><div className="sc-actions"><Button variant="outline" disabled={!data.present||!data.hasConsumerKey||!data.hasConsumerSecret||!o.canStart||busy} onClick={event=>open('verify',event.currentTarget)}>{c.verify}</Button>{data.present&&<Button variant="outline" disabled={!o.canStart||busy} onClick={event=>open('disconnect',event.currentTarget)}>{c.disconnect}</Button>}</div><p className="sc-muted">{c.checked}: {date(data.checkedAt)}</p>
    <details className="wc-help" open={!data.present||undefined}><summary>{c.connect}</summary><form ref={form} className="wc-form" noValidate onSubmit={event=>{event.preventDefault();reviewConnection();}}>{(['storeUrl','consumerKey','consumerSecret'] as const).map(field=><div key={field}><label htmlFor={'wc-'+field}>{c[field]}</label><div className={field==='storeUrl'?'':'wc-secret'}><input id={'wc-'+field} name={field} dir="ltr" type={field==='storeUrl'?'url':visible[field]?'text':'password'} autoComplete={field==='storeUrl'?'url':'new-password'} value={draft[field]} maxLength={field==='storeUrl'?500:160} disabled={o.busy} aria-invalid={!!errors[field]} aria-describedby={errors[field]?'wc-error-'+field:field!=='storeUrl'?'wc-key-hint':undefined} onChange={event=>{setDraft({...draft,[field]:event.target.value});setErrors({...errors,[field]:undefined});}}/>{field!=='storeUrl'&&<Button type="button" variant="outline" aria-label={`${visible[field]?c.hide:c.show} ${c[field]}`} aria-pressed={visible[field]} onClick={()=>setVisible({...visible,[field]:!visible[field]})}>{visible[field]?c.hide:c.show}</Button>}</div>{errors[field]&&<p className="wc-error" id={'wc-error-'+field} role="alert">{c[errors[field]!]}</p>}</div>)}<p id="wc-key-hint" className="sc-muted">{c.keyHint}</p><Button type="submit" disabled={!o.canStart||busy||draftRevision!==data.revision} onClick={event=>{opener.current=event.currentTarget;}}>{c.review}</Button></form></details>
   </section><div className="wc-stack"><section className="wc-panel"><h2>{c.sync}</h2><p className="sc-muted">{c.syncHint}</p>{!ready&&<p>{c.notReady}</p>}<div className="sc-actions"><Button disabled={!ready||!o.canStart||busy} onClick={event=>open('sync_products',event.currentTarget)}>{c.syncProducts}</Button><Button variant="outline" disabled={!ready||!o.canStart||busy} onClick={event=>open('sync_orders',event.currentTarget)}>{c.syncOrders}</Button></div></section><section className="wc-panel"><h2>{c.webhooks}</h2><strong>{data.webhooks.ready?c.ready:c.notReadyHooks}</strong><p className="sc-muted">{c.hookHint}</p><dl className="wc-facts">{(['registeredTopics','awaiting','needsReview','suppressed','recentCompleted'] as const).map(key=><div key={key}><dt>{c[key]}</dt><dd><bdi>{data.webhooks[key].toLocaleString(locale)}{key==='registeredTopics'?' / 6':''}</bdi></dd></div>)}</dl><Button variant="outline" onClick={()=>setTab('incidents')}>{c.incidents}</Button></section></div></div></>}
  </>}
  <Dialog open={!!review} onOpenChange={value=>{if(!value&&!o.busy)setReview(null);}}><DialogContent className="sc-dialog wc-dialog" closeLabel={c.close} showCloseButton={!o.busy} dir={locale==='ar'?'rtl':'ltr'} onCloseAutoFocus={event=>{event.preventDefault();(opener.current?.isConnected&&!opener.current.disabled?opener.current:heading.current)?.focus();}} onEscapeKeyDown={event=>{if(o.busy)event.preventDefault();}} onInteractOutside={event=>{if(o.busy)event.preventDefault();}}><DialogHeader><DialogTitle>{review?c[review.action]:c.review}</DialogTitle><DialogDescription>{review?.action==='connect'?c.connectReview:review?.action==='disconnect'?c.disconnectWarning:review?.action==='verify'?c.verifyHint:c.syncHint}</DialogDescription></DialogHeader>{review?.action==='connect'&&<p><bdi dir="ltr">{wooStoreDestination(review.draft?.storeUrl??'')}</bdi></p>}{review?.changed&&<p className="wc-notice">{c.replaceWarning}</p>}{(review?.action==='disconnect'||review?.changed)&&<label className="wc-check"><input type="checkbox" checked={consent} disabled={o.busy} onChange={event=>setConsent(event.target.checked)}/><span>{c.clearConsent}</span></label>}{review&&review.revision!==data?.revision&&<p role="alert">{c.changed}</p>}<DialogFooter><Button variant="outline" disabled={o.busy} onClick={()=>setReview(null)}>{c.cancel}</Button><Button disabled={!o.canStart||busy||review?.revision!==data?.revision||((review?.action==='disconnect'||!!review?.changed)&&!consent)} onClick={()=>void execute()}>{o.busy?c.working:c.confirm}</Button></DialogFooter></DialogContent></Dialog>
 </WooWorkspaceShell>;
}
