import {useEffect,useRef,useState} from 'react';
import {useTranslation} from 'react-i18next';
import {trpc} from '@/lib/trpc';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {zidNoticeReviewSchema,zidNoticeReviewReceipt} from '@shared/zid-notification-review';
import {zidWorkspaceLabels} from '@/lib/zid-workspace-labels';
import {WorkspaceState,workspaceFailureKind} from './WorkspaceState';
type Batch=ReturnType<typeof zidNoticeReviewSchema.parse>;
export function ZidNotificationReview({actorId,merchantId,refresh}:{actorId:number;merchantId:number;refresh:()=>Promise<unknown>}){
 const {t,i18n}=useTranslation(),copy=zidWorkspaceLabels(t),locale=i18n.language.startsWith('ar')?'ar':'en';
 const query=trpc.zid.notificationReview.useQuery(undefined,{retry:false,staleTime:0,refetchOnMount:'always',refetchOnWindowFocus:false}),mutation=trpc.zid.acknowledgeReviewedNotifications.useMutation({retry:false});
 const scope=(raw:unknown)=>{const p=zidNoticeReviewSchema.safeParse(raw);return p.success&&p.data.actorId===actorId&&p.data.merchantId===merchantId?p.data:null;},data=query.error?null:scope(query.data);
 const [review,setReview]=useState<Batch|null>(null),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[notice,setNotice]=useState<'acknowledged'|'uncertain'|'changed'|'refreshFailed'|null>(null);
 const alive=useRef(true),lock=useRef(false),opener=useRef<HTMLButtonElement>(null),heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 async function reload(){if(lock.current)return;lock.current=true;setBusy(true);try{const result=await query.refetch();if(!alive.current)return;if(result.error||!scope(result.data))throw Error('Unconfirmed batch');setBlocked(false);setReview(null);setNotice(null);}catch{if(alive.current){setNotice('refreshFailed');setBlocked(true);}}finally{lock.current=false;if(alive.current)setBusy(false);}}
 async function acknowledge(){if(lock.current||!review||blocked)return;lock.current=true;setBusy(true);try{const receipt=zidNoticeReviewReceipt.parse(await mutation.mutateAsync({items:review.rows.map(({id,revision})=>({id,revision}))}));if(!alive.current)return;if(receipt.actorId!==actorId||receipt.merchantId!==merchantId||receipt.ids.length!==review.rows.length||receipt.ids.some(id=>!review.rows.some(row=>row.id===id)))throw Error('Unconfirmed receipt');setReview(null);setNotice('acknowledged');await query.refetch();if(alive.current)await refresh();}catch(error){if(alive.current){setReview(null);setBlocked(true);setNotice((error as any)?.data?.code==='CONFLICT'?'changed':'uncertain');}}finally{lock.current=false;if(alive.current)setBusy(false);}}
 return <section className="zd-panel"><h2 ref={heading} tabIndex={-1}>{copy.reviewNotices}</h2><p>{copy.reviewHelp}</p>{notice&&<p role={notice==='acknowledged'?'status':'alert'} className="zd-notice">{copy[notice]}</p>}
 {query.isLoading?<WorkspaceState inline kind="loading"/>:!data?<WorkspaceState inline kind={workspaceFailureKind(query.error)} onRetry={()=>void reload()}/>:<><p>{copy.needsReview}: {data.total.toLocaleString(locale)}</p>{!data.rows.length?<p>{copy.noIncidents}</p>:<><p className="sc-muted">{copy.reviewBatch}</p><ul className="zd-batch">{data.rows.map(row=><li key={row.id}><strong>{copy.incidentId}: <bdi>{row.id}</bdi></strong><p>{copy.orderId}: <bdi>{row.orderId}</bdi></p><p>{copy.storeId}: <bdi>{row.storeId||copy.none}</bdi></p><p>{copy.attempts}: {row.attempts.toLocaleString(locale)}</p></li>)}</ul><Button ref={opener} disabled={busy||blocked||query.isFetching} onClick={()=>setReview(data)}>{copy.acknowledge}</Button></>}</>}
 <div><Button variant="outline" disabled={busy||query.isFetching} onClick={()=>void reload()}>{copy.refresh}</Button></div>
 <Dialog open={!!review} onOpenChange={open=>{if(!open&&!busy)setReview(null);}}><DialogContent className="sc-dialog zd-review" closeLabel={copy.close} showCloseButton={!busy} dir={locale==='ar'?'rtl':'ltr'} onCloseAutoFocus={event=>{event.preventDefault();(opener.current?.isConnected&&!opener.current.disabled?opener.current:heading.current)?.focus();}} onEscapeKeyDown={event=>{if(busy)event.preventDefault();}} onInteractOutside={event=>{if(busy)event.preventDefault();}}><DialogHeader><DialogTitle>{copy.reviewNotices}</DialogTitle><DialogDescription>{copy.reviewHelp}</DialogDescription></DialogHeader><ul className="zd-batch">{review?.rows.map(row=><li key={row.id}>{copy.incidentId}: <bdi>{row.id}</bdi> · {copy.orderId}: <bdi>{row.orderId}</bdi></li>)}</ul><DialogFooter><Button variant="outline" disabled={busy} onClick={()=>setReview(null)}>{copy.cancel}</Button><Button disabled={busy||blocked} onClick={()=>void acknowledge()}>{busy?copy.saving:copy.acknowledge}</Button></DialogFooter></DialogContent></Dialog>
 </section>;
}
