CREATE TABLE booking_calendar_reschedules (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 merchant_id INT NOT NULL,
 booking_reference INT NOT NULL,
 agreement_id INT NOT NULL,
 service_id INT NOT NULL,
 staff_id INT NULL,
 booking_date DATE NOT NULL,
 start_time VARCHAR(5) NOT NULL,
 end_time VARCHAR(5) NOT NULL,
 snapshot JSON NOT NULL,
 snapshot_hash CHAR(64) NOT NULL,
 state VARCHAR(24) NOT NULL DEFAULT 'pending',
 actor_user_id INT NULL,
 request_id CHAR(36) NULL,
 request_hash CHAR(64) NULL,
 event_etag VARCHAR(256) NULL,
 reason VARCHAR(500) NULL,
 failure_code VARCHAR(40) NULL,
 revision INT NOT NULL DEFAULT 0,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 UNIQUE KEY uq_booking_move_agreement (merchant_id,agreement_id),
 UNIQUE KEY uq_booking_move_request (merchant_id,request_id),
 KEY idx_booking_move_booking (merchant_id,booking_reference,id),
 KEY idx_booking_move_capacity (merchant_id,booking_date,state),
 CONSTRAINT fk_booking_move_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE CASCADE
);
