CREATE TABLE appointment_reminders (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 merchant_id INT NOT NULL,
 appointment_reference INT NOT NULL,
 source_message_id INT NOT NULL,
 hours_before INT NOT NULL,
 terms_hash CHAR(64) NOT NULL,
 snapshot JSON NOT NULL,
 snapshot_hash CHAR(64) NOT NULL,
 dispatch_text TEXT NOT NULL,
 due_at DATETIME(3) NOT NULL,
 expires_at DATETIME(3) NOT NULL,
 cancelled_at DATETIME(3) NULL,
 cancellation_source_id INT NULL,
 state VARCHAR(24) NOT NULL DEFAULT 'pending',
 claim_token CHAR(36) NULL,
 dispatch_started_at DATETIME(3) NULL,
 accepted_at DATETIME(3) NULL,
 provider_message_id VARCHAR(255) NULL,
 delivery_state VARCHAR(24) NOT NULL DEFAULT 'none',
 projection_message_id INT NULL,
 last_error VARCHAR(40) NULL,
 next_check_at DATETIME(3) NULL,
 created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 UNIQUE KEY uq_appointment_reminder_source (merchant_id,source_message_id),
 UNIQUE KEY uq_appointment_reminder_terms (merchant_id,appointment_reference,hours_before,terms_hash),
 KEY idx_appointment_reminder_due (state,next_check_at,id),
 CONSTRAINT chk_appointment_reminder_hours CHECK (hours_before IN (1,24)),
 CONSTRAINT chk_appointment_reminder_window CHECK (expires_at>due_at),
 CONSTRAINT fk_appointment_reminder_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE CASCADE
);
