CREATE TABLE `ai_sales_generation_output_reviews` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` int NOT NULL,
  `generation_id` bigint unsigned NOT NULL,
  `actor_user_id` int DEFAULT NULL,
  `revision` bigint unsigned NOT NULL,
  `request_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payload_digest` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `basis_digest` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `review_digest` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `snapshot` json NOT NULL,
  `outcome` varchar(16) NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sales_reply_review_request` (`merchant_id`,`request_id`),
  UNIQUE KEY `uq_sales_reply_review_revision` (`generation_id`,`revision`),
  CONSTRAINT `ck_sales_reply_review_revision` CHECK (`revision` BETWEEN 1 AND 9007199254740991),
  CONSTRAINT `ck_sales_reply_review_outcome` CHECK (`outcome` IN ('approved','rejected')),
  CONSTRAINT `fk_sales_reply_review_merchant` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_reply_review_generation` FOREIGN KEY (`generation_id`) REFERENCES `ai_sales_experiment_generations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_reply_review_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
);
