CREATE TABLE `ai_sales_reply_deliveries` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` int NOT NULL,
  `generation_id` bigint unsigned NOT NULL,
  `message_reference` int NOT NULL,
  `actor_user_id` int DEFAULT NULL,
  `request_id` char(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `payload_digest` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `basis_digest` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `authorization_digest` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `snapshot` json NOT NULL,
  `state` varchar(16) NOT NULL,
  `dispatch_started_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sales_reply_delivery_request` (`merchant_id`,`request_id`),
  UNIQUE KEY `uq_sales_reply_delivery_generation` (`merchant_id`,`generation_id`),
  UNIQUE KEY `uq_sales_reply_delivery_message` (`merchant_id`,`message_reference`),
  CONSTRAINT `ck_sales_reply_delivery_state` CHECK (`state` IN ('authorized','dispatching')),
  CONSTRAINT `ck_sales_reply_delivery_source` CHECK (`message_reference` > 0),
  CONSTRAINT `ck_sales_reply_delivery_dispatch` CHECK ((`state`='authorized' AND `dispatch_started_at` IS NULL) OR (`state`='dispatching' AND `dispatch_started_at` IS NOT NULL)),
  CONSTRAINT `fk_sales_reply_delivery_merchant` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_reply_delivery_generation` FOREIGN KEY (`generation_id`) REFERENCES `ai_sales_experiment_generations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_sales_reply_delivery_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
);
