CREATE TABLE IF NOT EXISTS `calendly_operations` (
 `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `merchant_id` INT NOT NULL,
 `actor_id` INT NOT NULL,
 `request_id` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 `kind` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 `review_revision` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 `payload_digest` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 `attempt_token` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 `state` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 `result_json` JSON NULL,
 `lease_until` DATETIME(3) NOT NULL,
 `started_at` DATETIME(3) NULL,
 `acknowledged_at` DATETIME(3) NULL,
 `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY `uq_calendly_operation_request` (`merchant_id`,`request_id`),
 KEY `idx_calendly_operation_active` (`merchant_id`,`state`,`lease_until`),
 KEY `idx_calendly_operation_actor` (`merchant_id`,`actor_id`,`id`),
 KEY `idx_calendly_operation_rate` (`merchant_id`,`created_at`),
 CONSTRAINT `fk_calendly_operation_merchant` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`id`) ON DELETE CASCADE,
 CONSTRAINT `fk_calendly_operation_actor` FOREIGN KEY (`actor_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
 CONSTRAINT `chk_calendly_operation_state` CHECK (`state` IN ('pending','success','rejected','unknown')),
 CONSTRAINT `chk_calendly_operation_kind` CHECK (`kind` IN ('connect','verify','disconnect','sync','settings')),
 CONSTRAINT `chk_calendly_operation_result` CHECK ((`state`='success' AND `result_json` IS NOT NULL AND `started_at` IS NOT NULL) OR (`state`<>'success' AND `result_json` IS NULL)),
 CONSTRAINT `chk_calendly_operation_rejected` CHECK (`state`<>'rejected' OR `started_at` IS NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
