CREATE TABLE IF NOT EXISTS `abandoned_cart_reminders` (
 `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `operation_key` CHAR(36) NOT NULL,
 `merchant_id` INT NOT NULL,
 `actor_id` INT NOT NULL,
 `cart_id` INT NOT NULL,
 `request_digest` CHAR(64) NOT NULL,
 `review_revision` CHAR(64) NOT NULL,
 `cart_revision` CHAR(64) NOT NULL,
 `channel_id` INT NOT NULL,
 `channel_revision` CHAR(64) NOT NULL,
 `discount_id` INT NULL,
 `discount_revision` CHAR(64) NULL,
 `locale` ENUM('ar','en') NOT NULL,
 `to_phone` VARCHAR(16) NOT NULL,
 `message_text` TEXT NOT NULL,
 `state` ENUM('reserved','dispatching','accepted','rejected','unknown','suppressed') NOT NULL DEFAULT 'reserved',
 `quota_subscription_id` INT NULL,
 `quota_period_start` DATETIME(3) NULL,
 `quota_reserved` TINYINT NOT NULL DEFAULT 0,
 `expires_at` DATETIME(3) NOT NULL,
 `created_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 `updated_at` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 UNIQUE KEY `uq_cart_reminder_operation` (`merchant_id`,`operation_key`),
 KEY `idx_cart_reminder_history` (`merchant_id`,`cart_id`,`id`),
 CONSTRAINT `fk_cart_reminder_merchant` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`id`) ON DELETE CASCADE,
 CONSTRAINT `fk_cart_reminder_cart` FOREIGN KEY (`cart_id`) REFERENCES `abandoned_carts` (`id`) ON DELETE CASCADE,
 CONSTRAINT `chk_cart_reminder_quota` CHECK ((`quota_reserved`=0 AND `quota_subscription_id` IS NULL AND `quota_period_start` IS NULL) OR (`quota_reserved`=1 AND `quota_subscription_id` IS NOT NULL AND `quota_period_start` IS NOT NULL)),
 CONSTRAINT `chk_cart_reminder_discount` CHECK ((`discount_id` IS NULL AND `discount_revision` IS NULL) OR (`discount_id` IS NOT NULL AND `discount_revision` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
