CREATE TABLE `competitor_analysis_jobs` (
 `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `merchant_id` INT NOT NULL,
 `request_id` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 `actor_id` INT NOT NULL,
 `owner_id` INT NOT NULL,
 `competitor_id` INT NOT NULL,
 `name` VARCHAR(255) NOT NULL,
 `website_url` VARCHAR(500) NOT NULL,
 `state` ENUM('running','completed','failed','interrupted') NOT NULL DEFAULT 'running',
 `active_slot` TINYINT NULL DEFAULT 1,
 `execution_token` CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 `lease_expires_at` DATETIME(3) NULL,
 `deadline_at` DATETIME(3) NOT NULL,
 UNIQUE KEY `uq_competitor_job_request` (`merchant_id`,`request_id`),
 UNIQUE KEY `uq_competitor_job_report` (`competitor_id`),
 UNIQUE KEY `uq_competitor_job_active` (`merchant_id`,`active_slot`),
 KEY `idx_competitor_job_history` (`merchant_id`,`started_at`),
 CONSTRAINT `ck_competitor_job_active` CHECK ((`state` = 'running' AND `active_slot` IS NOT NULL AND `active_slot` = 1) OR (`state` <> 'running' AND `active_slot` IS NULL)),
 CONSTRAINT `fk_competitor_job_merchant` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
