import { useTranslation } from "react-i18next";
export function useKnowledgePageCopy() {
  const { t } = useTranslation();
  return {
    title: t("merchantUx.knowledgePages.title"),
    description: t("merchantUx.knowledgePages.description"),
    scope: t("merchantUx.knowledgePages.scope"),
    saved: t("merchantUx.knowledgePages.saved"),
    enabledCount: t("merchantUx.knowledgePages.enabledCount"),
    search: t("merchantUx.knowledgePages.search"),
    searchButton: t("merchantUx.knowledgePages.searchButton"),
    filter: t("merchantUx.knowledgePages.filter"),
    all: t("merchantUx.knowledgePages.all"),
    enabled: t("merchantUx.knowledgePages.enabled"),
    paused: t("merchantUx.knowledgePages.paused"),
    inactive: t("merchantUx.knowledgePages.inactive"),
    empty: t("merchantUx.knowledgePages.empty"),
    loading: t("merchantUx.knowledgePages.loading"),
    loadFailed: t("merchantUx.knowledgePages.loadFailed"),
    retry: t("merchantUx.knowledgePages.retry"),
    noPages: t("merchantUx.knowledgePages.noPages"),
    previous: t("merchantUx.knowledgePages.previous"),
    next: t("merchantUx.knowledgePages.next"),
    review: t("merchantUx.knowledgePages.review"),
    close: t("merchantUx.knowledgePages.close"),
    reviewTitle: t("merchantUx.knowledgePages.reviewTitle"),
    reviewLoading: t("merchantUx.knowledgePages.reviewLoading"),
    reviewFailed: t("merchantUx.knowledgePages.reviewFailed"),
    missing: t("merchantUx.knowledgePages.missing"),
    content: t("merchantUx.knowledgePages.content"),
    linked: t("merchantUx.knowledgePages.linked"),
    linksHelp: t("merchantUx.knowledgePages.linksHelp"),
    sections: t("merchantUx.knowledgePages.sections"),
    faqs: t("merchantUx.knowledgePages.faqs"),
    noLinked: t("merchantUx.knowledgePages.noLinked"),
    action: t("merchantUx.knowledgePages.action"),
    choose: t("merchantUx.knowledgePages.choose"),
    enable: t("merchantUx.knowledgePages.enable"),
    pause: t("merchantUx.knowledgePages.pause"),
    delete: t("merchantUx.knowledgePages.delete"),
    scopeWarning: t("merchantUx.knowledgePages.scopeWarning"),
    blocked: t("merchantUx.knowledgePages.blocked"),
    duplicates: t("merchantUx.knowledgePages.duplicates"),
    acknowledge: t("merchantUx.knowledgePages.acknowledge"),
    apply: t("merchantUx.knowledgePages.apply"),
    applying: t("merchantUx.knowledgePages.applying"),
    savedMessage: t("merchantUx.knowledgePages.savedMessage"),
    conflict: t("merchantUx.knowledgePages.conflict"),
    uncertain: t("merchantUx.knowledgePages.uncertain"),
    refreshReview: t("merchantUx.knowledgePages.refreshReview"),
    readOnly: t("merchantUx.knowledgePages.readOnly"),
    pending: t("merchantUx.knowledgePages.pending"),
    expired: t("merchantUx.knowledgePages.expired"),
    excluded: t("merchantUx.knowledgePages.excluded"),
    eligible: t("merchantUx.knowledgePages.eligible"),
  };
}
