import { useTranslation } from "react-i18next";
export function useKnowledgePageIntakeCopy() {
  const { t } = useTranslation();
  return {
    permissionFailed: t("merchantUx.knowledgePageIntake.permissionFailed"),
    title: t("merchantUx.knowledgePageIntake.title"),
    description: t("merchantUx.knowledgePageIntake.description"),
    url: t("merchantUx.knowledgePageIntake.url"),
    prepare: t("merchantUx.knowledgePageIntake.prepare"),
    busy: t("merchantUx.knowledgePageIntake.busy"),
    invalid: t("merchantUx.knowledgePageIntake.invalid"),
    failed: t("merchantUx.knowledgePageIntake.failed"),
    limit: t("merchantUx.knowledgePageIntake.limit"),
    exists: t("merchantUx.knowledgePageIntake.exists"),
    review: t("merchantUx.knowledgePageIntake.review"),
    effect: t("merchantUx.knowledgePageIntake.effect"),
    fullText: t("merchantUx.knowledgePageIntake.fullText"),
    advisory: t("merchantUx.knowledgePageIntake.advisory"),
    advisoryHelp: t("merchantUx.knowledgePageIntake.advisoryHelp"),
    noAnalysis: t("merchantUx.knowledgePageIntake.noAnalysis"),
    expires: t("merchantUx.knowledgePageIntake.expires"),
    acknowledge: t("merchantUx.knowledgePageIntake.acknowledge"),
    save: t("merchantUx.knowledgePageIntake.save"),
    close: t("merchantUx.knowledgePageIntake.close"),
    open: t("merchantUx.knowledgePageIntake.open"),
    saved: t("merchantUx.knowledgePageIntake.saved"),
    changed: t("merchantUx.knowledgePageIntake.changed"),
    deleted: t("merchantUx.knowledgePageIntake.deleted"),
    pageId: t("merchantUx.knowledgePageIntake.pageId"),
    sectionId: t("merchantUx.knowledgePageIntake.sectionId"),
    expired: t("merchantUx.knowledgePageIntake.expired"),
    recover: t("merchantUx.knowledgePageIntake.recover"),
    uncertain: t("merchantUx.knowledgePageIntake.uncertain"),
    checking: t("merchantUx.knowledgePageIntake.checking"),
    storage: t("merchantUx.knowledgePageIntake.storage"),
    another: t("merchantUx.knowledgePageIntake.another"),
    retry: t("merchantUx.knowledgePageIntake.retry"),
    readOnly: t("merchantUx.knowledgePageIntake.readOnly"),
    indexing: t("merchantUx.knowledgePageIntake.indexing"),
    conflict: t("merchantUx.knowledgePageIntake.conflict"),
  };
}
