import {randomUUID} from 'node:crypto';
import type {PoolConnection} from 'mysql2/promise';
import {getPool} from '../db/connection';
import {assertRuntimeSchema} from '../db/schema-readiness';
import {hasPermission,type MerchantRole} from '../_core/permissions';
import {bookingReadId} from '../../shared/booking-read';
import {calendlyOperationIntent,calendlyOperationLookup,calendlyOperationReceipt,calendlyOperationResult,calendlyOperationReviewWorkspace,type CalendlyOperationKind,type CalendlyOperationReceipt} from '../../shared/calendly-operation';
import {calendlyStamp,calendlyCount} from './calendly-workspace';
export class CalendlyOperationFault extends Error{constructor(readonly reason:'unavailable'|'forbidden'|'missing'|'changed'|'busy'|'review_required'|'rate_limited'){super('calendly_operation:'+reason);}}
export const CALENDLY_OPERATION_REQUIREMENTS=[{table:'calendly_operations',columns:['merchant_id','actor_id','request_id','kind','review_revision','payload_digest','attempt_token','state','result_json','lease_until','started_at','acknowledged_at','created_at','updated_at'],uniqueIndexes:[{name:'uq_calendly_operation_request',columns:['merchant_id','request_id']}],checkConstraints:['chk_calendly_operation_state','chk_calendly_operation_kind','chk_calendly_operation_result','chk_calendly_operation_rejected']}];
export type CalendlyOperationLease=Readonly<{id:number;actorId:number;merchantId:number;token:string;kind:CalendlyOperationKind}>;
const selection='SELECT *,lease_until>UTC_TIMESTAMP(3) AS live FROM calendly_operations';
async function rows(tx:PoolConnection,query:string,args:Array<string|number|null>=[]):Promise<any[]>{const [result]=await tx.execute(query,args);if(!Array.isArray(result))throw new CalendlyOperationFault('unavailable');return result;}
export async function calendlyOperationTransaction<T>(work:(tx:PoolConnection)=>Promise<T>){let tx:PoolConnection|undefined,committing=false,reusable=true;try{const pool=await getPool();if(!pool)throw new CalendlyOperationFault('unavailable');tx=await pool.getConnection();await tx.beginTransaction();const value=await work(tx);committing=true;await tx.commit();return value;}catch(error){if(tx){if(committing)reusable=false;else try{await tx.rollback();}catch{reusable=false;}}if(error instanceof CalendlyOperationFault)throw error;throw new CalendlyOperationFault('unavailable');}finally{if(tx){if(reusable)tx.release();else tx.destroy();}}}
export async function calendlyOperationWriter(tx:PoolConnection,actorId:number,merchantId:number,kind:CalendlyOperationKind){
 bookingReadId.parse(actorId);bookingReadId.parse(merchantId);
 const merchant=(await rows(tx,'SELECT userId,status FROM merchants WHERE id=? FOR UPDATE',[merchantId]))[0];if(!merchant||merchant.status==='suspended')throw new CalendlyOperationFault('forbidden');
 const users=await rows(tx,'SELECT id,account_status FROM users WHERE id IN (?,?) ORDER BY id FOR SHARE',[actorId,merchant.userId]);if(![actorId,merchant.userId].every(id=>users.some(u=>u.id===id&&u.account_status==='active')))throw new CalendlyOperationFault('forbidden');
 const members=await rows(tx,'SELECT role,is_active FROM merchant_members WHERE merchant_id=? AND user_id=? FOR SHARE',[merchantId,actorId]);const role=members.length===1&&members[0].is_active===1?members[0].role:members.length===0&&merchant.userId===actorId?'owner':null;if(!role||!hasPermission(role as MerchantRole,'integrations.manage'))throw new CalendlyOperationFault('forbidden');
}
function receipt(row:any,replayed:boolean):CalendlyOperationReceipt{
 if(!row)throw new CalendlyOperationFault('missing');let result=null;try{result=row.result_json==null?null:calendlyOperationResult.parse(typeof row.result_json==='string'?JSON.parse(row.result_json):row.result_json);}catch{throw new CalendlyOperationFault('unavailable');}
 const started=row.started_at!=null,outcome=row.state==='pending'&&!Number(row.live)?started?'unknown':'rejected':row.state;
 return calendlyOperationReceipt.parse({actorId:row.actor_id,merchantId:row.merchant_id,requestId:row.request_id,kind:row.kind,revision:row.review_revision,outcome,started,reviewRequired:outcome==='unknown'&&row.acknowledged_at==null,result,createdAt:calendlyStamp(row.created_at),checkedAt:new Date().toISOString(),replayed});
}
/** A duplicate never gets a lease or re-runs review/provider work, even after an uncertain commit. */
export async function reserveCalendlyOperation(actorId:number,merchantId:number,raw:unknown,review:(tx:PoolConnection)=>Promise<void>){
 bookingReadId.parse(actorId);bookingReadId.parse(merchantId);const input=calendlyOperationIntent.parse(raw);await assertRuntimeSchema('Calendly reviewed operations',CALENDLY_OPERATION_REQUIREMENTS,{cacheSuccess:false});
 return calendlyOperationTransaction(async tx=>{
  await calendlyOperationWriter(tx,actorId,merchantId,input.kind);const existing=await rows(tx,selection+' WHERE merchant_id=? AND request_id=? FOR UPDATE',[merchantId,input.requestId]);
  if(existing.length){const row=existing[0];if(existing.length!==1||row.actor_id!==actorId||row.kind!==input.kind||row.review_revision!==input.revision||row.payload_digest!==input.payloadDigest)throw new CalendlyOperationFault('changed');return {receipt:receipt(row,true),lease:null};}
  await tx.execute("UPDATE calendly_operations SET state=IF(started_at IS NULL,'rejected','unknown'),updated_at=UTC_TIMESTAMP(3) WHERE merchant_id=? AND state='pending' AND lease_until<=UTC_TIMESTAMP(3)",[merchantId]);
  const counts=await rows(tx,"SELECT COALESCE(SUM(state='pending'),0) AS active,COALESCE(SUM(state='unknown' AND acknowledged_at IS NULL),0) AS needsReview,COALESCE(SUM(created_at>DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 5 MINUTE)),0) AS recent FROM calendly_operations WHERE merchant_id=?",[merchantId]);
  if(counts.length!==1)throw new CalendlyOperationFault('unavailable');if(calendlyCount(counts[0].active)>0)throw new CalendlyOperationFault('busy');if(calendlyCount(counts[0].needsReview)>0)throw new CalendlyOperationFault('review_required');if(calendlyCount(counts[0].recent)>=6)throw new CalendlyOperationFault('rate_limited');
  await review(tx);const token=randomUUID();const [saved]=await tx.execute<any>("INSERT INTO calendly_operations(merchant_id,actor_id,request_id,kind,review_revision,payload_digest,attempt_token,state,lease_until) VALUES (?,?,?,?,?,?,?,'pending',DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 120 SECOND))",[merchantId,actorId,input.requestId,input.kind,input.revision,input.payloadDigest,token]);
  const id=bookingReadId.parse(Number(saved.insertId)),stored=await rows(tx,selection+' WHERE id=?',[id]);return {receipt:receipt(stored[0],false),lease:Object.freeze({id,actorId,merchantId,token,kind:input.kind})};
 });
}
export async function guardCalendlyOperation(tx:PoolConnection,lease:CalendlyOperationLease){
 await calendlyOperationWriter(tx,lease.actorId,lease.merchantId,lease.kind);
 const [result]=await tx.execute<any>("UPDATE calendly_operations SET lease_until=DATE_ADD(UTC_TIMESTAMP(3),INTERVAL 120 SECOND),updated_at=UTC_TIMESTAMP(3) WHERE id=? AND merchant_id=? AND actor_id=? AND kind=? AND attempt_token=? AND state='pending' AND lease_until>UTC_TIMESTAMP(3)",[lease.id,lease.merchantId,lease.actorId,lease.kind,lease.token]);if(result.affectedRows!==1)throw new CalendlyOperationFault('changed');
}
export async function startCalendlyOperation(lease:CalendlyOperationLease,review:(tx:PoolConnection)=>Promise<void>){return calendlyOperationTransaction(async tx=>{await guardCalendlyOperation(tx,lease);await review(tx);const [result]=await tx.execute<any>('UPDATE calendly_operations SET started_at=UTC_TIMESTAMP(3) WHERE id=? AND started_at IS NULL',[lease.id]);if(result.affectedRows!==1)throw new CalendlyOperationFault('changed');});}
/** Must be called in the same transaction as the final local change it proves. */
export async function completeCalendlyOperation(tx:PoolConnection,lease:CalendlyOperationLease,raw:unknown){await guardCalendlyOperation(tx,lease);const result=calendlyOperationResult.parse(raw),stored=(await rows(tx,selection+' WHERE id=?',[lease.id]))[0];if(!stored?.started_at)throw new CalendlyOperationFault('changed');receipt({...stored,state:'success',result_json:result},false);await tx.execute("UPDATE calendly_operations SET state='success',result_json=?,updated_at=UTC_TIMESTAMP(3) WHERE id=?",[JSON.stringify(result),lease.id]);}
/** Metadata-only termination never overwrites success after a lost commit acknowledgement. */
export async function stopCalendlyOperation(lease:CalendlyOperationLease,cleanup?:(tx:PoolConnection)=>Promise<void>){return calendlyOperationTransaction(async tx=>{await rows(tx,'SELECT id FROM merchants WHERE id=? FOR UPDATE',[lease.merchantId]);const [stopped]=await tx.execute<any>("UPDATE calendly_operations SET state=IF(started_at IS NULL,'rejected','unknown'),updated_at=UTC_TIMESTAMP(3) WHERE id=? AND merchant_id=? AND actor_id=? AND attempt_token=? AND state='pending'",[lease.id,lease.merchantId,lease.actorId,lease.token]);if(stopped.affectedRows===1)await cleanup?.(tx);});}
export async function readCalendlyOperation(actorId:number,merchantId:number,raw:unknown){const {requestId}=calendlyOperationLookup.parse(raw);bookingReadId.parse(actorId);bookingReadId.parse(merchantId);return calendlyOperationTransaction(async tx=>{const found=await rows(tx,selection+' WHERE merchant_id=? AND actor_id=? AND request_id=?',[merchantId,actorId,requestId]);if(found.length!==1)throw new CalendlyOperationFault('missing');await calendlyOperationWriter(tx,actorId,merchantId,found[0].kind);return receipt(found[0],true);});}
/** Explicit review releases the block; it never dispatches the old operation. */
export async function acknowledgeCalendlyOperation(actorId:number,merchantId:number,raw:unknown){const {requestId}=calendlyOperationLookup.parse(raw);bookingReadId.parse(actorId);bookingReadId.parse(merchantId);return calendlyOperationTransaction(async tx=>{await rows(tx,'SELECT id FROM merchants WHERE id=? FOR UPDATE',[merchantId]);const found=await rows(tx,selection+' WHERE merchant_id=? AND request_id=? FOR UPDATE',[merchantId,requestId]);if(found.length!==1)throw new CalendlyOperationFault('missing');const row=found[0];await calendlyOperationWriter(tx,actorId,merchantId,row.kind);if(receipt(row,true).outcome!=='unknown')throw new CalendlyOperationFault('changed');await tx.execute("UPDATE calendly_operations SET state='unknown',acknowledged_at=UTC_TIMESTAMP(3),updated_at=UTC_TIMESTAMP(3) WHERE id=?",[row.id]);const stored=await rows(tx,selection+' WHERE id=?',[row.id]);return calendlyOperationReviewWorkspace.parse({actorId,merchantId,operation:receipt(stored[0],true)});});}
/** Authorized colleagues can review an interrupted operation if its original actor is unavailable. */
export async function readBlockingCalendlyOperation(actorId:number,merchantId:number){bookingReadId.parse(actorId);bookingReadId.parse(merchantId);return calendlyOperationTransaction(async tx=>{await rows(tx,'SELECT id FROM merchants WHERE id=? FOR UPDATE',[merchantId]);const found=await rows(tx,selection+" WHERE merchant_id=? AND (state='pending' OR (state='unknown' AND acknowledged_at IS NULL)) ORDER BY id DESC LIMIT 1",[merchantId]);await calendlyOperationWriter(tx,actorId,merchantId,found[0]?.kind??'connect');return calendlyOperationReviewWorkspace.parse({actorId,merchantId,operation:found.length?receipt(found[0],true):null});});}
