import crypto from 'node:crypto';
import {bookingReadId} from '../../shared/booking-read';
import {safePlatformUrl} from '../../shared/platform-workspace';
import {wooProductsInput,wooOrdersInput,wooOrderDetailsInput,wooProductsWorkspaceSchema,wooOrdersWorkspaceSchema,wooOrderDetailsWorkspaceSchema,wooStockStates,wooOrderStates,wooCurrencySchema,wooMoneySchema} from '../../shared/woocommerce-data-workspace';
import {wooSnapshot,wooRows,wooCount,wooStamp,WooWorkspaceFault} from './woocommerce-workspace';
/** Database decimals remain exact strings. Missing or invalid values never become zero. */
export function wooMoney(value:unknown):string|null{if(typeof value!=='string'&&typeof value!=='number')return null;const text=String(value),match=/^(0|[1-9][0-9]{0,15})(?:\.([0-9]{1,2}))?$/.exec(text);if(!match)return null;const result=match[1]+'.'+(match[2]??'').padEnd(2,'0');return wooMoneySchema.safeParse(result).success?result:null;}
export function wooCurrency(value:unknown){return wooCurrencySchema.safeParse(value).success?String(value):null;}
const optionalText=(value:unknown,max:number)=>typeof value==='string'?value.slice(0,max):null;
const optionalId=(value:unknown)=>bookingReadId.safeParse(value).success?Number(value):null;
const syncSql="CASE WHEN sync_status IN ('synced','pending','error') THEN sync_status ELSE 'unknown' END";
const productStateSql="CASE WHEN stock_status IN ('instock','outofstock','onbackorder') THEN stock_status ELSE 'unknown' END";
const orderStateSql="CASE WHEN BINARY status IN ('pending','processing','on-hold','completed','cancelled','refunded','failed') THEN status ELSE 'unknown' END";
const productColumns='id,merchant_id AS merchantId,woo_product_id AS providerId,name,slug,sku,price,regular_price AS regularPrice,sale_price AS salePrice,stock_quantity AS stockQuantity,manage_stock AS manageStock,image_url AS imageUrl,last_sync_at AS lastSyncAt,provider_updated_at AS providerUpdatedAt';
const orderColumns='id,merchant_id AS merchantId,woo_order_id AS providerId,order_number AS orderNumber,status AS rawStatus,currency,total,customer_name AS customerName,customer_phone AS customerPhone,order_date AS orderDate,last_sync_at AS lastSyncAt,provider_updated_at AS providerUpdatedAt';
function common(row:any){const value={id:wooCount(row.id),merchantId:wooCount(row.merchantId),providerId:optionalId(row.providerId),syncState:row.syncState,lastSyncAt:wooStamp(row.lastSyncAt),providerUpdatedAt:wooStamp(row.providerUpdatedAt)};return {...value,invalidData:value.providerId===null||value.syncState==='unknown'||!value.lastSyncAt||row.providerUpdatedAt!=null&&!value.providerUpdatedAt};}
function productRow(row:any){const base=common(row),price=wooMoney(row.price),regularPrice=wooMoney(row.regularPrice),salePrice=wooMoney(row.salePrice),manageStock=row.manageStock===1?true:row.manageStock===0?false:null,stockQuantity=typeof row.stockQuantity==='number'&&Number.isSafeInteger(row.stockQuantity)?row.stockQuantity:null;
 return {...base,name:row.name,slug:row.slug,sku:optionalText(row.sku,255),price,regularPrice,salePrice,state:row.state,manageStock,stockQuantity,imageUrl:safePlatformUrl(row.imageUrl),invalidData:base.invalidData||row.state==='unknown'||!row.name?.trim()||price===null||row.regularPrice!=null&&regularPrice===null||row.salePrice!=null&&salePrice===null||manageStock===null||row.stockQuantity!=null&&stockQuantity===null||manageStock===true&&stockQuantity===null};
}
function orderRow(row:any){const base=common(row),total=wooMoney(row.total),currency=wooCurrency(row.currency),orderDate=wooStamp(row.orderDate);return {...base,orderNumber:row.orderNumber,state:row.state,rawStatus:row.rawStatus,currency,total,customerName:optionalText(row.customerName,255),customerPhone:optionalText(row.customerPhone,50),orderDate,invalidData:base.invalidData||total===null||currency===null||!orderDate||row.state==='unknown'||!row.orderNumber?.trim()};}
async function readPage(actorId:number,merchantId:number,kind:'products'|'orders',input:unknown){const selection=kind==='products'?wooProductsInput.parse(input):wooOrdersInput.parse(input);return wooSnapshot(actorId,merchantId,async tx=>{
 const merchant=await wooRows(tx,'SELECT id FROM merchants WHERE id=?',[merchantId]);if(merchant.length!==1)throw new WooWorkspaceFault();
 const table=kind==='products'?'woocommerce_products':'woocommerce_orders',stateSql=kind==='products'?productStateSql:orderStateSql,keys:readonly string[]=kind==='products'?wooStockStates:wooOrderStates;
 const totalRows=await wooRows(tx,`SELECT COUNT(*) AS count FROM ${table} WHERE merchant_id=?`,[merchantId]);if(totalRows.length!==1)throw new WooWorkspaceFault();const args:Array<string|number>=[merchantId];let where='merchant_id=?';
 if(selection.search){const columns=kind==='products'?['name','sku','CAST(woo_product_id AS CHAR)']:['order_number','customer_name','customer_phone','customer_email','CAST(woo_order_id AS CHAR)'];where+=' AND ('+columns.map(c=>`${c} LIKE ? ESCAPE '!'`).join(' OR ')+')';const pattern='%'+selection.search.replace(/[!%_]/g,v=>'!'+v)+'%';args.push(...columns.map(()=>pattern));}
 if('startDate' in selection&&selection.startDate&&'endDate' in selection&&selection.endDate){where+=' AND order_date>=? AND order_date<DATE_ADD(?,INTERVAL 1 DAY)';args.push(selection.startDate,selection.endDate);}
 const grouped=await wooRows(tx,`SELECT ${stateSql} AS state,COUNT(*) AS count FROM ${table} WHERE ${where} GROUP BY state`,args);if(grouped.some(g=>!keys.includes(g.state))||new Set(grouped.map(g=>g.state)).size!==grouped.length)throw new WooWorkspaceFault();
 const groups=keys.map(key=>({key,count:wooCount(grouped.find(g=>g.state===key)?.count??0)})),matched=groups.reduce((n,g)=>n+g.count,0),total=selection.state==='all'?matched:groups.find(g=>g.key===selection.state)!.count;
 if(selection.state!=='all'){where+=` AND (${stateSql})=?`;args.push(selection.state);}const page=await wooRows(tx,`SELECT ${kind==='products'?productColumns:orderColumns},${stateSql} AS state,${syncSql} AS syncState FROM ${table} WHERE ${where} ORDER BY id DESC LIMIT ? OFFSET ?`,[...args,25,(selection.page-1)*25]);
 const common={actorId,merchantId,checkedAt:new Date().toISOString(),selection,summary:{stored:wooCount(totalRows[0].count),matched,groups},pagination:{page:selection.page,pageSize:25,total,pages:Math.ceil(total/25)}};
 if(kind==='orders')return wooOrdersWorkspaceSchema.parse({...common,rows:page.map(orderRow)});
 const settings=await wooRows(tx,'SELECT store_currency AS currency FROM woocommerce_settings WHERE merchant_id=?',[merchantId]);if(settings.length>1)throw new WooWorkspaceFault();return wooProductsWorkspaceSchema.parse({...common,currency:wooCurrency(settings[0]?.currency),rows:page.map(productRow)});
 });}
export async function readWooProductsWorkspace(actorId:number,merchantId:number,input:unknown){return wooProductsWorkspaceSchema.parse(await readPage(actorId,merchantId,'products',input));}
export async function readWooOrdersWorkspace(actorId:number,merchantId:number,input:unknown){return wooOrdersWorkspaceSchema.parse(await readPage(actorId,merchantId,'orders',input));}
function orderItems(value:unknown,page:number){let validArray=true,items:unknown[]=[];try{const parsed=typeof value==='string'?JSON.parse(value):null;if(!Array.isArray(parsed))throw Error();items=parsed;}catch{validArray=false;}
 const rows=items.map((value,index)=>{const r=value&&typeof value==='object'&&!Array.isArray(value)?value as any:{},providerId=optionalId(r.id),productId=optionalId(r.product_id),variationId=typeof r.variation_id==='number'&&Number.isSafeInteger(r.variation_id)&&r.variation_id>=0?r.variation_id:null,name=typeof r.name==='string'&&r.name.length<=500?r.name:null,sku=typeof r.sku==='string'&&r.sku.length<=255?r.sku:null,quantity=typeof r.quantity==='number'&&Number.isSafeInteger(r.quantity)&&r.quantity>0?r.quantity:null,subtotal=wooMoney(r.subtotal),total=wooMoney(r.total);
  return {position:index+1,providerId,productId,variationId,name,sku,quantity,subtotal,total,invalidData:!name?.trim()||quantity===null||subtotal===null||total===null||r.id!=null&&providerId===null||r.product_id!=null&&productId===null||r.variation_id!=null&&variationId===null||r.sku!=null&&sku===null};});
 return {validArray,invalidItems:rows.filter(r=>r.invalidData).length,total:rows.length,page,pageSize:25 as const,pages:Math.ceil(rows.length/25),rows:rows.slice((page-1)*25,page*25)};
}
export async function readWooOrderDetailsWorkspace(actorId:number,merchantId:number,input:unknown){const selection=wooOrderDetailsInput.parse(input);return wooSnapshot(actorId,merchantId,async tx=>{
 const merchant=await wooRows(tx,'SELECT id FROM merchants WHERE id=?',[merchantId]);if(merchant.length!==1)throw new WooWorkspaceFault();
 const records=await wooRows(tx,`SELECT ${orderColumns},${orderStateSql} AS state,${syncSql} AS syncState,customer_email AS customerEmail,subtotal,shipping_total AS shippingTotal,total_tax AS totalTax,discount_total AS discountTotal,payment_method AS paymentMethod,payment_method_title AS paymentMethodTitle,customer_note AS customerNote,line_items AS lineItems,paid_date AS paidAt,completed_date AS completedAt,created_at AS createdAt,updated_at AS updatedAt FROM woocommerce_orders WHERE merchant_id=? AND id=?`,[merchantId,selection.id]);
 if(records.length>1)throw new WooWorkspaceFault();const row=records[0],result={actorId,merchantId,checkedAt:new Date().toISOString(),selection};if(!row)return wooOrderDetailsWorkspaceSchema.parse({...result,order:null});
 const base=orderRow(row),items=orderItems(row.lineItems,selection.itemsPage),amounts=Object.fromEntries(['subtotal','shippingTotal','totalTax','discountTotal'].map(key=>[key,wooMoney(row[key])])),dates=Object.fromEntries(['paidAt','completedAt','createdAt','updatedAt'].map(key=>[key,wooStamp(row[key])]));
 const {lastSyncAt:_progress,updatedAt:_updated,...identity}={...row,...dates,orderDate:base.orderDate,lastSyncAt:base.lastSyncAt,providerUpdatedAt:base.providerUpdatedAt};
 const revision=crypto.createHash('sha256').update(JSON.stringify(identity)).digest('hex');
 return wooOrderDetailsWorkspaceSchema.parse({...result,order:{...base,revision,customerEmail:optionalText(row.customerEmail,255),...amounts,...dates,paymentMethod:optionalText(row.paymentMethod,100),paymentMethodTitle:optionalText(row.paymentMethodTitle,255),customerNote:typeof row.customerNote==='string'?row.customerNote:null,items,
  invalidData:base.invalidData||!items.validArray||items.invalidItems>0||amounts.subtotal===null||Object.entries(amounts).some(([key,value])=>row[key]!=null&&value===null)||Object.entries(dates).some(([key,value])=>row[key]!=null&&value===null)}});
 });}
