export const byaanDataEn = {
  stopTracking:'Stop tracking this request', stopTrackingHint:'This does not cancel a request that reached Byaan. Review the saved data before starting another sync.',
  title:'Byaan workspace', description:'Review your trainees, knowledge and academy content in one place.', overview:'Overview', trainees:'Trainees', faqs:'Knowledge questions', site:'Academy pages', sales:'Sales activity', tabs:'Byaan sections', connection:'Connection settings', refresh:'Refresh data',
  stored:'Stored records', matched:'Search matches', results:'Filtered results', search:'Search this section', filter:'Show', all:'All records', active:'Active', archived:'Archived', unknown:'Needs review', included:'Eligible for Sary', excluded:'Excluded from Sary', disabled:'Disabled', content:'With content', empty:'Empty content',
  searchHint:'Searches all records in this store.', noResults:'No matching records', noResultsHelp:'Try another search or show all records.', reset:'Clear filters', previous:'Previous page', next:'Next page', page:'Page', of:'of',
  courses:'Enrolled courses', noCourses:'No course names recorded', phone:'Phone', email:'Email', externalId:'Source reference', created:'Added to Sary', synced:'Last recorded sync', none:'Not recorded', details:'View details', close:'Close', courseWarning:'Some course data is invalid or shortened. Check the original record in Byaan.',
  question:'Question', answer:'Answer', category:'Category', activate:'Enable question', deactivate:'Disable question', include:'Include in Sary knowledge', exclude:'Exclude from Sary knowledge', review:'Review knowledge change', confirm:'Save this change', cancel:'Cancel', saving:'Saving…', saved:'Your choice was saved.', changed:'This record changed. Refresh and review the current version.', uncertain:'The change is not confirmed. Refresh the data before making another change.', forbidden:'Your permission changed. Refresh the page.',
  knowledgeHint:'These choices apply to the next knowledge sync. Eligibility does not confirm that the current assistant knowledge has been updated.', knowledgeReview:'This changes how the question is selected for the next knowledge sync. It does not delete the original question in Byaan.',
  about:'About the academy', vision:'Vision', mission:'Mission', policies:'Policies', custom:'Custom page', noTitle:'Untitled page', siteHint:'Synced source content is shown as plain text. Edit it in Byaan.',
  connectionRequired:'A verified active Byaan connection is required to open these records. Stored counts are retained.', sourceHint:'These are stored data counts, not revenue or a sales conversion rate.', test:'Test Sary', knowledge:'Knowledge sources', catalog:'Course catalog',
  resync:'Request a sync', resyncTitle:'Ask Byaan to sync again?', resyncHelp:'Send a signed request to your academy. Acceptance means the request was queued, not that all data finished syncing.', request:'Send request', requesting:'Sending request…', queued:'Byaan accepted the request into its queue. Completion is not yet confirmed.', not_sent:'This request was not sent to Byaan.', resyncUnknown:'We could not confirm the outcome. Check this same request before starting another.', recover:'Check request result', retrySame:'Continue the same request', requestId:'Request reference', requestDate:'Requested at', earlierLink:'This receipt belongs to an earlier connection version.', storage:'The request reference could not be saved in this browser. No new request was sent.', rate:'Please wait. Up to three new requests are allowed in five minutes.', recentRequest:'A previous request is recorded below. A new request can start another sync.', latestRequest:'Your latest sync request',
};
export const byaanDataAr: Record<keyof typeof byaanDataEn,string> = {
  stopTracking:'إنهاء متابعة هذا الطلب', stopTrackingHint:'لا يلغي ذلك طلبًا وصل إلى بيان. راجع البيانات المحفوظة قبل بدء مزامنة أخرى.',
  title:'مساحة بيان', description:'راجع المتدربين ومعرفة المساعد ومحتوى الأكاديمية في مكان واحد.', overview:'نظرة عامة', trainees:'المتدربون', faqs:'أسئلة المعرفة', site:'صفحات الأكاديمية', sales:'نشاط المبيعات', tabs:'أقسام بيان', connection:'إعدادات الربط', refresh:'تحديث البيانات',
  stored:'السجلات المحفوظة', matched:'مطابقات البحث', results:'نتائج التصفية', search:'ابحث في هذا القسم', filter:'عرض', all:'كل السجلات', active:'نشط', archived:'مؤرشف', unknown:'تحتاج مراجعة', included:'مؤهل لمعرفة ساري', excluded:'مستبعد من ساري', disabled:'معطل', content:'بمحتوى', empty:'محتوى فارغ',
  searchHint:'يشمل البحث كل سجلات هذا المتجر.', noResults:'لا توجد نتائج مطابقة', noResultsHelp:'جرّب بحثًا آخر أو اعرض كل السجلات.', reset:'مسح التصفية', previous:'الصفحة السابقة', next:'الصفحة التالية', page:'الصفحة', of:'من',
  courses:'الدورات المسجلة', noCourses:'لم تُسجل أسماء دورات', phone:'الهاتف', email:'البريد الإلكتروني', externalId:'مرجع المصدر', created:'أضيف إلى ساري', synced:'آخر مزامنة مسجلة', none:'غير مسجل', details:'عرض التفاصيل', close:'إغلاق', courseWarning:'بعض بيانات الدورات غير صالحة أو مختصرة. راجع السجل الأصلي في بيان.',
  question:'السؤال', answer:'الإجابة', category:'التصنيف', activate:'تفعيل السؤال', deactivate:'تعطيل السؤال', include:'إدراج في معرفة ساري', exclude:'استبعاد من معرفة ساري', review:'مراجعة تعديل المعرفة', confirm:'حفظ هذا التعديل', cancel:'إلغاء', saving:'جارٍ الحفظ…', saved:'حُفظ اختيارك.', changed:'تغير السجل. حدّث البيانات وراجع النسخة الحالية.', uncertain:'لم نتأكد من حفظ التعديل. حدّث البيانات قبل إجراء تعديل آخر.', forbidden:'تغيرت صلاحيتك. حدّث الصفحة.',
  knowledgeHint:'تُطبق هذه الاختيارات في مزامنة المعرفة القادمة. الأهلية لا تثبت تحديث معرفة المساعد الحالية.', knowledgeReview:'يغير هذا الاختيار إدراج السؤال في مزامنة المعرفة القادمة. لا يحذف السؤال الأصلي في بيان.',
  about:'عن الأكاديمية', vision:'الرؤية', mission:'الرسالة', policies:'السياسات', custom:'صفحة مخصصة', noTitle:'صفحة بلا عنوان', siteHint:'يعرض المحتوى المتزامن كنص عادي. عدّله من بيان.',
  connectionRequired:'يلزم ربط بيان موثق ونشط لفتح السجلات. تبقى أعداد البيانات المحفوظة ظاهرة.', sourceHint:'هذه أعداد بيانات محفوظة، ولا تمثل إيرادات أو نسبة تحويل المبيعات.', test:'جرّب ساري', knowledge:'مصادر المعرفة', catalog:'كتالوج الدورات',
  resync:'طلب مزامنة', resyncTitle:'تطلب مزامنة جديدة من بيان؟', resyncHelp:'أرسل طلبًا موقعًا إلى أكاديميتك. قبول الطلب يعني دخوله الطابور، ولا يثبت اكتمال مزامنة كل البيانات.', request:'إرسال الطلب', requesting:'جارٍ إرسال الطلب…', queued:'قبل بيان الطلب في الطابور. لم يتأكد اكتمال المزامنة بعد.', not_sent:'لم يُرسل هذا الطلب إلى بيان.', resyncUnknown:'لم نتأكد من النتيجة. تحقق من الطلب نفسه قبل بدء طلب آخر.', recover:'التحقق من نتيجة الطلب', retrySame:'متابعة الطلب نفسه', requestId:'مرجع الطلب', requestDate:'وقت الطلب', earlierLink:'هذا الإيصال يخص نسخة سابقة من الربط.', storage:'تعذر حفظ مرجع الطلب في هذا المتصفح. لم يُرسل طلب جديد.', rate:'انتظر قليلًا. يُسمح بثلاثة طلبات جديدة خلال خمس دقائق.', recentRequest:'يوجد طلب سابق مسجل أدناه. قد يبدأ الطلب الجديد مزامنة إضافية.', latestRequest:'آخر طلب مزامنة لك',
};
