export const cartWorkspaceEn={
 unlimited:'Unlimited by plan',storedStats:'Saved counters and amounts',unknownFlags:'Records with unknown flags',recoveredAmount:'Stored amount for recovered carts',excludedAmounts:'Recovered records excluded for invalid amounts',withoutReminder:'Recovery records without a reminder',
 title:'Abandoned carts',description:'Review each cart, send a considered reminder and follow the recorded result.',eyebrow:'Growth · Cart recovery',refresh:'Refresh',all:'All carts',waiting:'Ready for review',reminded:'Reminder recorded',recovered:'Recovery recorded',invalid:'Needs data review',total:'Saved carts',evidence:'These are saved states. A reminder or a recovery flag does not prove a paid order or an attributed sale.',automatic:'Reminders on this screen require review. A cart alone is not marketing consent.',readonly:'You can view carts. Managing reminders and recovery requires campaign permission.',
 search:'Search customer, phone, product or ID',searchAction:'Search',state:'Status',matches:'Matching carts',clear:'Clear filters',empty:'No saved carts yet.',noResults:'No carts match these filters.',outOfRange:'This page is outside the results.',first:'First page',previous:'Previous',next:'Next',page:'Page',of:'of',carts:'Carts',history:'Reminder history',historyHelp:'Check saved outcomes before sending again. Provider acceptance is separate from delivery, reading and sales.',historyEmpty:'No reviewed reminders yet.',cartId:'Cart',receiptId:'Receipt',
 details:'Cart details',close:'Close',cancel:'Cancel',remind:'Review reminder',recover:'Record recovery',recoverHelp:'Record this cart as recovered only if you intend to update this saved state. This does not create or verify a paid order.',recoverAck:'I understand that this updates the cart record only.',recoverConfirm:'Confirm recovery record',saved:'Recovery status recorded.',review:'Review message',reviewing:'Preparing review…',reviewFailed:'Could not load a current review. Check the connection and your permissions, then try again.',send:'Send this reminder',sendAck:'I reviewed this recipient, channel and message.',sending:'Saving the result…',sendHelp:'One message through this store’s selected channel. An uncertain outcome will not be resent automatically.',
 name:'Customer',phone:'Phone',unknown:'Unknown',notRecorded:'Not recorded',yes:'Yes',no:'No',amount:'Stored amount',unitUnknown:'Currency and amount unit are not stored. This is not verified revenue.',items:'Cart items',quantity:'Quantity',price:'Stored unit price',extra:'Additional saved item fields',raw:'Unparsed saved items',invalidHelp:'Some saved values are invalid. Details remain visible; actions stay blocked.',created:'Created',updated:'Last changed',reminderAt:'Reminder recorded at',recoveryAt:'Recovery recorded at',reminderFlag:'Stored reminder flag',recoveryFlag:'Stored recovery flag',
 discount:'Optional discount',noDiscount:'Send without a discount',chooseDiscount:'Choose an existing discount',discountSearch:'Search discount code',discountEmpty:'No matching discount codes.',discountUnavailable:'This code is not eligible for this reminder.',discountReadFailed:'Could not load discount codes. Retry or send without a discount.',discountHelp:'Choose an available percentage code without a minimum purchase. Sending does not reserve its use.',manageDiscounts:'Manage discounts',selectedDiscount:'Selected code',recipient:'Recipient',channel:'WhatsApp channel',message:'Message to send',quota:'Available messages',reviewStale:'The record or message options changed. Review again.',
 reserved:'Reserved · not yet confirmed',dispatching:'Attempt started · result pending',accepted:'Provider accepted',rejected:'Provider rejected',unknownResult:'Outcome unknown',suppressed:'Stopped before sending',receiptHelp:'Acceptance is not proof of delivery or a sale. Pending and unknown attempts need evidence before any resend. Hiding this receipt does not cancel the attempt; its record stays in reminder history.',restore:'Check saved result',restoreFailed:'Could not confirm the saved result. Keep this receipt and check again; do not send a replacement.',notFound:'No receipt was found for this request. Refresh the cart before making a new decision.',dismiss:'Hide receipt',storageFailed:'Local tracking storage is unavailable. A new send cannot start until it is available. Check reminder history for earlier attempts.',uncertain:'The outcome was not confirmed. Check the saved result before taking another action.',conflict:'The record changed. Refresh and review it again.',
 blocker_cart_state:'This cart is not waiting for a reminder.',blocker_phone:'The stored phone must use international format beginning with +.',blocker_channel:'Connect an active primary WhatsApp channel for this store.',blocker_consent:'No valid recorded marketing consent exists for this number.',blocker_quiet_hours:'Marketing messages are available from 08:00 to 22:00 in the store’s timezone.',blocker_subscription:'The current subscription is unavailable or no longer valid.',blocker_quota:'No message quota is available.',blocker_discount:'Choose an eligible percentage discount or send without a discount.',blocker_prior_reminder:'An earlier attempt is accepted or unresolved. Check its result before any new send.',blocker_message:'The message could not be prepared within the allowed length.',blocker_merchant:'The store or its owner is not active.',
};
export type CartWorkspaceCopy=typeof cartWorkspaceEn;
export const cartWorkspaceAr:CartWorkspaceCopy={
 unlimited:'غير محدودة وفق الباقة',storedStats:'الأعلام والمبالغ المحفوظة',unknownFlags:'سجلات بأعلام غير معروفة',recoveredAmount:'المبلغ المخزن للسلات المسجلة كمستعادة',excludedAmounts:'سجلات استعادة مستبعدة لخلل في المبلغ',withoutReminder:'سجلات استعادة دون تذكير',
 title:'السلات المتروكة',description:'راجع السلة، وأرسل تذكيرًا مدروسًا، وتابع النتيجة المسجلة.',eyebrow:'النمو · استعادة السلات',refresh:'تحديث',all:'كل السلات',waiting:'جاهزة للمراجعة',reminded:'سُجّل تذكير',recovered:'سُجّلت استعادة',invalid:'تحتاج مراجعة البيانات',total:'السلات المسجلة',evidence:'هذه حالات محفوظة. التذكير أو علامة الاستعادة لا يثبتان طلبًا مدفوعًا أو بيعًا ناتجًا عنهما.',automatic:'التذكيرات في هذه الشاشة تُراجع قبل الإرسال. وجود سلة وحده لا يثبت موافقة العميل على التسويق.',readonly:'يمكنك عرض السلات. إدارة التذكيرات والاستعادة تتطلب صلاحية الحملات.',
 search:'ابحث بالعميل أو الهاتف أو المنتج أو المعرّف',searchAction:'بحث',state:'الحالة',matches:'السلات المطابقة',clear:'مسح الفلاتر',empty:'لا توجد سلات محفوظة بعد.',noResults:'لا توجد سلات تطابق الفلاتر.',outOfRange:'هذه الصفحة خارج النتائج.',first:'الصفحة الأولى',previous:'السابق',next:'التالي',page:'صفحة',of:'من',carts:'السلات',history:'سجل التذكيرات',historyHelp:'راجع النتيجة المحفوظة قبل تكرار الإرسال. قبول المزوّد منفصل عن التسليم والقراءة والمبيعات.',historyEmpty:'لا توجد تذكيرات مراجعة بعد.',cartId:'السلة',receiptId:'الإيصال',
 details:'تفاصيل السلة',close:'إغلاق',cancel:'إلغاء',remind:'مراجعة التذكير',recover:'تسجيل الاستعادة',recoverHelp:'سجّل السلة كمستعادة إذا كنت تقصد تحديث حالتها المحفوظة. هذا لا ينشئ طلبًا مدفوعًا ولا يتحقق منه.',recoverAck:'أفهم أن هذا يحدّث سجل السلة فقط.',recoverConfirm:'تأكيد تسجيل الاستعادة',saved:'سُجّلت حالة الاستعادة.',review:'مراجعة الرسالة',reviewing:'جارٍ تجهيز المراجعة…',reviewFailed:'تعذّر تحميل مراجعة حديثة. تحقق من الاتصال والصلاحية ثم حاول مجددًا.',send:'إرسال هذا التذكير',sendAck:'راجعت المستلم والقناة ونص الرسالة.',sending:'جارٍ حفظ النتيجة…',sendHelp:'رسالة واحدة عبر قناة هذا المتجر المختارة. النتيجة غير المحسومة لا تُرسل مجددًا تلقائيًا.',
 name:'العميل',phone:'الهاتف',unknown:'غير معروف',notRecorded:'لم يُسجل',yes:'نعم',no:'لا',amount:'المبلغ المخزن',unitUnknown:'العملة ووحدة المبلغ غير محفوظتين. هذه ليست إيرادات مؤكدة.',items:'بنود السلة',quantity:'الكمية',price:'سعر الوحدة المخزن',extra:'حقول إضافية محفوظة للبند',raw:'بنود محفوظة تعذّر تفسيرها',invalidHelp:'بعض القيم المحفوظة غير صالحة. التفاصيل تبقى ظاهرة وتتوقف الإجراءات.',created:'تاريخ الإنشاء',updated:'آخر تعديل',reminderAt:'تاريخ تسجيل التذكير',recoveryAt:'تاريخ تسجيل الاستعادة',reminderFlag:'علامة التذكير المخزنة',recoveryFlag:'علامة الاستعادة المخزنة',
 discount:'خصم اختياري',noDiscount:'الإرسال دون خصم',chooseDiscount:'اختيار خصم موجود',discountSearch:'ابحث عن كود الخصم',discountEmpty:'لا توجد أكواد مطابقة.',discountUnavailable:'هذا الكود غير مؤهل لهذا التذكير.',discountReadFailed:'تعذّر تحميل الأكواد. أعد المحاولة أو أرسل دون خصم.',discountHelp:'اختر كود نسبة متاحًا دون حد شراء. الإرسال لا يحجز استخدام الكود.',manageDiscounts:'إدارة الخصومات',selectedDiscount:'الكود المختار',recipient:'المستلم',channel:'قناة واتساب',message:'الرسالة التي ستُرسل',quota:'الرسائل المتاحة',reviewStale:'تغير السجل أو خيارات الرسالة. راجعها مجددًا.',
 reserved:'محجوز · لم يتأكد التنفيذ',dispatching:'بدأت المحاولة · النتيجة قيد التحقق',accepted:'قبله المزوّد',rejected:'رفضه المزوّد',unknownResult:'النتيجة غير محسومة',suppressed:'توقف قبل الإرسال',receiptHelp:'القبول لا يثبت التسليم أو البيع. المحاولات المعلقة وغير المحسومة تحتاج دليلًا قبل أي إعادة إرسال. إخفاء الإيصال لا يلغي المحاولة؛ يبقى سجلها في سجل التذكيرات.',restore:'التحقق من النتيجة المحفوظة',restoreFailed:'تعذّر تأكيد النتيجة المحفوظة. احتفظ بهذا الإيصال وتحقق مجددًا، ولا ترسل بديلًا.',notFound:'لم يُعثر على إيصال لهذا الطلب. حدّث السلة قبل اتخاذ قرار جديد.',dismiss:'إخفاء الإيصال',storageFailed:'تعذّر استخدام التخزين المحلي للمتابعة. لن يبدأ إرسال جديد حتى يتاح. راجع سجل التذكيرات للمحاولات السابقة.',uncertain:'لم تتأكد النتيجة. تحقق من الإيصال المحفوظ قبل إجراء آخر.',conflict:'تغير السجل. حدّثه وراجعه مجددًا.',
 blocker_cart_state:'هذه السلة ليست بانتظار تذكير.',blocker_phone:'يجب حفظ الهاتف بالصيغة الدولية التي تبدأ بـ +.',blocker_channel:'اربط قناة واتساب أساسية فعالة لهذا المتجر.',blocker_consent:'لا توجد موافقة تسويق صالحة وموثقة لهذا الرقم.',blocker_quiet_hours:'الرسائل التسويقية متاحة من ٨ صباحًا إلى ١٠ مساءً بتوقيت المتجر.',blocker_subscription:'الاشتراك الحالي غير متاح أو انتهت صلاحيته.',blocker_quota:'لا توجد حصة رسائل متاحة.',blocker_discount:'اختر خصم نسبة مؤهلًا أو أرسل دون خصم.',blocker_prior_reminder:'هناك محاولة سابقة مقبولة أو غير محسومة. تحقق من نتيجتها قبل إرسال جديد.',blocker_message:'تعذّر تجهيز الرسالة ضمن الطول المسموح.',blocker_merchant:'المتجر أو حساب مالكه غير نشط.',
};
