export const referralWorkspaceEn = {
 codeId:'Code ID',storedState:'Saved reward status',notRecorded:'Not recorded',
 title:'Referrals and rewards', description:'Review invitations, referrals and recorded rewards in one place.', eyebrow:'Growth · Referrals',
 codes:'Referral codes', referrals:'Referrals', rewards:'Rewards', all:'All', active:'Active', inactive:'Disabled', pending:'Pending', completed:'Recorded complete', claimed:'Recorded as used', expired:'Expired', invalid:'Needs data review',
 refresh:'Refresh', search:'Search name, code, phone or ID', searchAction:'Search', state:'Status', matches:'Matching records', previous:'Previous', next:'Next', page:'Page', of:'of', clear:'Clear filters', empty:'No records in this section yet.', noResults:'No matching records.', outOfRange:'This page is outside the results.', first:'First page',
 evidence:'Counts describe saved records. A completed referral or a used reward does not prove a sale or a granted subscription benefit.', readonly:'Only a store owner can manage merchant invitations and reward records.',
 invitation:'Your merchant invitation', invitationHelp:'Keep merchant invitations separate from customer referral codes. Applying an invitation requires a review by the invited store owner.', create:'Create invitation code', createHelp:'Create one code for this store. Opening this page never creates a code. Existing customer codes stay separate.', createConfirm:'Create this code', noInvitation:'No merchant invitation code has been created.', invitationInvalid:'The invitation record needs review before it can be shared.', copy:'Copy invitation link', copied:'Invitation link copied.', copyFailed:'Could not copy. Select the link and copy it manually.',
 apply:'Use an invitation', inputCode:'Invitation code', review:'Review invitation', invalidCode:'Enter a valid invitation code, up to 50 letters, digits or hyphens.', invitationFailed:'Could not review this invitation. Check the code and store access, then try again.', applied:'This store already has a recorded invitation.', from:'Inviting store', applyHelp:'This records a referral and a pending 10% reward for the inviting store. It does not grant a subscription benefit or change either subscription.', applyAck:'I reviewed the inviting store and understand the recorded effect.', applyConfirm:'Record this invitation',
 details:'Details', close:'Close', cancel:'Cancel', confirm:'Confirm recording', claim:'Record reward as used', claimHelp:'This only changes the saved reward status. It does not apply a discount, extend a subscription or unlock analytics. Record it only when you intend to change this record.', claimAck:'I understand that this records a status only and does not grant a benefit.',
 code:'Code', name:'Name', phone:'Phone', storedCount:'Stored counter', rewardGiven:'Saved reward flag', completedFlag:'Saved completion flag', referralId:'Referral ID', type:'Reward type', descriptionLabel:'Description', created:'Created', updated:'Last changed', expiry:'Expiry', claimedAt:'Recorded use date', sourceAvailable:'Referral record available', yes:'Yes', no:'No', unknown:'Unknown', discount_10:'10% discount', free_month:'Free month', analytics_upgrade:'Analytics upgrade',
 saving:'Saving…', reviewing:'Reviewing…', saved:'Record saved. This action did not grant a subscription benefit.', createdNotice:'Invitation code created.', uncertain:'The result was not confirmed. Refresh and review the saved records before taking another action.', conflict:'The record changed. Refresh and review it again.', invalidHelp:'Some saved values or references are invalid. Review the details before taking action.',
};
export type ReferralWorkspaceCopy = typeof referralWorkspaceEn;
export const referralWorkspaceAr: ReferralWorkspaceCopy = {
 codeId:'معرّف الكود',storedState:'حالة المكافأة المخزنة',notRecorded:'لم يُسجل',
 title:'الإحالات والمكافآت', description:'راجع الدعوات والإحالات والمكافآت المسجلة من مكان واحد.', eyebrow:'النمو · الإحالات',
 codes:'أكواد الإحالة', referrals:'الإحالات', rewards:'المكافآت', all:'الكل', active:'مفعّل', inactive:'معطّل', pending:'بانتظار الإكمال', completed:'مسجلة كمكتملة', claimed:'مسجلة كمستخدمة', expired:'منتهية', invalid:'تحتاج مراجعة البيانات',
 refresh:'تحديث', search:'بحث بالاسم أو الكود أو الهاتف أو المعرّف', searchAction:'بحث', state:'الحالة', matches:'السجلات المطابقة', previous:'السابق', next:'التالي', page:'صفحة', of:'من', clear:'مسح الفلاتر', empty:'لا توجد سجلات في هذا القسم بعد.', noResults:'لا توجد نتائج مطابقة.', outOfRange:'هذه الصفحة خارج النتائج.', first:'الصفحة الأولى',
 evidence:'الأعداد تصف السجلات المحفوظة. اكتمال الإحالة أو تسجيل استخدام المكافأة لا يثبت بيعًا أو منح ميزة للاشتراك.', readonly:'مالك المتجر فقط يدير دعوات التجار وسجلات المكافآت.',
 invitation:'دعوة التاجر الخاصة بك', invitationHelp:'دعوات التجار مستقلة عن أكواد إحالة العملاء. تسجيل الدعوة يتطلب مراجعة مالك المتجر المدعو.', create:'إنشاء كود الدعوة', createHelp:'أنشئ كودًا واحدًا لهذا المتجر. فتح الصفحة لا ينشئ كودًا، وتبقى أكواد العملاء مستقلة.', createConfirm:'إنشاء هذا الكود', noInvitation:'لم يُنشأ كود دعوة للتاجر بعد.', invitationInvalid:'سجل الدعوة يحتاج مراجعة قبل مشاركته.', copy:'نسخ رابط الدعوة', copied:'نُسخ رابط الدعوة.', copyFailed:'تعذر النسخ. حدد الرابط وانسخه يدويًا.',
 apply:'استخدام دعوة', inputCode:'كود الدعوة', review:'مراجعة الدعوة', invalidCode:'أدخل كودًا صحيحًا حتى 50 حرفًا أو رقمًا أو شرطة.', invitationFailed:'تعذرت مراجعة الدعوة. تحقق من الكود وصلاحية المتجر ثم حاول مجددًا.', applied:'سُجلت دعوة لهذا المتجر مسبقًا.', from:'المتجر الداعي', applyHelp:'يسجل الإجراء إحالة ومكافأة خصم 10% معلّقة للمتجر الداعي. لا يمنح ميزة اشتراك ولا يغيّر اشتراك أي من المتجرين.', applyAck:'راجعت المتجر الداعي وأفهم أثر التسجيل.', applyConfirm:'تسجيل هذه الدعوة',
 details:'التفاصيل', close:'إغلاق', cancel:'إلغاء', confirm:'تأكيد التسجيل', claim:'تسجيل استخدام المكافأة', claimHelp:'يغيّر هذا الإجراء حالة سجل المكافأة فقط؛ لا يطبق خصمًا أو يمدد الاشتراك أو يفتح التحليلات. أكّد فقط إذا كنت تقصد تغيير هذا السجل.', claimAck:'أفهم أن الإجراء يسجل الحالة فقط ولا يمنح ميزة.',
 code:'الكود', name:'الاسم', phone:'الهاتف', storedCount:'العداد المخزن', rewardGiven:'علم المكافأة المحفوظ', completedFlag:'علم الإكمال المحفوظ', referralId:'معرّف الإحالة', type:'نوع المكافأة', descriptionLabel:'الوصف', created:'أُنشئ في', updated:'آخر تغيير', expiry:'الانتهاء', claimedAt:'تاريخ تسجيل الاستخدام', sourceAvailable:'سجل الإحالة متاح', yes:'نعم', no:'لا', unknown:'غير معروف', discount_10:'خصم 10%', free_month:'شهر مجاني', analytics_upgrade:'ترقية التحليلات',
 saving:'جارٍ الحفظ…', reviewing:'جارٍ المراجعة…', saved:'حُفظ السجل. لم يمنح هذا الإجراء ميزة للاشتراك.', createdNotice:'أُنشئ كود الدعوة.', uncertain:'لم تتأكد النتيجة. حدّث البيانات وراجع السجلات المحفوظة قبل أي إجراء آخر.', conflict:'تغير السجل. حدّث البيانات وراجعه من جديد.', invalidHelp:'بعض القيم أو المراجع المحفوظة غير سليمة. راجع التفاصيل قبل أي إجراء.',
};
