export const serviceCatalogAr={
 eyebrow:'خدمات واضحة. حجز أسهل.',title:'خدماتك',description:'رتّب ما تقدّمه، واضبط أسعاره ووقت تنفيذه من مكان واحد.',create:'إضافة خدمة',refresh:'تحديث',categories:'التصنيفات',packages:'حزم الخدمات',
 total:'جميع الخدمات',active:'نشطة',inactive:'معطّلة',unknown:'حالة غير معروفة',search:'البحث باسم الخدمة',searchHint:'اكتب اسم الخدمة',searchAction:'بحث',status:'الحالة',all:'كل الحالات',clear:'مسح الفلاتر',
 results:'{{total}} خدمة مطابقة',page:'صفحة {{page}} من {{pages}}',previous:'السابق',next:'التالي',first:'الصفحة الأولى',
 empty:'أضف أول خدمة إلى متجرك',emptyHint:'ابدأ بالاسم والسعر والمدة. يمكنك تنظيم التصنيفات والحزم لاحقًا.',noResults:'لا توجد خدمات بهذه الفلاتر',noResultsHint:'جرّب اسمًا آخر أو غيّر الحالة.',outOfRange:'هذه الصفحة لم تعد تحتوي خدمات',
 price:'السعر',duration:'مدة الخدمة',minutes:'{{value}} دقيقة',customPrice:'حسب الاتفاق',unavailable:'غير متاح',range:'{{min}} – {{max}}',uncategorized:'دون تصنيف',categoryUnavailable:'التصنيف غير متاح',appointment:'تحتاج موعدًا',noAppointment:'لا تتطلب موعدًا',
 details:'التفاصيل',edit:'تعديل',archive:'تعطيل',archiveNamed:'تعطيل {{name}}',archiveTitle:'تعطيل «{{name}}»؟',archiveHint:'تخرج الخدمة من قائمة الخدمات النشطة. تبقى حجوزاتها وسجلاتها محفوظة، ويمكن إعادة تفعيلها من التعديل. قد تحتاج الحزم المرتبطة بها إلى مراجعة.',confirmArchive:'تعطيل الخدمة',cancel:'إلغاء',archiveSuccess:'عُطّلت الخدمة وحُفظت سجلاتها.',
 changed:'تغيرت الخدمة أو الصفحة منذ فتح النافذة. أغلقها وحدّث القائمة ثم راجع الخدمة.',actionError:'تعذر تأكيد النتيجة. حدّث القائمة وراجع حالة الخدمة قبل المحاولة مجددًا.',conflict:'تغيرت نسخة الخدمة. حدّث القائمة وراجعها مجددًا.',reviewState:'تحديث ومراجعة الحالة',readOnly:'يمكنك عرض الخدمات. يلزم إذن الإدارة لإضافتها أو تعديلها.',
 repair:'تحتاج مراجعة',repairHint:'بعض الحقول أو العلاقات غير صالحة. افتح التعديل لمراجعتها قبل استخدامها.',unnamed:'خدمة دون اسم',loadingUpdate:'جارٍ تحديث القائمة…',unknownHint:'توجد خدمات بحالة غير معروفة. افتح تعديلها لتحديد الحالة الصحيحة.',
};
export const serviceCatalogEn:{[K in keyof typeof serviceCatalogAr]:string}={
 eyebrow:'Clear services. Easier booking.',title:'Your services',description:'Organize what you offer, set prices, and manage delivery time in one place.',create:'Add service',refresh:'Refresh',categories:'Categories',packages:'Service packages',
 total:'All services',active:'Active',inactive:'Inactive',unknown:'Unknown status',search:'Search service names',searchHint:'Enter a service name',searchAction:'Search',status:'Status',all:'All statuses',clear:'Clear filters',
 results:'{{total}} matching services',page:'Page {{page}} of {{pages}}',previous:'Previous',next:'Next',first:'First page',
 empty:'Add your first service',emptyHint:'Start with a name, price, and duration. Organize categories and packages later.',noResults:'No services match these filters',noResultsHint:'Try another name or change the status.',outOfRange:'This page no longer contains services',
 price:'Price',duration:'Service duration',minutes:'{{value}} minutes',customPrice:'By agreement',unavailable:'Unavailable',range:'{{min}} – {{max}}',uncategorized:'Uncategorized',categoryUnavailable:'Category unavailable',appointment:'Appointment required',noAppointment:'No appointment required',
 details:'Details',edit:'Edit',archive:'Deactivate',archiveNamed:'Deactivate {{name}}',archiveTitle:'Deactivate “{{name}}”?',archiveHint:'The service leaves the active catalog. Its bookings and history stay available, and you can reactivate it by editing. Related packages may need review.',confirmArchive:'Deactivate service',cancel:'Cancel',archiveSuccess:'Service deactivated. Its history is preserved.',
 changed:'The service or page changed after this dialog opened. Close it, refresh, and review the service.',actionError:'The result could not be confirmed. Refresh and review the service status before trying again.',conflict:'The service version changed. Refresh the list and review it again.',reviewState:'Refresh and review status',readOnly:'You can view services. Management permission is required to add or change them.',
 repair:'Needs review',repairHint:'Some fields or references are invalid. Open the editor to review them before use.',unnamed:'Unnamed service',loadingUpdate:'Refreshing the list…',unknownHint:'Some services have an unknown status. Open the editor to choose a valid status.',
};
