import {serviceCatalogAr,serviceCatalogEn} from './service-catalog-workspace';
import {serviceEditorAr,serviceEditorEn} from './service-editor-workspace';
export const serviceCollectionAr={...serviceEditorAr,
 title:'إضافة',editTitle:'تعديل',description:'رتّب التفاصيل بوضوح، وراجعها قبل الحفظ.',back:'العودة للقائمة',basics:'المعلومات الأساسية',advancedHint:'الاسم الإضافي والرمز واللون وترتيب العرض',preview:'ملخص التغييرات',confirm:'حفظ التغييرات',reviewTitle:'راجع التغييرات قبل الحفظ',reviewHint:'ستُحفظ هذه الإعدادات في كتالوج متجرك.',name:'الاسم',isActive:'الحالة',noName:'لم يُكتب الاسم',stale:'تغير السجل منذ فتحه. راجع النسخة الحالية قبل استبدال تعديلاتك.',readOnly:'يمكنك عرض التفاصيل؛ يلزم إذن الإدارة لحفظ التغييرات.',saveError:'تعذر تأكيد الحفظ. راجع القائمة قبل إنشاء أو حفظ نسخة أخرى؛ قد يكون الطلب السابق اكتمل.',viewList:'مراجعة القائمة',
 categoryCreate:'إضافة تصنيف',categoryEdit:'تعديل التصنيف',packageCreate:'إضافة باقة',packageEdit:'تعديل الباقة',nameEn:'الاسم بالإنجليزية',icon:'رمز اختياري',iconHint:'اكتب رمزًا مثل ✂️ أو 🧑‍💻؛ حتى 100 حرف.',color:'اللون الاختياري',colorHint:'اتركه فارغًا أو أدخل لونًا مثل #4f46e5.',colorError:'أدخل لونًا يبدأ بـ # ويتبعه 3 أو 6 أو 8 رموز سداسية، أو اتركه فارغًا.',orderHint:'عدد صحيح من 0 إلى 2147483647.',originalPrice:'السعر الأصلي بالريال',packagePrice:'سعر الباقة بالريال',serviceIds:'الخدمات داخل الباقة',servicesError:'اختر خدمة واحدة على الأقل، وحتى 200 خدمة متاحة.',packageRange:'سعر الباقة يجب ألا يتجاوز السعر الأصلي.',discount:'نسبة الخصم',discountValue:'{{value}}٪',saving:'قيمة التوفير',calculated:'يُحسب الخصم من الأسعار المدخلة. ليس نتيجة مبيعات فعلية.',saved:'حُفظت التغييرات.',selectionNote:'اختر خدمات نشطة من متجرك. يمكن البحث والتنقل بين جميع النتائج.',emptyValue:'غير محدد',
};
export const serviceCollectionEn:{[K in keyof typeof serviceCollectionAr]:string}={...serviceEditorEn,
 title:'Add',editTitle:'Edit',description:'Keep details clear, then review before saving.',back:'Back to list',basics:'Essential information',advancedHint:'Additional name, icon, color, and display order',preview:'Change summary',confirm:'Save changes',reviewTitle:'Review changes before saving',reviewHint:'These settings will be saved in your store catalog.',name:'Name',isActive:'Status',noName:'No name entered',stale:'This record changed after you opened it. Review the current version before replacing your changes.',readOnly:'You can view details. Management permission is required to save changes.',saveError:'The save result could not be confirmed. Review the list before creating or saving another version; the previous request may have completed.',viewList:'Review list',
 categoryCreate:'Add category',categoryEdit:'Edit category',packageCreate:'Add package',packageEdit:'Edit package',nameEn:'English name',icon:'Optional icon',iconHint:'Enter an icon such as ✂️ or 🧑‍💻; up to 100 characters.',color:'Optional color',colorHint:'Leave blank or enter a color such as #4f46e5.',colorError:'Enter # followed by 3, 6, or 8 hexadecimal characters, or leave blank.',orderHint:'A whole number from 0 to 2147483647.',originalPrice:'Original price in SAR',packagePrice:'Package price in SAR',serviceIds:'Services in this package',servicesError:'Choose at least one and up to 200 available services.',packageRange:'Package price must not exceed the original price.',discount:'Discount',discountValue:'{{value}}%',saving:'Savings',calculated:'The discount is calculated from the entered prices. It is not an actual sales result.',saved:'Changes saved.',selectionNote:'Choose active services from your store. Search and browse all results.',emptyValue:'Not specified',
};
const commonAr={...serviceCatalogAr,eyebrow:'كتالوج متجرك',total:'إجمالي السجلات',search:'البحث بالاسم',searchHint:'اكتب الاسم',results:'{{total}} نتيجة مطابقة',emptyHint:'أضف الاسم والتفاصيل، ثم راجعها قبل الحفظ.',noResults:'لا توجد نتائج بهذه الفلاتر',outOfRange:'لا توجد سجلات في هذه الصفحة',confirmArchive:'تأكيد التعطيل',archiveSuccess:'عُطّل السجل وحُفظت بياناته.',changed:'تغير السجل أو الصفحة منذ فتح النافذة. حدّث القائمة وراجع التفاصيل.',actionError:'تعذر تأكيد النتيجة. حدّث القائمة وراجع الحالة قبل المحاولة مجددًا.',conflict:'تغيرت نسخة السجل. حدّث القائمة وراجعها مجددًا.',readOnly:'يمكنك عرض السجلات؛ يلزم إذن الإدارة لإضافتها أو تعديلها.',unnamed:'دون اسم',unknownHint:'توجد سجلات بحالة غير معروفة. افتح التعديل لتحديد الحالة الصحيحة.'};
const commonEn={...serviceCatalogEn,eyebrow:'Your store catalog',total:'All records',search:'Search names',searchHint:'Enter a name',results:'{{total}} matching results',emptyHint:'Add a name and details, then review before saving.',noResults:'No results match these filters',outOfRange:'No records on this page',confirmArchive:'Confirm deactivation',archiveSuccess:'Record deactivated. Its data is preserved.',changed:'The record or page changed after this dialog opened. Refresh the list and review the details.',actionError:'The result could not be confirmed. Refresh and review the status before trying again.',conflict:'The record version changed. Refresh the list and review it again.',readOnly:'You can view records. Management permission is required to add or change them.',unnamed:'Unnamed',unknownHint:'Some records have an unknown status. Open the editor to choose a valid status.'};
export const serviceCategoryAr={...commonAr,title:'تصنيفات الخدمات',description:'اجمع الخدمات المتشابهة لتسهيل العثور عليها.',create:'إضافة تصنيف',empty:'أضف أول تصنيف',archiveHint:'يخرج التصنيف من الخيارات النشطة، وتبقى بياناته محفوظة. راجع الخدمات المرتبطة به لتحديد تصنيف متاح. يمكنك إعادة تفعيله من التعديل.'};
export const serviceCategoryEn={...commonEn,title:'Service categories',description:'Group related services so they are easier to find.',create:'Add category',empty:'Add your first category',archiveHint:'The category leaves active choices and its data is preserved. Review related services to choose an available category. You can reactivate it by editing.'};
export const servicePackageAr={...commonAr,title:'باقات الخدمات',description:'اجمع خدماتك في باقات بأسعار واضحة وخصم محسوب.',create:'إضافة باقة',empty:'أضف أول باقة',archiveHint:'تخرج الباقة من القائمة النشطة وتبقى بياناتها محفوظة. لا تتغير الخدمات التي تحتويها. يمكنك إعادة تفعيلها من التعديل.'};
export const servicePackageEn={...commonEn,title:'Service packages',description:'Bundle your services with clear prices and a calculated discount.',create:'Add package',empty:'Add your first package',archiveHint:'The package leaves the active list and its data is preserved. Its services are not changed. You can reactivate it by editing.'};
