export const serviceDetailsAr={
 title:'تفاصيل الخدمة',description:'راجع أداء الخدمة وحجوزاتها وإعداداتها من مكان واحد.',back:'العودة للخدمات',edit:'تعديل الخدمة',refresh:'تحديث البيانات',bookingsLink:'إدارة الحجوزات',readOnly:'يمكنك عرض التفاصيل؛ يلزم إذن الإدارة لتعديل الخدمة.',price:'سعر الخدمة',duration:'المدة',rating:'متوسط التقييم',noRating:'لا توجد تقييمات',outOfFive:'{{value}} من 5',sample:'{{count}} سجل تقييم عام صالح',unavailable:'غير متاح',unknown:'غير معروف',category:'التصنيف',noCategory:'دون تصنيف',repair:'بعض إعدادات الخدمة أو علاقاتها تحتاج مراجعة. افتح التعديل لتصحيحها.',
 bookings:'الحجوزات',allTime:'جميع الحجوزات المسجلة لهذه الخدمة في متجرك.',total:'كل الحجوزات',pending:'قيد الانتظار',confirmed:'مؤكدة',in_progress:'جارٍ التنفيذ',completed:'مكتملة',cancelled:'ملغاة',no_show:'لم يحضر',unknownStatus:'حالة غير معروفة',paidValue:'قيمة الحجوزات المكتملة والمدفوعة المسجلة',paidHint:'مجموع السعر النهائي لـ {{count}} حجز مكتمل بحالة دفع «مدفوع». لا يمثل كشف تحصيل أو تسوية دفع.',invalidValue:'توجد {{count}} قيمة غير صالحة؛ لا يمكن عرض مجموع كامل قبل مراجعتها.',completion:'نسبة الحجوزات المكتملة',completionHint:'المكتمل من جميع الحجوزات؛ ليست نسبة تحويل مبيعات.',percent:'{{value}}٪',recent:'آخر الحجوزات حسب تاريخ الموعد',recentHint:'عرض آخر {{count}} من {{total}}، مرتبة بتاريخ الموعد ثم رقم الحجز. قد تشمل مواعيد مستقبلية.',emptyBookings:'لم تُسجل حجوزات لهذه الخدمة بعد.',customer:'عميل دون اسم',bookingNumber:'حجز #{{id}}',date:'تاريخ الموعد',time:'وقت الموعد',finalPrice:'السعر النهائي',unpaid:'غير مدفوع',paid:'مدفوع',refunded:'مسترد',payment:'حالة الدفع',
 ratings:'توزيع التقييمات',ratingsHint:'سجلات التقييم العامة بدرجة من 1 إلى 5، والمرتبطة بحجز من الخدمة والمتجر نفسيهما.',excluded:'استُبعد {{count}} سجل تقييم عام بسبب درجة أو علاقة غير صالحة.',stars:'{{value}} نجوم',ratingCount:'{{count}} سجل',settings:'إعدادات الخدمة',settingsHint:'المواعيد ومقدمو الخدمة والتصنيف وطريقة العرض',checked:'آخر قراءة: {{value}}',
};
export const serviceDetailsEn:{[K in keyof typeof serviceDetailsAr]:string}={
 title:'Service details',description:'Review service activity, bookings, and settings in one place.',back:'Back to services',edit:'Edit service',refresh:'Refresh data',bookingsLink:'Manage bookings',readOnly:'You can view details. Management permission is required to edit the service.',price:'Service price',duration:'Duration',rating:'Average rating',noRating:'No ratings yet',outOfFive:'{{value}} out of 5',sample:'{{count}} valid public rating records',unavailable:'Unavailable',unknown:'Unknown',category:'Category',noCategory:'Uncategorized',repair:'Some service settings or references need review. Open the editor to repair them.',
 bookings:'Bookings',allTime:'All bookings recorded for this service in your store.',total:'All bookings',pending:'Pending',confirmed:'Confirmed',in_progress:'In progress',completed:'Completed',cancelled:'Cancelled',no_show:'No show',unknownStatus:'Unknown status',paidValue:'Recorded completed and paid booking value',paidHint:'Final prices of {{count}} completed bookings marked paid. This is not a collection or payment settlement statement.',invalidValue:'{{count}} invalid values prevent a complete total. Review them first.',completion:'Completed bookings',completionHint:'Completed out of all bookings; this is not a sales conversion rate.',percent:'{{value}}%',recent:'Latest bookings by appointment date',recentHint:'Showing {{count}} of {{total}}, ordered by appointment date then booking number. Future appointments may be included.',emptyBookings:'No bookings have been recorded for this service yet.',customer:'Unnamed customer',bookingNumber:'Booking #{{id}}',date:'Appointment date',time:'Appointment time',finalPrice:'Final price',unpaid:'Unpaid',paid:'Paid',refunded:'Refunded',payment:'Payment status',
 ratings:'Rating distribution',ratingsHint:'Public rating records from 1 to 5 linked to a booking for this service and store.',excluded:'{{count}} public rating records were excluded because of an invalid score or reference.',stars:'{{value}} stars',ratingCount:'{{count}} records',settings:'Service settings',settingsHint:'Bookings, service staff, categories, and display',checked:'Last read: {{value}}',
};
