// Kept deliberately small: used before loading either UI bundle.
export const CENTRAL_ROUTE_PATHS = [
  "/subscribe",
  "/pay",
  "/payment/callback",
  "/payment/return",
  "/solutions/sales",
  "/solutions/marketing",
  "/solutions/support",
  "/product/ai-agent",
  "/product/chatbot",
  "/product/whatsapp",
  "/product/broadcasts",
  "/ai-whatsapp-sales-agent",
  "/whatsapp-ordering-system",
  "/whatsapp-booking-system",
  "/ai-customer-service-whatsapp",
  "/solutions/clinics",
  "/solutions/clinics/appointment-booking",
  "/solutions/clinics/no-show-reminders",
  "/solutions/clinics/patient-inquiries",
  "/solutions/restaurants",
  "/solutions/restaurants/whatsapp-ordering",
  "/solutions/restaurants/digital-menu-payment",
  "/solutions/restaurants/delivery-repeat-orders",
  "/solutions/salons",
  "/solutions/salons/appointment-booking",
  "/solutions/salons/deposits-service-menu",
  "/solutions/salons/loyalty-campaigns",
  "/solutions/training-centers",
  "/solutions/training-centers/course-registration",
  "/solutions/training-centers/class-reminders-certificates",
  "/solutions/training-centers/course-marketing",
  "/solutions/real-estate",
  "/solutions/real-estate/lead-qualification",
  "/solutions/real-estate/property-catalog",
  "/solutions/real-estate/viewing-followup",
  "/solutions/consultants",
  "/solutions/consultants/consultation-booking",
  "/solutions/consultants/advance-payment",
  "/solutions/consultants/client-followup",
  "/docs/how-sari-works",
  "/docs/whatsapp-payment-guide",
  "/docs/ai-sales-guide",
  "/resources/blog/measure-impact",
  "/resources/blog/getting-started",
  "/resources/blog/human-handoff",
  "/resources/blog/training-byaan",
  "/resources/blog/voice-messages",
  "/resources/blog/verified-case-study",
  "/resources/blog/reading-reports",
  "/company/terms",
  "/company/privacy",
  "/",
  "/pricing",
  "/try-sari",
  "/sectors",
  "/products",
  "/resources/blog",
  "/resources/help-center",
  "/resources/success-stories",
  "/company/about",
  "/company/contact",
  "/support",
  "/login",
  "/signup",
  "/forgot-password",
  "/reset-password",
  "/verify-email",
  "/accept-invite",
] as const;
const routes = new Set<string>(CENTRAL_ROUTE_PATHS);
export function isCentralRoute(path: string): boolean {
  const clean = path.replace(/\/+$/, "") || "/";
  return (
    routes.has(clean) ||
    /^\/subscribe\/[^/]+$/.test(clean) ||
    /^\/pay\/[^/]+(?:\/status)?$/.test(clean) ||
    /^\/reset-password\/[^/]+$/.test(clean)
  );
}
