import {randomUUID} from 'node:crypto';
import {afterAll,afterEach,beforeEach,describe,it,expect} from 'vitest';
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {calendlyRouter} from './integrations/calendly';
describe.skipIf(!process.env.DATABASE_URL)('Calendly selected merchant MySQL access',()=>{
 let own:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof own;
 const q=async(sql:string,args:any[]=[]) => (await(await getPool())!.execute<any>(sql,args))[0];
 beforeEach(async()=>{own=await createDisposableMerchant('cal-dashboard');other=await createDisposableMerchant('cal-other');for(const [id,name] of [[own.merchantId,'Selected'],[other.merchantId,'Other']])await q("INSERT INTO platform_integrations (merchant_id,platform_type,store_name,is_active,settings) VALUES (?,'calendly',?,0,'{}')",[id,name]);});
 afterEach(async()=>cleanupDisposableMerchants([own.userId,other.userId]));afterAll(closeDb);
 const caller=(userId=own.userId,merchantId:number|null=own.merchantId)=>calendlyRouter.createCaller({user:{id:userId,role:'user'},merchantId:999,merchantRole:'owner',req:{headers:merchantId?{'x-merchant-id':String(merchantId)}:{}},res:{}} as any);
 it('reads and updates the explicit selected tenant for a manager with two memberships',async()=>{await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'manager',1)",[own.merchantId,other.userId]);expect(await caller(other.userId).getConnection()).toMatchObject({userName:'Selected',connected:false});expect(await caller(other.userId,other.merchantId).getConnection()).toMatchObject({userName:'Other'});await expect(caller(other.userId).updateSettings({syncToWhatsApp:false})).rejects.toMatchObject({code:'PRECONDITION_FAILED'});const current=await caller(other.userId).getWorkspace();await caller(other.userId).saveWorkspaceSettings({requestId:randomUUID(),revision:current.revision,syncToWhatsApp:false});await expect(caller(other.userId,null).getConnection()).rejects.toMatchObject({code:'PRECONDITION_FAILED'});const rows=await q("SELECT merchant_id,settings FROM platform_integrations WHERE merchant_id IN (?,?) ORDER BY merchant_id",[own.merchantId,other.merchantId]);expect(JSON.parse(rows.find((r:any)=>r.merchant_id===own.merchantId).settings)).toEqual({syncToWhatsApp:false});expect(JSON.parse(rows.find((r:any)=>r.merchant_id===other.merchantId).settings)).toEqual({});});
 it.each(['viewer','sales_supervisor'])('blocks %s reads and mutations before provider access',async role=>{await q('INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,?,1)',[own.merchantId,other.userId,role]);for(const read of [()=>caller(other.userId).getConnection(),()=>caller(other.userId).getUpcomingEvents({limit:5}),()=>caller(other.userId).getEventTypes(),()=>caller(other.userId).getStats(),()=>caller(other.userId).disconnect(),()=>caller(other.userId).syncNow(),()=>caller(other.userId).connect({apiKey:'synthetic-local-token-only'}),()=>caller(other.userId).updateSettings({syncToWhatsApp:true})])await expect(read()).rejects.toMatchObject({code:'FORBIDDEN'});});
 it('rejects foreign selection, revoked owner and suspended account',async()=>{await expect(caller(own.userId,other.merchantId).getConnection()).rejects.toMatchObject({code:'FORBIDDEN'});await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'owner',0)",[own.merchantId,own.userId]);await expect(caller().getConnection()).rejects.toMatchObject({code:'FORBIDDEN'});await q('UPDATE merchant_members SET is_active=1 WHERE merchant_id=? AND user_id=?',[own.merchantId,own.userId]);await q("UPDATE merchants SET status='suspended' WHERE id=?",[own.merchantId]);await expect(caller().updateSettings({syncToWhatsApp:false})).rejects.toMatchObject({code:'FORBIDDEN'});});
});
