import {afterAll,afterEach,beforeEach,describe,it,expect} from 'vitest';
import {getPool,closeDb,getDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {readCalendlyWorkspace,readCalendlyAppointments,readCalendlyReceipts} from './integrations/calendly-workspace';
describe.skipIf(!process.env.DATABASE_URL)('Calendly complete local workspace MySQL',()=>{
 let own:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof own,id:number,foreignId:number;
 const q=async(query:string,args:any[]=[]) => (await(await getPool())!.execute<any>(query,args))[0];
 beforeEach(async()=>{await getDb();own=await createDisposableMerchant('cal-workspace');other=await createDisposableMerchant('cal-foreign');const seed=async(merchantId:number)=>(await q("INSERT INTO platform_integrations(merchant_id,platform_type,is_active,store_name,store_url,access_token,webhook_endpoint_id,webhook_signing_secret,webhook_subscription_uri,settings) VALUES (?,'calendly',1,'Local account','https://api.calendly.com/users/LOCAL_123456','PRIVATE_TOKEN',?,'PRIVATE_SIGNING','https://api.calendly.com/webhook_subscriptions/LOCAL_123456','{\"syncToWhatsApp\":true,\"secret\":\"PRIVATE_SETTINGS\"}')",[merchantId,'E'+String(merchantId).padStart(42,'0')])).insertId;id=Number(await seed(own.merchantId));foreignId=Number(await seed(other.merchantId));});
 afterEach(async()=>cleanupDisposableMerchants([own.userId,other.userId]));afterAll(closeDb);
 const appointment=(index:number,merchantId=own.merchantId,integrationId=id)=>q("INSERT INTO calendly_appointments(merchant_id,integration_id,event_uri,invitee_uri,event_name,customer_name,customer_email,customer_phone,start_at,end_at,status,provider_updated_at,cancelled_at) VALUES (?,?,?,?,?,?,?,'966500000001','2026-01-02 12:00:00','2026-01-02 13:00:00',?,'2026-01-01 12:00:00',?)",[merchantId,integrationId,'https://api.calendly.com/scheduled_events/EVENT_12345678','https://api.calendly.com/scheduled_events/EVENT_12345678/invitees/INVITEE_'+String(index).padStart(8,'0'),index===5?'Literal %_! meeting':'Local meeting '+index,'Customer '+index,'customer'+index+'@example.test',index%2?'active':'cancelled',index%2?null:'2026-01-01 13:00:00']);
 const receipt=(index:number,merchantId=own.merchantId,integrationId=id)=>q("INSERT INTO calendly_webhook_receipts(merchant_id,integration_id,event_key,event_type,event_uri,invitee_uri,signature_timestamp,status,attempt_count,effect_applied,notification_required,last_error,processing_token) VALUES (?,?,?,'invitee.created','https://api.calendly.com/scheduled_events/EVENT_12345678','https://api.calendly.com/scheduled_events/EVENT_12345678/invitees/INVITEE_12345678',1800000000,?,3,1,0,'PRIVATE_PROVIDER_ERROR','PRIVATE_LEASE')",[merchantId,integrationId,String(index).padStart(64,'0'),index%2?'manual_review':'completed']);
 it('returns credential presence and stable review identity without secret values',async()=>{const a=await readCalendlyWorkspace(own.userId,own.merchantId);expect(a).toMatchObject({actorId:own.userId,merchantId:own.merchantId,present:true,state:'configured',credentialsStored:true,identityValid:true,settingsValid:true,settings:{syncToWhatsApp:true},webhooks:{registered:true,stored:0},counts:{appointments:0}});expect(JSON.stringify(a)).not.toMatch(/PRIVATE|tokenVersion|signingVersion|settingsVersion|subscription|endpoint/);await q('UPDATE platform_integrations SET last_sync_at=UTC_TIMESTAMP() WHERE id=?',[id]);expect((await readCalendlyWorkspace(own.userId,own.merchantId)).revision).toBe(a.revision);await q("UPDATE platform_integrations SET access_token='PRIVATE_NEW' WHERE id=?",[id]);expect((await readCalendlyWorkspace(own.userId,own.merchantId)).revision).not.toBe(a.revision);});
 it('distinguishes disabled, invalid and absent connection data',async()=>{await q("UPDATE platform_integrations SET is_active=0,settings='invalid-json',store_url='javascript:unsafe',webhook_subscription_uri='https://other.example.test/private' WHERE id=?",[id]);expect(await readCalendlyWorkspace(own.userId,own.merchantId)).toMatchObject({state:'disabled',userUri:null,identityValid:false,settingsValid:false,settings:{syncToWhatsApp:false},webhooks:{registered:false}});await q('DELETE FROM platform_integrations WHERE id=?',[id]);expect(await readCalendlyWorkspace(own.userId,own.merchantId)).toMatchObject({present:false,state:'unlinked',credentialsStored:false,userUri:null,settingsValid:true});});
 it.each(['{"syncToWhatsApp":"true"}','{"syncToWhatsApp":null}','[]'])('does not represent legacy settings %s as a confirmed choice',async settings=>{await q('UPDATE platform_integrations SET settings=? WHERE id=?',[settings,id]);expect(await readCalendlyWorkspace(own.userId,own.merchantId)).toMatchObject({settingsValid:false,settings:{syncToWhatsApp:false}});});
 it('paginates every saved appointment without foreign rows or hidden top-N limits',async()=>{for(let i=1;i<=56;i++)await appointment(i);await appointment(999,other.merchantId,foreignId);const first=await readCalendlyAppointments(own.userId,own.merchantId,{}),second=await readCalendlyAppointments(own.userId,own.merchantId,{page:2}),third=await readCalendlyAppointments(own.userId,own.merchantId,{page:3});expect(first).toMatchObject({summary:{stored:56,matched:56},pagination:{total:56,pages:3,page:1,pageSize:25}});expect([first.rows.length,second.rows.length,third.rows.length]).toEqual([25,25,6]);const all=[...first.rows,...second.rows,...third.rows];expect(new Set(all.map(r=>r.id)).size).toBe(56);expect(all.every(r=>r.merchantId===own.merchantId&&!r.invalidData)).toBe(true);expect(all.some(r=>r.customerName==='Customer 999')).toBe(false);expect((await readCalendlyAppointments(own.userId,own.merchantId,{page:4})).rows).toEqual([]);expect((await readCalendlyWorkspace(own.userId,own.merchantId)).counts).toMatchObject({appointments:56,active:28,cancelled:28,confirmationsAccepted:0});});
 it('searches literal symbols and combines dates and status against all stored appointments',async()=>{for(let i=1;i<=31;i++)await appointment(i);const literal=await readCalendlyAppointments(own.userId,own.merchantId,{search:'%_!'});expect(literal.rows.map(r=>r.eventName)).toEqual(['Literal %_! meeting']);expect((await readCalendlyAppointments(own.userId,own.merchantId,{search:"' OR 1=1 --"})).rows).toEqual([]);expect(await readCalendlyAppointments(own.userId,own.merchantId,{state:'active',startDate:'2026-01-02',endDate:'2026-01-02'})).toMatchObject({summary:{matched:31},pagination:{total:16}});expect((await readCalendlyAppointments(own.userId,own.merchantId,{startDate:'2026-01-03',endDate:'2026-01-03'})).rows).toEqual([]);});
 it('marks an invalid saved appointment range without fabricating a replacement',async()=>{const row=await appointment(1);await q("UPDATE calendly_appointments SET end_at='2026-01-02 11:00:00' WHERE id=?",[row.insertId]);const data=await readCalendlyAppointments(own.userId,own.merchantId,{});expect(data.rows[0]).toMatchObject({invalidData:true,startAt:'2026-01-02T12:00:00.000Z',endAt:'2026-01-02T11:00:00.000Z'});});
 it('paginates all update receipts and hides provider errors, leases and resource identifiers',async()=>{for(let i=1;i<=31;i++)await receipt(i);await receipt(999,other.merchantId,foreignId);const first=await readCalendlyReceipts(own.userId,own.merchantId,{}),second=await readCalendlyReceipts(own.userId,own.merchantId,{page:2});expect([first.rows.length,second.rows.length]).toEqual([25,6]);expect(first).toMatchObject({summary:{stored:31,matched:31},pagination:{total:31,pages:2}});expect(first.rows.every(r=>r.hasError&&r.effectApplied&&!r.notificationRequired&&!r.invalidData)).toBe(true);expect(JSON.stringify(first)).not.toMatch(/PRIVATE|eventUri|inviteeUri|processingToken|lastError/);expect(await readCalendlyReceipts(own.userId,own.merchantId,{state:'manual_review'})).toMatchObject({pagination:{total:16}});expect((await readCalendlyReceipts(own.userId,own.merchantId,{search:'%'})).rows).toEqual([]);expect((await readCalendlyWorkspace(own.userId,own.merchantId)).webhooks).toMatchObject({stored:31,needsReview:16,recentCompleted:15});});
});
