import {beforeEach,afterEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({reviewedSettings:vi.fn(),readOperation:vi.fn(),blockingOperation:vi.fn(),ackOperation:vi.fn(),workspace:vi.fn(),appointments:vi.fn(),receipts:vi.fn(),access:vi.fn(),db:vi.fn(),integration:vi.fn(),pool:vi.fn(),lock:vi.fn(),release:vi.fn(),replace:vi.fn(),remove:vi.fn(),settings:vi.fn(),lastSync:vi.fn(),current:vi.fn(),create:vi.fn(),delete:vi.fn(),request:vi.fn(),list:vi.fn(),health:vi.fn(),stats:vi.fn(),sync:vi.fn()}));
vi.mock('./accounts/merchant-access',()=>({resolveMerchantAccess:m.access}));
vi.mock('./db',async original=>({...await original<typeof import('./db')>(),getDb:m.db,getPool:m.pool,getIntegrationByType:m.integration,replaceCalendlyIntegration:m.replace,deleteIntegrationByType:m.remove,updateIntegrationSettings:m.settings,updateIntegrationLastSync:m.lastSync}));
vi.mock('./integrations/calendly-api',async original=>({...await original<typeof import('./integrations/calendly-api')>(),getCalendlyCurrentUser:m.current,createCalendlyWebhookSubscription:m.create,deleteCalendlyWebhookSubscription:m.delete,calendlyApiRequest:m.request,listCalendlyCollection:m.list}));
vi.mock('./integrations/calendly-webhook-receipts',()=>({getCalendlyWebhookHealth:m.health,getCalendlyAppointmentStats:m.stats,syncCalendlyAppointments:m.sync}));
vi.mock('./integrations/calendly-workspace',()=>({readCalendlyWorkspace:m.workspace,readCalendlyAppointments:m.appointments,readCalendlyReceipts:m.receipts}));
vi.mock('./integrations/calendly-settings',()=>({saveReviewedCalendlySettings:m.reviewedSettings}));
vi.mock('./integrations/calendly-operation',async original=>({...await original<typeof import('./integrations/calendly-operation')>(),readCalendlyOperation:m.readOperation,readBlockingCalendlyOperation:m.blockingOperation,acknowledgeCalendlyOperation:m.ackOperation}));
import {calendlyRouter} from './integrations/calendly';
import {appRouter} from './routers';
const requestId='d6749734-b63a-4d83-b5a6-84c57fdfdd60';
const inputs={saveWorkspaceSettings:{requestId,revision:'a'.repeat(64),syncToWhatsApp:false},getOperation:{requestId},getBlockingOperation:undefined,acknowledgeOperation:{requestId},getWorkspace:undefined,getAppointmentsWorkspace:{},getReceiptsWorkspace:{},getConnection:undefined,connect:{apiKey:'synthetic-token-for-local-test'},disconnect:undefined,syncNow:undefined,updateSettings:{syncToWhatsApp:false},getUpcomingEvents:{limit:5},getEventTypes:undefined,getStats:undefined};
const names=Object.keys(inputs) as (keyof typeof inputs)[];
afterEach(()=>vi.unstubAllEnvs());
beforeEach(()=>{vi.resetAllMocks();m.workspace.mockResolvedValue({});m.appointments.mockResolvedValue({});m.receipts.mockResolvedValue({});m.access.mockResolvedValue({merchantId:40,role:'owner'});m.db.mockResolvedValue({});m.integration.mockResolvedValue({id:11,merchantId:40,isActive:1,storeName:'Selected',storeUrl:'https://api.calendly.com/users/LOCAL_123456',accessToken:'PRIVATE_TOKEN',webhookSigningSecret:'PRIVATE_SIGNING',webhookEndpointId:'PRIVATE_ENDPOINT',webhookSubscriptionUri:'https://api.calendly.com/webhook_subscriptions/OLD_123456',settings:'{}'});m.pool.mockResolvedValue({getConnection:async()=>({query:m.lock,release:m.release})});m.lock.mockResolvedValue([[{acquired:1}]]);m.replace.mockResolvedValue({id:11});m.current.mockResolvedValue({uri:'https://api.calendly.com/users/LOCAL_123456',current_organization:'https://api.calendly.com/organizations/LOCAL_123456',name:'Local user'});m.create.mockResolvedValue('https://api.calendly.com/webhook_subscriptions/NEW_123456');m.delete.mockResolvedValue(undefined);m.request.mockResolvedValue({collection:[]});m.list.mockResolvedValue([]);m.health.mockResolvedValue({recentTotal:0,recentCompleted:0,awaiting:0,manualReview:0,oldestPendingSeconds:null});m.stats.mockResolvedValue({total:3,upcoming:2,remindersSent:1});m.sync.mockResolvedValue(3);vi.stubEnv('CALENDLY_WEBHOOK_BASE_URL','https://local-only.example.test');});
for(const mounted of [false,true]){
 const caller=(user:any={id:7,role:'user'},selected:any='40')=>{const ctx={user,merchantId:999,merchantRole:'owner',req:{headers:{'x-merchant-id':selected}},res:{}} as any;return mounted?appRouter.createCaller(ctx).calendly:calendlyRouter.createCaller(ctx);};
 const call=(name:typeof names[number],api=caller(),value:any=inputs[name])=>(api[name] as any)(value);
 it.each(names)(`requires integration permission before ${mounted?'mounted':'local'} %s`,async name=>{await expect(call(name,caller(null))).rejects.toMatchObject({code:'UNAUTHORIZED'});for(const access of [null,{merchantId:40,role:'viewer'},{merchantId:40,role:'sales_supervisor'}]){m.access.mockResolvedValue(access);await expect(call(name)).rejects.toMatchObject({code:'FORBIDDEN'});}expect(m.db).not.toHaveBeenCalled();expect(m.integration).not.toHaveBeenCalled();expect(m.current).not.toHaveBeenCalled();expect(m.sync).not.toHaveBeenCalled();});
 it.each(names)(`rejects unavailable storage before %s (${mounted})`,async name=>{m.db.mockResolvedValue(null);await expect(call(name)).rejects.toMatchObject({code:'INTERNAL_SERVER_ERROR',message:'calendly_dashboard:unavailable'});m.db.mockRejectedValue(Error('PRIVATE_SQL'));await expect(call(name)).rejects.toMatchObject({message:'calendly_dashboard:unavailable'});expect(m.integration).not.toHaveBeenCalled();expect(m.pool).not.toHaveBeenCalled();});
 it.each(names)(`rejects forged tenant and actor inputs on %s (${mounted})`,async name=>{for(const extra of [{merchantId:999},{actorId:999},{unexpected:true}])await expect(call(name,caller(),{...inputs[name],...extra})).rejects.toMatchObject({code:'BAD_REQUEST'});expect(m.integration).not.toHaveBeenCalled();expect(m.current).not.toHaveBeenCalled();});
 it.each(['owner','manager'])(`uses the selected %s tenant throughout all routes (${mounted})`,async role=>{m.access.mockResolvedValue({merchantId:40,role});for(const name of names)await call(name);expect(m.access).toHaveBeenCalledWith(7,40);expect(m.reviewedSettings).toHaveBeenCalledWith(7,40,inputs.saveWorkspaceSettings);expect(m.readOperation).toHaveBeenCalledWith(7,40,{requestId});expect(m.blockingOperation).toHaveBeenCalledWith(7,40);expect(m.ackOperation).toHaveBeenCalledWith(7,40,{requestId});expect(m.workspace).toHaveBeenCalledWith(7,40);expect(m.appointments).toHaveBeenCalledWith(7,40,{search:'',state:'all',period:'all',page:1});expect(m.receipts).toHaveBeenCalledWith(7,40,{search:'',state:'all',event:'all',page:1});expect(m.integration.mock.calls.every(args=>args[0]===40&&args[1]==='calendly')).toBe(true);expect(m.health).toHaveBeenCalledWith(40);expect(m.stats).toHaveBeenCalledWith(40);expect(m.replace).toHaveBeenCalledWith(expect.objectContaining({merchantId:40}));expect(m.remove).toHaveBeenCalledWith(40,'calendly');expect(m.lock).toHaveBeenCalledWith('SELECT GET_LOCK(?, 20) AS acquired',['sari:calendly:connection:40']);});
 it(`redacts connection secrets and dependency errors (${mounted})`,async()=>{expect(JSON.stringify(await caller().getConnection())).not.toMatch(/PRIVATE|accessToken|webhookSigningSecret|webhookEndpointId|webhookSubscriptionUri/);m.integration.mockRejectedValue(Error('PRIVATE_DATABASE'));await expect(caller().getConnection()).rejects.toMatchObject({message:'calendly_dashboard:unavailable'});});
 it(`distinguishes provider failures from empty event lists (${mounted})`,async()=>{expect(await caller().getUpcomingEvents({limit:5})).toEqual([]);expect(await caller().getEventTypes()).toEqual([]);m.request.mockRejectedValue(Error('PRIVATE_API'));m.list.mockRejectedValue(Error('PRIVATE_API'));await expect(caller().getUpcomingEvents({limit:5})).rejects.toMatchObject({message:'calendly_dashboard:unavailable'});await expect(caller().getEventTypes()).rejects.toMatchObject({message:'calendly_dashboard:unavailable'});m.request.mockResolvedValue({wrong:[]});await expect(caller().getUpcomingEvents({limit:5})).rejects.toMatchObject({message:'calendly_dashboard:unavailable'});});
 it(`does not call the provider for inactive or missing connections (${mounted})`,async()=>{for(const row of [undefined,{isActive:0,accessToken:'PRIVATE',storeUrl:'https://api.calendly.com/users/LOCAL_123456'}]){m.integration.mockResolvedValue(row);expect(await caller().getUpcomingEvents({limit:5})).toEqual([]);expect(await caller().getEventTypes()).toEqual([]);}expect(m.request).not.toHaveBeenCalled();expect(m.list).not.toHaveBeenCalled();});
 it(`rejects malformed selection and token before reading credentials (${mounted})`,async()=>{await expect(caller(undefined,'bad').getConnection()).rejects.toMatchObject({code:'BAD_REQUEST'});for(const apiKey of ['', 'x'.repeat(4097),'a'.repeat(20)+'\u0001'])await expect(caller().connect({apiKey})).rejects.toMatchObject({code:'BAD_REQUEST'});expect(m.integration).not.toHaveBeenCalled();});
 it.each(['connect','disconnect','syncNow','updateSettings'] as const)(`rechecks authority after waiting for the lock on %s (${mounted})`,async name=>{
  m.lock.mockImplementation(async(sql:string)=>{if(sql.includes('GET_LOCK'))m.access.mockResolvedValue(null);return [[{acquired:1}]];});
  await expect(call(name)).rejects.toMatchObject({code:'FORBIDDEN'});expect(m.integration).not.toHaveBeenCalled();expect(m.current).not.toHaveBeenCalled();expect(m.sync).not.toHaveBeenCalled();expect(m.release).toHaveBeenCalledOnce();
 });
 it(`does not delete the new remote subscription after an ambiguous local save (${mounted})`,async()=>{
  m.replace.mockRejectedValue(Error('commit acknowledgement lost'));await expect(call('connect')).rejects.toMatchObject({code:'BAD_REQUEST'});expect(m.create).toHaveBeenCalledOnce();expect(m.delete).not.toHaveBeenCalled();
 });

}
