// @vitest-environment jsdom
import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';
import {Router,Route} from 'wouter';import {memoryLocation} from 'wouter/memory-location';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {campaignReportWorkspaceAr as ar,campaignReportWorkspaceEn as en} from '../client/src/locales/campaign-report-workspace';
const m=vi.hoisted(()=>({actor:7,merchant:20,language:'en',query:{} as any,read:vi.fn(),export:vi.fn(),download:vi.fn(),retry:vi.fn(),auth:vi.fn()}));
vi.mock('@/lib/trpc',()=>({trpc:{auth:{me:{useQuery:(_:any,options:any)=>{m.auth(options);return {data:{id:m.actor}};}}},merchants:{getCurrent:{useQuery:()=>({data:{id:m.merchant}})}},campaigns:{reportWorkspace:{useQuery:(input:any,options:any)=>{m.read(input,options);return {...m.query,data:typeof m.query.data==='function'?m.query.data(input):m.query.data};}}},useUtils:()=>({campaigns:{reportExport:{fetch:m.export}}})}}));
vi.mock('@/lib/campaign-report-csv',()=>({downloadCampaignReportCsv:m.download}));
vi.mock('react-i18next',()=>({useTranslation:()=>({i18n:{language:m.language},t:(key:string,values:Record<string,unknown>={})=>{const copy=m.language==='ar'?ar:en;return (copy[key.split('.').at(-1) as keyof typeof en]??key).replace(/{{(\w+)}}/g,(_,name)=>String(values[name]??''));}})}));
vi.mock('@/components/merchant/WorkspaceState',()=>({WorkspaceState:({kind,onRetry}:any)=><div data-state={kind}>{kind}<button onClick={onRetry}>retry</button></div>,workspaceFailureKind:(error:any)=>error?.data?.code==='FORBIDDEN'?'forbidden':'error'}));
import CampaignReport from '../client/src/pages/merchant/CampaignReport';
import {campaignReportId,campaignReportNavigation} from '../client/src/lib/campaign-report-navigation';
let root:Root,container:HTMLDivElement,memory:ReturnType<typeof memoryLocation>;
const fixture=(selection:any)=>{
 const total=selection.search==='absent'?0:selection.status==='all'?40:5,offset=(selection.page-1)*25;
 const rows=Array.from({length:Math.max(0,Math.min(25,total-offset))},(_,i)=>selection.view==='results'?{kind:'result',id:offset+i+1,phone:`96650000${String(i).padStart(3,'0')}`,name:`Customer ${i}`,status:selection.status==='all'?'success':selection.status,reason:'none',recordedAt:'2026-10-01T10:00:00.000Z'}:{kind:'recipient',id:offset+i+1,phone:`96650000${String(i).padStart(3,'0')}`,name:null,status:selection.status==='all'?'manual_review':selection.status,reason:'uncertain',recordedAt:'2026-10-01T10:00:00.000Z',acceptedAt:null,attempts:3,quotaHeld:true});
 return {actorId:7,merchantId:20,canManage:true,selection,checkedAt:'2026-10-01T12:00:00.000Z',timezone:'Asia/Riyadh',campaign:{id:selection.id,name:'Campaign fixture',message:'Visible message',imageUrl:null,status:'completed',createdAt:'2026-10-01T00:00:00.000Z',scheduledAt:null,recipients:40,accepted:5,basis:'stored_campaign_counters'},summary:{results:{total:40,success:30,failed:5,pending:5,successRate:75,excludedLinks:0},recipients:{total:40,pending:10,processing:5,sent:5,failed:5,suppressed:10,manualReview:5}},pagination:{page:selection.page,pageSize:25,total,pages:Math.ceil(total/25)},rows};
};
const full=(input:any)=>{const first=fixture({...input,page:1}),second=fixture({...input,page:2});return {...first,pagination:{page:1,pageSize:10000,total:first.pagination.total,pages:first.pagination.total?1:0},rows:[...first.rows,...second.rows]};};
const render=()=>act(async()=>root.render(<Router hook={memory.hook} searchHook={memory.searchHook}><Route path="/merchant/campaigns/:id/report"><CampaignReport/></Route></Router>));
const button=(name:string)=>Array.from(container.querySelectorAll('button')).find(element=>element.textContent?.trim()===name)!;
const click=(element:Element)=>act(async()=>{element.dispatchEvent(new MouseEvent('click',{bubbles:true}));});
const navigate=(path:string)=>act(async()=>memory.navigate(path));
beforeEach(()=>{vi.clearAllMocks();Object.assign(globalThis,{React,IS_REACT_ACT_ENVIRONMENT:true});m.actor=7;m.merchant=20;m.language='en';m.query={data:fixture,error:null,isLoading:false,isFetching:false,refetch:m.retry};m.export.mockImplementation(async input=>full(input));memory=memoryLocation({path:'/merchant/campaigns/7/report',record:true});container=document.createElement('div');document.body.append(container);root=createRoot(container);});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();vi.useRealTimers();vi.restoreAllMocks();});
describe('actual campaign report page',()=>{
 it('shows scoped recipient evidence and held quota without claiming delivery',async()=>{await render();expect(container.textContent).toContain(en.basis);expect(container.querySelectorAll('.cr-records>li')).toHaveLength(25);expect(container.textContent).toContain(en.quotaHeld);expect(container.textContent).toContain(en.reasonUncertain);expect(m.download).not.toHaveBeenCalled();});
 it('restores the section, filters and page from a shared link',async()=>{memory.navigate('/merchant/campaigns/7/report?view=results&status=failed&q=966&page=2&lang=en');await render();expect(m.read.mock.calls.at(-1)?.[0]).toEqual({id:7,view:'results',status:'failed',search:'966',page:2});expect(container.textContent).toContain(en.outOfRange);await click(button(en.first));expect(memory.history?.at(-1)).toBe('/merchant/campaigns/7/report?view=results&status=failed&q=966&lang=en');});
 it('changes sections with a valid status and restores browser navigation',async()=>{memory.navigate('/merchant/campaigns/7/report?status=manual_review&page=2&lang=en');await render();await click(button(en.results));expect(m.read.mock.calls.at(-1)?.[0]).toMatchObject({view:'results',status:'all',page:1});expect(memory.history?.at(-1)).toContain('lang=en');await navigate('/merchant/campaigns/7/report?status=manual_review');expect(m.read.mock.calls.at(-1)?.[0]).toMatchObject({view:'recipients',status:'manual_review'});});
 it('shows full stored result counts and their sample instead of deriving them from one page',async()=>{memory.navigate('/merchant/campaigns/7/report?view=results');await render();expect(container.querySelector('.cr-result-totals')?.textContent).toContain('40');expect(container.querySelector('.cr-result-totals')?.textContent).toContain('75%');});
 it('keeps empty and filtered-out states actionable without making up a zero success rate',async()=>{memory.navigate('/merchant/campaigns/7/report?view=results&q=absent');await render();expect(container.textContent).toContain(en.noMatches);expect(container.textContent).toContain('75%');await click(button(en.clear));expect(memory.history?.at(-1)).toBe('/merchant/campaigns/7/report?view=results');});
 it('warns about excluded links and links directly to unresolved outcomes',async()=>{m.query.data=(input:any)=>{const data=fixture(input);data.summary.results.excludedLinks=2;return data;};await render();expect(container.textContent).toContain('2 records were excluded');await click(button(en.showReviews));expect(m.read.mock.calls.at(-1)?.[0]).toMatchObject({view:'recipients',status:'manual_review',search:'',page:1});});
 it.each(['actor','tenant','campaign','selection','rows'])('hides invalid or stale %s snapshots',async mode=>{m.query.data=(input:any)=>{const data=fixture(input);if(mode==='actor')data.actorId=8;if(mode==='tenant')data.merchantId=21;if(mode==='campaign')data.campaign.id=9;if(mode==='selection')data.selection={...input,search:'other'};if(mode==='rows')data.rows.pop();return data;};await render();expect(container.querySelector('[data-state=error]')).toBeTruthy();expect(container.textContent).not.toContain('Campaign fixture');expect(m.download).not.toHaveBeenCalled();});
 it('hides stale counts on read failure and retries the read',async()=>{m.query.error={data:{code:'FORBIDDEN'}};await render();expect(container.querySelector('[data-state=forbidden]')).toBeTruthy();expect(container.querySelector('dl')).toBeNull();await click(button('retry'));expect(m.retry).toHaveBeenCalledOnce();});
 it('refuses partial route IDs without reading a report',async()=>{memory.navigate('/merchant/campaigns/7x/report');await render();expect(container.querySelector('[data-state=missing]')).toBeTruthy();expect(m.read).not.toHaveBeenCalled();expect(m.auth.mock.calls.at(-1)?.[0]).toMatchObject({enabled:false});});
 it('renders unsafe or unavailable images as an explicit missing attachment',async()=>{m.query.data=(input:any)=>({...fixture(input),campaign:{...fixture(input).campaign,imageUrl:'javascript:alert(1)'}});await render();expect(container.querySelector('.cr-message img')).toBeNull();expect(container.textContent).toContain(en.imageUnavailable);});
 it('uses safe image URLs with no referrer and handles image-load failure',async()=>{m.query.data=(input:any)=>({...fixture(input),campaign:{...fixture(input).campaign,imageUrl:'/uploads/fixture.png'}});await render();const image=container.querySelector('.cr-message img')!;expect(image.getAttribute('referrerpolicy')).toBe('no-referrer');await act(async()=>image.dispatchEvent(new Event('error')));expect(container.querySelector('.cr-message img')).toBeNull();expect(container.textContent).toContain(en.imageUnavailable);});
 it('keeps malformed timezone data from crashing the report',async()=>{m.query.data=(input:any)=>({...fixture(input),timezone:'Invalid/Zone'});await render();expect(container.textContent).toContain(en.unknownDate);});
 it('renders Arabic labels and keeps translation keys out of the visible report',async()=>{m.language='ar';await render();expect(container.textContent).toContain(ar.title);expect(container.textContent).not.toContain('merchantUx.campaignReportWorkspace');expect(container.querySelector('[dir=rtl]')).toBeTruthy();});
});
describe('report export boundary in the actual UI',()=>{
 it('downloads a fresh complete matching export and ignores the visible page size',async()=>{await render();await click(button(en.export));expect(m.export).toHaveBeenCalledWith({id:7,view:'recipients',status:'all',search:''},{staleTime:0});expect(m.download.mock.calls[0][0].rows).toHaveLength(40);expect(container.textContent).toContain(en.exportStarted);});
 it.each(['actor','tenant','campaign','filters','partial'])('does not download a mismatched %s export',async mode=>{m.export.mockImplementation(async input=>{const data=full(input);if(mode==='actor')data.actorId=9;if(mode==='tenant')data.merchantId=99;if(mode==='campaign'){data.campaign.id=9;data.selection.id=9;}if(mode==='filters')data.selection.search='different';if(mode==='partial')data.rows.pop();return data;});await render();await click(button(en.export));expect(m.download).not.toHaveBeenCalled();expect(container.textContent).toContain(en.exportFailed);});
 it('reports a server-side size increase without leaking raw errors',async()=>{m.export.mockRejectedValue({data:{code:'PAYLOAD_TOO_LARGE'},message:'PRIVATE detail'});await render();await click(button(en.export));expect(container.textContent).toContain('10,000');expect(container.textContent).not.toContain('PRIVATE');expect(m.download).not.toHaveBeenCalled();});
 it('ignores a late export after changing filters',async()=>{let finish!:(data:any)=>void;m.export.mockImplementation(()=>new Promise(resolve=>finish=resolve));await render();await click(button(en.export));await navigate('/merchant/campaigns/7/report?status=manual_review');await act(async()=>finish(full({id:7,view:'recipients',status:'all',search:''})));expect(m.download).not.toHaveBeenCalled();});
 it('ignores a late export after switching accounts',async()=>{let finish!:(data:any)=>void;m.export.mockImplementation(()=>new Promise(resolve=>finish=resolve));await render();await click(button(en.export));m.actor=8;m.query.data=(input:any)=>({...fixture(input),actorId:8});await render();await act(async()=>finish(full({id:7,view:'recipients',status:'all',search:''})));expect(m.download).not.toHaveBeenCalled();});
 it('prevents duplicate export while its first request is pending',async()=>{let finish!:(data:any)=>void;m.export.mockImplementation(()=>new Promise(resolve=>finish=resolve));await render();await click(button(en.export));expect(button(en.exporting).disabled).toBe(true);await click(button(en.exporting));expect(m.export).toHaveBeenCalledOnce();await act(async()=>finish(full({id:7,view:'recipients',status:'all',search:''})));expect(m.download).toHaveBeenCalledOnce();});
});
it('parses only canonical route IDs and matching report filter vocabularies',()=>{expect(campaignReportId('7x')).toBeNull();expect(campaignReportId('07')).toBeNull();expect(campaignReportId('9007199254740992')).toBeNull();expect(campaignReportNavigation(7,'?view=results&status=manual_review&page=2x')).toMatchObject({view:'results',status:'all',page:1});});
