import {afterAll,afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const provider=vi.hoisted(()=>({send:vi.fn()}));
vi.mock('./channels/whatsapp/providers',()=>({getWhatsAppProvider:()=>({send:provider.send})}));
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {acknowledgeCampaignManualReviews,CampaignReviewScopeError,runCampaignDeliveryBatch} from './automation/campaign-delivery-outbox';

describe.skipIf(!process.env.DATABASE_URL)('campaign review isolation and atomic state in local MySQL',()=>{
  let owner:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof owner;
  const q=async(sql:string,args:any[]=[]) => (await (await getPool())!.execute<any>(sql,args))[0];
  const campaign=async(merchant=owner.merchantId,status='failed')=>Number((await q("INSERT INTO campaigns (merchantId,name,message,status) VALUES (?,'Review fixture','Local test only',?)",[merchant,status])).insertId);
  const queue=async(id:number,phone='999000001',status='manual_review',merchant=owner.merchantId)=>Number((await q(`INSERT INTO campaign_delivery_outbox (campaign_id,merchant_id,customer_phone,status,processing_token,claimed_at,available_at,last_error)
    VALUES (?,?,?,?,?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 1 DAY),'ambiguous_provider_outcome')`,[id,merchant,phone,status,status==='processing'?'fixture-token':null,status==='processing'?new Date():null])).insertId);
  const log=async(id:number,delivery:number,phone='999000001')=>Number((await q("INSERT INTO campaignLogs (campaignId,campaign_outbox_id,customerPhone,status,errorMessage) VALUES (?,?,?,'failed','ambiguous_provider_outcome')",[id,delivery,phone])).insertId);
  const acknowledge=(id:number)=>acknowledgeCampaignManualReviews(id,owner.merchantId);
  const rows=(id:number)=>q('SELECT id,status,last_error,quota_reserved,quota_subscription_id,quota_period_start FROM campaign_delivery_outbox WHERE campaign_id=? ORDER BY id',[id]);
  const parent=async(id:number)=>(await q('SELECT status,sentCount,totalRecipients FROM campaigns WHERE id=?',[id]))[0];
  beforeEach(async()=>{vi.clearAllMocks();owner=await createDisposableMerchant('campaign-review');other=await createDisposableMerchant('campaign-review-other');});
  afterEach(async()=>{vi.restoreAllMocks();expect(provider.send).not.toHaveBeenCalled();await q('DELETE l FROM campaignLogs l JOIN campaigns c ON c.id=l.campaignId WHERE c.merchantId IN (?,?)',[owner.merchantId,other.merchantId]);await cleanupDisposableMerchants([owner.userId,other.userId]);});afterAll(closeDb);

  it('commits acknowledgement, safe log annotation and campaign totals together without refund or resend',async()=>{
    const id=await campaign(),review=await queue(id),sent=await queue(id,'999000002','sent');await log(id,review);await q('UPDATE campaign_delivery_outbox SET quota_reserved=1,quota_subscription_id=123,quota_period_start=UTC_TIMESTAMP(3) WHERE id=?',[review]);const before=(await rows(id))[0];
    expect(await acknowledge(id)).toEqual({acknowledged:1});expect((await rows(id))[0]).toEqual({...before,status:'suppressed',last_error:'merchant_acknowledged'});expect(await parent(id)).toEqual({status:'completed',sentCount:1,totalRecipients:2});expect((await q('SELECT status,errorMessage FROM campaignLogs WHERE campaign_outbox_id=?',[review]))[0]).toEqual({status:'failed',errorMessage:'merchant_acknowledged'});expect((await rows(id))[1].id).toBe(sent);
  });
  it('keeps active recipients sending and never acknowledges pending work',async()=>{const id=await campaign(),review=await queue(id);await queue(id,'999000002','pending');await log(id,review);expect(await acknowledge(id)).toEqual({acknowledged:1});expect((await rows(id)).map(r=>r.status)).toEqual(['suppressed','pending']);expect(await parent(id)).toEqual({status:'sending',sentCount:0,totalRecipients:2});});
  it('rejects missing and foreign parents, including forged child ownership',async()=>{const foreign=await campaign(other.merchantId),delivery=await queue(foreign);await log(foreign,delivery);for(const id of [foreign,2147483647])await expect(acknowledge(id)).rejects.toBeInstanceOf(CampaignReviewScopeError);expect((await rows(foreign))[0].status).toBe('manual_review');});
  it('rolls everything back when a child has contradictory tenant ownership',async()=>{const id=await campaign(),mine=await queue(id);await queue(id,'999000002','sent',other.merchantId);await log(id,mine);await expect(acknowledge(id)).rejects.toThrow('ownership is inconsistent');expect((await rows(id))[0].status).toBe('manual_review');expect((await q('SELECT errorMessage FROM campaignLogs WHERE campaign_outbox_id=?',[mine]))[0].errorMessage).toBe('ambiguous_provider_outcome');expect((await parent(id)).status).toBe('failed');});
  it('does not annotate logs linked to another campaign or a different phone',async()=>{
    const id=await campaign(),foreign=await campaign(other.merchantId),a=await queue(id),b=await queue(id,'999000002'),c=await queue(id,'999000003');const wrongParent=await log(foreign,a),wrongPhone=await log(id,b,'999000004'),valid=await log(id,c,'999000003');
    expect(await acknowledge(id)).toEqual({acknowledged:3});const logs=await q('SELECT id,errorMessage FROM campaignLogs WHERE id IN (?,?,?) ORDER BY id',[wrongParent,wrongPhone,valid]);expect(logs.map(r=>r.errorMessage)).toEqual(['ambiguous_provider_outcome','ambiguous_provider_outcome','merchant_acknowledged']);
  });
  it.each(['UPDATE campaign_delivery_outbox','UPDATE campaigns SET sentCount'])('rolls back the log and all state when %s fails',async failure=>{
    const id=await campaign(),delivery=await queue(id);await log(id,delivery);const pool=(await getPool())!,connection=await pool.getConnection(),native=connection.execute.bind(connection);vi.spyOn(pool,'getConnection').mockResolvedValueOnce(connection);vi.spyOn(connection,'execute').mockImplementation((async(...args:any[])=>{if(String(args[0]).includes(failure))throw Error('Injected write failure');return native(...args as [any,any]);})as any);
    await expect(acknowledge(id)).rejects.toThrow('Injected write failure');vi.restoreAllMocks();expect((await rows(id))[0].status).toBe('manual_review');expect((await q('SELECT errorMessage FROM campaignLogs WHERE campaign_outbox_id=?',[delivery]))[0].errorMessage).toBe('ambiguous_provider_outcome');expect(await parent(id)).toEqual({status:'failed',sentCount:0,totalRecipients:0});
  });
  it('serializes simultaneous acknowledgements so each recipient closes once',async()=>{const id=await campaign();await queue(id);await queue(id,'999000002');const results=await Promise.all(Array.from({length:6},()=>acknowledge(id)));expect(results.map(r=>r.acknowledged).sort()).toEqual([0,0,0,0,0,2]);expect(await parent(id)).toEqual({status:'completed',sentCount:0,totalRecipients:2});});
  it.each([true,false])('updates only an occasion owned by the campaign tenant (matching=%s)',async matching=>{const id=await campaign();await queue(id);await queue(id,'999000002','sent');await q("INSERT INTO occasion_campaigns (merchantId,campaign_id,occasionType,year,status) VALUES (?,?,'national_day',2026,'sending')",[matching?owner.merchantId:other.merchantId,id]);await acknowledge(id);const occasion=(await q('SELECT status,recipientCount,sentAt FROM occasion_campaigns WHERE campaign_id=?',[id]))[0];expect(occasion.status).toBe(matching?'completed':'sending');expect(occasion.recipientCount).toBe(matching?1:0);expect(occasion.sentAt!==null).toBe(matching);});
  it('keeps a legacy campaign without queue evidence unchanged',async()=>{const id=await campaign();await q('UPDATE campaigns SET sentCount=7,totalRecipients=10 WHERE id=?',[id]);expect(await acknowledge(id)).toEqual({acknowledged:0});expect(await parent(id)).toEqual({status:'failed',sentCount:7,totalRecipients:10});});
  it('rechecks parent ownership after waiting on another transaction',async()=>{
    const id=await campaign();await queue(id);const holder=await (await getPool())!.getConnection();let pending:Promise<unknown>|undefined;
    try{await holder.beginTransaction();await holder.execute('SELECT id FROM campaigns WHERE id=? FOR UPDATE',[id]);let done=false;pending=acknowledge(id).then(value=>({value}),error=>({error})).finally(()=>{done=true;});await new Promise(r=>setTimeout(r,50));expect(done).toBe(false);await holder.execute('UPDATE campaigns SET merchantId=? WHERE id=?',[other.merchantId,id]);await holder.commit();expect((await pending as any).error).toBeInstanceOf(CampaignReviewScopeError);expect((await rows(id))[0].status).toBe('manual_review');}finally{await holder.rollback();holder.release();await pending;}
  });
  it('waits for an in-flight terminal write and acknowledges the committed review set',async()=>{
    const id=await campaign(owner.merchantId,'sending'),delivery=await queue(id,'999000001','processing'),holder=await (await getPool())!.getConnection();let pending:Promise<unknown>|undefined;
    try{await holder.beginTransaction();await holder.execute('SELECT id FROM campaign_delivery_outbox WHERE id=? FOR UPDATE',[delivery]);let done=false;pending=acknowledge(id).finally(()=>{done=true;});await new Promise(r=>setTimeout(r,50));expect(done).toBe(false);await holder.execute("UPDATE campaign_delivery_outbox SET status='manual_review',processing_token=NULL,claimed_at=NULL WHERE id=?",[delivery]);await holder.execute("INSERT INTO campaignLogs (campaignId,campaign_outbox_id,customerPhone,status,errorMessage) VALUES (?,?,'999000001','failed','ambiguous_provider_outcome')",[id,delivery]);await holder.commit();expect(await pending).toEqual({acknowledged:1});expect((await rows(id))[0].status).toBe('suppressed');expect((await parent(id)).status).toBe('completed');}finally{await holder.rollback();holder.release();await pending;}
  });
  it('worker reconciliation counts current locked recipients after waiting for the parent',async()=>{
    const id=await campaign(owner.merchantId,'sending');await queue(id,'999000001','sent');const second=await queue(id,'999000002','pending'),holder=await (await getPool())!.getConnection();let pending:Promise<unknown>|undefined;
    try{await holder.beginTransaction();await holder.execute('SELECT id FROM campaigns WHERE id=? FOR UPDATE',[id]);let done=false;pending=runCampaignDeliveryBatch(1).finally(()=>{done=true;});await new Promise(r=>setTimeout(r,70));expect(done).toBe(false);await holder.execute("UPDATE campaign_delivery_outbox SET status='sent' WHERE id=?",[second]);await holder.commit();await pending;expect(await parent(id)).toEqual({status:'completed',sentCount:2,totalRecipients:2});}finally{await holder.rollback();holder.release();await pending;}
  });
});
