import {beforeEach,describe,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({db:vi.fn()}));vi.mock('./db/connection',()=>({getDb:mocks.db}));
import {readCampaignDetails,CampaignDetailsUnavailableError} from './campaign-details';
import {campaignDetailsSchema} from '../shared/campaign-details';
const fixture=()=>({actorId:1,merchantId:2,canManage:false,checkedAt:'2026-10-01T12:00:00Z',timezone:'Asia/Riyadh',campaign:{id:7,name:'Fixture',message:'Message',imageUrl:null,status:'draft',createdAt:'2026-10-01T10:00:00Z',scheduledAt:null,recipients:10,accepted:8,basis:'stored_campaign_counters',definitionKey:'a'.repeat(64)},audience:{status:'valid',filters:{}},queue:null,excludedRecipients:0});
beforeEach(()=>{mocks.db.mockReset();mocks.db.mockResolvedValue(null);});
describe('campaign details snapshot contract',()=>{
  it.each([{id:0},{id:1.5},{id:Number.MAX_SAFE_INTEGER+1},{id:7,merchantId:9},{id:7,actorId:9},{id:7,expectedDefinition:'a'.repeat(64)}])('rejects forged details selection %j before storage',async raw=>{await expect(readCampaignDetails(1,2,raw)).rejects.toThrow();expect(mocks.db).not.toHaveBeenCalled();});
  it.each([0,-1,NaN,Infinity,1.5,Number.MAX_SAFE_INTEGER+1])('rejects unsafe account or tenant identity %s',async id=>{await expect(readCampaignDetails(id,2,{id:7})).rejects.toBeInstanceOf(CampaignDetailsUnavailableError);await expect(readCampaignDetails(1,id,{id:7})).rejects.toBeInstanceOf(CampaignDetailsUnavailableError);expect(mocks.db).not.toHaveBeenCalled();});
  it('does not return an empty successful snapshot on storage failure',async()=>{await expect(readCampaignDetails(1,2,{id:7})).rejects.toThrow('Campaign details unavailable');mocks.db.mockRejectedValue(Error('PRIVATE SQL'));await expect(readCampaignDetails(1,2,{id:7})).rejects.toThrow('Campaign details unavailable');});
  it('rejects an invalid capture clock before storage',async()=>{await expect(readCampaignDetails(1,2,{id:7},new Date(NaN))).rejects.toBeInstanceOf(CampaignDetailsUnavailableError);expect(mocks.db).not.toHaveBeenCalled();});
  it('accepts unknown recipient evidence only as null and never a fabricated empty queue',()=>{expect(campaignDetailsSchema.safeParse(fixture()).success).toBe(true);expect(campaignDetailsSchema.safeParse({...fixture(),queue:{total:0,accepted:0,awaiting:0,suppressed:0,needsReview:0}}).success).toBe(false);});
  it('rejects inconsistent counters and malformed reviewed identities',()=>{const value=fixture();for(const patch of [{accepted:11},{definitionKey:'invalid'},{recipients:-1}])expect(campaignDetailsSchema.safeParse({...value,campaign:{...value.campaign,...patch}}).success).toBe(false);expect(campaignDetailsSchema.safeParse({...value,queue:{total:4,accepted:1,awaiting:1,suppressed:1,needsReview:0}}).success).toBe(false);});
  it('keeps invalid audience evidence separate instead of broadening it to all customers',()=>{expect(campaignDetailsSchema.safeParse({...fixture(),audience:{status:'invalid'}}).success).toBe(true);expect(campaignDetailsSchema.safeParse({...fixture(),audience:{status:'valid',filters:{unknown:true}}}).success).toBe(false);expect(campaignDetailsSchema.safeParse({...fixture(),audience:{status:'invalid',filters:{}}}).success).toBe(false);});
});
