// @vitest-environment jsdom
import React,{act} from 'react';
import { createRoot,type Root } from 'react-dom/client';
import { Router } from 'wouter';
import { memoryLocation } from 'wouter/memory-location';
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { campaignWorkspaceAr as ar,campaignWorkspaceEn as en } from '../client/src/locales/campaign-workspace';
const m=vi.hoisted(()=>({language:'en',actor:7,merchant:20,query:{} as any,calls:vi.fn(),send:vi.fn(),remove:vi.fn(),review:vi.fn(),refresh:vi.fn(),invalidate:vi.fn()}));
vi.mock('@/lib/trpc',()=>({trpc:{auth:{me:{useQuery:()=>({data:{id:m.actor},isFetching:false})}},merchants:{getCurrent:{useQuery:()=>({data:{id:m.merchant},isFetching:false})}},
  campaigns:{workspace:{useQuery:(input:any,options:any)=>{m.calls(input,options);return {...m.query,data:typeof m.query.data==='function'?m.query.data(input):m.query.data};}},send:{useMutation:()=>({mutateAsync:m.send})},delete:{useMutation:()=>({mutateAsync:m.remove})},acknowledgeManualReview:{useMutation:()=>({mutateAsync:m.review})}},useUtils:()=>({campaigns:{performanceSnapshot:{invalidate:m.invalidate}}})}}));
vi.mock('react-i18next',()=>({useTranslation:()=>({i18n:{language:m.language},t:(key:string,vars:any={})=>{let value=(m.language==='ar'?ar:en)[key.split('.').at(-1) as keyof typeof en]??key;for(const [k,v] of Object.entries(vars))value=value.replaceAll(`{{${k}}}`,String(v));return value;}})}));
vi.mock('@/components/merchant/WorkspaceState',()=>({WorkspaceState:({kind,onRetry}:any)=><div data-state={kind}>{kind}<button onClick={onRetry}>retry</button></div>,workspaceFailureKind:(error:any)=>error?.data?.code==='FORBIDDEN'?'forbidden':'error'}));
vi.mock('@/components/merchant/CampaignPerformance',()=>({CampaignPerformance:()=> <div data-performance>Performance section</div>}));
import Campaigns from '../client/src/pages/merchant/Campaigns';
import { campaignNavigation,campaignHref } from '../client/src/lib/campaign-navigation';
let container:HTMLDivElement,root:Root,memory:ReturnType<typeof memoryLocation>;
const row=(id:number,status='draft')=>({id,name:`Campaign ${id}`,status,createdAt:'2026-10-01T10:00:00.000Z',scheduledAt:null,recipients:3,accepted:1,queue:status==='draft'?null:{total:3,accepted:1,awaiting:1,suppressed:0,needsReview:1}});
const snapshot=(selection:any)=>({actorId:7,merchantId:20,canManage:true,selection,checkedAt:'2026-10-01T12:00:00.000Z',timezone:'Asia/Riyadh',summary:{total:621,draft:620,scheduled:0,sending:1,completed:0,failed:0,accepted:1,recipients:3,unconfirmed:2,acceptanceRate:33.3,acceptanceBasis:'stored_campaign_counters'},needsReview:1,pagination:{page:selection.page,pageSize:25,total:55,pages:3},rows:selection.page>3?[]:[row(1),row(2,'sending')]});
const render=()=>act(async()=>root.render(<Router hook={memory.hook} searchHook={memory.searchHook}><Campaigns/></Router>));
const button=(text:string)=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent?.trim()===text) as HTMLButtonElement;
const click=(element:Element)=>act(async()=>{element.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}));});
const navigate=(path:string)=>act(async()=>memory.navigate(path));
beforeEach(()=>{vi.clearAllMocks();m.language='en';m.actor=7;m.merchant=20;m.query={data:snapshot,isLoading:false,isFetching:false,error:null,refetch:m.refresh};m.send.mockResolvedValue({success:true});m.remove.mockResolvedValue({success:true});m.review.mockResolvedValue({acknowledged:1});memory=memoryLocation({path:'/merchant/campaigns',record:true});container=document.createElement('div');document.body.append(container);root=createRoot(container);Object.assign(globalThis,{React,IS_REACT_ACT_ENVIRONMENT:true});});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();vi.useRealTimers();vi.restoreAllMocks();});
describe('campaign list navigation and scope',()=>{
  it('keeps a real empty list actionable without manufacturing an error',async()=>{m.query.data=(selection:any)=>({...snapshot(selection),rows:[],needsReview:0,summary:{...snapshot(selection).summary,total:0,draft:0,sending:0,accepted:0,recipients:0,unconfirmed:0,acceptanceRate:0},pagination:{page:1,pageSize:25,total:0,pages:0}});await render();expect(container.textContent).toContain(en.empty);expect(container.querySelector('a[href="/merchant/campaigns/new"]')).toBeTruthy();expect(container.querySelector('[data-state]')).toBeNull();});
  it('retries a failed read without showing stale rows or an empty success',async()=>{m.query.error=Error('Failed');await render();expect(container.querySelector('[data-state=error]')).toBeTruthy();expect(container.textContent).not.toContain(en.empty);expect(container.querySelector('dl')).toBeNull();await click(button('retry'));expect(m.refresh).toHaveBeenCalledOnce();});
  it('shows full counts and processed progress rather than accepted-only progress',async()=>{await render();expect(container.textContent).toContain('621');expect(container.textContent).toContain('Processed 2 of 3');expect(container.querySelector('progress')?.value).toBe(2);expect(m.send).not.toHaveBeenCalled();});
  it('loads filters, review-only state and page from a link',async()=>{memory.navigate('/merchant/campaigns?q=Fixture&status=sending&review=1&page=2&lang=en');await render();expect(m.calls.mock.calls.at(-1)?.[0]).toEqual({search:'Fixture',status:'sending',needsReview:true,page:2});});
  it('restores the performance section and browser navigation',async()=>{memory.navigate('/merchant/campaigns?q=Fixture&tab=performance&lang=en');await render();expect(container.querySelector('[data-performance]')).toBeTruthy();await click(button(en.list));expect(memory.history?.at(-1)).toBe('/merchant/campaigns?q=Fixture&lang=en');await navigate('/merchant/campaigns?tab=performance');expect(container.querySelector('[data-performance]')).toBeTruthy();});
  it('resets only the page when a debounced search changes and cancels old timers on navigation',async()=>{vi.useFakeTimers();memory.navigate('/merchant/campaigns?page=2&status=sending&lang=en');await render();const input=container.querySelector('input:not([type=checkbox])')!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(input,'Updated');input.dispatchEvent(new Event('input',{bubbles:true}));});await act(async()=>vi.advanceTimersByTime(301));expect(memory.history?.at(-1)).toContain('q=Updated');expect(memory.history?.at(-1)).not.toContain('page=');await navigate('/merchant/campaigns?q=Before&page=2');await act(async()=>vi.advanceTimersByTime(350));expect((input as HTMLInputElement).value).toBe('Before');expect(memory.history?.at(-1)).toContain('page=2');});
  it('recovers an out-of-range page while keeping filters',async()=>{memory.navigate('/merchant/campaigns?q=Fixture&page=999');await render();expect(container.textContent).toContain(en.outOfRange);await click(button(en.first));expect(memory.history?.at(-1)).toBe('/merchant/campaigns?q=Fixture');});
  it('opens every campaign with pending review, including one still sending',async()=>{await render();await click(button(en.showReview));expect(m.calls.mock.calls.at(-1)?.[0]).toMatchObject({needsReview:true,status:'all',page:1});});
  it.each(['actor','merchant','selection','schema'])('rejects stale or malformed %s data',async mode=>{m.query.data=(selection:any)=>({...snapshot(selection),...(mode==='actor'?{actorId:99}:mode==='merchant'?{merchantId:99}:mode==='selection'?{selection:{...selection,page:9}}:{rows:[{...row(1),status:'unknown'}]})});await render();expect(container.querySelector('[data-state=error]')).toBeTruthy();expect(container.textContent).not.toContain('Campaign 1');});
  it('hides stale totals when reading fails',async()=>{m.query.error={data:{code:'FORBIDDEN'}};await render();expect(container.querySelector('[data-state=forbidden]')).toBeTruthy();expect(container.textContent).not.toContain('621');});
  it('keeps view-only navigation and removes management controls',async()=>{m.query.data=(selection:any)=>({...snapshot(selection),canManage:false});await render();expect(container.textContent).toContain(en.readOnly);expect(button(en.send)).toBeUndefined();expect(button(en.remove)).toBeUndefined();expect(container.querySelector('a[href="/merchant/campaigns/new"]')).toBeNull();expect(container.querySelector('a[href="/merchant/campaigns/2/report"]')).toBeTruthy();});
  it('renders Arabic labels without exposing translation keys',async()=>{m.language='ar';await render();expect(container.textContent).toContain(ar.title);expect(container.textContent).not.toContain('merchantUx.');expect(container.querySelector('[dir=rtl]')).toBeTruthy();});
});
describe('campaign confirmations and late responses',()=>{
  it('opens the actual detail review instead of sending unseen content from the list',async()=>{await render();const link=container.querySelector('a[href="/merchant/campaigns/1?review=send"]')!;expect(link.textContent).toContain(en.send);await click(link);expect(memory.history?.at(-1)).toBe('/merchant/campaigns/1?review=send');expect(m.send).not.toHaveBeenCalled();});
  it('cancels deletion without a mutation',async()=>{await render();await click(button(en.remove));await click(button(en.cancel));expect(m.remove).not.toHaveBeenCalled();});
  it('requires review confirmation without treating it as a resend',async()=>{await render();await click(button(en.review));expect(button(en.confirmReview).disabled).toBe(true);await click(document.querySelector('[role=dialog] input[type=checkbox]')!);await click(button(en.confirmReview));expect(m.review).toHaveBeenCalledWith({id:2});expect(m.send).not.toHaveBeenCalled();expect(container.textContent).toContain(en.reviewSuccess);});
  it('disables confirmation when the reviewed row changes',async()=>{await render();await click(button(en.remove));m.query.data=(selection:any)=>({...snapshot(selection),rows:[{...row(1),status:'scheduled'},row(2,'sending')]});await render();expect(button(en.confirmDelete).disabled).toBe(true);expect(document.body.textContent).toContain(en.changed);expect(m.send).not.toHaveBeenCalled();});
  it('sanitizes action errors and catches the rejected promise',async()=>{m.remove.mockRejectedValue(Error('PRIVATE SQL detail'));await render();await click(button(en.remove));await click(button(en.confirmDelete));expect(document.body.textContent).toContain(en.actionError);expect(document.body.textContent).not.toContain('PRIVATE');expect(m.refresh).toHaveBeenCalledOnce();});
  it('ignores a late mutation result after changing the selected view',async()=>{let finish!:(value:any)=>void;m.remove.mockReturnValue(new Promise(r=>finish=r));await render();await click(button(en.remove));await click(button(en.confirmDelete));await navigate('/merchant/campaigns?status=sending');await act(async()=>finish({success:true}));expect(container.textContent).not.toContain(en.deleteSuccess);expect(m.refresh).not.toHaveBeenCalled();});
  it('ignores a late result after switching account scope',async()=>{let finish!:(value:any)=>void;m.remove.mockReturnValue(new Promise(r=>finish=r));await render();await click(button(en.remove));await click(button(en.confirmDelete));m.actor=8;m.query.data=(selection:any)=>({...snapshot(selection),actorId:8});await render();await act(async()=>finish({success:true}));expect(container.textContent).not.toContain(en.deleteSuccess);expect(m.refresh).not.toHaveBeenCalled();});
});
describe('campaign URL parsing',()=>{
  it('rejects partial numeric pages and preserves unrelated parameters',()=>{expect(campaignNavigation('?page=2x&status=unknown&review=1').selection).toEqual({search:'',status:'all',page:1,needsReview:true});expect(campaignHref('/merchant/campaigns','lang=en&q=Keep',{status:'sending',page:null})).toBe('/merchant/campaigns?lang=en&q=Keep&status=sending');});
});
