import {afterAll,afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {getDb,getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {readCampaignPerformance,CampaignWorkspaceUnavailableError} from './campaign-workspace';
describe.skipIf(!process.env.DATABASE_URL)('campaign performance consistent MySQL snapshot',()=>{
 let owner:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof owner;
 const q=async(sql:string,args:any[]=[])=> (await (await getPool())!.execute<any>(sql,args))[0];
 const create=async(merchantId=owner.merchantId,status='completed',accepted=8,recipients=10)=>Number((await q("INSERT INTO campaigns (merchantId,name,message,status,sentCount,totalRecipients) VALUES (?,'Fixture','Fixture',?,?,?)",[merchantId,status,accepted,recipients])).insertId);
 const log=async(id:number,date:string,status='success')=>q("INSERT INTO campaignLogs (campaignId,customerPhone,status,sentAt) VALUES (?,'999000001',?,?)",[id,status,date]);
 const read=(days:7|30|90=7,now=new Date('2026-10-01T12:00:00.000Z'))=>readCampaignPerformance(owner.userId,owner.merchantId,{days},now);
 beforeEach(async()=>{owner=await createDisposableMerchant('campaign-performance');other=await createDisposableMerchant('campaign-performance-other');});
 afterEach(async()=>{vi.restoreAllMocks();await cleanupDisposableMerchants([owner.userId,other.userId]);});afterAll(closeDb);
 it('separates completed counters from all-campaign success logs and isolates the tenant',async()=>{const id=await create(),active=await create(owner.merchantId,'sending',3,10),foreign=await create(other.merchantId);await log(id,'2026-10-01 11:00:00');await log(active,'2026-10-01 11:00:00');await log(foreign,'2026-10-01 11:00:00');await log(id,'2026-10-01 11:00:00','failed');const data=await read();expect(data).toMatchObject({actorId:owner.userId,merchantId:owner.merchantId,days:7,timezone:'UTC',stats:{completed:1,accepted:8,recipients:10,unconfirmed:2,acceptanceRate:80,basis:'stored_campaign_counters'},timeline:{start:'2026-09-25',end:'2026-10-01',total:2,basis:'campaign_success_logs'}});expect(data.timeline.rows).toHaveLength(7);expect(data.timeline.rows.at(-1)?.acceptedByProvider).toBe(2);});
 it('includes the exact UTC start and cutoff and excludes older and future records',async()=>{const id=await create();for(const time of ['2026-09-24 23:59:59','2026-09-25 00:00:00','2026-10-01 12:00:00','2026-10-01 12:00:01','2026-10-02 00:00:00'])await log(id,time);expect((await read()).timeline.total).toBe(2);});
 it.each([7,30,90] as const)('fills every calendar day across a year boundary for %s days',async days=>{const data=await read(days,new Date('2026-01-02T00:00:00Z'));expect(data.timeline.rows).toHaveLength(days);expect(data.timeline.end).toBe('2026-01-02');expect(data.timeline.total).toBe(0);expect(new Set(data.timeline.rows.map(row=>row.date)).size).toBe(days);});
 it('does not truncate complete counters or timeline records at 500',async()=>{const id=await create();const rows=Array.from({length:621},()=>[id,'999000001','success','2026-10-01 10:00:00']);await q(`INSERT INTO campaignLogs (campaignId,customerPhone,status,sentAt) VALUES ${rows.map(()=>'(?,?,?,?)').join(',')}`,rows.flat());expect((await read()).timeline.total).toBe(621);});
 it('does not turn corrupt counter evidence into a performance percentage',async()=>{await create(owner.merchantId,'completed',15,10);await expect(read()).rejects.toBeInstanceOf(CampaignWorkspaceUnavailableError);});
 it('keeps counters and logs in one snapshot during a concurrent update',async()=>{const id=await create();await log(id,'2026-10-01 10:00:00');const db=(await getDb())!,native=db.transaction.bind(db);let changed=false;vi.spyOn(db,'transaction').mockImplementation(((run:any,options:any)=>native(async tx=>{const execute=tx.execute.bind(tx);vi.spyOn(tx,'execute').mockImplementation((async(...args:any[])=>{const result=await execute(...args as [any]);if(!changed&&Array.isArray(result[0])&&'completedAccepted' in (result[0][0]||{})){changed=true;await q('UPDATE campaigns SET sentCount=9 WHERE id=?',[id]);await log(id,'2026-10-01 11:00:00');}return result;})as any);return run(tx);},options))as any);const data=await read();expect(changed).toBe(true);expect(data.stats.accepted).toBe(8);expect(data.timeline.total).toBe(1);vi.restoreAllMocks();expect(await read()).toMatchObject({stats:{accepted:9},timeline:{total:2}});});
});
