// @vitest-environment jsdom
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {campaignCsvCell,campaignReportCsv,downloadCampaignReportCsv,type CampaignReportCsvLabels} from '../client/src/lib/campaign-report-csv';
import {campaignReportExportSchema} from '../shared/campaign-report';
const labels:CampaignReportCsvLabels={phone:'Phone',name:'Name',status:'Status',reason:'Reason',recordedAt:'Recorded at',acceptedAt:'Accepted at',attempts:'Attempts',quotaHeld:'Quota held',yes:'Yes',no:'No',statusLabel:value=>value,reasonLabel:value=>value};
const fixture=()=>({actorId:1,merchantId:2,canManage:true,selection:{id:7,view:'results',status:'all',search:'',page:1},checkedAt:'2026-10-01T12:00:00.000Z',timezone:'Asia/Riyadh',
 campaign:{id:7,name:'Fixture',message:'Visible',imageUrl:null,status:'completed',createdAt:'2026-10-01T00:00:00.000Z',scheduledAt:null,recipients:1,accepted:1,basis:'stored_campaign_counters'},summary:{results:{total:1,success:1,failed:0,pending:0,successRate:100,excludedLinks:0},recipients:{total:0,pending:0,processing:0,sent:0,failed:0,suppressed:0,manualReview:0}},pagination:{page:1,pageSize:10000,total:1,pages:1},rows:[{kind:'result',id:1,phone:'0012345',name:'Customer',status:'success',reason:'none',recordedAt:'2026-10-01T09:00:00.000Z'}]});
beforeEach(()=>{vi.useFakeTimers();});afterEach(()=>{vi.runAllTimers();vi.useRealTimers();vi.restoreAllMocks();vi.unstubAllGlobals();});
describe('safe complete campaign CSV',()=>{
 it.each(['=1+1','+SUM(1)','-1+2','@SUM(1)',' \t=1','\r\n=1','\uFEFF=1','\u200B@SUM(1)','\u0000=1'])('neutralizes spreadsheet formula prefix %j',input=>expect(campaignCsvCell(input).startsWith('"\'')).toBe(true));
 it('escapes quotes, commas and line breaks and preserves international text',()=>{expect(campaignCsvCell('أحمد "خاص",\nNew line')).toBe('"أحمد ""خاص"",\nNew line"');expect(campaignCsvCell('Normal')).toBe('"Normal"');expect(campaignCsvCell('0012345',true)).toBe('"\'0012345"');});
 it('uses BOM and CRLF records with UTC times and text phone numbers',()=>{const csv=campaignReportCsv(fixture(),labels);expect(csv.startsWith('\ufeff"Phone","Name"')).toBe(true);expect(csv).toContain('"Recorded at (UTC)"');expect(csv).toContain('"\'0012345","Customer","success","none","2026-10-01T09:00:00.000Z"');expect(csv.endsWith('\r\n')).toBe(true);});
 it('localizes headers and neutralizes malicious stored names without raw error text',()=>{const data=fixture();data.rows[0].name='=HYPERLINK("https://example.test")';const csv=campaignReportCsv(data,{...labels,name:'اسم العميل',statusLabel:()=> 'قبول مسجل',reasonLabel:()=> 'سبب آخر'});expect(csv).toContain('"اسم العميل"');expect(csv).toContain('"\'=HYPERLINK(""https://example.test"")"');expect(csv).toContain('قبول مسجل');});
 it.each(['partial','ordinary-page','wrong-total','duplicate','oversized-field'])('refuses %s data before creating a file',mode=>{const data=fixture();if(mode==='partial')data.rows=[];if(mode==='ordinary-page')data.pagination.pageSize=25;if(mode==='wrong-total')data.pagination.total=2;if(mode==='duplicate'){data.rows.push({...data.rows[0]});data.pagination.total=2;}if(mode==='oversized-field')data.rows[0].name='x'.repeat(256);expect(()=>campaignReportCsv(data,labels)).toThrow();});
 it('exports a real empty result as headers only',()=>{const data=fixture();data.rows=[];data.pagination={...data.pagination,total:0,pages:0};data.summary.results={...data.summary.results,total:0,success:0,successRate:0};expect(campaignReportCsv(data,labels).split('\r\n')).toHaveLength(2);});
 it('exports recipient attempts and held quota without turning the receipt date into an invented value',()=>{const data:any=fixture();data.selection.view='recipients';data.summary.recipients={...data.summary.recipients,total:1,manualReview:1};data.rows=[{kind:'recipient',id:3,phone:'966500000001',name:null,status:'manual_review',reason:'uncertain',recordedAt:'2026-10-01T10:00:00.000Z',attempts:3,quotaHeld:true,acceptedAt:null}];const csv=campaignReportCsv(data,labels);expect(csv).toContain('"Attempts","Quota held","Accepted at (UTC)"');expect(csv).toContain('"3","Yes",""\r\n');expect(csv).not.toContain('merchantId');});
 it('rejects a falsely empty export or rows outside the chosen status',()=>{const data=fixture();data.rows=[];data.pagination={...data.pagination,total:0,pages:0};expect(()=>campaignReportCsv(data,labels)).toThrow();const filtered=fixture();filtered.selection.status='failed';expect(()=>campaignReportCsv(filtered,labels)).toThrow();});
 it('cleans up the link and revokes the object URL after the browser starts the download',()=>{const create=vi.fn().mockReturnValue('blob:local-campaign'),revoke=vi.fn();vi.stubGlobal('URL',class extends URL{static createObjectURL=create;static revokeObjectURL=revoke;});const click=vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(function(this:HTMLAnchorElement){expect(this.isConnected).toBe(true);expect(this.download).toBe('campaign_7_results.csv');});downloadCampaignReportCsv(campaignReportExportSchema.parse(fixture()),labels);expect(click).toHaveBeenCalledOnce();expect(document.querySelector('a')).toBeNull();expect(revoke).not.toHaveBeenCalled();vi.advanceTimersByTime(1000);expect(revoke).toHaveBeenCalledWith('blob:local-campaign');});
 it('also revokes and removes the temporary link if initiating download fails',()=>{const revoke=vi.fn();vi.stubGlobal('URL',class extends URL{static createObjectURL=vi.fn().mockReturnValue('blob:failed-campaign');static revokeObjectURL=revoke;});vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{throw Error('Failed');});expect(()=>downloadCampaignReportCsv(campaignReportExportSchema.parse(fixture()),labels)).toThrow('Failed');expect(document.querySelector('a')).toBeNull();vi.advanceTimersByTime(1000);expect(revoke).toHaveBeenCalledWith('blob:failed-campaign');});
});
