// @vitest-environment jsdom
import React, { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { Router, Route, Switch } from 'wouter';
import { memoryLocation } from 'wouter/memory-location';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { campaignEditorWorkspaceAr as ar, campaignEditorWorkspaceEn as en } from '../client/src/locales/campaign-editor-workspace';
import { CAMPAIGN_OPT_OUT_NOTICE_AR } from '../shared/campaign-message';
const m = vi.hoisted(() => ({ actor: 7, merchant: 20, language: 'en', query: {} as any, preview: {} as any, read: vi.fn(), readAudience: vi.fn(), create: vi.fn(), update: vi.fn(), refresh: vi.fn(), refreshAudience: vi.fn(), invalidate: vi.fn() }));
vi.mock('@/lib/trpc', () => ({ trpc: {
  auth: { me: { useQuery: () => ({ data: { id: m.actor }, isFetching: false }) } }, merchants: { getCurrent: { useQuery: () => ({ data: { id: m.merchant }, isFetching: false }) } },
  campaigns: { editorWorkspace: { useQuery: (input: any, options: any) => { m.read(input, options); return m.query; } }, audiencePreview: { useQuery: (input: any, options: any) => { m.readAudience(input, options); return m.preview; } }, create: { useMutation: () => ({ mutateAsync: m.create }) }, update: { useMutation: () => ({ mutateAsync: m.update }) } },
  useUtils: () => ({ campaigns: { workspace: { invalidate: m.invalidate }, performanceSnapshot: { invalidate: m.invalidate }, detailsWorkspace: { invalidate: m.invalidate }, editorWorkspace: { invalidate: m.invalidate } } }),
} }));
vi.mock('react-i18next', () => ({ useTranslation: () => ({ i18n: { language: m.language }, t: (key: string, vars: any = {}) => { const copy = m.language === 'ar' ? ar : en; let value = copy[key.split('.').at(-1) as keyof typeof en] ?? key; for (const [name, text] of Object.entries(vars)) value = value.replaceAll(`{{${name}}}`, String(text)); return value; } }) }));
vi.mock('@/components/merchant/WorkspaceState', () => ({ WorkspaceState: ({ kind, onRetry }: any) => <div data-state={kind}>{kind}<button onClick={onRetry}>retry</button></div>, workspaceFailureKind: () => 'error' }));
import NewCampaign from '../client/src/pages/merchant/NewCampaign';
let container: HTMLDivElement, root: Root, memory: ReturnType<typeof memoryLocation>;
const campaign = () => ({ id: 1, name: 'Stored name', message: 'Stored message', imageUrl: null, status: 'draft', scheduledAt: null, definitionKey: 'a'.repeat(64), audience: { status: 'valid', filters: { lastActivityDays: 45, purchaseCountMin: 0, purchaseCountMax: 2 } } });
const snapshot = () => ({ actorId: 7, merchantId: 20, canManage: true, checkedAt: '2026-10-01T12:00:00Z', timezone: 'Asia/Riyadh', merchantStatus: 'active', campaign: null as any });
const preview = (filters = {}) => ({ actorId: 7, merchantId: 20, checkedAt: '2026-10-01T12:00:00Z', filters, count: 5, recipientCount: 2, invalidPhoneCount: 2, duplicateCount: 1, recipientLimit: 2000, exceedsLimit: false, basis: 'matched_conversations_before_consent' });
const render = () => act(async () => root.render(<Router hook={memory.hook} searchHook={memory.searchHook}><Switch><Route path="/merchant/campaigns/new"><NewCampaign /></Route><Route path="/merchant/campaigns/:id/edit"><NewCampaign /></Route><Route>Destination</Route></Switch></Router>));
const input = (id: string) => container.querySelector(`#ce-${id}`) as HTMLInputElement;
const button = (name: string) => Array.from(document.querySelectorAll('button')).find(el => el.textContent?.trim() === name) as HTMLButtonElement;
const click = (el: Element) => act(async () => { el.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true })); });
const change = (key: string, value: string) => act(async () => { const el = input(key); const prototype = el instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype; Object.getOwnPropertyDescriptor(prototype, 'value')!.set!.call(el, value); el.dispatchEvent(new Event('input', { bubbles: true })); });
const submit = () => act(async () => { container.querySelector('form')!.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })); });
const fill = async () => { await change('name', 'New campaign'); await change('message', 'Hello customer'); };
const schedule = async (date = '2027-01-01T15:00:27') => { await click(container.querySelectorAll('input[type=radio]')[1]); await change('scheduledAt', date); };
const edit = () => { memory.navigate('/merchant/campaigns/1/edit'); m.query.data.campaign = campaign(); m.preview.data = preview(m.query.data.campaign.audience.filters); };
beforeEach(() => { vi.clearAllMocks(); vi.useFakeTimers({ toFake: ['Date'] }); vi.setSystemTime(new Date('2026-10-01T12:00:00Z')); m.actor = 7; m.merchant = 20; m.language = 'en'; m.query = { data: snapshot(), isFetching: false, isLoading: false, error: null, refetch: m.refresh }; m.preview = { data: preview(), isFetching: false, error: null, refetch: m.refreshAudience }; m.create.mockResolvedValue({ id: 9, merchantId: 20 }); m.update.mockResolvedValue({ success: true }); m.invalidate.mockResolvedValue(undefined); memory = memoryLocation({ path: '/merchant/campaigns/new', record: true }); container = document.createElement('div'); document.body.append(container); root = createRoot(container); Object.assign(globalThis, { React, IS_REACT_ACT_ENVIRONMENT: true }); });
afterEach(async () => { await act(async () => root.unmount()); container.remove(); vi.useRealTimers(); vi.restoreAllMocks(); });
describe('actual campaign editor interactions', () => {
  it('preserves the activity period when selecting purchase presets and clears it only with all customers', async () => { edit(); await render(); await click(button(en.repeat)); expect(input('audience').value).toBe('45'); expect(input('purchaseCountMin').value).toBe('1'); expect(input('purchaseCountMax').value).toBe('5'); await click(button(en.all)); expect(input('audience').value).toBe(''); expect(input('purchaseCountMin').value).toBe(''); });
  it('validates each required field inline and focuses the first error', async () => { await render(); await change('imageUrl', 'http://example.test/x'); await submit(); expect(input('name').getAttribute('aria-invalid')).toBe('true'); expect(input('message').getAttribute('aria-invalid')).toBe('true'); expect(input('imageUrl').getAttribute('aria-invalid')).toBe('true'); expect(document.activeElement).toBe(input('name')); expect(m.create).not.toHaveBeenCalled(); });
  it('requires review and a separate explicit confirmation to save a draft', async () => { await render(); await fill(); await submit(); expect(m.create).not.toHaveBeenCalled(); expect(document.activeElement?.textContent).toBe(en.reviewTitle); expect(document.querySelector('[role=dialog]')?.textContent).toContain(CAMPAIGN_OPT_OUT_NOTICE_AR); await click(button(en.confirmDraft)); expect(m.create).toHaveBeenCalledWith({ name: 'New campaign', message: 'Hello customer', targetAudience: '{}', imageUrl: undefined, scheduledAt: undefined }); expect(memory.history.at(-1)).toBe('/merchant/campaigns/9'); });
  it('cancels review without saving and restores focus', async () => { await render(); await fill(); button(en.review).focus(); await submit(); await click(button(en.cancel)); await act(async () => new Promise(resolve => setTimeout(resolve, 0))); expect(m.create).not.toHaveBeenCalled(); expect(document.activeElement).toBe(button(en.review)); });
  it('saves a schedule in store time with an explicit automatic sending warning', async () => { await render(); await fill(); await schedule(); await submit(); expect(document.querySelector('[role=dialog]')?.textContent).toContain(en.scheduleWarning); await click(button(en.confirmSchedule)); expect(m.create).toHaveBeenCalledWith(expect.objectContaining({ scheduledAt: new Date('2027-01-01T12:00:27Z') })); });
  it('rechecks elapsed time at final confirmation', async () => { await render(); await fill(); await schedule('2026-10-01T15:01'); await submit(); vi.setSystemTime(new Date('2026-10-01T12:02:00Z')); await click(button(en.confirmSchedule)); expect(m.create).not.toHaveBeenCalled(); expect(container.textContent).toContain(en.schedulePast); });
  it.each([['2027-03-14T02:30', 'scheduleGap'], ['2027-11-07T01:30', 'scheduleFold']] as const)('reports a DST problem for %s at the schedule field', async (value, key) => { m.query.data.timezone = 'America/New_York'; await render(); await fill(); await schedule(value); await submit(); expect(container.querySelector('#ce-schedule-error')?.textContent).toBe(en[key]); expect(m.create).not.toHaveBeenCalled(); });
  it('preserves custom saved audience values and sends the reviewed edit identity', async () => { edit(); await render(); expect(input('audience').value).toBe('45'); expect(input('purchaseCountMin').value).toBe('0'); expect(input('purchaseCountMax').value).toBe('2'); await submit(); await click(button(en.confirmDraft)); expect(m.update).toHaveBeenCalledWith({ id: 1, expectedDefinition: 'a'.repeat(64), name: 'Stored name', message: 'Stored message', imageUrl: null, scheduledAt: null, targetAudience: '{"lastActivityDays":45,"purchaseCountMin":0,"purchaseCountMax":2}' }); });
  it('removes a persisted image and schedule without sending', async () => { edit(); m.query.data.campaign.imageUrl = 'https://example.test/image.png'; m.query.data.campaign.scheduledAt = '2027-01-01T12:00:27Z'; m.query.data.campaign.status = 'scheduled'; await render(); expect(input('scheduledAt').value).toBe('2027-01-01T15:00:27.000'); await change('imageUrl', ''); await click(container.querySelectorAll('input[type=radio]')[0]); await submit(); await click(button(en.confirmDraft)); expect(m.update).toHaveBeenCalledWith(expect.objectContaining({ imageUrl: null, scheduledAt: null })); });
  it('requires explicit repair of invalid saved audience before saving', async () => { edit(); m.query.data.campaign.audience = { status: 'invalid' }; await render(); await submit(); expect(document.querySelector('[role=dialog]')).toBeNull(); expect(m.update).not.toHaveBeenCalled(); await click(button(en.resetAudience)); await submit(); await click(button(en.confirmDraft)); expect(m.update).toHaveBeenCalledWith(expect.objectContaining({ targetAudience: '{}' })); });
  it('keeps invalid numeric input visible and prevents silent broadening', async () => { await render(); await fill(); await change('audience', '1e2'); await submit(); expect(input('audience').value).toBe('1e2'); expect(container.textContent).toContain(en.audienceError); expect(document.querySelector('[role=dialog]')).toBeNull(); });
  it('validates caption length including the notice without truncating typed text', async () => { await render(); await fill(); await change('message', 'x'.repeat(1000)); await change('imageUrl', 'https://example.test/image.png'); await submit(); expect(input('message').value).toHaveLength(1000); expect(container.querySelector('#ce-message-error')?.textContent).toBe(en.captionError); expect(m.create).not.toHaveBeenCalled(); });
  it.each(['actor', 'merchant', 'filters', 'counts'])('rejects mismatched %s audience evidence for scheduling', async mode => { await render(); await fill(); await schedule(); m.preview.data = { ...preview(), ...(mode === 'actor' ? { actorId: 99 } : mode === 'merchant' ? { merchantId: 99 } : mode === 'filters' ? { filters: { purchaseCountMin: 2 } } : { count: 99 }) }; await render(); await submit(); expect(document.querySelector('[role=dialog]')).toBeNull(); expect(container.textContent).toContain(en.previewUnavailable); expect(m.create).not.toHaveBeenCalled(); });
  it.each(['empty', 'over', 'unavailable', 'refreshing'])('blocks activating a schedule for %s audience while permitting a draft', async mode => { if (mode === 'empty') m.preview.data = { ...preview(), count: 0, recipientCount: 0, invalidPhoneCount: 0, duplicateCount: 0 }; if (mode === 'over') m.preview.data = { ...preview(), count: 2001, recipientCount: 2001, invalidPhoneCount: 0, duplicateCount: 0, exceedsLimit: true }; if (mode === 'unavailable') m.preview.error = Error('PRIVATE'); if (mode === 'refreshing') m.preview.isFetching = true; await render(); await fill(); await schedule(); await submit(); expect(document.querySelector('[role=dialog]')).toBeNull(); await click(container.querySelectorAll('input[type=radio]')[0]); await submit(); expect(document.querySelector('[role=dialog]')).toBeTruthy(); });
  it('retains unsaved fields when a source refresh fails and disables saving', async () => { await render(); await fill(); m.query.error = Error('PRIVATE SQL'); await render(); expect(input('message').value).toBe('Hello customer'); expect(container.textContent).toContain(en.sourceUnavailable); expect(container.textContent).not.toContain('PRIVATE'); expect(button(en.review).disabled).toBe(true); });
  it('blocks stale edits and asks before replacing typed data with a fresh version', async () => { edit(); await render(); await change('message', 'Unsaved text'); m.query.data.campaign = { ...campaign(), name: 'Changed name', definitionKey: 'b'.repeat(64) }; await render(); expect(input('message').value).toBe('Unsaved text'); expect(button(en.review).disabled).toBe(true); await click(button(en.reload)); expect(input('message').value).toBe('Unsaved text'); await click(button(en.reloadConfirm)); expect(input('message').value).toBe('Stored message'); expect(input('name').value).toBe('Changed name'); });
  it('invalidates an open review when the source definition changes', async () => { edit(); await render(); await submit(); m.query.data.campaign = { ...campaign(), definitionKey: 'b'.repeat(64) }; await render(); expect(button(en.confirmDraft).disabled).toBe(true); expect(m.update).not.toHaveBeenCalled(); });
  it('does not display raw save failures or automatically retry an uncertain create', async () => { m.create.mockRejectedValue(Error('PRIVATE SQL')); await render(); await fill(); await submit(); await click(button(en.confirmDraft)); expect(document.body.textContent).toContain(en.saveFailed); expect(document.body.textContent).not.toContain('PRIVATE'); expect(button(en.confirmDraft).disabled).toBe(true); expect(m.create).toHaveBeenCalledOnce(); });
  it('rejects an unverified creation result instead of navigating', async () => { m.create.mockResolvedValue({ id: 9, merchantId: 99 }); await render(); await fill(); await submit(); await click(button(en.confirmDraft)); expect(document.body.textContent).toContain(en.saveFailed); expect(memory.history.at(-1)).toBe('/merchant/campaigns/new'); });
  it('handles save conflicts without discarding draft text', async () => { edit(); m.update.mockRejectedValue({ data: { code: 'CONFLICT' } }); await render(); await change('message', 'Retain me'); await submit(); await click(button(en.confirmDraft)); expect(input('message').value).toBe('Retain me'); expect(button(en.confirmDraft).disabled).toBe(true); expect(m.refresh).toHaveBeenCalledOnce(); });
  it.each(['account', 'location'])('ignores late save results after changing %s', async mode => { let finish!: (value: any) => void; m.create.mockReturnValue(new Promise(resolve => finish = resolve)); await render(); await fill(); await submit(); await click(button(en.confirmDraft)); if (mode === 'account') { m.actor = 8; m.query.data.actorId = 8; await render(); } else await act(async () => memory.navigate('/merchant/campaigns/new?other=1')); await act(async () => finish({ id: 9, merchantId: 20 })); expect(memory.history.at(-1)).not.toBe('/merchant/campaigns/9'); expect(m.invalidate).not.toHaveBeenCalled(); });
  it('prevents duplicate submissions during save', async () => { let finish!: (value: any) => void; m.create.mockReturnValue(new Promise(resolve => finish = resolve)); await render(); await fill(); await submit(); const confirm = button(en.confirmDraft); await click(confirm); await click(confirm); expect(m.create).toHaveBeenCalledOnce(); await act(async () => finish({ id: 9, merchantId: 20 })); });
  it.each(['0', '01', '7x', '9007199254740992'])('rejects a noncanonical editor route %s', async id => { memory.navigate(`/merchant/campaigns/${id}/edit`); await render(); expect(container.querySelector('[data-state=missing]')).toBeTruthy(); expect(m.read).not.toHaveBeenCalled(); });
  it.each([0, -1, 1.5, Number.MAX_SAFE_INTEGER + 1])('does not navigate to an invalid created identity %s', async id => { m.create.mockResolvedValue({ id, merchantId: 20 }); await render(); await fill(); await submit(); await click(button(en.confirmDraft)); expect(document.body.textContent).toContain(en.saveFailed); expect(memory.history.at(-1)).toBe('/merchant/campaigns/new'); });
  it.each(['actor', 'merchant', 'campaign'])('rejects a mismatched initial %s snapshot', async mode => { m.query.data = { ...snapshot(), ...(mode === 'actor' ? { actorId: 99 } : mode === 'merchant' ? { merchantId: 99 } : { campaign: campaign() }) }; await render(); expect(container.querySelector('[data-state=error]')).toBeTruthy(); expect(input('message')).toBeNull(); });
  it('does not render management fields for read-only users', async () => { m.query.data.canManage = false; await render(); expect(container.textContent).toContain(en.readOnly); expect(input('message')).toBeNull(); });
  it('does not edit a completed campaign', async () => { edit(); m.query.data.campaign.status = 'completed'; await render(); expect(container.textContent).toContain(en.locked); expect(input('message')).toBeNull(); expect(container.querySelector('a[href="/merchant/campaigns/1"]')).toBeTruthy(); });
  it('does not show stale image media or activate scheduling when it fails to load', async () => { await render(); await fill(); await change('imageUrl', 'https://example.test/image.png'); const image = container.querySelector('img')!; expect(image.getAttribute('referrerpolicy')).toBe('no-referrer'); await act(async () => image.dispatchEvent(new Event('error'))); expect(container.querySelector('img')).toBeNull(); await schedule(); await submit(); expect(document.querySelector('[role=dialog]')).toBeNull(); expect(container.textContent).toContain(en.imageFailed); });
  it('renders translated Arabic without exposing translation keys', async () => { m.language = 'ar'; await render(); expect(container.querySelector('[dir=rtl]')).toBeTruthy(); expect(container.textContent).toContain(ar.title); expect(container.textContent).not.toContain('merchantUx.'); });
});
