import {afterAll,afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {getPool,closeDb} from './db/connection';import {readDashboardSources} from './dashboard-sources';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
describe.skipIf(!process.env.DATABASE_URL)('dashboard sources snapshot (MySQL)',()=>{
 const users:number[]=[];let merchantId:number;
 const run=async(text:string,args:unknown[]=[]) => (await (await getPool())!.execute(text,args))[0] as any;
 const account=async()=>{const a=await createDisposableMerchant('home-sources');users.push(a.userId);return a.merchantId;};
 beforeEach(async()=>{merchantId=await account();});afterEach(async()=>{vi.restoreAllMocks();await cleanupDisposableMerchants(users);users.length=0;});afterAll(closeDb);
 it('returns real empty source groups and no recorded connection',async()=>{const v=await readDashboardSources(merchantId);expect(v).toMatchObject({merchantId,audience:{kind:'customers',count:0},integration:{source:'none',state:'not_connected',records:[]},groups:{documents:{total:0},products:{total:0}}});});
 it('reads Salla only for the selected store and never returns credentials',async()=>{const foreign=await account();await run("UPDATE merchants SET integration_source='salla' WHERE id=?",[merchantId]);for(const id of [merchantId,foreign])await run("INSERT INTO salla_connections (merchantId,storeUrl,accessToken,syncStatus,lastSyncAt) VALUES (?,'https://fixture.invalid','PRIVATE_ACCESS','error',?)",[id,id===merchantId?'2024-01-01 12:00:00':'2025-01-01 12:00:00']);const v=await readDashboardSources(merchantId);expect(v.integration).toEqual({source:'salla',state:'error',records:[{scope:'all',at:'2024-01-01T12:00:00.000Z'}]});expect(JSON.stringify(v)).not.toContain('PRIVATE_ACCESS');});
 it('keeps Zid sync scopes separate including missing dates',async()=>{await run("UPDATE merchants SET integration_source='zid' WHERE id=?",[merchantId]);await run("INSERT INTO zid_settings (merchant_id,is_active,last_product_sync,last_order_sync) VALUES (?,1,'2024-01-01 12:00:00','2024-02-01 12:00:00')",[merchantId]);const v=await readDashboardSources(merchantId);expect(v.integration.state).toBe('configured');expect(v.integration.records).toEqual([{scope:'products',at:'2024-01-01T12:00:00.000Z'},{scope:'orders',at:'2024-02-01T12:00:00.000Z'},{scope:'customers',at:null}]);});
 it('uses the Byaan audience definition without reading connection secrets',async()=>{await run("UPDATE merchants SET integration_source='byaan' WHERE id=?",[merchantId]);const v=await readDashboardSources(merchantId);expect(v.audience).toEqual({kind:'trainees',count:0});expect(v.integration.state).toBe('not_connected');});
 it('retains the source snapshot when metadata triggers a concurrent merchant change',async()=>{const pool=(await getPool())!,conn=await pool.getConnection(),original=conn.execute.bind(conn);let changed=false;vi.spyOn(pool,'getConnection').mockResolvedValue(conn);vi.spyOn(conn,'execute').mockImplementation((async(text:any,args:any)=>{if(String(text).includes('integration_source')&&!changed){changed=true;await pool.execute("UPDATE merchants SET integration_source='unknown-new-source' WHERE id=?",[merchantId]);}return original(text,args);}) as any);const v=await readDashboardSources(merchantId);expect(changed).toBe(true);expect(v.integration.source).toBe('none');vi.restoreAllMocks();expect((await readDashboardSources(merchantId)).integration.source).toBe('unknown');});
});
