// @vitest-environment jsdom
import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {beforeEach,afterEach,describe,expect,it,vi} from 'vitest';
import ar from '../client/src/locales/ar.json';import en from '../client/src/locales/en.json';import {DashboardSources} from '../client/src/components/merchant/DashboardSources';import {dashboardSourcesFixture} from './tests/fixtures/dashboard-sources';
let lng:'ar'|'en'='en';vi.mock('react-i18next',()=>({useTranslation:()=>({t:(key:string)=>key.split('.').reduce((v:any,k)=>v?.[k],{ar,en}[lng])??key,i18n:{language:lng}})}));
let root:Root,container:HTMLDivElement;const refresh=vi.fn();
beforeEach(()=>{lng='en';refresh.mockClear();vi.stubGlobal('React',React);vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);container=document.createElement('div');document.body.append(container);root=createRoot(container);});afterEach(async()=>{await act(async()=>root.unmount());container.remove();vi.unstubAllGlobals();});
const mount=async(props:Partial<React.ComponentProps<typeof DashboardSources>>={})=>{await act(async()=>root.render(React.createElement(DashboardSources,{merchantId:20,data:dashboardSourcesFixture(),failed:false,loading:false,onRefresh:refresh,...props})));};
describe('home stored sources',()=>{
 it.each(['ar','en'] as const)('renders file processing states, all legacy destinations and localized copy in %s',async lang=>{lng=lang;await mount();expect(container.textContent).not.toMatch(/dashboardSourcesUx|knowledgeGroupsUx|undefined/);expect(container.querySelectorAll('h3')).toHaveLength(7);expect(container.querySelector('a[href="/merchant/products"]')).toBeTruthy();expect(container.querySelectorAll('time')).toHaveLength(2);if(lng==='en'){expect(container.textContent).toContain('Extraction failed');expect(container.textContent).toContain('No integration record');expect(container.textContent).not.toMatch(/[\u0600-\u06ff]/);}});
 it.each([{failed:true},{loading:true},{merchantId:21},{data:undefined}])('hides stale counts for %j',async props=>{await mount(props);expect(container.querySelector('h3')).toBeNull();expect(container.querySelector('time')).toBeNull();});
 it('recovers after failure and does not turn missing time into today',async()=>{await mount({failed:true});await act(async()=>container.querySelector('button')!.click());expect(refresh).toHaveBeenCalledOnce();const d=dashboardSourcesFixture();d.integration={source:'zid',state:'configured',records:[{scope:'products',at:null},{scope:'orders',at:'2024-01-01T00:00:00Z'},{scope:'customers',at:null}]};await mount({data:d});expect(container.textContent).toContain('Latest product sync');expect(container.textContent).toContain('Latest order sync');expect(container.querySelector('time[datetime="2024-01-01T00:00:00Z"]')).toBeTruthy();expect(container.querySelectorAll('time')).toHaveLength(3);});
 it('rejects mismatched nested source ownership and inconsistent counts',async()=>{const d=dashboardSourcesFixture();d.groups.merchantId=21;await mount({data:d});expect(container.querySelector('[role=alert]')).toBeTruthy();d.groups.merchantId=20;d.groups.documents.total=99;await mount({data:d});expect(container.querySelector('h3')).toBeNull();});
});
