import {beforeEach,describe,expect,it,vi} from 'vitest';
import {dashboardSourcesFixture} from './tests/fixtures/dashboard-sources';
const mocks=vi.hoisted(()=>({snapshot:vi.fn(),execute:vi.fn(),access:vi.fn()}));
vi.mock('./knowledge/source-groups',()=>({withKnowledgeSourceGroupsSnapshot:mocks.snapshot}));
vi.mock('./accounts/merchant-access',()=>({resolveMerchantAccess:mocks.access}));
import {readDashboardSources} from './dashboard-sources';
import {dashboardRouter} from './routers-dashboard';
let source:string,records:any[],foreign=false,total:unknown;
beforeEach(()=>{vi.resetAllMocks();source='none';records=[];foreign=false;total=2;mocks.access.mockResolvedValue({merchantId:20,role:'owner',memberId:1});mocks.snapshot.mockImplementation(async(id,read)=>read(dashboardSourcesFixture(id).groups,{execute:mocks.execute}));mocks.execute.mockImplementation(async(text:string)=>[text.includes('integration_source')?[{id:foreign?21:20,integration_source:source}]:text.includes('COUNT(*)')?[{total}]:records,[]]);});
describe('dashboard source and synchronization metadata',()=>{
 it('extends the stored-source snapshot with scoped metadata without secrets or schema writes',async()=>{const result=await readDashboardSources(20);expect(result).toMatchObject({merchantId:20,audience:{kind:'customers',count:2},integration:{source:'none',state:'not_connected',records:[]}});expect(mocks.snapshot.mock.calls[0][0]).toBe(20);for(const [text,args]of mocks.execute.mock.calls){expect(args[0]).toBe(20);expect(text).not.toMatch(/SELECT \*|accessToken|secret|CREATE|ALTER|UPDATE|DELETE|INSERT/i);}});
 it.each(['byaan','salla'])('reads only %s synchronization metadata and preserves error status',async selected=>{source=selected;records=[{state:'error',synced:new Date('2024-01-01T12:00:00Z'),enabled:1}];const result=await readDashboardSources(20);expect(result.integration).toEqual({source:selected,state:'error',records:[{scope:'all',at:'2024-01-01T12:00:00.000Z'}]});expect(result.audience.kind).toBe(selected==='byaan'?'trainees':'customers');if(selected==='byaan')expect(mocks.execute.mock.calls[1][0]).toContain("status='active'");});
 it('keeps Zid product, order and customer timestamps separate',async()=>{source='zid';records=[{enabled:1,last_product_sync:new Date('2024-01-01'),last_order_sync:null,last_customer_sync:'unknown'}];const v=await readDashboardSources(20);expect(v.integration.state).toBe('configured');expect(v.integration.records).toEqual([{scope:'products',at:'2024-01-01T00:00:00.000Z'},{scope:'orders',at:null},{scope:'customers',at:null}]);});
 it.each(['woocommerce','shopify','calendly'])('scopes platform metadata by both merchant and %s',async selected=>{source=selected;records=[{enabled:0,synced:null}];const v=await readDashboardSources(20);expect(v.integration.state).toBe('paused');expect(mocks.execute.mock.calls[2][1]).toEqual([20,selected]);});
 it('does not query a dynamically supplied table or invent a connection for unknown providers',async()=>{source="evil' UNION SELECT secret";const v=await readDashboardSources(20);expect(v.integration).toEqual({source:'unknown',state:'unavailable',records:[]});expect(mocks.execute).toHaveBeenCalledTimes(2);});
 it('distinguishes a missing connection and inactive records',async()=>{source='byaan';expect((await readDashboardSources(20)).integration.state).toBe('not_connected');records=[{state:'active',enabled:0,synced:null}];expect((await readDashboardSources(20)).integration.state).toBe('paused');});
 it.each(['foreign','badCount','duplicates','readFailure'])('rejects %s instead of returning zero/partial success',async kind=>{if(kind==='foreign')foreign=true;if(kind==='badCount')total=-1;if(kind==='duplicates'){source='salla';records=[{},{}];}if(kind==='readFailure')mocks.execute.mockRejectedValueOnce(Error('private SQL'));await expect(readDashboardSources(20)).rejects.toThrow();});
 it('checks API membership and sanitizes errors',async()=>{const caller=dashboardRouter.createCaller({user:{id:7,role:'merchant'},req:{headers:{}},res:{}} as any);mocks.execute.mockRejectedValueOnce(Error('private SQL'));await expect(caller.sources()).rejects.toMatchObject({code:'INTERNAL_SERVER_ERROR',message:'Source summary unavailable'});mocks.access.mockResolvedValueOnce(null);await expect(caller.sources()).rejects.toMatchObject({code:'FORBIDDEN'});});
});
