import { createHash } from 'node:crypto';
import { discountPageSize, discountWorkspaceInput, discountWorkspaceSchema, type DiscountSelection, type DiscountWorkspaceRow } from '../shared/discount-workspace';

/** Pure projection of a single authorized complete storage snapshot. */
export function discountRow(raw: any, now: Date): DiscountWorkspaceRow {
  const issues: DiscountWorkspaceRow['issues'] = [];
  const number = (value: unknown, field: DiscountWorkspaceRow['issues'][number], nullable = false, positive = false) => {
    if (value == null && nullable) return null;
    if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < (positive ? 1 : 0)) { issues.push(field); return null; }
    return value;
  };
  const flag = (value: unknown, field: 'activation' | 'origin') => { if (value !== 0 && value !== 1) { issues.push(field); return null; } return value === 1; };
  const stamp = (value: any, field: 'expiry' | 'created' | 'updated', nullable = false) => {
    if (value == null && nullable) return null;
    const text = value instanceof Date ? value.toISOString() : String(value ?? '').replace(' ', 'T');
    if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d{3})?Z?$/.test(text)) { issues.push(field); return null; }
    const date = new Date(text.endsWith('Z') ? text : text + 'Z');
    if (!Number.isFinite(date.getTime()) || date.toISOString().slice(0, 19) !== text.slice(0, 19)) { issues.push(field); return null; }
    return date.toISOString();
  };
  const code = typeof raw.code === 'string' ? raw.code : '';
  if (!code.trim() || code.length > 50 || /[\u0000-\u001f\u007f]/.test(code)) issues.push('code');
  const type = raw.type === 'percentage' || raw.type === 'fixed' ? raw.type : null; if (!type) issues.push('type');
  let value = number(raw.value, 'value', false, true); if (type === 'percentage' && value !== null && value > 100) { issues.push('value'); value = null; }
  const minOrderAmount = number(raw.minOrderAmount, 'minimum', true), maxUses = number(raw.maxUses, 'limit', true, true), usedCount = number(raw.usedCount, 'usage');
  const isActive = flag(raw.isActive, 'activation'), isAutoGenerated = flag(raw.isAutoGenerated, 'origin');
  const expiresAt = stamp(raw.expiresAt, 'expiry', true), createdAt = stamp(raw.createdAt, 'created'), updatedAt = stamp(raw.updatedAt, 'updated');
  const state = issues.length ? 'invalid' : !isActive ? 'inactive' : expiresAt && new Date(expiresAt).getTime() <= now.getTime() ? 'expired' : maxUses !== null && usedCount! >= maxUses ? 'exhausted' : 'available';
  return { id: raw.id, code, type, value, minOrderAmount, maxUses, usedCount, isActive, isAutoGenerated,
    customerPhone: raw.customerPhone == null ? null : String(raw.customerPhone), expiresAt, createdAt, updatedAt, state, issues,
    revision: createHash('sha256').update(JSON.stringify([raw.id, raw.merchantId, raw.code, raw.type, raw.value, raw.minOrderAmount, raw.maxUses, raw.usedCount, raw.isActive, raw.isAutoGenerated, raw.customerPhone, raw.expiresAt, raw.createdAt, raw.updatedAt])).digest('hex') };
}
export function projectDiscountWorkspace(actorId: number, merchantId: number, canManage: boolean, input: DiscountSelection, source: any[], now = new Date()) {
  const selection = discountWorkspaceInput.parse(input);
  if (source.some(row => row.merchantId !== merchantId)) throw Error('Invalid discount source scope');
  const rows = source.map(row => discountRow(row, now));
  const counts = { available: 0, inactive: 0, expired: 0, exhausted: 0, invalid: 0 }, usage = { recorded: 0, invalidRows: 0 };
  for (const row of rows) { counts[row.state]++; if (row.usedCount === null) usage.invalidRows++; else usage.recorded += row.usedCount; }
  const query = selection.query.toLocaleLowerCase('en');
  const matched = rows.filter(row => (selection.status === 'all' || row.state === selection.status)
    && (selection.origin === 'all' || row.isAutoGenerated === (selection.origin === 'automatic'))
    && (!query || row.code.toLocaleLowerCase('en').includes(query) || String(row.id) === query));
  return discountWorkspaceSchema.parse({ actorId, merchantId, checkedAt: now.toISOString(), canManage, selection, pageSize: discountPageSize,
    total: rows.length, matched: matched.length, pages: Math.ceil(matched.length / discountPageSize), counts, usage,
    rows: matched.slice((selection.page - 1) * discountPageSize, selection.page * discountPageSize) });
}
