import type { PoolConnection } from 'mysql2/promise';
import type { DiscountCode } from '../drizzle/schema';
import { discountCreateInput, discountUpdateInput, discountRecordId, type DiscountCreateInput, type DiscountUpdateInput } from '../shared/discount-dashboard';
import { ALL_ROLES, hasPermission, type MerchantRole } from './_core/permissions';
import { getPool } from './db/connection';

export class DiscountDashboardError extends Error {
  constructor(readonly reason: 'unavailable' | 'forbidden' | 'missing' | 'duplicate') { super(`discounts:${reason}`); }
}
async function rows(tx: PoolConnection, sql: string, args: any[]): Promise<any[]> {
  const [data] = await tx.execute(sql, args);
  if (!Array.isArray(data)) throw new DiscountDashboardError('unavailable');
  return data;
}
async function authority(tx: PoolConnection, actorId: number, merchantId: number, write: boolean) {
  const merchants = await rows(tx, 'SELECT userId,status FROM merchants WHERE id=? ' + (write ? 'FOR UPDATE' : 'FOR SHARE'), [merchantId]);
  const users = await rows(tx, 'SELECT account_status FROM users WHERE id=? FOR SHARE', [actorId]);
  const members = await rows(tx, 'SELECT role,is_active FROM merchant_members WHERE merchant_id=? AND user_id=? FOR SHARE', [merchantId, actorId]);
  const role = members.length === 1 && members[0].is_active === 1 ? members[0].role
    : members.length === 0 && merchants[0]?.userId === actorId ? 'owner' : null;
  if (users.length !== 1 || users[0].account_status !== 'active' || merchants.length !== 1 || merchants[0].status === 'suspended'
    || !ALL_ROLES.includes(role) || write && !hasPermission(role as MerchantRole, 'campaigns.manage')) throw new DiscountDashboardError('forbidden');
}
async function transaction<T>(actorId: number, merchantId: number, write: boolean, operation: (tx: PoolConnection) => Promise<T>): Promise<T> {
  discountRecordId.parse(actorId); discountRecordId.parse(merchantId);
  let tx: PoolConnection | undefined, committing = false, reusable = true;
  try {
    const pool = await getPool(); if (!pool) throw new DiscountDashboardError('unavailable');
    tx = await pool.getConnection(); await tx.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ'); await tx.beginTransaction();
    await authority(tx, actorId, merchantId, write);
    const result = await operation(tx); committing = true; await tx.commit(); return result;
  } catch (error) {
    if (committing) reusable = false;
    else if (tx) try { await tx.rollback(); } catch { reusable = false; }
    if (error instanceof DiscountDashboardError) throw error;
    if (!committing && (error as any)?.code === 'ER_DUP_ENTRY') throw new DiscountDashboardError('duplicate');
    throw new DiscountDashboardError('unavailable');
  } finally { if (tx) { if (reusable) tx.release(); else tx.destroy(); } }
}
const projection = 'id,merchantId,code,type,value,minOrderAmount,maxUses,usedCount,expiresAt,isActive,is_auto_generated AS isAutoGenerated,customer_phone AS customerPhone,createdAt,updatedAt';
function record(row: any): DiscountCode {
  const stamp = (value: any): string | null => value == null ? null : value instanceof Date ? value.toISOString().slice(0, 19).replace('T', ' ') : String(value);
  return { ...row, expiresAt: stamp(row.expiresAt), createdAt: stamp(row.createdAt)!, updatedAt: stamp(row.updatedAt)! };
}
async function target(tx: PoolConnection, merchantId: number, id: number, lock = false) {
  const found = await rows(tx, `SELECT ${projection} FROM discount_codes WHERE merchantId=? AND id=?${lock ? ' FOR UPDATE' : ''}`, [merchantId, id]);
  if (found.length !== 1) throw new DiscountDashboardError('missing');
  return record(found[0]);
}
export function listDashboardDiscounts(actorId: number, merchantId: number) {
  return transaction(actorId, merchantId, false, async tx => (await rows(tx, `SELECT ${projection} FROM discount_codes WHERE merchantId=? ORDER BY createdAt DESC,id DESC`, [merchantId])).map(record));
}
export function getDashboardDiscount(actorId: number, merchantId: number, id: number) {
  discountRecordId.parse(id); return transaction(actorId, merchantId, false, tx => target(tx, merchantId, id));
}
export function createDashboardDiscount(actorId: number, merchantId: number, input: DiscountCreateInput) {
  const data = discountCreateInput.parse(input);
  return transaction(actorId, merchantId, true, async tx => {
    const [saved] = await tx.execute<any>('INSERT INTO discount_codes (merchantId,code,type,value,minOrderAmount,maxUses,usedCount,isActive,expiresAt) VALUES (?,?,?,?,?,?,0,1,?)',
      [merchantId, data.code.toUpperCase(), data.type, data.value, data.minOrderAmount ?? null, data.maxUses ?? null, data.expiresAt ? data.expiresAt + ' 00:00:00' : null]);
    const id = Number(saved.insertId);
    if (saved.affectedRows !== 1 || !Number.isSafeInteger(id) || id <= 0) throw new DiscountDashboardError('unavailable');
    return target(tx, merchantId, id);
  });
}
export function updateDashboardDiscount(actorId: number, merchantId: number, input: DiscountUpdateInput) {
  const data = discountUpdateInput.parse(input);
  return transaction(actorId, merchantId, true, async tx => {
    await target(tx, merchantId, data.id, true);
    const fields: string[] = [], values: any[] = [];
    if (data.isActive !== undefined) { fields.push('isActive=?'); values.push(data.isActive ? 1 : 0); }
    if (data.maxUses !== undefined) { fields.push('maxUses=?'); values.push(data.maxUses); }
    if (data.expiresAt !== undefined) { fields.push('expiresAt=?'); values.push(data.expiresAt + ' 00:00:00'); }
    await tx.execute(`UPDATE discount_codes SET ${fields.join(',')},updatedAt=UTC_TIMESTAMP() WHERE merchantId=? AND id=?`, [...values, merchantId, data.id]);
    return target(tx, merchantId, data.id);
  });
}
export function deleteDashboardDiscount(actorId: number, merchantId: number, id: number) {
  discountRecordId.parse(id);
  return transaction(actorId, merchantId, true, async tx => {
    await target(tx, merchantId, id, true);
    const [result] = await tx.execute<any>('DELETE FROM discount_codes WHERE merchantId=? AND id=?', [merchantId, id]);
    if (result.affectedRows !== 1) throw new DiscountDashboardError('unavailable');
  });
}
