import { expect, it } from 'vitest';
import { discountWorkspaceInput } from '../shared/discount-workspace';
import { projectDiscountWorkspace } from './discount-workspace-source';
const now = new Date('2026-10-03T12:00:00Z');
const row = (id = 1, patch: any = {}) => ({ id, merchantId: 20, code: 'LOCAL' + id, type: 'percentage', value: 10, minOrderAmount: null, maxUses: null, usedCount: 0, isActive: 1, isAutoGenerated: 0, customerPhone: null, expiresAt: null, createdAt: '2026-10-02 00:00:00', updatedAt: '2026-10-02 00:00:00', ...patch });
const read = (source: any[], patch = {}) => projectDiscountWorkspace(7, 20, true, discountWorkspaceInput.parse(patch), source, now);
it('counts the complete snapshot while paginating and searching beyond the first page', () => {
  const source = Array.from({ length: 61 }, (_, i) => row(i + 1));
  const first = read(source), last = read(source, { page: 3 }), found = read(source, { query: 'local61' });
  expect(first).toMatchObject({ total: 61, matched: 61, pages: 3, pageSize: 25, counts: { available: 61 } }); expect(first.rows).toHaveLength(25);
  expect(last.rows).toHaveLength(11); expect(last.rows[0].id).toBe(51); expect(found.rows.map(row => row.id)).toEqual([61]); expect(found.total).toBe(61);
});
it.each([
  [{}, 'available'], [{ isActive: 0, expiresAt: '2020-01-01 00:00:00' }, 'inactive'],
  [{ expiresAt: '2026-10-03 12:00:00' }, 'expired'], [{ expiresAt: '2026-10-03 12:00:01' }, 'available'],
  [{ maxUses: 2, usedCount: 2 }, 'exhausted'], [{ maxUses: 2, usedCount: 3 }, 'exhausted'],
  [{ value: 0 }, 'invalid'], [{ value: 101 }, 'invalid'], [{ type: 'fixed', value: 101 }, 'available'],
  [{ type: 'free' }, 'invalid'], [{ usedCount: -1 }, 'invalid'], [{ maxUses: 0 }, 'invalid'],
  [{ isActive: 2 }, 'invalid'], [{ isAutoGenerated: 9 }, 'invalid'], [{ minOrderAmount: -1 }, 'invalid'],
  [{ expiresAt: '2026-02-30 00:00:00' }, 'invalid'], [{ createdAt: '0000-00-00 00:00:00' }, 'invalid'],
])('classifies %j as %s without converting invalid data into availability', (patch, state) => { expect(read([row(1, patch)]).rows[0].state).toBe(state); });
it('separates state counts, matched records and recorded usage with excluded corrupt counters', () => {
  const source = [row(1, { usedCount: 2 }), row(2, { isActive: 0, usedCount: 3 }), row(3, { expiresAt: '2020-01-01 00:00:00' }), row(4, { maxUses: 1, usedCount: 1 }), row(5, { usedCount: -1 })];
  expect(read(source, { status: 'inactive' })).toMatchObject({ total: 5, matched: 1, counts: { available: 1, inactive: 1, expired: 1, exhausted: 1, invalid: 1 }, usage: { recorded: 6, invalidRows: 1 } });
});
it('preserves customer-bound automatic coupons and filters only known origin', () => {
  const source = [row(1), row(2, { isAutoGenerated: 1, customerPhone: '+966500000002' }), row(3, { isAutoGenerated: 3 })];
  expect(read(source, { origin: 'manual' }).rows.map(row => row.id)).toEqual([1]);
  expect(read(source, { origin: 'automatic' }).rows[0]).toMatchObject({ id: 2, customerPhone: '+966500000002', isAutoGenerated: true });
});
it('does not silently clamp a stale page to another page', () => { const r = read([row()], { page: 3 }); expect(r.selection.page).toBe(3); expect(r.pages).toBe(1); expect(r.rows).toEqual([]); });
it('keeps full text as inert data including HTML-like coupon codes', () => { expect(read([row(1, { code: '<b>SAFE</b>' })]).rows[0].code).toBe('<b>SAFE</b>'); });
it('rejects foreign scope, unsafe aggregates and malformed input rather than returning a partial snapshot', () => {
  expect(() => read([row(1, { merchantId: 21 })])).toThrow('scope');
  expect(() => read([row(1, { usedCount: Number.MAX_SAFE_INTEGER }), row(2, { usedCount: 1 })])).toThrow();
  for (const input of [{ page: 0 }, { page: 1.5 }, { query: 'x'.repeat(81) }, { merchantId: 99 }, { status: 'enabled' }]) expect(discountWorkspaceInput.safeParse(input).success).toBe(false);
});
it('changes the revision on usage, fields and scope and keeps repeated reads stable', () => {
  const initial = read([row()]).rows[0].revision; expect(read([row()]).rows[0].revision).toBe(initial);
  for (const patch of [{ usedCount: 1 }, { isActive: 0 }, { maxUses: 1 }, { customerPhone: 'sample-only' }, { value: 11 }]) expect(read([row(1, patch)]).rows[0].revision).not.toBe(initial);
});
