import {it,expect} from 'vitest';
import {occasionNavigation,scopedOccasionWorkspace,scopedOccasionResult} from '../client/src/lib/occasion-workspace';
import {projectOccasionWorkspace} from './occasion-workspace-source';
import {occasionWorkspaceInput} from '../shared/occasion-workspace';
import {occasionWorkspaceEn,occasionWorkspaceAr} from '../client/src/locales/occasion-workspace';
it('normalizes invalid URL state, year and page without discarding bounded search',()=>{expect(occasionNavigation('?state=forged&year=12&page=1e5&q=%20hello%20')).toEqual({state:'all',year:null,page:1,query:'hello'});expect(occasionNavigation('?state=disabled&year=2027&page=2')).toEqual({state:'disabled',year:2027,page:2,query:''});expect(occasionNavigation('?q='+('x'.repeat(150))).query).toHaveLength(100);});
it('checks selected actor/tenant and exact list selection',()=>{const selection=occasionWorkspaceInput.parse({}),raw=projectOccasionWorkspace(7,20,true,selection,[],[],[]);expect(scopedOccasionWorkspace(raw,7,20,selection)).not.toBeNull();expect(scopedOccasionWorkspace(raw,8,20,selection)).toBeNull();expect(scopedOccasionWorkspace(raw,7,21,selection)).toBeNull();expect(scopedOccasionWorkspace(raw,7,20,{...selection,page:2})).toBeNull();expect(scopedOccasionWorkspace({...raw,deliveryEvidence:'sales'},7,20,selection)).toBeNull();});
it('does not treat wrong effect, flag or immediately-sent result as a saved decision',()=>{const target={action:'toggle' as const,id:9,enabled:true},result={actorId:7,merchantId:20,id:9,enabled:true,effect:'allow_automatic_admission',sentImmediately:false};expect(scopedOccasionResult(result,7,20,target)).not.toBeNull();for(const patch of [{id:10},{enabled:false},{effect:'save_disabled'},{sentImmediately:true},{merchantId:21}])expect(scopedOccasionResult({...result,...patch},7,20,target)).toBeNull();});
it('keeps Arabic and English keys aligned and nonempty',()=>{expect(Object.keys(occasionWorkspaceAr).sort()).toEqual(Object.keys(occasionWorkspaceEn).sort());expect(Object.values(occasionWorkspaceAr).every(value=>value.trim())).toBe(true);expect(Object.values(occasionWorkspaceEn).every(value=>value.trim())).toBe(true);});
