import {beforeEach,it,expect,vi} from 'vitest';
import {buildOccasionAuthorization,occasionAuthorizationDigest,occasionCampaignDigest,occasionDiscountDigest} from './occasion-authorization';
import {lockOccasionWorkerAuthority,bindOccasionPreparedEnvelope,OccasionAuthorizationDenied} from './occasion-worker-authority';
import {generateOccasionMessage} from '../shared/occasion-calendar';
const at=new Date('2027-01-01T09:00:00Z'),execute=vi.fn();
let merchant:any,oc:any,campaign:any,discount:any,grants:any[],users:any[],members:any[],clock:Date;
beforeEach(()=>{
 execute.mockReset();merchant={id:7,userId:1,status:'active',businessName:'Local shop'};oc={id:9,merchantId:7,campaignId:null,occasionType:'new_year',year:2027,enabled:1,discountPercentage:15,status:'pending',discountCode:null,messageTemplate:null,recipientCount:0,sentAt:null};campaign=null;
 const terms={effect:'allow_automatic_admission',occasionType:'new_year',year:2027,discountPercent:15,discountMaxUses:2000,discountMinOrder:0,discountExpiry:'occasion_end',audience:'eligible_conversations',audienceLimit:2000,timezone:'Asia/Riyadh',calendar:'gregory_and_islamic_umalqura',sendsImmediately:false,deliveryGuaranteed:false,salesVerified:false,messagePreview:generateOccasionMessage('رأس السنة الميلادية',null,'[CODE]',15,'Local shop'),messageSource:'generated',savedTemplateUsed:false};
 const contract=buildOccasionAuthorization({actorId:1,merchantId:7,reviewRevision:'a'.repeat(64),eligible:true,target:{action:'toggle',id:9,enabled:true},row:{id:9,occasionType:'new_year',year:2027},terms} as any,'Local shop',null,null,at);
 grants=[{id:90,actor_id:1,merchant_id:7,occasion_id:9,active:1,revoked_at:null,review_revision:contract.reviewRevision,contract_digest:occasionAuthorizationDigest(contract),reviewed_contract:contract,created_at:'2026-10-03 10:00:00',prepared_campaign_id:null,prepared_campaign_digest:null,prepared_discount_id:null,prepared_discount_digest:null}];
 users=[{id:1,account_status:'active'}];members=[];clock=at;
 discount={id:41,merchantId:7,code:'LOCAL',type:'percentage',value:15,minOrderAmount:0,maxUses:2000,usedCount:0,isActive:1,expiresAt:'2027-01-01 20:59:59',customer_phone:null};
 execute.mockImplementation(async(sql:string)=>{
  if(sql.includes('FROM occasion_authorizations'))return [grants];if(sql.includes('FROM users'))return [users];if(sql.includes('FROM merchant_members'))return [members];if(sql.includes('FROM discount_codes'))return [[discount]];if(sql.includes('FROM campaigns'))return [[campaign]];return [{affectedRows:1}];
 });
});
const run=(phase:'prepare'|'admission'|'dispatch'='prepare')=>lockOccasionWorkerAuthority({execute} as any,{merchant,occasion:oc,campaign,now:()=>clock,phase});
const prepared=()=>{campaign={id:77,merchantId:7,name:'Occasion',message:generateOccasionMessage('رأس السنة الميلادية',null,'LOCAL',15,'Local shop'),imageUrl:null,targetAudience:'{}',scheduledAt:null,status:'draft'};oc.campaignId=77;oc.discountCode='LOCAL';Object.assign(grants[0],{prepared_campaign_id:77,prepared_campaign_digest:occasionCampaignDigest(campaign),prepared_discount_id:41,prepared_discount_digest:occasionDiscountDigest(discount)});};
it('authorizes the reviewed active owner under locks without creating any side effect',async()=>{expect((await run()).contract.actorId).toBe(1);expect(execute.mock.calls.every(([sql])=>sql.startsWith('SELECT'))).toBe(true);expect(execute.mock.calls.map(([sql])=>sql)).toEqual([expect.stringContaining('FOR UPDATE'),expect.stringContaining('FOR SHARE'),expect.stringContaining('FOR SHARE')]);});
it('allows a current manager member when the approver differs from the owner',async()=>{merchant.userId=2;users.push({id:2,account_status:'active'});members=[{role:'manager',is_active:1}];expect((await run()).contract.actorId).toBe(1);});
it.each(['missing-grant','revoked','forged-tenant','viewer','revoked-owner','removed-member','inactive-actor','missing-actor','inactive-owner','merchant','name','future-grant','expired','changed-value','template','old-count','old-send'])('denies %s before any effect',async kind=>{
 if(kind==='missing-grant')grants=[];if(kind==='revoked')grants[0].active=null;if(kind==='forged-tenant')grants[0].merchant_id=8;if(kind==='viewer')members=[{role:'viewer',is_active:1}];if(kind==='revoked-owner')members=[{role:'owner',is_active:0}];if(kind==='removed-member'){merchant.userId=2;users.push({id:2,account_status:'active'});}
 if(kind==='inactive-actor')users[0].account_status='deletion_pending';if(kind==='missing-actor')users=[];if(kind==='inactive-owner'){merchant.userId=2;users.push({id:2,account_status:'deletion_pending'});members=[{role:'manager',is_active:1}];}
 if(kind==='merchant')merchant.status='suspended';if(kind==='name')merchant.businessName='Changed';if(kind==='future-grant')grants[0].created_at='2027-01-02 00:00:00';if(kind==='expired')clock=new Date('2027-01-02T09:00:00Z');if(kind==='changed-value')oc.discountPercentage=20;if(kind==='template')oc.messageTemplate='Edited';if(kind==='old-count')oc.recipientCount=1;if(kind==='old-send')oc.sentAt='2027-01-01 09:00:00';
 await expect(run()).rejects.toBeInstanceOf(OccasionAuthorizationDenied);expect(execute.mock.calls.every(([sql])=>sql.startsWith('SELECT'))).toBe(true);
});
it('rechecks the current clock after authority reads waited',async()=>{const original=execute.getMockImplementation()!;execute.mockImplementation(async(sql:string,...args:any[])=>{const result=await original(sql,...args);if(sql.includes('FROM merchant_members'))clock=new Date('2027-01-02T09:00:00Z');return result;});await expect(run()).rejects.toBeInstanceOf(OccasionAuthorizationDenied);});
it('requires the generated preview to match the approved store and occasion',async()=>{grants[0].reviewed_contract.terms.messagePreview='Another message';grants[0].contract_digest=occasionAuthorizationDigest(grants[0].reviewed_contract);await expect(run()).rejects.toBeInstanceOf(OccasionAuthorizationDenied);});
it('authorizes only unchanged prepared content and discount terms, allowing legitimate redeemed usage',async()=>{prepared();discount.usedCount=1;expect((await run()).record.id).toBe(90);campaign.message='Edited';await expect(run()).rejects.toBeInstanceOf(OccasionAuthorizationDenied);});
it.each(['code','expiry','limit','inactive','campaign-id','discount-id','message','audience','unbound'])('denies altered prepared %s',async kind=>{prepared();if(kind==='code')discount.code='OTHER';if(kind==='expiry')discount.expiresAt='2027-01-02 20:59:59';if(kind==='limit')discount.maxUses=100;if(kind==='inactive')discount.isActive=0;if(kind==='campaign-id')oc.campaignId=78;if(kind==='discount-id')discount.id=42;if(kind==='message')campaign.message='Edited';if(kind==='audience')campaign.targetAudience='{"purchaseCountMin":1}';if(kind==='unbound')grants[0].prepared_campaign_digest=null;await expect(run()).rejects.toBeInstanceOf(OccasionAuthorizationDenied);});
it('validates sending phase independently from preparation and retains verified usage counters',async()=>{prepared();campaign.status='sending';oc.status='sending';oc.recipientCount=2;expect((await run('dispatch')).record.id).toBe(90);await expect(run('prepare')).rejects.toBeInstanceOf(OccasionAuthorizationDenied);});
it('binds a newly created envelope once to its authorized payload',async()=>{
 const authority=await run();prepared();authority.record={...authority.record,prepared_campaign_id:null,prepared_campaign_digest:null,prepared_discount_id:null,prepared_discount_digest:null};
 await bindOccasionPreparedEnvelope({execute} as any,authority,77,'LOCAL',at);expect(execute.mock.calls.at(-1)).toEqual([expect.stringContaining('active=1 AND prepared_campaign_id IS NULL'),[77,occasionCampaignDigest(campaign),41,occasionDiscountDigest(discount),90,7,9]]);
 campaign.message='Edited';await expect(bindOccasionPreparedEnvelope({execute} as any,authority,77,'LOCAL',at)).rejects.toBeInstanceOf(OccasionAuthorizationDenied);
});
