import {beforeEach,it,expect,vi} from 'vitest';
const m=vi.hoisted(()=>({access:vi.fn(),read:vi.fn(),current:vi.fn(),all:vi.fn(),create:vi.fn(),health:vi.fn()}));
vi.mock('./accounts/merchant-access',()=>({resolveMerchantAccess:m.access}));
vi.mock('./integrations/platform-workspace',()=>({readPlatformWorkspace:m.read}));
vi.mock('./integrations/platform-checker',()=>({getCurrentPlatform:m.current,getAllConnectedPlatforms:m.all}));
vi.mock('./integrations/byaan-connection-workspace',async original=>({...await original<typeof import('./integrations/byaan-connection-workspace')>(),registerByaanDomain:m.create}));
vi.mock('./integrations/byaan',()=>({createByaanConnection:m.create,getByaanHealth:m.health,getTerminology:()=>({products:'Courses',customers:'Trainees'})}));
import {integrationsRouter} from './routers-integrations';
import {appRouter} from './routers';
const names=['workspace','getCurrentPlatform','getAllConnectedPlatforms','getByaanStatus','connectByaan','testByaanConnection'] as const;
const sample=()=>({actorId:7,merchantId:20,source:'byaan',platforms:[{platform:'byaan',present:true,occupiesSlot:true,state:'configured',storeUrl:'https://academy.example.test/',lastSyncAt:'2026-10-01T00:00:00Z'}],stats:{products:601,customers:501}});
beforeEach(()=>{vi.resetAllMocks();m.access.mockResolvedValue({merchantId:20,role:'owner'});m.read.mockResolvedValue(sample());m.all.mockResolvedValue([]);m.current.mockResolvedValue(null);m.health.mockResolvedValue({success:true,capabilities:['courses']});m.create.mockResolvedValue({success:false,pendingVerification:true,tenantDomain:'academy.example.test'});});
for(const mounted of [true,false]) {
 const caller=(user:any={id:7,role:'user'},selection='20')=>{const ctx={user,merchantId:999,merchantRole:'owner',req:{headers:{'x-merchant-id':selection}},res:{}} as any;return mounted?appRouter.createCaller(ctx).integrations:integrationsRouter.createCaller(ctx);};
 const call=(name:typeof names[number],api=caller())=>(api[name] as any)(name==='connectByaan'?{tenantDomain:'academy.example.test'}:undefined);
 it.each(['owner','manager'])(`scopes all integration actions for %s (${mounted})`,async role=>{m.access.mockResolvedValue({merchantId:20,role});for(const name of names)await call(name);expect(m.access).toHaveBeenCalledWith(7,20);expect(m.read).toHaveBeenCalledWith(7,20);expect(m.all).toHaveBeenCalledWith(20);expect(m.create).toHaveBeenCalledWith(20,'academy.example.test',7);expect(m.health).toHaveBeenCalledWith(20);});
 it.each(names)(`denies anonymous, revoked and unauthorized members for %s (${mounted})`,async name=>{await expect(call(name,caller(null))).rejects.toMatchObject({code:'UNAUTHORIZED'});m.access.mockResolvedValue(null);await expect(call(name)).rejects.toMatchObject({code:'FORBIDDEN'});for(const role of ['viewer','sales_supervisor','agent']){m.access.mockResolvedValue({merchantId:20,role});await expect(call(name)).rejects.toMatchObject({code:'FORBIDDEN'});}expect(m.read).not.toHaveBeenCalled();expect(m.create).not.toHaveBeenCalled();expect(m.health).not.toHaveBeenCalled();});
 it(`rejects ambiguous selection and redacts read failure (${mounted})`,async()=>{m.access.mockRejectedValue(Object.assign(Error(),{name:'MerchantSelectionRequiredError'}));await expect(caller().workspace()).rejects.toMatchObject({code:'PRECONDITION_FAILED'});m.access.mockResolvedValue({merchantId:20,role:'owner'});m.read.mockRejectedValue(Error('PRIVATE SQL'));await expect(caller().workspace()).rejects.toMatchObject({code:'INTERNAL_SERVER_ERROR',message:'Platform connection data unavailable'});});
 it(`rejects injected scope and conflicts before connecting (${mounted})`,async()=>{await expect(caller().connectByaan({tenantDomain:'academy.example.test',merchantId:999} as any)).rejects.toMatchObject({code:'BAD_REQUEST'});m.all.mockResolvedValue([{platform:'byaan'},{platform:'salla'}]);await expect(call('connectByaan')).rejects.toMatchObject({code:'CONFLICT'});expect(m.create).not.toHaveBeenCalled();});
 it(`does not disclose the created connection secrets or claim verification (${mounted})`,async()=>{const result=await call('connectByaan');expect(result).toEqual({success:false,pendingVerification:true,tenantDomain:'academy.example.test'});expect(JSON.stringify(result)).not.toContain('PRIVATE');});
 it(`preserves complete audience counts and blocks live health on pending verification (${mounted})`,async()=>{const value=sample();value.platforms[0].state='pending_verification';m.read.mockResolvedValue(value);expect(await caller().getByaanStatus()).toMatchObject({isConnected:false,verificationPending:true,stats:{products:601,customers:501}});expect(await caller().testByaanConnection()).toMatchObject({success:false,status:'pending_verification'});expect(m.health).not.toHaveBeenCalled();});
}
