// @vitest-environment jsdom
import React,{act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {Router} from 'wouter';
import {memoryLocation} from 'wouter/memory-location';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import en from '../client/src/locales/merchant-ux.en';
import ar from '../client/src/locales/merchant-ux.ar';
import {platformIds} from '../shared/platform-workspace';
const m=vi.hoisted(()=>({actor:7,merchant:20,language:'en',query:{} as any,sheets:{} as any,calendar:{} as any,health:vi.fn(),refresh:vi.fn()}));
vi.mock('@/lib/trpc',()=>({trpc:{auth:{me:{useQuery:()=>({data:{id:m.actor}})}},merchants:{workspaceIdentity:{useQuery:()=>({data:{id:m.merchant, actorId:m.actor}})}},integrations:{workspace:{useQuery:()=>m.query},testByaanConnection:{useMutation:()=>({mutateAsync:m.health})}},sheets:{getStatus:{useQuery:()=>m.sheets}},calendar:{settings:{useQuery:()=>m.calendar}}}}));
vi.mock('react-i18next',()=>({useTranslation:()=>({i18n:{language:m.language},t:(key:string)=>{let value:any=m.language==='ar'?ar:en;for(const k of key.split('.').slice(1))value=value?.[k];return typeof value==='string'?value:key;}})}));
import PlatformIntegrations from '../client/src/pages/PlatformIntegrations';
let root:Root,container:HTMLDivElement;
const sample=()=>({actorId:7,merchantId:20,checkedAt:'2026-10-02T12:00:00Z',source:'none',occupied:0,conflict:false,stats:{products:601,customers:501,audience:'customers'},platforms:platformIds.map(platform=>({platform,present:false,occupiesSlot:false,state:platform==='shopify'?'unavailable':'unlinked',storeUrl:null,createdAt:null,lastSyncAt:null,hasSyncErrors:false,legacy:false}))});
beforeEach(()=>{
 Object.assign(globalThis,{React,IS_REACT_ACT_ENVIRONMENT:true});vi.resetAllMocks();m.actor=7;m.merchant=20;m.language='en';
 m.query={data:sample(),refetch:m.refresh};m.calendar={data:{actorId:7,merchantId:20,digest:'a'.repeat(64),hasIntegration:false,active:false,oauthReady:true,state:'unlinked',calendarId:null,lastSync:null,retainedAppointments:0},refetch:m.refresh};
 m.sheets={data:{actorId:7,merchantId:20,digest:'a'.repeat(64),hasIntegration:false,isConnected:false,oauthReady:true,state:'unlinked',reports:{sendDailyReports:false,sendWeeklyReports:false,sendMonthlyReports:false}},refetch:m.refresh};
 container=document.createElement('div');document.body.append(container);root=createRoot(container);
});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();});
const render=async()=>act(async()=>root.render(<Router hook={memoryLocation({path:'/merchant/platform-integrations'}).hook}><PlatformIntegrations/></Router>));
const click=async(name:string)=>act(async()=>{const b=Array.from(container.querySelectorAll('button')).find(b=>b.textContent===name)!;expect(b).toBeTruthy();b.click();});
function byaan(){const row=m.query.data.platforms[4];Object.assign(row,{present:true,occupiesSlot:true,state:'configured',storeUrl:'https://academy.example.test/'});Object.assign(m.query.data,{source:'byaan',occupied:1,stats:{products:601,customers:501,audience:'trainees'}});}
it.each(['ar','en'])('renders all platforms, Google settings and truthful full counts in %s',async lang=>{m.language=lang;await render();const copy=(lang==='ar'?ar:en).platformWorkspace;expect(container.querySelectorAll('h1')).toHaveLength(1);expect(container.querySelectorAll('[data-platform]')).toHaveLength(5);expect(container.textContent).toContain(copy.storedHint);expect(container.textContent).toContain(copy.dataHint);expect(container.textContent).not.toContain('merchantUx.');expect(container.querySelector('a[href="/merchant/calendar/settings"]')).not.toBeNull();expect(container.querySelector('a[href="/merchant/sheets/settings"]')).not.toBeNull();expect(container.querySelector('[data-platform="shopify"] button')).toBeNull();});
it('does not hide multiple links, offers their settings and blocks a new unrelated link',async()=>{byaan();Object.assign(m.query.data.platforms[0],{present:true,occupiesSlot:true,state:'error'});m.query.data.occupied=2;m.query.data.conflict=true;await render();expect(container.textContent).toContain(en.platformWorkspace.conflict);expect(container.querySelector('[data-platform="salla"] a[href="/merchant/salla"]')).not.toBeNull();expect(container.querySelector('[data-platform="byaan"] a[href="/merchant/integrations/byaan"]')).not.toBeNull();expect(container.querySelector('[data-platform="zid"] a')).toBeNull();expect(container.textContent).toContain(en.platformWorkspace.trainees);});
it.each(['actorId','merchantId'])('rejects cross-scope %s snapshots',async key=>{m.query.data[key]=99;await render();expect(container.querySelector('[data-state="error"]')).not.toBeNull();expect(container.querySelector('[data-platform]')).toBeNull();});
it.each(['FORBIDDEN','UNAUTHORIZED','INTERNAL_SERVER_ERROR'])('hides stale data when %s is returned',async code=>{m.query.error={data:{code},message:'PRIVATE'};await render();expect(container.querySelector('[data-platform]')).toBeNull();expect(container.textContent).not.toContain('PRIVATE');expect(container.querySelector('[data-state]')).not.toBeNull();});
it('treats a malformed conflict count as an error',async()=>{m.query.data.occupied=4;await render();expect(container.querySelector('[data-state="error"]')).not.toBeNull();});
it.each(['javascript:alert(1)','https://user:secret@example.test'])('never creates an unsafe store link for %s',async url=>{byaan();m.query.data.platforms[4].storeUrl=url;await render();expect(container.querySelector('[data-platform="byaan"] a[target]')).toBeNull();});
it('strips secret query values from a provider display link',async()=>{byaan();m.query.data.platforms[4].storeUrl='https://academy.example.test/?token=PRIVATE#SECRET';await render();expect(container.querySelector('[data-platform="byaan"] a[target]')!.getAttribute('href')).toBe('https://academy.example.test/');expect(container.textContent).not.toContain('PRIVATE');});
it('shows unread Google data as unknown without a false connection badge',async()=>{m.sheets.error={data:{code:'INTERNAL_SERVER_ERROR'}};m.calendar.data.actorId=99;await render();expect(container.querySelector('[data-sheets-connection-card]')!.textContent).toContain(en.platformWorkspace.statusError);expect(container.querySelector('[data-calendar-connection-card]')!.textContent).toContain(en.calendarConnection.unknown);});
it.each([['active',true,'healthOk'],['error',false,'healthFailed'],['pending_verification',false,'healthPending'],['not_connected',false,'healthNone']])('reports %s health without trusting raw provider text',async(status,success,key)=>{byaan();m.health.mockResolvedValue({status,success,message:'PRIVATE'});await render();await click(en.platformWorkspace.test);expect(container.textContent).toContain(en.platformWorkspace[key as keyof typeof en.platformWorkspace]);expect(container.textContent).not.toContain('PRIVATE');expect(m.health).toHaveBeenCalledTimes(1);});
it('ignores a late health result after the tenant changes',async()=>{byaan();let finish!:(v:any)=>void;m.health.mockImplementation(()=>new Promise(resolve=>finish=resolve));await render();await click(en.platformWorkspace.test);m.merchant=21;m.query.data.merchantId=21;await render();await act(async()=>finish({status:'active',success:true}));expect(container.textContent).not.toContain(en.platformWorkspace.healthOk);});
it('does not retry a failed live health check automatically',async()=>{byaan();m.health.mockRejectedValue(Error('PRIVATE'));await render();await click(en.platformWorkspace.test);expect(container.textContent).toContain(en.platformWorkspace.healthFailed);expect(m.health).toHaveBeenCalledTimes(1);});
it('translates the existing check result when the language changes without another request',async()=>{byaan();m.health.mockResolvedValue({status:'active',success:true});await render();await click(en.platformWorkspace.test);m.language='ar';await render();expect(container.textContent).toContain(ar.platformWorkspace.healthOk);expect(container.textContent).not.toContain(en.platformWorkspace.healthOk);expect(m.health).toHaveBeenCalledTimes(1);});
