import {randomUUID} from 'node:crypto';
import {beforeEach,afterEach,afterAll,describe,it,expect,vi} from 'vitest';
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {reviewPromotionAction,applyPromotionAction,readPromotionActionReceipt} from './promotion-actions';
describe.skipIf(!process.env.DATABASE_URL)('reviewed promotion decisions and durable receipts',()=>{
 let owner:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof owner;
 const q=async(sql:string,args:any[]=[]) => (await (await getPool())!.execute<any>(sql,args))[0];
 const target=(patch:any={})=>({action:'create',data:{title:'Reviewed offer',type:'percentage',value:15,...patch}});
 const review=(value:any=target())=>reviewPromotionAction(owner.userId,owner.merchantId,value);
 const apply=(r:any,requestKey=randomUUID())=>({target:r.target,reviewRevision:r.reviewRevision,checkedAt:r.checkedAt,requestKey});
 const save=(r:any)=>applyPromotionAction(owner.userId,owner.merchantId,r);
 const counts=async()=>({offers:(await q('SELECT COUNT(*) n FROM promotions WHERE merchant_id=?',[owner.merchantId]))[0].n,codes:(await q('SELECT COUNT(*) n FROM discount_codes WHERE merchantId=?',[owner.merchantId]))[0].n,receipts:(await q('SELECT COUNT(*) n FROM promotion_action_receipts WHERE merchant_id=?',[owner.merchantId]))[0].n});
 beforeEach(async()=>{owner=await createDisposableMerchant('promotion-review');other=await createDisposableMerchant('promotion-review-other');});
 afterEach(async()=>{vi.restoreAllMocks();await cleanupDisposableMerchants([owner.userId,other.userId]);});afterAll(closeDb);
 it('reviews all conditions without side effects and saves one offer, coupon and receipt',async()=>{
  const r=await review(target({autoGenerateCode:true,autoCodeValue:15,minOrderAmount:50,description:'Terms',expiresAt:'2027-02-01'}));
  expect(r).toMatchObject({actorId:owner.userId,merchantId:owner.merchantId,effect:'create_active',salesVerified:false,newDiscount:{value:15,minOrderAmount:50},proposed:{description:'Terms',expiresAt:'2027-02-01 20:59:59'}});expect(await counts()).toEqual({offers:0,codes:0,receipts:0});
  const input=apply(r),result=await save(input);expect(await save(input)).toEqual(result);expect(await readPromotionActionReceipt(owner.userId,owner.merchantId,{requestKey:input.requestKey})).toEqual({state:'saved',result});expect(await counts()).toEqual({offers:1,codes:1,receipts:1});
 });
 it('serializes simultaneous duplicate create requests into one result',async()=>{const input=apply(await review(target({autoGenerateCode:true,autoCodeValue:15})));const result=await Promise.all([save(input),save(input)]);expect(result[0]).toEqual(result[1]);expect(await counts()).toEqual({offers:1,codes:1,receipts:1});});
 it('rejects reusing an accepted request key with changed conditions',async()=>{const input=apply(await review());await save(input);await expect(save({...input,target:target({title:'Different'})})).rejects.toMatchObject({reason:'reused'});expect(await counts()).toEqual({offers:1,codes:0,receipts:1});});
 it('binds the review to actor, merchant and exact proposed values',async()=>{const input=apply(await review());await expect(applyPromotionAction(other.userId,other.merchantId,input)).rejects.toMatchObject({reason:'stale'});await expect(save({...input,target:target({value:80})})).rejects.toMatchObject({reason:'stale'});expect(await counts()).toEqual({offers:0,codes:0,receipts:0});});
 it('rejects a changed definition, but counters alone do not invalidate a review',async()=>{
  const row=await save(apply(await review())),r=await review({action:'update',data:{id:row.id,title:'New'}}),input=apply(r);
  await q('UPDATE promotions SET view_count=view_count+1,updated_at=DATE_ADD(updated_at,INTERVAL 1 SECOND) WHERE id=?',[row.id]);await save(input);
  const stale=apply(await review({action:'update',data:{id:row.id,title:'Other'}}));await q("UPDATE promotions SET description='Concurrent change' WHERE id=?",[row.id]);await expect(save(stale)).rejects.toMatchObject({reason:'stale'});expect((await q('SELECT title FROM promotions WHERE id=?',[row.id]))[0].title).toBe('New');
 });
 it('requires a new review after slot conditions change',async()=>{const input=apply(await review());await save(apply(await review()));await expect(save(input)).rejects.toMatchObject({reason:'stale'});expect(await counts()).toEqual({offers:1,codes:0,receipts:1});});
 it('uses an absolute active state and replays pause without toggling back',async()=>{const row=await save(apply(await review())),input=apply(await review({action:'toggle',id:row.id,enabled:false}));const result=await save(input);expect(await save(input)).toEqual(result);expect((await q('SELECT is_active FROM promotions WHERE id=?',[row.id]))[0].is_active).toBe(0);await expect(review({action:'toggle',id:row.id,enabled:false})).rejects.toMatchObject({reason:'stale'});});
 it('retains linked discounts on update and deletion, and replays deletion after the row is gone',async()=>{
  const row=await save(apply(await review(target({autoGenerateCode:true,autoCodeValue:15}))));
  const edit=await review({action:'update',data:{id:row.id,value:25}});expect(edit.retainsLinkedDiscount).toBe(true);expect(edit.before?.linkedDiscount?.value).toBe(15);await save(apply(edit));
  const input=apply(await review({action:'delete',id:row.id})),result=await save(input);expect(await save(input)).toEqual(result);expect(await counts()).toEqual({offers:0,codes:1,receipts:3});expect((await q('SELECT value FROM discount_codes WHERE merchantId=?',[owner.merchantId]))[0].value).toBe(15);
 });
 it('never exposes a foreign linked discount during review or deletes it',async()=>{const row=await save(apply(await review())),code=Number((await q("INSERT INTO discount_codes (merchantId,code,type,value) VALUES (?,'PRIVATE-OTHER','percentage',80)",[other.merchantId])).insertId);await q('UPDATE promotions SET auto_discount_code_id=? WHERE id=?',[code,row.id]);const r=await review({action:'delete',id:row.id});expect(r.before?.linkedDiscount).toBeNull();expect(JSON.stringify(r)).not.toContain('PRIVATE-OTHER');await save(apply(r));expect(await q('SELECT id FROM discount_codes WHERE id=?',[code])).toHaveLength(1);});
 it('rolls back the offer and code if recording the receipt fails',async()=>{const input=apply(await review(target({autoGenerateCode:true,autoCodeValue:15}))),pool=(await getPool())!,tx=await pool.getConnection(),execute=tx.execute.bind(tx);vi.spyOn(pool,'getConnection').mockResolvedValueOnce(tx);vi.spyOn(tx,'execute').mockImplementation((async(sql:any,args:any)=>{if(String(sql).startsWith('INSERT INTO promotion_action_receipts'))throw Error('Disk failure');return execute(sql,args);}) as any);await expect(save(input)).rejects.toMatchObject({reason:'unavailable'});vi.restoreAllMocks();expect(await counts()).toEqual({offers:0,codes:0,receipts:0});});
 it('recovers a committed write after lost acknowledgement without duplicate offers or coupons',async()=>{const input=apply(await review(target({autoGenerateCode:true,autoCodeValue:15}))),pool=(await getPool())!,tx=await pool.getConnection(),commit=tx.commit.bind(tx);vi.spyOn(pool,'getConnection').mockResolvedValueOnce(tx);const destroyed=vi.spyOn(tx,'destroy');vi.spyOn(tx,'commit').mockImplementation(async()=>{await commit();throw Error('Lost response');});await expect(save(input)).rejects.toMatchObject({reason:'unknown'});expect(destroyed).toHaveBeenCalledOnce();vi.restoreAllMocks();const receipt=await readPromotionActionReceipt(owner.userId,owner.merchantId,{requestKey:input.requestKey});expect(receipt.state).toBe('saved');expect(await save(input)).toEqual(receipt.result);expect(await counts()).toEqual({offers:1,codes:1,receipts:1});});
 it('checks current permission before applying or reading/replaying a receipt',async()=>{const input=apply(await review()),result=await save(input);await q("INSERT INTO merchant_members (merchant_id,user_id,role,is_active) VALUES (?,?,'owner',0)",[owner.merchantId,owner.userId]);await expect(save(input)).rejects.toMatchObject({reason:'forbidden'});await expect(readPromotionActionReceipt(owner.userId,owner.merchantId,{requestKey:result.requestKey})).rejects.toMatchObject({reason:'forbidden'});});
 it('does not reveal another actor receipt even to a current manager',async()=>{const input=apply(await review());await save(input);await q("INSERT INTO merchant_members (merchant_id,user_id,role,is_active) VALUES (?,?,'manager',1)",[owner.merchantId,other.userId]);await expect(applyPromotionAction(other.userId,owner.merchantId,input)).rejects.toMatchObject({reason:'reused'});await expect(readPromotionActionReceipt(other.userId,owner.merchantId,{requestKey:input.requestKey})).rejects.toMatchObject({reason:'reused'});expect(await readPromotionActionReceipt(other.userId,other.merchantId,{requestKey:input.requestKey})).toEqual({state:'missing',result:null});});
 it('expires old reviews but still allows authorized receipt recovery',async()=>{const input=apply(await review()),result=await save(input),pending=apply(await review()),real=Date.now();vi.spyOn(Date,'now').mockReturnValue(real+300001);await expect(save(pending)).rejects.toMatchObject({reason:'stale'});expect(await save(input)).toEqual(result);});
 it('rejects a schedule boundary crossed after review',async()=>{const row=await save(apply(await review(target({startsAt:new Date(Date.now()+60000).toISOString()})))),r=apply(await review({action:'update',data:{id:row.id,title:'Changed'}})),real=Date.now();vi.spyOn(Date,'now').mockReturnValue(real+61000);await expect(save(r)).rejects.toMatchObject({reason:'stale'});});
 it('rolls back if the review expires while its receipt is being written',async()=>{const input=apply(await review(target({autoGenerateCode:true,autoCodeValue:15}))),pool=(await getPool())!,tx=await pool.getConnection(),execute=tx.execute.bind(tx),now=Date.now();vi.spyOn(pool,'getConnection').mockResolvedValueOnce(tx);vi.spyOn(tx,'execute').mockImplementation((async(sql:any,args:any)=>{const result=await execute(sql,args);if(String(sql).startsWith('INSERT INTO promotion_action_receipts'))vi.spyOn(Date,'now').mockReturnValue(now+300001);return result;}) as any);await expect(save(input)).rejects.toMatchObject({reason:'stale'});vi.restoreAllMocks();expect(await counts()).toEqual({offers:0,codes:0,receipts:0});});
 it('allows pausing invalid legacy targeting while keeping its exact data',async()=>{const row=await save(apply(await review()));await q("UPDATE promotions SET scope='products',product_ids='bad' WHERE id=?",[row.id]);const r=await review({action:'toggle',id:row.id,enabled:false});expect(r.before?.issues).toContain('products');await save(apply(r));expect((await q('SELECT product_ids,is_active FROM promotions WHERE id=?',[row.id]))[0]).toEqual({product_ids:'bad',is_active:0});});
});
