import {beforeEach,afterEach,afterAll,describe,it,expect} from 'vitest';
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {readPromotionTargets} from './promotion-targets';
describe.skipIf(!process.env.DATABASE_URL)('promotion product and category choices',()=>{
 let owner:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof owner;
 const q=async(sql:string,args:any[]=[]) => (await (await getPool())!.execute<any>(sql,args))[0];
 beforeEach(async()=>{owner=await createDisposableMerchant('promo-targets');other=await createDisposableMerchant('promo-targets-other');});afterEach(async()=>{await cleanupDisposableMerchants([owner.userId,other.userId]);});afterAll(closeDb);
 it.each(['products','categories'] as const)('keeps every %s page, names and selected IDs without leaking foreign names',async kind=>{
  const table=kind==='products'?'products':'product_categories',column=kind==='products'?'merchantId':'merchant_id',alt=kind==='products'?'nameAr':'name_en';
  const insert=async(merchant:number,name:string)=>Number((await q(`INSERT INTO ${table} (${column},name,${alt}${kind==='products'?',price':''}) VALUES (?,?,?${kind==='products'?',100':''})`,[merchant,name,'اسم '+name])).insertId);
  const ids=[];for(let i=0;i<31;i++)ids.push(await insert(owner.merchantId,'Sample '+i));const foreign=await insert(other.merchantId,'PRIVATE-TARGET');
  const first=await readPromotionTargets(owner.userId,owner.merchantId,{kind,selectedIds:[ids[0],foreign]});expect(first).toMatchObject({actorId:owner.userId,merchantId:owner.merchantId,total:31,pages:2,missingIds:[foreign]});expect(first.rows).toHaveLength(25);expect(first.selected).toHaveLength(1);expect(first.selected[0]).toMatchObject({id:ids[0],name:'Sample 0',alternateName:'اسم Sample 0',active:true});expect(JSON.stringify(first)).not.toContain('PRIVATE-TARGET');expect((await readPromotionTargets(owner.userId,owner.merchantId,{kind,page:2})).rows).toHaveLength(6);expect((await readPromotionTargets(owner.userId,owner.merchantId,{kind,query:'اسم Sample 30'})).rows.map(r=>r.id)).toEqual([ids[30]]);expect((await readPromotionTargets(owner.userId,owner.merchantId,{kind,query:String(ids[0])})).rows.map(r=>r.id)).toEqual([ids[0]]);expect((await readPromotionTargets(owner.userId,owner.merchantId,{kind,page:99})).rows).toEqual([]);
 });
 it('uses literal text search and rejects wildcard or SQL broadening',async()=>{await q("INSERT INTO products (merchantId,name,price) VALUES (?,'Normal',100)",[owner.merchantId]);for(const query of ['%','_',"' OR 1=1 --"]){expect((await readPromotionTargets(owner.userId,owner.merchantId,{kind:'products',query})).total).toBe(0);}});
 it('permits current selected managers and rejects revoked, inactive and foreign owners',async()=>{await q("INSERT INTO merchant_members (merchant_id,user_id,role,is_active) VALUES (?,?,'manager',1)",[other.merchantId,owner.userId]);expect((await readPromotionTargets(owner.userId,other.merchantId,{kind:'products'})).merchantId).toBe(other.merchantId);await q("UPDATE merchant_members SET is_active=0 WHERE merchant_id=? AND user_id=?",[other.merchantId,owner.userId]);await expect(readPromotionTargets(owner.userId,other.merchantId,{kind:'products'})).rejects.toMatchObject({reason:'forbidden'});await expect(readPromotionTargets(other.userId,owner.merchantId,{kind:'categories'})).rejects.toMatchObject({reason:'forbidden'});await q("UPDATE users SET account_status='deletion_pending' WHERE id=?",[owner.userId]);await expect(readPromotionTargets(owner.userId,owner.merchantId,{kind:'products'})).rejects.toMatchObject({reason:'forbidden'});});
});
