// @vitest-environment jsdom
import React,{act,useState} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {promotionWorkspaceLabels} from '../client/src/lib/promotion-workspace-labels';
import {promotionWorkspaceEn as en} from '../client/src/locales/promotion-workspace';
const m=vi.hoisted(()=>({selection:{} as any,error:null as any,override:{} as any,initial:'1',change:vi.fn(),refresh:vi.fn()}));
vi.mock('@/lib/trpc',()=>({trpc:{promotions:{targetChoices:{useQuery:(selection:any)=>{m.selection=selection;return {data:{actorId:7,merchantId:20,selection,total:26,pages:2,pageSize:25,rows:selection.page===1?[{id:1,name:'Shirt',alternateName:'قميص',active:true}]:[{id:2,name:'Bag',alternateName:'حقيبة',active:false}],selected:selection.selectedIds.filter((id:number)=>id!==99).map((id:number)=>({id,name:id===1?'Shirt':'Bag',alternateName:null,active:true})),missingIds:selection.selectedIds.filter((id:number)=>id===99),...m.override},error:m.error,isFetching:false,refetch:m.refresh};}}}}}));
import {PromotionTargetPicker,promotionTargetIds} from '../client/src/components/merchant/PromotionTargetPicker';
const c=promotionWorkspaceLabels(k=>(en as any)[k.split('.').pop()!]??k);
function App(){const [value,setValue]=useState(m.initial);return <PromotionTargetPicker actorId={7} merchantId={20} kind="products" value={value} onChange={s=>{m.change(s);setValue(s);}} busy={false} c={c} locale="en"/>;}
let root:Root,container:HTMLDivElement;const render=()=>act(async()=>root.render(<App/>));const click=(el:Element)=>act(async()=>el.dispatchEvent(new MouseEvent('click',{bubbles:true})));const button=(text:string)=>Array.from(document.querySelectorAll<HTMLButtonElement>('button')).find(b=>b.textContent?.startsWith(text))!;
beforeEach(()=>{Object.assign(globalThis,{React,IS_REACT_ACT_ENVIRONMENT:true});vi.resetAllMocks();Object.assign(m,{selection:{},error:null,override:{},initial:'1'});container=document.createElement('div');document.body.append(container);root=createRoot(container);});afterEach(async()=>{await act(async()=>root.unmount());container.remove();});
it('keeps selected names across choice pages and toggles by ID',async()=>{await render();expect(container.textContent).toContain('Shirt');expect(container.querySelector<HTMLInputElement>('input[type=checkbox]')?.checked).toBe(true);await click(button(en.next));expect(container.textContent).toContain('Shirt');expect(container.textContent).toContain('Bag');await click(container.querySelector('input[type=checkbox]')!);expect(m.change).toHaveBeenLastCalledWith('1, 2');expect(m.selection.selectedIds).toEqual([1,2]);});
it('preserves unavailable IDs and offers explicit removal',async()=>{m.initial='1,99';await render();expect(container.textContent).toContain(en.missingTargets);expect(m.change).not.toHaveBeenCalled();await click(button(en.removeTarget+' #99'));expect(m.change).toHaveBeenLastCalledWith('1');});
it.each([{merchantId:21},{actorId:8},{selection:{kind:'categories',query:'',page:1,selectedIds:[1]}}])('rejects mismatched choice snapshots %j',async override=>{m.override=override;await render();expect(container.textContent).toContain(en.choicesFailed);expect(container.textContent).not.toContain('Shirt');expect(m.change).not.toHaveBeenCalled();});
it('does not remove selected values when choices fail',async()=>{m.error=Error('PRIVATE');await render();expect(container.textContent).toContain(en.choicesFailed);expect(container.textContent).not.toContain('PRIVATE');await click(button(en.refresh));expect(m.refresh).toHaveBeenCalledOnce();expect(m.change).not.toHaveBeenCalled();});
it('requires repair of malformed IDs before toggling choices',async()=>{m.initial='1,bad';await render();expect(container.textContent).toContain(en.fieldIds);expect(container.querySelector<HTMLInputElement>('input[type=checkbox]')?.disabled).toBe(true);});
it('supports Arabic IDs and rejects silent coercion or duplicates',()=>{expect(promotionTargetIds('١، ۲')).toEqual([1,2]);for(const value of ['1e2','1.2','1,1','0','-1','bad'])expect(promotionTargetIds(value)).toBeNull();});
