import {beforeEach,afterEach,afterAll,describe,it,expect} from 'vitest';
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {readPromotionTargetNames} from './promotion-target-names';
import {readPromotionWorkspace} from './promotion-workspace-store';
import {promotionWorkspaceInput} from '../shared/promotion-workspace';
describe.skipIf(!process.env.DATABASE_URL)('stored promotion target names on disposable tenants',()=>{
 let owner:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof owner,id:number,own:number,foreign:number;
 const q=async(sql:string,args:any[]=[]) => (await (await getPool())!.execute<any>(sql,args))[0];
 const input=async()=>{const row=(await readPromotionWorkspace(owner.userId,owner.merchantId,promotionWorkspaceInput.parse({}))).rows[0];return {id:row.id,revision:row.revision};};
 beforeEach(async()=>{owner=await createDisposableMerchant('promo-names');other=await createDisposableMerchant('promo-names-other');id=Number((await q("INSERT INTO promotions (merchant_id,title,type,value,scope) VALUES (?,'Names','percentage',15,'products')",[owner.merchantId])).insertId);});
 afterEach(async()=>{await cleanupDisposableMerchants([owner.userId,other.userId]);});afterAll(closeDb);
 it.each(['products','categories'] as const)('resolves stored %s only and reports missing or foreign references without names',async kind=>{
  const products=kind==='products',table=products?'products':'product_categories',col=products?'merchantId':'merchant_id',alt=products?'nameAr':'name_en',field=products?'product_ids':'category_ids';
  own=Number((await q(`INSERT INTO ${table} (${col},name,${alt}${products?',price':''}) VALUES (?,'Current','بديل'${products?',100':''})`,[owner.merchantId])).insertId);
  foreign=Number((await q(`INSERT INTO ${table} (${col},name${products?',price':''}) VALUES (?,'PRIVATE-TARGET'${products?',100':''})`,[other.merchantId])).insertId);
  await q(`UPDATE promotions SET scope=?,${field}=? WHERE id=?`,[kind,JSON.stringify([own,foreign,2147483647]),id]);
  const data=await readPromotionTargetNames(owner.userId,owner.merchantId,await input());expect(data.state).toBe('ready');if(data.state!=='ready')throw Error();expect(data[kind]).toMatchObject({ids:[own,foreign,2147483647],choices:[{id:own,name:'Current',alternateName:'بديل',active:true}],missingIds:[foreign,2147483647]});expect(JSON.stringify(data)).not.toContain('PRIVATE-TARGET');
  await q(`UPDATE ${table} SET name='Renamed',${products?'isActive':'is_active'}=0 WHERE id=?`,[own]);const renamed=await readPromotionTargetNames(owner.userId,owner.merchantId,await input());expect(renamed[kind]?.choices[0]).toMatchObject({name:'Renamed',active:false});
 });
 it('returns changed or missing without exposing new names and never searches arbitrary IDs',async()=>{const key=await input();await q("UPDATE promotions SET title='Changed' WHERE id=?",[id]);expect(await readPromotionTargetNames(owner.userId,owner.merchantId,key)).toMatchObject({state:'changed',products:null,categories:null});expect(await readPromotionTargetNames(other.userId,other.merchantId,key)).toMatchObject({state:'missing',products:null});await q('DELETE FROM promotions WHERE id=?',[id]);expect((await readPromotionTargetNames(owner.userId,owner.merchantId,key)).state).toBe('missing');expect(()=>readPromotionTargetNames(owner.userId,owner.merchantId,{...key,selectedIds:[1]})).toThrow();});
 it('allows current read-only members but rejects revocation, suspended tenants and inactive accounts',async()=>{const key=await input();await q("INSERT INTO merchant_members (merchant_id,user_id,role,is_active) VALUES (?,?,'viewer',1)",[owner.merchantId,other.userId]);expect((await readPromotionTargetNames(other.userId,owner.merchantId,key)).state).toBe('ready');await q('UPDATE merchant_members SET is_active=0 WHERE merchant_id=? AND user_id=?',[owner.merchantId,other.userId]);await expect(readPromotionTargetNames(other.userId,owner.merchantId,key)).rejects.toMatchObject({reason:'forbidden'});await q("UPDATE merchants SET status='suspended' WHERE id=?",[owner.merchantId]);await expect(readPromotionTargetNames(owner.userId,owner.merchantId,key)).rejects.toMatchObject({reason:'forbidden'});await q("UPDATE merchants SET status='active' WHERE id=?",[owner.merchantId]);await q("UPDATE users SET account_status='deletion_pending' WHERE id=?",[owner.userId]);await expect(readPromotionTargetNames(owner.userId,owner.merchantId,key)).rejects.toMatchObject({reason:'forbidden'});});
 it('preserves malformed legacy targets as unknown instead of showing an empty valid scope',async()=>{await q("UPDATE promotions SET product_ids='[1,1]',category_ids=NULL WHERE id=?",[id]);expect(await readPromotionTargetNames(owner.userId,owner.merchantId,await input())).toMatchObject({state:'ready',products:{ids:null,choices:[],missingIds:[]},categories:{ids:[],choices:[],missingIds:[]}});});
});
