import {beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({access:vi.fn(),create:vi.fn(),review:vi.fn(),apply:vi.fn(),claim:vi.fn(),code:vi.fn(),legacy:vi.fn(),stats:vi.fn(),limit:vi.fn()}));
vi.mock('./accounts/merchant-access',()=>({resolveMerchantAccess:m.access}));
vi.mock('./_core/rateLimiter',()=>({checkRateLimit:m.limit}));
vi.mock('./referral-program-store',async original=>({...await original<typeof import('./referral-program-store')>(),createMerchantInvitation:m.create,reviewMerchantInvitation:m.review,applyMerchantInvitation:m.apply,recordMerchantRewardClaim:m.claim,getMerchantInvitation:m.code,readReferralLegacy:m.legacy,readReferralLegacyStats:m.stats}));
import {referralsRouter} from './routers-referrals';
import {appRouter} from './routers';
const revision='a'.repeat(64),inputs={createInvitation:{confirm:true},reviewInvitation:{code:'SARY-INVITE'},applyReferralCode:{code:'SARY-INVITE',expectedRevision:revision,acknowledgePendingReward:true},claimReward:{rewardId:1,expectedRevision:revision,recordOnly:true}};
beforeEach(()=>{vi.resetAllMocks();m.access.mockResolvedValue({merchantId:20,role:'owner'});m.limit.mockReturnValue({allowed:true});m.apply.mockResolvedValue({success:true,replayed:true});});
for(const mounted of [false,true]){
 const caller=(user:any={id:7,role:'user'},selection='20')=>{const ctx={user,merchantId:999,merchantRole:'owner',req:{headers:{'x-merchant-id':selection}},res:{}} as any;return mounted?appRouter.createCaller(ctx).referrals:referralsRouter.createCaller(ctx);};
 it(`scopes reads and reviewed writes to selected store mounted=${mounted}`,async()=>{const c=caller();await c.getMyCode();await c.getMyReferrals();await c.getMyRewards();await c.getStats();for(const [method,input] of Object.entries(inputs))await (c as any)[method](input);expect(m.code).toHaveBeenCalledExactlyOnceWith(7,20);expect(m.legacy).toHaveBeenCalledWith(7,20,'referrals');expect(m.legacy).toHaveBeenCalledWith(7,20,'rewards');expect(m.stats).toHaveBeenCalledExactlyOnceWith(7,20);for(const [fn,input] of [[m.create,inputs.createInvitation],[m.review,inputs.reviewInvitation],[m.apply,inputs.applyReferralCode],[m.claim,inputs.claimReward]] as const)expect(fn).toHaveBeenCalledExactlyOnceWith(7,20,input);});
 it.each(['viewer','manager','sales_supervisor'])(`denies %s all writes mounted=${mounted}`,async role=>{m.access.mockResolvedValue({merchantId:20,role});for(const [method,input] of Object.entries(inputs))await expect((caller() as any)[method](input)).rejects.toMatchObject({code:'FORBIDDEN'});expect(m.create).not.toHaveBeenCalled();expect(m.claim).not.toHaveBeenCalled();});
 it(`rejects unreviewed legacy payloads and injected fields mounted=${mounted}`,async()=>{await expect(caller().claimReward({rewardId:1} as any)).rejects.toMatchObject({code:'BAD_REQUEST'});await expect(caller().applyReferralCode({code:'SARY-INVITE'} as any)).rejects.toMatchObject({code:'BAD_REQUEST'});await expect(caller().createInvitation({confirm:true,merchantId:99} as any)).rejects.toMatchObject({code:'BAD_REQUEST'});await expect(caller().getMyCode({merchantId:99} as any)).rejects.toMatchObject({code:'BAD_REQUEST'});expect(m.create).not.toHaveBeenCalled();expect(m.apply).not.toHaveBeenCalled();});
 it(`rejects anonymous/revoked and hides internal errors mounted=${mounted}`,async()=>{await expect(caller(null).createInvitation(inputs.createInvitation as any)).rejects.toMatchObject({code:'UNAUTHORIZED'});m.access.mockResolvedValue(null);await expect(caller().getStats()).rejects.toMatchObject({code:'FORBIDDEN'});m.access.mockResolvedValue({merchantId:20,role:'owner'});m.create.mockRejectedValue(Error('PRIVATE SQL'));await expect(caller().createInvitation({confirm:true})).rejects.toMatchObject({code:'INTERNAL_SERVER_ERROR',message:'تعذر تأكيد النتيجة. حدّث البيانات قبل المحاولة مجددًا.'});});
 it(`limits code lookup before storage mounted=${mounted}`,async()=>{m.limit.mockReturnValue({allowed:false});await expect(caller().reviewInvitation({code:'SARY-INVITE'})).rejects.toMatchObject({code:'TOO_MANY_REQUESTS'});await expect(caller().applyReferralCode(inputs.applyReferralCode as any)).rejects.toMatchObject({code:'TOO_MANY_REQUESTS'});expect(m.review).not.toHaveBeenCalled();expect(m.apply).not.toHaveBeenCalled();});
}
