import { afterAll, afterEach, beforeEach, describe, expect, it } from 'vitest';
import { getPool, closeDb } from './db/connection';
import { createDisposableMerchant, cleanupDisposableMerchants } from './tests/helpers/disposable-merchant';
import { readSallaDashboardStatus, readSallaDashboardLogs } from './integrations/salla-dashboard-read';
import { sallaDashboardProcedures } from './routers-salla-dashboard';
import { router } from './_core/trpc';
const api = router(sallaDashboardProcedures);
describe.skipIf(!process.env.DATABASE_URL)('Salla dashboard scoped MySQL reads', () => {
  let own: Awaited<ReturnType<typeof createDisposableMerchant>>, other: typeof own;
  const q = async (sql: string, params: unknown[] = []) => (await (await getPool())!.execute<any>(sql,params))[0];
  beforeEach(async () => { own = await createDisposableMerchant('salla-dashboard'); other = await createDisposableMerchant('salla-other'); });
  afterEach(async () => cleanupDisposableMerchants([own.userId,other.userId])); afterAll(closeDb);
  const insert = (merchantId: number, url = 'https://store.example.test/?token=PRIVATE') => q("INSERT INTO salla_connections(merchantId,storeUrl,accessToken,syncStatus) VALUES (?,?,'PRIVATE','paused')",[merchantId,url]);
  const caller = (userId = own.userId) => api.createCaller({ user: { id:userId,role:'user' }, req: { headers: { 'x-merchant-id':String(own.merchantId) } }, res:{} } as any);
  it('keeps another tenant private and distinguishes a missing stored connection', async () => { await insert(other.merchantId,'https://private.example.test'); expect(await readSallaDashboardStatus(own.merchantId)).toEqual({connected:false}); await insert(own.merchantId); const result = await caller().getConnection(); expect(result).toMatchObject({connected:true,storeUrl:'https://store.example.test/',syncStatus:'paused',webhookHealth:{awaiting:0,manualReview:0}}); expect(JSON.stringify(result)).not.toMatch(/PRIVATE|private\.example/); });
  it('paginates the legacy history deterministically and never projects raw error contents', async () => { const rows = Array.from({length:23},()=>[own.merchantId,'full_sync','failed',3,'PRIVATE provider SQL']); await q('INSERT INTO sync_logs(merchantId,syncType,status,itemsSynced,errors) VALUES '+rows.map(()=>'(?,?,?,?,?)').join(','),rows.flat()); await q("INSERT INTO sync_logs(merchantId,syncType,status,itemsSynced,errors) VALUES (?,'stock_sync','success',999,'FOREIGN')",[other.merchantId]); const result = await readSallaDashboardLogs(own.merchantId); expect(result).toHaveLength(20); expect(result.every(row=>row.itemsSynced===3)).toBe(true); expect(result.map(row=>row.id)).toEqual([...result.map(row=>row.id)].sort((a,b)=>b-a)); expect(JSON.stringify(result)).not.toMatch(/PRIVATE|FOREIGN/); });
  it('authorizes selected membership and immediately rejects downgrade or revocation', async () => { await insert(own.merchantId); await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'manager',1)",[own.merchantId,other.userId]); const selected = caller(other.userId); expect(await selected.getConnection()).toMatchObject({connected:true}); await q("UPDATE merchant_members SET role='viewer' WHERE merchant_id=? AND user_id=?",[own.merchantId,other.userId]); await expect(selected.getConnection()).rejects.toMatchObject({code:'FORBIDDEN'}); await expect(selected.getSyncLogs()).rejects.toMatchObject({code:'FORBIDDEN'}); await expect(selected.disconnect({revision:'a'.repeat(64)})).rejects.toMatchObject({code:'FORBIDDEN'}); await q('UPDATE merchant_members SET is_active=0 WHERE merchant_id=? AND user_id=?',[own.merchantId,other.userId]); await expect(selected.syncNow({syncType:'stock'})).rejects.toMatchObject({code:'FORBIDDEN'}); expect(await readSallaDashboardStatus(own.merchantId)).toMatchObject({connected:true}); });
  it('disconnects only the authorized selected tenant and preserves synchronization history', async () => { await insert(own.merchantId); await insert(other.merchantId); await q("INSERT INTO sync_logs(merchantId,syncType,status,itemsSynced) VALUES (?,'full_sync','success',7)",[own.merchantId]); await caller().disconnect({revision:(await caller().getConnection()).revision}); expect(await readSallaDashboardStatus(own.merchantId)).toEqual({connected:false}); expect(await readSallaDashboardStatus(other.merchantId)).toMatchObject({connected:true}); expect(await readSallaDashboardLogs(own.merchantId)).toHaveLength(1); });
});
