import { afterAll,afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { getPool,closeDb } from './db/connection';
import { createDisposableMerchant,cleanupDisposableMerchants } from './tests/helpers/disposable-merchant';
import { readSallaWorkspace,readSallaLogsWorkspace } from './integrations/salla-workspace';
describe.skipIf(!process.env.DATABASE_URL)('Salla complete workspace MySQL',()=>{
  let own:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof own;
  const q=async(sql:string,args:unknown[]=[]) => (await(await getPool())!.execute<any>(sql,args))[0];
  beforeEach(async()=>{own=await createDisposableMerchant('salla-complete');other=await createDisposableMerchant('salla-foreign');});
  afterEach(async()=>{vi.restoreAllMocks();await cleanupDisposableMerchants([own.userId,other.userId]);});afterAll(closeDb);
  const read=()=>readSallaWorkspace(own.userId,own.merchantId),logs=(input:unknown={})=>readSallaLogsWorkspace(own.userId,own.merchantId,input);
  const connect=async(id=own.merchantId,storeId=String(own.merchantId))=>q("INSERT INTO salla_connections(merchantId,salla_store_id,storeUrl,accessToken,syncStatus) VALUES (?,?,'https://sample.example.test/?SECRET','PRIVATE','active')",[id,storeId]);
  const log=async(merchantId=own.merchantId,state='success',kind='full_sync',count=3)=>q('INSERT INTO sync_logs(merchantId,status,syncType,itemsSynced,errors) VALUES (?,?,?,?,?)',[merchantId,state,kind,count,'PRIVATE']);
  it('preserves complete retained data while unlinked and excludes another tenant',async()=>{await connect(other.merchantId,String(other.merchantId));await log();await log(other.merchantId);const result=await read();expect(result).toMatchObject({present:false,state:'unlinked',storeId:null,counts:{catalog:0,linkedProducts:0,syncLogs:1}});expect(JSON.stringify(result)).not.toContain('PRIVATE');});
  it.each(['active','syncing','paused','error'])('represents stored %s honestly and never decrypts display reads',async state=>{await connect();await q('UPDATE salla_connections SET syncStatus=? WHERE merchantId=?',[state,own.merchantId]);const result=await read();expect(result).toMatchObject({present:true,state:state==='active'?'configured':state,storeId:String(own.merchantId),credentialsStored:true,storeUrl:'https://sample.example.test/'});expect(JSON.stringify(result)).not.toMatch(/SECRET|PRIVATE/);});
  it('separates legacy identity from a stored credential and fences replacement tokens',async()=>{await connect();const initial=await read();await q("UPDATE salla_connections SET syncStatus='paused',lastSyncAt=UTC_TIMESTAMP() WHERE merchantId=?",[own.merchantId]);expect((await read()).revision).toBe(initial.revision);await q("UPDATE salla_connections SET accessToken='CHANGED',salla_store_id=NULL WHERE merchantId=?",[own.merchantId]);expect(await read()).toMatchObject({storeId:null,credentialsStored:true});expect((await read()).revision).not.toBe(initial.revision);});
  it('counts and traverses more than500 logs with independent kind, state and literal reference search',async()=>{const rows=Array.from({length:503},(_,i)=>[own.merchantId,i%2?'failed':'success',i%3?'stock_sync':'full_sync',i]);await q('INSERT INTO sync_logs(merchantId,status,syncType,itemsSynced) VALUES '+rows.map(()=>'(?,?,?,?)').join(','),rows.flat());await log(other.merchantId);const first=await logs(),last=await logs({page:21});expect(first.summary.stored).toBe(503);expect(first.rows).toHaveLength(25);expect(last.rows).toHaveLength(3);expect(last.rows[2].itemsSynced).toBe(0);expect((await logs({state:'failed'})).pagination.total).toBe(251);const filtered=await logs({kind:'full_sync',state:'failed'});expect(filtered.rows.every(row=>row.kind==='full_sync'&&row.state==='failed')).toBe(true);const matched=await logs({search:String(first.rows[0].id)});expect(matched.rows.some(row=>row.id===first.rows[0].id)).toBe(true);expect((await logs({search:'%_!'})).pagination.total).toBe(0);expect((await read()).counts.syncLogs).toBe(503);});
  it('keeps invalid legacy counts visible without inventing zero and retains archived connection history',async()=>{await connect();await log(own.merchantId,'failed','full_sync',-1);const result=await logs();expect(result.rows[0]).toMatchObject({itemsSynced:null,invalidData:true,hasErrors:true});await q('DELETE FROM salla_connections WHERE merchantId=?',[own.merchantId]);expect((await logs()).summary.stored).toBe(1);expect((await read()).counts.syncLogs).toBe(1);});
  it('counts only current-store product projections and hides source secrets',async()=>{
    const inserted=await connect();await q("INSERT INTO products(merchantId,name,sallaProductId,price) VALUES (?,'Local','local-item',0)",[own.merchantId]);
    for(const [storeId,externalId,archived] of [[String(own.merchantId),'101',0],[String(own.merchantId)+'9','102',0],[String(own.merchantId),'103',1]] as const){
      const product=await q("INSERT INTO products(merchantId,name,sallaProductId,price) VALUES (?,'Sample',?,0)",[own.merchantId,`salla:${storeId}:${externalId}`]);
      await q('INSERT INTO salla_product_projections(merchant_id,store_id,external_product_id,local_product_id,connection_id,read_revision,archived,observed_at) VALUES (?,?,?,?,?,1,?,UTC_TIMESTAMP(3))',[own.merchantId,storeId,externalId,product.insertId,inserted.insertId,archived]);
    }
    await log();expect((await read()).counts).toMatchObject({catalog:2,linkedProducts:1,syncLogs:1});
    await q("UPDATE salla_connections SET syncStatus='paused' WHERE merchantId=?",[own.merchantId]);expect((await read()).counts).toMatchObject({catalog:1,linkedProducts:1});
  });
  it('separates recent completed webhook evidence from all outstanding work and other tenants',async()=>{
    for(const [i,status,age,merchantId] of [[1,'completed',0,own.merchantId],[2,'pending',9,own.merchantId],[3,'manual_review',0,own.merchantId],[4,'failed',0,other.merchantId]] as const)
      await q("INSERT INTO salla_webhook_receipts(merchant_id,salla_store_id,event_key,event_type,resource_id,status,effect_applied,created_at) VALUES (?,? ,?,'product.updated',?, ?,?,DATE_SUB(UTC_TIMESTAMP(3),INTERVAL ? DAY))",[merchantId,String(merchantId),`phase298-${merchantId}-${i}`,String(i),status,status==='completed'?1:0,age]);
    const result=await read();expect(result.webhooks).toMatchObject({recentTotal:2,recentCompleted:1,awaiting:1,manualReview:1});expect(result.webhooks.oldestPendingSeconds).toBeGreaterThanOrEqual(9*86400-2);
  });
  it('keeps summary and page in one repeatable snapshot during a concurrent insert',async()=>{await log();const pool=(await getPool())!,get=pool.getConnection.bind(pool);let intercepted=false;vi.spyOn(pool,'getConnection').mockImplementation(async()=>{const connection=await get(),execute=connection.execute.bind(connection);vi.spyOn(connection,'execute').mockImplementation(async(sql:any,args:any)=>{const value=await execute(sql,args);if(!intercepted&&String(sql).startsWith('SELECT COUNT(*) AS count FROM sync_logs')){intercepted=true;await log();}return value;});return connection;});const result=await logs();expect(result.summary.stored).toBe(1);expect(result.rows).toHaveLength(1);expect((await q('SELECT COUNT(*) AS n FROM sync_logs WHERE merchantId=?',[own.merchantId]))[0].n).toBe(2);});
});
