import {beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({access:vi.fn(),db:vi.fn(),workspace:vi.fn(),logs:vi.fn(),completeLogs:vi.fn(),register:vi.fn(),disconnect:vi.fn(),connection:vi.fn(),full:vi.fn(),stock:vi.fn(),ctor:vi.fn()}));
vi.mock('./accounts/merchant-access',()=>({resolveMerchantAccess:m.access}));
vi.mock('./db',async original=>({...await original<typeof import('./db')>(),getDb:m.db,getSallaConnectionByMerchantId:m.connection}));
vi.mock('./integrations/salla-dashboard-read',()=>({readSallaDashboardLogs:m.logs}));
vi.mock('./integrations/salla-workspace',()=>({readSallaWorkspace:m.workspace,readSallaLogsWorkspace:m.completeLogs}));
vi.mock('./integrations/salla-connection',async original=>({...await original<typeof import('./integrations/salla-connection')>(),registerSallaConnection:m.register,disconnectSallaConnection:m.disconnect}));
vi.mock('./integrations/salla',()=>({SallaIntegration:class{constructor(...args:unknown[]){m.ctor(...args);}fullSync=m.full;syncStock=m.stock;}}));
import {router} from './_core/trpc';
import {sallaDashboardProcedures} from './routers-salla-dashboard';
import {appRouter} from './routers';
import {SallaConnectionFault} from './integrations/salla-connection';
const local=router(sallaDashboardProcedures),names=['workspace','logsWorkspace','getConnection','getSyncLogs','registerConnection','connect','disconnect','syncNow'] as const,revision='a'.repeat(64),registration={revision,accessToken:'synthetic-token'};
let selected=20;
beforeEach(()=>{vi.resetAllMocks();selected++;m.db.mockResolvedValue({});m.access.mockResolvedValue({merchantId:selected,role:'owner'});m.workspace.mockResolvedValue({actorId:7,merchantId:selected,revision,present:true,state:'configured',storeUrl:'https://sample.example.test/',lastSyncAt:null,webhooks:{awaiting:0}});m.logs.mockResolvedValue([]);m.completeLogs.mockResolvedValue({rows:[]});m.register.mockResolvedValue({registered:true,revision});m.disconnect.mockResolvedValue({actorId:7,merchantId:selected,disconnected:true});m.connection.mockResolvedValue({accessToken:'stored-token'});m.full.mockResolvedValue({success:true,synced:3});m.stock.mockResolvedValue({success:true,updated:2});});
for(const mounted of [false,true]){
  const api=(user:any={id:7,role:'user'})=>{const ctx={user,merchantId:999,merchantRole:'owner',req:{headers:{'x-merchant-id':String(selected)}},res:{}} as any;return mounted?appRouter.createCaller(ctx).salla:local.createCaller(ctx);};
  const call=(name:typeof names[number],caller=api())=>(caller[name] as any)(name==='registerConnection'?registration:name==='connect'?{...registration,storeUrl:'https://display.example.test'}:name==='disconnect'?{revision}:name==='syncNow'?{syncType:'stock',revision}:name==='logsWorkspace'?{}:undefined);
  it.each(['owner','manager'])(`uses the selected %s scope and passes reviewed versions (${mounted})`,async role=>{m.access.mockResolvedValue({merchantId:selected,role});for(const name of names)await call(name);expect(m.access).toHaveBeenCalledWith(7,selected);expect(m.workspace).toHaveBeenCalledWith(7,selected);expect(m.completeLogs).toHaveBeenCalledWith(7,selected,{search:'',state:'all',kind:'all',page:1});expect(m.logs).toHaveBeenCalledWith(selected);expect(m.register).toHaveBeenCalledWith(7,selected,registration);expect(m.disconnect).toHaveBeenCalledWith(7,selected,{revision});expect(m.ctor.mock.calls.every(call=>call[0]===selected)).toBe(true);});
  it.each(names)(`rejects missing, revoked or insufficient permission for %s (${mounted})`,async name=>{await expect(call(name,api(null))).rejects.toMatchObject({code:'UNAUTHORIZED'});for(const access of [null,{merchantId:selected,role:'viewer'},{merchantId:selected,role:'sales_supervisor'}]){m.access.mockResolvedValue(access);await expect(call(name)).rejects.toMatchObject({code:'FORBIDDEN'});}expect(m.db).not.toHaveBeenCalled();expect(m.ctor).not.toHaveBeenCalled();});
  it.each(names)(`fails closed when storage is missing or throws a private error for %s (${mounted})`,async name=>{m.db.mockResolvedValue(null);await expect(call(name)).rejects.toMatchObject({code:'INTERNAL_SERVER_ERROR'});m.db.mockRejectedValue(Error('PRIVATE token=secret'));await expect(call(name)).rejects.toMatchObject({message:'تعذر تأكيد بيانات سلة. حدّث حالة الربط قبل إعادة المحاولة.'});expect(m.register).not.toHaveBeenCalled();expect(m.disconnect).not.toHaveBeenCalled();});
  it.each(['forbidden','changed','conflict','missing','credentials','unavailable'] as const)(`maps safe lifecycle fault %s and redacts unexpected dependency errors (${mounted})`,async reason=>{m.register.mockRejectedValue(new SallaConnectionFault(reason));await expect(api().registerConnection(registration)).rejects.toMatchObject({message:'salla_connection:'+reason});m.disconnect.mockRejectedValue(Error('PRIVATE SQL'));await expect(api().disconnect({revision})).rejects.toMatchObject({message:'تعذر تأكيد بيانات سلة. حدّث حالة الربط قبل إعادة المحاولة.'});});
  it(`rejects missing versions, extra tenants and credential misuse (${mounted})`,async()=>{for(const input of [{},{revision:'invalid'},{revision,merchantId:999}])await expect(api().disconnect(input as any)).rejects.toMatchObject({code:'BAD_REQUEST'});for(const accessToken of ['A'.repeat(8193),'enc:v1:opaque','token\nprivate'])await expect(api().registerConnection({...registration,accessToken})).rejects.toMatchObject({code:'BAD_REQUEST'});await expect(api().connect({...registration,storeUrl:'https://user:secret@example.test'})).rejects.toMatchObject({code:'BAD_REQUEST'});await expect(api().logsWorkspace({merchantId:999} as any)).rejects.toMatchObject({code:'BAD_REQUEST'});expect(m.register).not.toHaveBeenCalled();});
  it(`keeps the legacy initial sync after a confirmed save while the reviewed endpoint only saves (${mounted})`,async()=>{await api().registerConnection(registration);expect(m.full).not.toHaveBeenCalled();await call('connect');expect(m.full).toHaveBeenCalledOnce();m.full.mockClear();m.register.mockRejectedValue(new SallaConnectionFault('changed'));await expect(call('connect')).rejects.toBeTruthy();expect(m.full).not.toHaveBeenCalled();});
  it(`exposes the current revision for the transitional UI and requires successful sync results (${mounted})`,async()=>{expect(await api().getConnection()).toMatchObject({connected:true,revision,syncStatus:'active'});expect(await api().syncNow({syncType:'full',revision})).toMatchObject({success:true});m.full.mockResolvedValue({success:false,synced:3});m.stock.mockResolvedValue({success:false,updated:2});for(const syncType of ['full','stock'] as const)await expect(api().syncNow({syncType,revision})).rejects.toMatchObject({code:'INTERNAL_SERVER_ERROR'});m.connection.mockResolvedValue(undefined);await expect(api().syncNow({syncType:'stock',revision})).rejects.toMatchObject({code:'NOT_FOUND'});});
  it(`requires a reviewed sync and attaches an ongoing guard to manual and initial sync (${mounted})`,async()=>{for(const input of [{syncType:'full'},{syncType:'full',revision:'bad'},{syncType:'full',revision,merchantId:999}])await expect(api().syncNow(input as any)).rejects.toMatchObject({code:'BAD_REQUEST'});expect(m.ctor).not.toHaveBeenCalled();await api().syncNow({revision,syncType:'stock'});await call('connect');expect(m.ctor.mock.calls).toHaveLength(2);for(const args of m.ctor.mock.calls){expect(args[0]).toBe(selected);expect(args[2]).toBeTypeOf('function');}});
}
