import { beforeEach, expect, it, vi } from 'vitest';
const m = vi.hoisted(() => ({ access: vi.fn(), db: vi.fn(), status: vi.fn(), logs: vi.fn(), connection: vi.fn(), create: vi.fn(), update: vi.fn(), remove: vi.fn(), platforms: vi.fn(), test: vi.fn(), full: vi.fn(), stock: vi.fn(), ctor: vi.fn() }));
vi.mock('./accounts/merchant-access', () => ({ resolveMerchantAccess: m.access }));
vi.mock('./db', async original => ({ ...await original<typeof import('./db')>(), getDb: m.db, getSallaConnectionByMerchantId: m.connection, createSallaConnection: m.create, updateSallaConnection: m.update, deleteSallaConnection: m.remove }));
vi.mock('./integrations/salla-dashboard-read', () => ({ readSallaDashboardStatus: m.status, readSallaDashboardLogs: m.logs }));
vi.mock('./integrations/platform-checker', () => ({ checkExistingIntegrations: m.platforms }));
vi.mock('./integrations/salla', () => ({ SallaIntegration: class { constructor(...args: unknown[]) { m.ctor(...args); } testConnection = m.test; fullSync = m.full; syncStock = m.stock; } }));
import { router } from './_core/trpc';
import { sallaDashboardProcedures } from './routers-salla-dashboard';
import { appRouter } from './routers';
const local = router(sallaDashboardProcedures), names = ['getConnection','getSyncLogs','connect','disconnect','syncNow'] as const;
let selected = 20;
const connect = { storeUrl: 'https://display.example.test', accessToken: 'fake-example-token' };
beforeEach(() => { vi.resetAllMocks(); selected++; m.db.mockResolvedValue({}); m.access.mockResolvedValue({ merchantId: selected, role: 'owner' }); m.status.mockResolvedValue({ connected: true, storeUrl: 'https://verified.example.test' }); m.logs.mockResolvedValue([]); m.connection.mockResolvedValue({ merchantId: selected, accessToken: 'saved-example-token' }); m.create.mockResolvedValue({ merchantId: selected }); m.platforms.mockResolvedValue([]); m.test.mockResolvedValue({ success: true, storeInfo: { id: '12001', domain: 'https://verified.example.test' } }); m.full.mockResolvedValue({ success: true, synced: 3 }); m.stock.mockResolvedValue({ success: true, updated: 2 }); });
for (const mounted of [false,true]) {
  const api = (user: any = { id: 7, role: 'user' }) => { const ctx = { user, merchantId: 999, merchantRole: 'owner', req: { headers: { 'x-merchant-id': String(selected) } }, res: {} } as any; return mounted ? appRouter.createCaller(ctx).salla : local.createCaller(ctx); };
  const call = (name: typeof names[number], caller = api()) => (caller[name] as any)(name === 'connect' ? connect : name === 'syncNow' ? { syncType: 'stock' } : undefined);
  it.each(['owner','manager'])(`uses selected member scope for every %s action (${mounted})`, async role => { m.access.mockResolvedValue({ merchantId: selected, role }); for (const name of names) await call(name); expect(m.access).toHaveBeenCalledWith(7,selected); expect(m.status).toHaveBeenCalledWith(selected); expect(m.logs).toHaveBeenCalledWith(selected); expect(m.remove).toHaveBeenCalledWith(selected); expect(m.ctor.mock.calls.every(call => call[0] === selected)).toBe(true); expect(m.update).toHaveBeenCalledWith(selected,expect.objectContaining({sallaStoreId:'12001',storeUrl:'https://verified.example.test'})); });
  it.each(names)(`denies anonymous, revoked and non-manager access to ${mounted} %s before dependencies`, async name => { await expect(call(name,api(null))).rejects.toMatchObject({code:'UNAUTHORIZED'}); m.access.mockResolvedValue(null); await expect(call(name)).rejects.toMatchObject({code:'FORBIDDEN'}); for (const role of ['viewer','sales_supervisor','support_agent']) { m.access.mockResolvedValue({merchantId:selected,role}); await expect(call(name)).rejects.toMatchObject({code:'FORBIDDEN'}); } expect(m.db).not.toHaveBeenCalled(); expect(m.ctor).not.toHaveBeenCalled(); });
  it.each(names)(`does not turn unavailable storage into success or empty data for ${mounted} %s`, async name => { m.db.mockResolvedValue(null); await expect(call(name)).rejects.toMatchObject({code:'INTERNAL_SERVER_ERROR'}); expect(m.status).not.toHaveBeenCalled(); expect(m.remove).not.toHaveBeenCalled(); expect(m.ctor).not.toHaveBeenCalled(); });
  it.each(names)(`redacts unexpected and forged errors for ${mounted} %s`, async name => { const bad = Error('PRIVATE_SQL token=secret'); for (const dependency of [m.status,m.logs,m.platforms,m.connection,m.remove]) dependency.mockRejectedValue(bad); await expect(call(name)).rejects.toMatchObject({code:'INTERNAL_SERVER_ERROR',message:'تعذر تأكيد بيانات سلة. حدّث حالة الربط قبل إعادة المحاولة.'}); });
  it(`rejects extra scopes and malformed credentials (${mounted})`, async () => { for (const extra of [{ merchantId:999 },{ actorId:999 }]) await expect(api().connect({...connect,...extra} as any)).rejects.toMatchObject({code:'BAD_REQUEST'}); for (const storeUrl of ['javascript:alert(1)','https://user:secret@example.test']) await expect(api().connect({...connect,storeUrl})).rejects.toMatchObject({code:'BAD_REQUEST'}); await expect(api().connect({...connect,accessToken:'A'.repeat(8193)})).rejects.toMatchObject({code:'BAD_REQUEST'}); await expect(api().syncNow({syncType:'stock',merchantId:999} as any)).rejects.toMatchObject({code:'BAD_REQUEST'}); expect(m.ctor).not.toHaveBeenCalled(); });
  it(`rejects occupied slots, unverified identity and duplicate stores without raw errors (${mounted})`, async () => { m.platforms.mockResolvedValue([{name:'PRIVATE'}]); await expect(api().connect(connect)).rejects.toMatchObject({code:'CONFLICT'}); expect(m.test).not.toHaveBeenCalled(); m.platforms.mockResolvedValue([]); m.test.mockResolvedValue({success:false}); await expect(api().connect(connect)).rejects.toMatchObject({code:'BAD_REQUEST'}); m.test.mockResolvedValue({success:true,storeInfo:{id:'12001',domain:'https://verified.example.test'}}); m.update.mockRejectedValue(Object.assign(Error('PRIVATE'),{code:'ER_DUP_ENTRY'})); await expect(api().connect(connect)).rejects.toMatchObject({code:'CONFLICT',message:'متجر سلة هذا مرتبط بحساب تاجر آخر.'}); expect(m.full).not.toHaveBeenCalled(); });
  it(`confirms an actual saved creation before starting initial sync (${mounted})`, async () => { m.connection.mockResolvedValue(undefined); m.create.mockResolvedValue(undefined); await expect(api().connect(connect)).rejects.toMatchObject({code:'INTERNAL_SERVER_ERROR'}); expect(m.full).not.toHaveBeenCalled(); });
  it(`requires explicit successful catalog outcomes and keeps scope for full and stock (${mounted})`, async () => { expect(await api().syncNow({syncType:'full'})).toMatchObject({success:true}); expect(await api().syncNow({syncType:'stock'})).toMatchObject({success:true}); m.full.mockResolvedValue({success:false,synced:3}); m.stock.mockResolvedValue({success:false,updated:2}); for (const syncType of ['full','stock'] as const) await expect(api().syncNow({syncType})).rejects.toMatchObject({code:'INTERNAL_SERVER_ERROR'}); m.connection.mockResolvedValue(undefined); await expect(api().syncNow({syncType:'stock'})).rejects.toMatchObject({code:'NOT_FOUND'}); });
}
