// @vitest-environment jsdom
import React, { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { Router } from 'wouter';
import { memoryLocation } from 'wouter/memory-location';
import { beforeEach, afterEach, expect, it, vi } from 'vitest';
import { scheduledWorkspaceEn as en, scheduledWorkspaceAr as ar } from '../client/src/locales/scheduled-workspace';
import { projectScheduledMessage } from './scheduled-message-workspace';
import { scheduledDefinitionFields, scheduledMessagePreview } from '../shared/scheduled-message-policy';
const m = vi.hoisted(() => ({ actor: 7, merchant: 20, language: 'en', source: [] as any[], override: {} as any, selection: {} as any, error: null as any, fetching: false, manage: true, refresh: vi.fn(), review: vi.fn(), apply: vi.fn(), receipt: vi.fn(), resolve: vi.fn(), historyOverride: {} as any }));
vi.mock('@/lib/trpc', () => ({ trpc: { auth: { me: { useQuery: () => ({ data: { id: m.actor } }) } }, merchants: { workspaceIdentity: { useQuery: () => ({ data: { id: m.merchant, actorId:m.actor } }) } }, useUtils: () => ({ scheduledMessages: { actionReceipt: { fetch: m.receipt } } }), scheduledMessages: {
  workspace: { useQuery: (selection: any) => { m.selection = selection; return { data: snapshot(), error: m.error, isFetching: m.fetching, refetch: m.refresh }; } },
  history: { useQuery: (selection: any) => ({ data: { actorId: m.actor, merchantId: m.merchant, selection, checkedAt: new Date().toISOString(), total: 0, pages: 0, currentPage: 1, pageSize: 25, rows: [], ...m.historyOverride }, refetch: m.refresh }) },
  reviewAction: { useMutation: () => ({ mutateAsync: m.review }) }, applyAction: { useMutation: () => ({ mutateAsync: m.apply }) }, resolveActionReceipt: { useMutation: () => ({ mutateAsync: m.resolve }) },
} } }));
vi.mock('react-i18next', () => ({ useTranslation: () => ({ i18n: { language: m.language }, t: (key: string) => (m.language === 'ar' ? ar : en)[key.split('.').pop() as keyof typeof en] ?? key }) }));
import Page from '../client/src/pages/merchant/ScheduledMessages';
const raw = (id = 30) => ({ id, merchant_id: 20, title: 'Weekly sample', message: 'Literal message', day_of_week: 4, time: '10:00', is_active: 1, last_sent_at: '2026-10-01 09:00:00', created_at: '2026-10-01 09:00:00', updated_at: '2026-10-01 09:00:00' });
function snapshot() {
  const s = m.selection, filtered = m.source.filter(r => (!s.query || r.title.includes(s.query) || r.message.includes(s.query)) && (s.day === null || r.day_of_week === s.day) && (s.state === 'all' || (r.is_active ? 'enabled' : 'disabled') === s.state));
  const pages = Math.ceil(filtered.length / 25), currentPage = Math.min(s.page, Math.max(1, pages));
  return { actorId: m.actor, merchantId: m.merchant, checkedAt: new Date().toISOString(), canManage: m.manage, selection: s, pageSize: 25, currentPage, pages, total: m.source.length, matched: filtered.length,
    counts: { enabled: m.source.filter(r => r.is_active === 1).length, disabled: m.source.filter(r => r.is_active === 0).length, unknown: 0 }, definitionsWithRecordedTimestamp: m.source.length, timezone: 'UTC', timeBasis: 'explicit_activation_review', deliveryEvidence: 'scoped_provider_receipts', audienceEvidence: 'rechecked_at_dispatch', channelEvidence: 'reviewed_primary', salesAttribution: 'not_verified',
    rows: filtered.slice((currentPage - 1) * 25, currentPage * 25).map(r => ({ ...projectScheduledMessage(r), authorization: { state: 'recorded', actorId: 7, reviewedAt: '2026-10-01T09:00:00Z', timezone: 'UTC', instanceId: 1, firstDueAt: '2026-10-08T10:00:00Z' }, nextDueAt: null, nextIssue: null, occurrenceCount: 0, latestOccurrence: null })), ...m.override };
}
function review(target: any) {
  const before = target.action === 'create' ? null : projectScheduledMessage(m.source.find(r => r.id === target.id));
  const proposed = ['create', 'update'].includes(target.action) ? target.data : target.action === 'toggle' && target.enabled ? scheduledDefinitionFields.parse({ title: before!.title, message: before!.message, dayOfWeek: before!.dayOfWeek, time: before!.time, timezone: 'UTC' }) : null;
  return { actorId: m.actor, merchantId: m.merchant, target, reviewRevision: 'a'.repeat(64), checkedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 300000).toISOString(), before, proposed,
    effect: target.action === 'create' ? 'create_paused' : target.action === 'update' ? 'update_paused' : target.action === 'toggle' ? target.enabled ? 'enable' : 'disable' : 'delete',
    nextDueAt: target.enabled ? new Date(Date.now() + 86400000).toISOString() : null, instanceId: target.enabled ? 1 : null, channelPhone: null, messagePreview: proposed ? scheduledMessagePreview(proposed) : null,
    repeat: 'weekly_until_paused', audience: 'current_consented_conversations', audienceLimit: 2000, admissionMinutes: 15, deliveryMinutes: 1440, sendsImmediately: false, deliveryGuaranteed: false, salesVerified: false, retainsDeliveryHistory: true };
}
const result = (value: any) => ({ requestKey: value.requestKey, actorId: 7, merchantId: 20, id: value.target.action === 'create' ? 31 : value.target.id, action: value.target.action,
  enabled: value.target.action === 'delete' ? null : value.target.action === 'toggle' ? value.target.enabled : false, authorizationId: value.target.enabled ? 1 : null, nextDueAt: value.target.enabled ? new Date(Date.now() + 86400000).toISOString() : null, savedAt: new Date().toISOString() });
let root: Root, container: HTMLDivElement, memory: ReturnType<typeof memoryLocation>;
const render = () => act(async () => { root.render(<Router hook={memory.hook} searchHook={memory.searchHook}><Page /></Router>); });
const button = (text: string) => Array.from(document.querySelectorAll<HTMLButtonElement>('button')).find(n => n.textContent?.trim().startsWith(text))!;
const click = (text: string) => act(async () => { expect(button(text)).toBeTruthy(); button(text).click(); });
const fill = (id: string, value: string) => act(async () => { const el = document.getElementById(id) as HTMLInputElement; Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')!.set!.call(el, value); el.dispatchEvent(new Event('input', { bubbles: true })); });
beforeEach(() => { Object.assign(globalThis, { React, IS_REACT_ACT_ENVIRONMENT: true }); vi.resetAllMocks(); sessionStorage.clear(); Object.assign(m, { actor: 7, merchant: 20, language: 'en', manage: true, error: null, fetching: false, override: {}, historyOverride: {}, source: [raw()] }); m.refresh.mockImplementation(async () => ({ data: snapshot() })); m.review.mockImplementation(async target => review(target)); m.apply.mockImplementation(async value => result(value)); m.receipt.mockResolvedValue({ state: 'missing', result: null }); memory = memoryLocation({ path: '/merchant/scheduled-messages', record: true }); container = document.createElement('div'); document.body.append(container); root = createRoot(container); });
afterEach(async () => { await act(async () => root.unmount()); container.remove(); vi.restoreAllMocks(); });
it.each(['ar', 'en'])('renders the actual page, old-time caveat and history in %s', async language => { m.language = language; const c = language === 'ar' ? ar : en; m.source[0].message = '<img src=x onerror=alert(1)>'; await render(); expect(container.textContent).not.toContain('merchantUx.'); await click(c.details); expect(document.body.textContent).toContain(c.legacyHelp); expect(document.body.textContent).toContain(c.noHistory); expect(document.body.textContent).toContain('<img src=x onerror=alert(1)>'); expect(document.querySelector('img')).toBeNull(); expect(document.activeElement?.textContent).toBe(c.details); });
it('shows field-specific errors and focuses the first invalid input', async () => { await render(); await click(en.create); await click(en.review); expect(document.getElementById('sm-title')?.getAttribute('aria-invalid')).toBe('true'); expect(document.getElementById('sm-message')?.getAttribute('aria-invalid')).toBe('true'); expect(document.activeElement?.id).toBe('sm-title'); expect(m.review).not.toHaveBeenCalled(); });
it('reviews edited fields and saves paused with the persisted request reference', async () => { await render(); await click(en.edit); await fill('sm-title', 'Changed title'); await click(en.review); expect(m.review).toHaveBeenCalledWith({ action: 'update', id: 30, data: { title: 'Changed title', message: 'Literal message', dayOfWeek: 4, time: '10:00', timezone: 'UTC' } }); expect(document.body.textContent).toContain(en.updateEffect); expect(m.apply).not.toHaveBeenCalled(); await click(en.confirm); expect(m.apply.mock.calls[0][0].requestKey).toMatch(/^[a-f0-9-]{36}$/); expect(container.textContent).toContain(en.saved); expect(sessionStorage.length).toBe(0); });
it('reviews activation with its audience and time window before any write', async () => { m.source[0].is_active = 0; await render(); await click(en.enable); expect(document.body.textContent).toContain(en.audience); expect(document.body.textContent).toContain(en.window); expect(document.body.textContent).toContain(en.noGuarantee); expect(m.apply).not.toHaveBeenCalled(); await click(en.confirm); expect(m.apply.mock.calls[0][0].target).toEqual({ action: 'toggle', id: 30, enabled: true }); });
it('keeps deletion in details and requires a separate reviewed confirmation', async () => { await render(); expect(button(en.remove)).toBeUndefined(); await click(en.details); await click(en.remove); expect(document.body.textContent).toContain(en.deleteEffect); expect(m.apply).not.toHaveBeenCalled(); await click(en.confirm); expect(m.apply.mock.calls[0][0].target).toEqual({ action: 'delete', id: 30 }); });
it.each(['actor', 'merchant', 'target', 'shape'])('refuses mismatched %s reviews', async mode => { m.review.mockImplementation(async target => { const r = review(target); if (mode === 'actor') r.actorId++; if (mode === 'merchant') r.merchantId++; if (mode === 'target') r.target = { ...target, id: 31 }; return mode === 'shape' ? {} : r; }); await render(); await click(en.disable); expect(button(en.confirm).disabled).toBe(true); expect(m.apply).not.toHaveBeenCalled(); });
it('keeps uncertain saves fenced and recovers the same request without sending another write', async () => { m.apply.mockRejectedValue(Error('PRIVATE SQL')); await render(); await click(en.disable); await click(en.confirm); const value = m.apply.mock.calls[0][0]; expect(document.body.textContent).toContain(en.pending); expect(document.body.textContent).not.toContain('PRIVATE SQL'); expect(sessionStorage.getItem('sari.weekly.request.v1:7:20')).toBe(value.requestKey); expect(button(en.confirm)).toBeUndefined(); m.receipt.mockResolvedValue({ state: 'saved', result: result(value) }); await click(en.recover); expect(m.apply).toHaveBeenCalledOnce(); expect(container.textContent).toContain(en.saved); expect(sessionStorage.length).toBe(0); });
it('does not write when browser request storage is unavailable', async () => { await render(); await click(en.disable); vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw Error('No storage'); }); await click(en.confirm); expect(document.body.textContent).toContain(en.storageError); expect(m.apply).not.toHaveBeenCalled(); });
it('distinguishes absent receipts from cancellation and checks cancellation identity', async () => { const key = '23e7d06e-a668-41ac-8327-f920a7d7c662'; sessionStorage.setItem('sari.weekly.request.v1:7:20', key); await render(); await click(en.recover); expect(container.textContent).toContain(en.missingReceipt); expect(button(en.create).disabled).toBe(true); const cancel = { state: 'cancelled', requestKey: key, actorId: 7, merchantId: 21, cancelledAt: new Date().toISOString() }; m.resolve.mockResolvedValue({ state: 'cancelled', result: cancel }); await click(en.resolve); expect(sessionStorage.length).toBe(1); m.resolve.mockResolvedValue({ state: 'cancelled', result: { ...cancel, merchantId: 20 } }); await click(en.resolve); expect(sessionStorage.length).toBe(0); expect(container.textContent).toContain(en.cancelledRequest); expect(m.apply).not.toHaveBeenCalled(); });
it('discards old reviews after filter changes and hides stale rows after source failure', async () => { let finish!: (v: any) => void; m.review.mockImplementation(() => new Promise(r => finish = r)); await render(); await click(en.disable); const old = review({ action: 'toggle', id: 30, enabled: false }); await act(async () => memory.navigate('/merchant/scheduled-messages?day=0')); await act(async () => finish(old)); expect(document.querySelector('[role=dialog]')).toBeNull(); m.error = Error('PRIVATE'); await render(); expect(container.querySelector('.sm-card')).toBeNull(); expect(container.textContent).not.toContain('PRIVATE'); });
it('shows complete page navigation and read-only details without write controls', async () => { m.source = Array.from({ length: 31 }, (_, i) => raw(i + 1)); m.manage = false; await render(); expect(container.querySelectorAll('.sm-card')).toHaveLength(25); await click(en.next); expect(container.querySelectorAll('.sm-card')).toHaveLength(6); expect(button(en.create)).toBeUndefined(); expect(button(en.edit)).toBeUndefined(); await click(en.details); expect(button(en.remove)).toBeUndefined(); });
it('rejects a history response from another tenant', async () => { m.historyOverride = { merchantId: 21 }; await render(); await click(en.details); expect(document.body.textContent).not.toContain(en.noHistory); expect(document.querySelector('.sm-history [data-state=error]')).not.toBeNull(); });
it('locks repeated confirmation until its one request settles', async () => {
  let finish!: (v: any) => void; m.apply.mockImplementation(() => new Promise(r => finish = r));
  await render(); await click(en.disable);
  await act(async () => { const confirm = button(en.confirm); confirm.click(); confirm.click(); });
  expect(m.apply).toHaveBeenCalledOnce(); const value = m.apply.mock.calls[0][0];
  expect(sessionStorage.getItem('sari.weekly.request.v1:7:20')).toBe(value.requestKey);
  await act(async () => finish(result(value))); expect(container.textContent).toContain(en.saved);
});
it('keeps an unresolved request with its original tenant after a tenant switch', async () => {
  let finish!: (v: any) => void; m.apply.mockImplementation(() => new Promise(r => finish = r));
  await render(); await click(en.disable); await click(en.confirm); const value = m.apply.mock.calls[0][0];
  m.merchant = 21; await render(); await act(async () => finish(result(value)));
  expect(container.textContent).not.toContain(en.saved); expect(container.textContent).not.toContain(en.pending);
  expect(sessionStorage.getItem('sari.weekly.request.v1:7:20')).toBe(value.requestKey);
  m.merchant = 20; await render(); expect(container.textContent).toContain(en.pending);
  m.receipt.mockResolvedValue({ state: 'saved', result: result(value) }); await click(en.recover);
  expect(m.apply).toHaveBeenCalledOnce(); expect(sessionStorage.length).toBe(0);
});
