import {readFileSync} from 'node:fs';import {describe,it,expect} from 'vitest';
import {ServicePreviewModel,serviceModes,serviceQueries,serviceMutations} from '../prototypes/tenant-dashboard/src/service-preview-model';
import {servicePreviewHref,previewNavigation,validServicePath} from '../prototypes/tenant-dashboard/src/service-preview-router';
const read=(m:ServicePreviewModel,name:string,input?:any)=>{const result=m.read('services.'+name,input);expect(result.error).toBeNull();return result.data;};
const draft={name:'New service',priceType:'fixed',basePrice:0,durationMinutes:30};
describe('actual service preview',()=>{
 it('covers all actual route query and mutation contracts',()=>{
  const routes=JSON.parse(readFileSync('docs/audits/tenant-features-2026-09-30/coverage.json','utf8')).routes.filter((r:any)=>/^\/merchant\/(?:services(?:\/|$)|order-notifications$|reviews$|booking-reviews$|scheduled-messages$|media-library$|promotions$|discounts$|referrals$|abandoned-carts$|occasion-campaigns$|service-categories$|service-packages$|staff$|bookings$|integrations\/(?:byaan|zid|calendly)$|zid\/(?:settings|products|sync-logs|callback)$|woocommerce\/(?:settings|products|orders|analytics)$|byaan-dashboard$|salla$|platform-integrations$|calendar(?:\/settings)?$)/.test(r.route));
  expect(routes).toHaveLength(34);expect([...new Set(routes.flatMap((r:any)=>r.queries))].sort()).toEqual([...serviceQueries].sort());expect([...new Set(routes.flatMap((r:any)=>r.mutations))].sort()).toEqual([...serviceMutations].sort());
 });
 it.each(serviceModes)('provides scoped %s scenarios for both tenants',mode=>{for(const id of [269,270]){const m=new ServicePreviewModel(id,mode);expect(m.read('auth.me').data?.id??null).toBe(mode==='session'?null:id+1000);expect(m.operations).toBe(0);for(const entity of ['service','category','package']){const result=m.read('services.catalogWorkspace',{entity});if(['failure','forbidden','loading'].includes(mode))continue;if(mode==='stale-error')expect(result.error).toBeTruthy();else expect(result.error).toBeNull();expect(result.data?.merchantId).toBe(mode==='foreign'?999:id);}}});
 it.each(['service','category','package'])('paginates and filters the full %s catalog',entity=>{const m=new ServicePreviewModel(269);const first=read(m,'catalogWorkspace',{entity}),second=read(m,'catalogWorkspace',{entity,page:2});expect(first.rows).toHaveLength(24);expect(second.rows).toHaveLength(7);expect(new Set([...first.rows,...second.rows].map(r=>r.id)).size).toBe(31);expect(read(m,'catalogWorkspace',{entity,status:'inactive'}).rows).toHaveLength(6);expect(read(m,'catalogWorkspace',{entity,search:'31'}).rows.map(r=>r.id)).toEqual([31]);expect(read(m,'catalogEditor',{entity}).record).toBeNull();});
 it('offers only active references with paging and actual selected labels',()=>{const m=new ServicePreviewModel(269);expect(read(m,'catalogChoices',{kind:'service',page:2}).rows).toHaveLength(1);expect(read(m,'catalogChoices',{kind:'staff',page:2}).rows).toHaveLength(1);expect(read(m,'catalogEditor',{entity:'service',id:1}).record.references.map(r=>r.kind)).toEqual(['category','staff']);});
 it('creates a free service, edits by version, archives and preserves independent tenants',async()=>{const m=new ServicePreviewModel(269),other=new ServicePreviewModel(270);const created=await m.mutate('services.create',draft);const row=read(m,'catalogEditor',{entity:'service',id:created.serviceId}).record;expect(row.fields.basePrice).toBe(0);expect(read(m,'detailsWorkspace',{serviceId:created.serviceId}).bookings.total).toBe(0);await m.mutate('services.update',{...draft,name:'Updated',serviceId:row.id,expectedDefinition:row.definition});await expect(m.mutate('services.delete',{serviceId:row.id,expectedDefinition:row.definition})).rejects.toMatchObject({data:{code:'CONFLICT'}});const changed=read(m,'catalogRecord',{entity:'service',id:row.id}).record;await m.mutate('services.delete',{serviceId:row.id,expectedDefinition:changed.definition});expect(read(m,'catalogRecord',{entity:'service',id:row.id}).record.fields.isActive).toBe(false);expect(read(other,'catalogWorkspace',{entity:'service'}).summary.total).toBe(31);expect(m.operations).toBe(3);});
 it('persists category fields and package prices with derived discount and null clearing',async()=>{const m=new ServicePreviewModel(269);const cat=await m.mutate('serviceCategories.create',{name:'Category',icon:'🧑‍💻',color:'#ABC',displayOrder:0});const row=read(m,'catalogRecord',{entity:'category',id:cat.categoryId}).record;expect(row.fields).toMatchObject({icon:'🧑‍💻',color:'#ABC',displayOrder:0});const pack=await m.mutate('servicePackages.create',{name:'Pack',serviceIds:[1,2],originalPrice:10050,packagePrice:8040});const record=read(m,'catalogRecord',{entity:'package',id:pack.packageId}).record;expect(record.fields.discountPercentage).toBe(20);await m.mutate('servicePackages.update',{packageId:pack.packageId,expectedDefinition:record.definition,originalPrice:0,packagePrice:0,description:null});expect(read(m,'catalogRecord',{entity:'package',id:pack.packageId}).record.fields).toMatchObject({discountPercentage:0,description:null});await expect(m.mutate('servicePackages.create',{name:'Bad',serviceIds:[5],originalPrice:100,packagePrice:80})).rejects.toMatchObject({data:{code:'BAD_REQUEST'}});});
 it('keeps detail evidence consistent and exposes legacy values without false zeros',()=>{const normal=read(new ServicePreviewModel(269),'detailsWorkspace',{serviceId:1});expect(normal.recent).toHaveLength(10);expect(normal.bookings).toMatchObject({total:105,paidValue:{minor:224000,eligible:16,invalid:0}});const legacy=read(new ServicePreviewModel(269,'legacy'),'detailsWorkspace',{serviceId:1});expect(legacy.bookings.paidValue.minor).toBeNull();expect(legacy.ratings.excluded).toBe(1);expect(legacy.service.fields.staffIds).toBeNull();});
 it.each(['readonly','forbidden','session','foreign','failure','stale-error'] as const)('rejects content writes in %s while own missing-receipt resolution remains separately tested',async mode=>{const m=new ServicePreviewModel(269,mode);for(const name of serviceMutations.filter(name=>mode!=='readonly'||name!=='scheduledMessages.resolveActionReceipt'))await expect(m.mutate(name,draft)).rejects.toMatchObject({data:{code:'FORBIDDEN'}});expect(m.operations).toBe(0);});
 it('discards pending work on tenant disposal and completes only on explicit simulation',async()=>{const m=new ServicePreviewModel(269,'pending-save'),promise=m.mutate('services.create',draft);expect(m.pending).toBe(1);m.finishPending();await expect(promise).resolves.toMatchObject({success:true,serviceId:32});const b=new ServicePreviewModel(270,'pending-save'),late=b.mutate('services.create',draft),check=expect(late).rejects.toMatchObject({data:{code:'CONFLICT'}});b.dispose();await check;expect(b.operations).toBe(0);});
 it('represents uncertain completion honestly and recovers by rereading the committed local data',async()=>{const m=new ServicePreviewModel(269,'uncertain-save');await expect(m.mutate('services.create',draft)).rejects.toBeTruthy();expect(m.operations).toBe(1);expect((await m.refetch('services.catalogWorkspace',{entity:'service'})).data.summary.total).toBe(32);});
 it.each([0,-1,1.5,2147483648,999])('rejects invalid or missing service %s',serviceId=>{expect(new ServicePreviewModel(269).read('services.detailsWorkspace',{serviceId}).error).toBeTruthy();});
 it('preserves preview context while replacing application filters',()=>{const href=servicePreviewHref('/merchant/service-packages?edit=new','?tenant=270&lang=en&embed=brain&q=old');const nav=previewNavigation(href!);expect(nav.path).toBe('/merchant/service-packages');expect(nav.search).toBe('edit=new');expect(nav.params.get('tenant')).toBe('270');for(const route of ['//evil.test','/merchant/services/0','/merchant/services/2147483648','/merchant/services/01','/merchant/settings'])expect(validServicePath(route)).toBe(false);});
 it('imports the actual pages and routes all six pages before legacy generic forms',()=>{const root='prototypes/tenant-dashboard/',entry=readFileSync(root+'src/service-preview.tsx','utf8'),pages=readFileSync(root+'site/pages.js','utf8');for(const page of ['merchant/ServicesManagement','merchant/ServiceForm','merchant/ServiceCategories','merchant/ServicePackages','ServiceDetails'])expect(entry).toContain('pages/'+page);expect(pages.indexOf('service-workspace.html')).toBeLessThan(pages.indexOf("if(mode!=='normal')"));expect(pages).not.toContain("current.route.includes('/services/')");});
});
