// @vitest-environment jsdom
import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {serviceEditorEn} from '../client/src/locales/service-editor-workspace';import {serviceCollectionEn} from '../client/src/locales/service-collection-workspace';
vi.mock('@/lib/trpc',()=>import('../prototypes/tenant-dashboard/src/service-preview-api'));
vi.mock('wouter',()=>import('../prototypes/tenant-dashboard/src/service-preview-router'));
vi.mock('react-i18next',()=>({useTranslation:()=>({i18n:{language:'en'},t:(key:string,vars:any={})=>{const value=({...serviceEditorEn,...serviceCollectionEn} as Record<string,string>)[key.split('.').at(-1)!]??key;return value.replace(/\{\{(\w+)\}\}/g,(_,k)=>String(vars[k]??''));}})}));
import ServiceForm from '../client/src/pages/merchant/ServiceForm';import ServiceCategories from '../client/src/pages/merchant/ServiceCategories';import ServicePackages from '../client/src/pages/merchant/ServicePackages';
import {ServicePreviewContext} from '../prototypes/tenant-dashboard/src/service-preview-api';import {ServicePreviewModel} from '../prototypes/tenant-dashboard/src/service-preview-model';
let root:Root,container:HTMLDivElement,model:ServicePreviewModel;
beforeEach(()=>{Object.assign(globalThis,{React,IS_REACT_ACT_ENVIRONMENT:true});container=document.createElement('div');document.body.append(container);root=createRoot(container);model=new ServicePreviewModel(269);});
afterEach(async()=>{await act(async()=>root.unmount());model.dispose();container.remove();});
const render=async(path:string,page:React.ReactNode)=>{history.replaceState(null,'','/?path='+encodeURIComponent(path.split('?')[0])+(path.includes('?')?'&'+path.split('?')[1]:''));await act(async()=>root.render(<ServicePreviewContext.Provider value={model}>{page}</ServicePreviewContext.Provider>));};
const set=async(id:string,value:string)=>act(async()=>{const el=document.getElementById(id) as HTMLInputElement;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));});
const review=()=>act(async()=>container.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
const save=async()=>{const dialog=document.querySelector('[role=dialog]')!,button=Array.from(dialog.querySelectorAll('button')).find(b=>b.textContent?.trim()===serviceCollectionEn.confirm||b.textContent?.trim()===serviceEditorEn.confirm)!;await act(async()=>button.click());};
it('uses the real creation receipt to navigate from service form to its new details',async()=>{await render('/merchant/services/new',<ServiceForm/>);await set('se-name','Saved from actual preview');await set('se-basePrice','0');await review();await save();expect(model.operations).toBe(1);expect(new URLSearchParams(location.search).get('path')).toBe('/merchant/services/32');expect(document.querySelector('[role=dialog]')).toBeNull();expect(model.read('services.detailsWorkspace',{serviceId:32}).data.service.fields.name).toBe('Saved from actual preview');});
it('uses the real category receipt to return to its filtered list',async()=>{await render('/merchant/service-categories?edit=new&q=test',<ServiceCategories/>);await set('scf-name','test category');await review();await save();expect(model.operations).toBe(1);expect(new URLSearchParams(location.search).get('edit')).toBeNull();expect(new URLSearchParams(location.search).get('q')).toBe('test');expect(document.querySelector('[role=dialog]')).toBeNull();});
it('uses the package update receipt and retains derived prices',async()=>{await render('/merchant/service-packages?edit=1',<ServicePackages/>);await set('scf-packagePrice','0');await review();await save();expect(model.operations).toBe(1);expect(new URLSearchParams(location.search).get('edit')).toBeNull();expect(model.read('services.catalogRecord',{entity:'package',id:1}).data.record.fields).toMatchObject({packagePrice:0,discountPercentage:100});});
it('keeps a real uncertain save disabled while the model records its completion',async()=>{model=new ServicePreviewModel(269,'uncertain-save');await render('/merchant/services/new',<ServiceForm/>);await set('se-name','Uncertain');await set('se-basePrice','0');await review();await save();expect(model.operations).toBe(1);expect(new URLSearchParams(location.search).get('path')).toBe('/merchant/services/new');expect(document.querySelector('[role=dialog] [role=alert]')).not.toBeNull();expect(Array.from(document.querySelectorAll('[role=dialog] button')).some(b=>(b as HTMLButtonElement).disabled)).toBe(true);});
