import {beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({execute:vi.fn(),run:vi.fn(),integration:vi.fn(),update:vi.fn(),append:vi.fn()}));
vi.mock('./sheets-user-operation',()=>({runSheetsUserOperation:m.run}));
vi.mock('./db',()=>({getGoogleIntegration:m.integration,updateGoogleIntegration:m.update}));
vi.mock('./_core/googleSheets',()=>({appendToSheet:m.append}));
import {readConversationExportRows,exportScopedConversationsToSheets} from './sheets-conversation-export';
const scope={userId:9,merchantId:7,sessionId:'a'.repeat(64)},input={conversationIds:[4]},row={id:5,createdAt:'2026-10-04T12:30:00Z',direction:'incoming',content:'=IMPORTXML("https://example.test")',customerName:'Synthetic',customerPhone:'99900000001'},tx={execute:m.execute}as any;
beforeEach(()=>{vi.resetAllMocks();m.run.mockImplementation(async(_scope,work)=>work(tx));m.execute.mockImplementation(async sql=>sql.startsWith('UPDATE')?[{affectedRows:1}]:sql.includes('SELECT id FROM conversations')?[[{id:4}]]:[[row]]);m.integration.mockResolvedValue({id:8,isActive:1,sheetId:'local'});m.append.mockImplementation(async(_m,_s,_r,_v,options)=>{await options.beforeSend();return {success:true,message:'PRIVATE'};});});
it('exports exact scoped messages as literal cells in stable UTC order',async()=>{expect(await exportScopedConversationsToSheets(scope,input)).toMatchObject({success:true});expect(m.run).toHaveBeenCalledWith(scope,expect.any(Function));expect(m.execute.mock.calls[0][1]).toEqual([7,4]);expect(m.execute.mock.calls[1][0]).toContain('WHERE c.merchantId=? AND c.id IN');expect(m.append).toHaveBeenCalledWith(7,'local','المحادثات!A:F',[['2026-10-04','12:30:00 UTC','Synthetic','99900000001','وارد',row.content]],expect.objectContaining({raw:true}));});
it.each([[],[{id:8}],[{id:4},{id:8}]])('rejects a missing, foreign or ambiguous selection before reading messages or contacting provider %j',async selected=>{m.execute.mockResolvedValue([selected]);await expect(exportScopedConversationsToSheets(scope,input)).rejects.toMatchObject({code:'FORBIDDEN'});expect(m.execute).toHaveBeenCalledOnce();expect(m.integration).not.toHaveBeenCalled();expect(m.append).not.toHaveBeenCalled();});
it('does not send a partial export when more than 10000 messages match',async()=>{m.execute.mockResolvedValueOnce([[{id:4}]]).mockResolvedValue([Array.from({length:10001},()=>row)]);await expect(exportScopedConversationsToSheets(scope,input)).rejects.toMatchObject({code:'PRECONDITION_FAILED',message:'sheets_export:too_large'});expect(m.append).not.toHaveBeenCalled();});
it('does not send an oversized payload',async()=>{m.execute.mockResolvedValueOnce([[{id:4}]]).mockResolvedValue([Array.from({length:50},()=>({...row,content:'x'.repeat(50000)}))]);await expect(exportScopedConversationsToSheets(scope,input)).rejects.toMatchObject({code:'PRECONDITION_FAILED'});expect(m.append).not.toHaveBeenCalled();});
it.each([{createdAt:'bad'},{direction:'other'},{content:null},{customerPhone:null}])('refuses invalid source data without inventing values %j',async patch=>{m.execute.mockResolvedValueOnce([[{id:4}]]).mockResolvedValue([[{...row,...patch}]]);await expect(readConversationExportRows(tx,7,input)).rejects.toThrow();});
it('does not claim success or contact the provider for empty messages',async()=>{m.execute.mockResolvedValueOnce([[{id:4}]]).mockResolvedValue([[]]);expect(await exportScopedConversationsToSheets(scope,input)).toMatchObject({success:false});expect(m.append).not.toHaveBeenCalled();});
it('checks the destination again immediately before append',async()=>{m.integration.mockResolvedValueOnce({id:8,isActive:1,sheetId:'local'}).mockResolvedValue({id:8,isActive:1,sheetId:'changed'});await expect(exportScopedConversationsToSheets(scope,input)).rejects.toThrow();expect(m.update).not.toHaveBeenCalled();});
it('redacts a negative provider acknowledgement and does not update last sync',async()=>{m.append.mockResolvedValue({success:false,message:'PRIVATE'});await expect(exportScopedConversationsToSheets(scope,input)).rejects.toMatchObject({message:'sheets_export:unconfirmed'});expect(m.update).not.toHaveBeenCalled();});

it('does not claim a persisted sync time without an update acknowledgement',async()=>{m.execute.mockImplementation(async sql=>sql.startsWith('UPDATE')?[{affectedRows:0}]:sql.includes('SELECT id FROM conversations')?[[{id:4}]]:[[row]]);await expect(exportScopedConversationsToSheets(scope,input)).rejects.toMatchObject({message:'sheets_export:unconfirmed'});});
