import {beforeEach,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({access:vi.fn(),run:vi.fn(),export:vi.fn(),daily:vi.fn(),weekly:vi.fn(),monthly:vi.fn(),custom:vi.fn(),send:vi.fn(),legacy:vi.fn()}));
vi.mock('./accounts/merchant-access',()=>({resolveMerchantAccess:m.access}));
vi.mock('./sheets-user-operation',()=>({runSheetsUserOperation:m.run}));
vi.mock('./sheets-conversation-export',()=>({exportScopedConversationsToSheets:m.export}));
vi.mock('./sheetsReports',()=>({generateDailyReport:m.daily,generateWeeklyReport:m.weekly,generateMonthlyReport:m.monthly,generateCustomReport:m.custom,sendReportViaWhatsApp:m.send}));
vi.mock('./db',()=>({getMerchantByUserId:m.legacy,getOrderById:vi.fn()}));
import {sheetsRouter} from './routers-sheets';
const sessionId='a'.repeat(64),caller=(session:any={sessionId})=>sheetsRouter.createCaller({user:{id:9,role:'user'},session,req:{headers:{'x-merchant-id':'7'}},res:{}}as any);
const actions=['export','daily','weekly','monthly','custom','send']as const;
function call(name:typeof actions[number],c=caller()){return name==='export'?c.exportConversations({conversationIds:[4],reviewed:true,expectedSpreadsheetId:'local'}):name==='daily'?c.generateDailyReport():name==='weekly'?c.generateWeeklyReport():name==='monthly'?c.generateMonthlyReport():name==='custom'?c.generateCustomReport({startDate:new Date('2026-10-01'),endDate:new Date('2026-10-02')}):c.sendReportViaWhatsApp({reportType:'يومي'});}
beforeEach(()=>{vi.resetAllMocks();m.access.mockResolvedValue({merchantId:7,role:'manager'});m.run.mockImplementation(async(_scope,work)=>work({}));for(const f of [m.daily,m.weekly,m.monthly,m.custom])f.mockResolvedValue({success:true,data:{totalOrders:1},message:'PRIVATE'});m.send.mockResolvedValue({success:true,message:'PRIVATE'});m.export.mockResolvedValue({success:true});});
it.each(actions)('uses the selected tenant and authenticated session for %s',async name=>{const result=await call(name);expect(name==='export'?m.export:m.run).toHaveBeenCalledWith({merchantId:7,userId:9,sessionId},expect.anything());expect(m.legacy).not.toHaveBeenCalled();if(name!=='export')expect(m[name]).toHaveBeenCalledWith(7,...name==='custom'?[new Date('2026-10-01'),new Date('2026-10-02')]:name==='send'?['يومي',{totalOrders:1}]:[]);expect(JSON.stringify(result)).not.toContain('PRIVATE');});
it.each(actions)('blocks a viewer before %s effects',async name=>{m.access.mockResolvedValue({merchantId:7,role:'viewer'});await expect(call(name)).rejects.toMatchObject({code:'FORBIDDEN'});expect(m.run).not.toHaveBeenCalled();expect(m.export).not.toHaveBeenCalled();});
it.each(actions)('requires a real session for %s',async name=>{await expect(call(name,caller(null))).rejects.toMatchObject({code:'UNAUTHORIZED'});expect(m.run).not.toHaveBeenCalled();expect(m.export).not.toHaveBeenCalled();});
it.each([[],[0],[-1],[1.2],[1,1],Array.from({length:101},(_,i)=>i+1)])('rejects invalid export selections %j',async ids=>{await expect(caller().exportConversations({conversationIds:ids,reviewed:true,expectedSpreadsheetId:'local'})).rejects.toMatchObject({code:'BAD_REQUEST'});expect(m.export).not.toHaveBeenCalled();});
it.each(['daily','weekly','monthly','custom','send']as const)('does not expose raw provider failures for %s',async name=>{for(const f of [m.daily,m.weekly,m.monthly,m.custom,m.send])f.mockResolvedValue({success:false,message:'PRIVATE'});await expect(call(name)).rejects.toMatchObject({code:'PRECONDITION_FAILED',message:'sheets_operation:unconfirmed'});expect(m.send).not.toHaveBeenCalled();});
it('rejects unsupported report kinds and inverted or excessive custom periods',async()=>{await expect(caller().sendReportViaWhatsApp({reportType:'PRIVATE'}as any)).rejects.toMatchObject({code:'BAD_REQUEST'});for(const endDate of ['2026-09-01','2028-01-01'])await expect(caller().generateCustomReport({startDate:new Date('2026-10-01'),endDate:new Date(endDate)})).rejects.toMatchObject({code:'BAD_REQUEST'});expect(m.run).not.toHaveBeenCalled();});
