import {afterAll,afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const provider=vi.hoisted(()=>({append:vi.fn()}));
vi.mock('./_core/googleSheets',()=>({appendToSheet:provider.append}));
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {createSessionId,hashSessionId} from './_core/session-security';
import {apiRateLimitBucketHash} from './api/distributed-rate-limit';
import {exportScopedConversationsToSheets} from './sheets-conversation-export';
import {sheetsRouter} from './routers-sheets';
describe.skipIf(!process.env.DATABASE_URL)('scoped conversation export on disposable MySQL and mocked Sheets',()=>{
 let a:Awaited<ReturnType<typeof createDisposableMerchant>>,b:typeof a,sessionId:string,owned:number,foreign:number;
 const q=async(sql:string,args:any[]=[]) => (await (await getPool())!.execute<any>(sql,args))[0];
 const scope=()=>({...a,sessionId}),input=()=>({conversationIds:[owned]});
 beforeEach(async()=>{vi.resetAllMocks();a=await createDisposableMerchant('sheet-export511');b=await createDisposableMerchant('sheet-foreign511');sessionId=createSessionId();await q('INSERT INTO auth_sessions(user_id,token_id_hash,expires_at) VALUES (?,?,DATE_ADD(NOW(),INTERVAL 1 DAY))',[a.userId,hashSessionId(sessionId)]);
  for(const [index,tenant]of [a,b].entries()){const id=Number((await q("INSERT INTO conversations(merchantId,customerPhone,customerName) VALUES (?,'99900000001',?)",[tenant.merchantId,index?'PRIVATE_FOREIGN':'Synthetic'])).insertId);if(index)foreign=id;else owned=id;await q("INSERT INTO messages(conversationId,direction,content,createdAt) VALUES (?,'incoming',?,'2026-10-04 12:30:00')",[id,index?'PRIVATE_FOREIGN_MESSAGE':'=SUM(1,1)']);await q("INSERT INTO google_integrations(merchant_id,integration_type,is_active,sheet_id,credentials) VALUES (?,'sheets',1,?,'{}')",[tenant.merchantId,'local-'+tenant.merchantId]);}
  provider.append.mockImplementation(async(_m,_s,_r,_rows,options)=>{await options.beforeSend();return {success:true,message:'PRIVATE_PROVIDER'};});
 });
 afterEach(async()=>{for(const tenant of [a,b].filter(Boolean))await q('DELETE FROM api_rate_limit_windows WHERE bucket_hash=?',[apiRateLimitBucketHash('sheets:user-operation',String(tenant.merchantId))]);await cleanupDisposableMerchants([a?.userId,b?.userId].filter(Boolean));});afterAll(closeDb);
 it('exports only the complete selected owned message set as RAW cells',async()=>{expect(await exportScopedConversationsToSheets(scope(),input())).toMatchObject({success:true});expect(provider.append).toHaveBeenCalledWith(a.merchantId,'local-'+a.merchantId,'المحادثات!A:F',[['2026-10-04','12:30:00 UTC','Synthetic','99900000001','وارد','=SUM(1,1)']],expect.objectContaining({raw:true}));expect(JSON.stringify(provider.append.mock.calls)).not.toContain('PRIVATE_FOREIGN');});
 it.each(['foreign','mixed','missing'])('rejects %s IDs before any provider interaction',async kind=>{const ids=kind==='foreign'?[foreign]:kind==='mixed'?[owned,foreign]:[2147483647];await expect(exportScopedConversationsToSheets(scope(),{conversationIds:ids})).rejects.toMatchObject({code:'FORBIDDEN'});expect(provider.append).not.toHaveBeenCalled();});
 it('uses the selected tenant rather than another store owned by the actor',async()=>{await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'manager',1)",[b.merchantId,a.userId]);const caller=sheetsRouter.createCaller({user:{id:a.userId,role:'user'},session:{sessionId},req:{headers:{'x-merchant-id':String(b.merchantId)}}}as any);expect(await caller.exportConversations({conversationIds:[foreign]})).toMatchObject({success:true});expect(provider.append.mock.calls[0][0]).toBe(b.merchantId);expect(provider.append.mock.calls[0][1]).toBe('local-'+b.merchantId);});
 it.each(['session','membership','actor','owner'])('checks live %s authority before export',async kind=>{if(kind==='session')await q('UPDATE auth_sessions SET revoked_at=NOW() WHERE user_id=?',[a.userId]);if(kind==='membership')await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'owner',0)",[a.merchantId,a.userId]);if(kind==='actor')await q("UPDATE users SET account_status='deletion_pending' WHERE id=?",[a.userId]);if(kind==='owner'){await q('UPDATE merchants SET userId=? WHERE id=?',[b.userId,a.merchantId]);await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'manager',1)",[a.merchantId,a.userId]);await q("UPDATE users SET account_status='deletion_pending' WHERE id=?",[b.userId]);}await expect(exportScopedConversationsToSheets(scope(),input())).rejects.toMatchObject({code:'FORBIDDEN'});expect(provider.append).not.toHaveBeenCalled();});
 it('does not export a partial result above the bounded message count',async()=>{const pool=(await getPool())!;await pool.query("INSERT INTO messages(conversationId,direction,content) VALUES ?",[Array.from({length:10000},()=>[owned,'incoming','local'])]);await expect(exportScopedConversationsToSheets(scope(),input())).rejects.toMatchObject({code:'PRECONDITION_FAILED',message:'sheets_export:too_large'});expect(provider.append).not.toHaveBeenCalled();});
 it('does not invent a successful empty export',async()=>{await q('DELETE FROM messages WHERE conversationId=?',[owned]);expect(await exportScopedConversationsToSheets(scope(),input())).toMatchObject({success:false});expect(provider.append).not.toHaveBeenCalled();});
 it('shares the ten-operation limit across concurrent calls',async()=>{const results=await Promise.allSettled(Array.from({length:12},()=>exportScopedConversationsToSheets(scope(),input())));expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(10);expect(results.filter(r=>r.status==='rejected'&&r.reason.code==='TOO_MANY_REQUESTS')).toHaveLength(2);expect(provider.append).toHaveBeenCalledTimes(10);});
});
