// @vitest-environment jsdom
import React,{act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {beforeEach,afterEach,describe,expect,it,vi} from 'vitest';
import ar from '../client/src/locales/ar.json';import en from '../client/src/locales/en.json';import {TrialBanner} from '../client/src/components/TrialBanner';
const api=vi.hoisted(()=>({query:{} as any,retry:vi.fn()}));
vi.mock('../client/src/lib/trpc',()=>({trpc:{merchantSubscription:{getCurrentSubscription:{useQuery:()=>({...api.query,refetch:api.retry})}}}}));
let lng:'ar'|'en'='en';vi.mock('react-i18next',()=>({useTranslation:()=>({t:(key:string)=>key.split('.').reduce((v:any,k)=>v?.[k],{ar,en}[lng])??key,i18n:{language:lng,dir:()=>lng==='ar'?'rtl':'ltr'}})}));
let root:Root,container:HTMLDivElement;const now=Date.parse('2026-10-01T12:00:00Z');
beforeEach(()=>{lng='en';api.retry.mockClear();vi.useFakeTimers();vi.setSystemTime(now);api.query={data:{id:1,status:'trial',endDate:'2026-10-03 12:00:00',trialEndsAt:'2026-10-05 12:00:00',daysRemaining:99},isFetching:false,isLoading:false,isError:false};vi.stubGlobal('React',React);vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);container=document.createElement('div');document.body.append(container);root=createRoot(container);});
afterEach(async()=>{await act(async()=>root.unmount());expect(vi.getTimerCount()).toBe(0);container.remove();vi.useRealTimers();vi.unstubAllGlobals();});
const mount=async()=>{await act(async()=>root.render(React.createElement(TrialBanner)));};
describe('trial notice',()=>{
 it.each(['ar','en']as const)('shows the earlier end, translated units and distinct destinations in %s',async lang=>{lng=lang;await mount();expect(container.querySelector('time')?.dateTime).toBe('2026-10-03T12:00:00.000Z');expect(container.querySelector('[aria-label]')?.getAttribute('dir')).toBe(lang==='ar'?'rtl':'ltr');expect(container.textContent).not.toMatch(/99|trialNoticeUx|NaN|undefined/);expect(container.querySelector('a[href="/merchant/subscription/compare"]')).toBeTruthy();expect(container.querySelector('a[href="/merchant/my-subscription"]')).toBeTruthy();expect(container.querySelector('a button')).toBeNull();if(lang==='en')expect(container.textContent).toContain('2 days');});
 it.each(['failed','loading','missing'])('does not show stale trial status for %s',async state=>{if(state==='failed')api.query.isError=true;if(state==='loading')api.query.isFetching=true;if(state==='missing')api.query.data=undefined;await mount();expect(container.querySelector('time')).toBeNull();expect(container.textContent).not.toContain('You are in the trial');expect(container.textContent).not.toContain('No active subscription');});
 it('offers retry for failed reading without treating it as no subscription',async()=>{api.query.isError=true;await mount();await act(async()=>container.querySelector('button')!.click());expect(api.retry).toHaveBeenCalledOnce();api.query.isError=false;api.query.data=null;await mount();expect(container.textContent).toContain('No active subscription recorded');});
 it('keeps invalid end time unknown without inventing urgent expiry',async()=>{api.query.data.endDate='2026-02-30';await mount();expect(container.textContent).toContain('reliable expiry time is unavailable');expect(container.querySelector('time')).toBeNull();expect(container.textContent).not.toContain('has ended');});
 it('changes to expired exactly after the local countdown ends and releases its timer on unmount',async()=>{api.query.data.trialEndsAt='2026-10-01T12:00:01Z';await mount();expect(container.textContent).toContain('Less than a minute');await act(async()=>vi.advanceTimersByTime(1000));expect(container.textContent).toContain('recorded trial period has ended');expect(container.textContent).not.toContain('Time remaining');});
 it('hides a paid active banner and does not mislabel a paid expired subscription as trial',async()=>{api.query.data.status='active';await mount();expect(container.textContent).toBe('');api.query.data.status='expired';await mount();expect(container.textContent).toContain('recorded subscription period has ended');expect(container.textContent).not.toContain('trial period');});
 it('updates language and subscription identity without reusing old countdown text',async()=>{await mount();lng='ar';api.query.data={...api.query.data,id:2,endDate:'2026-10-01T12:30:00Z',trialEndsAt:null};await mount();expect(container.textContent).not.toContain('days');expect(container.querySelector('time')?.dateTime).toBe('2026-10-01T12:30:00.000Z');expect(container.textContent).not.toMatch(/trialNoticeUx/);});
});
