// @vitest-environment jsdom
import React,{act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {beforeEach,afterEach,expect,it,vi} from 'vitest';
import ar from '../client/src/locales/ar.json';import en from '../client/src/locales/en.json';
const state=vi.hoisted(()=>({lang:'en'}));
vi.mock('@/lib/trpc',()=>import('../prototypes/tenant-dashboard/src/service-preview-api'));
vi.mock('wouter',()=>import('../prototypes/tenant-dashboard/src/service-preview-router'));
vi.mock('react-i18next',()=>({useTranslation:()=>({i18n:{language:state.lang},t:(key:string)=>key.split('.').reduce((o:any,k)=>o?.[k],state.lang==='ar'?ar:en)||key})}));
import Page from '../client/src/pages/merchant/WhatsAppTest';
import {ServicePreviewContext} from '../prototypes/tenant-dashboard/src/service-preview-api';
import {ServicePreviewModel,type ServiceMode} from '../prototypes/tenant-dashboard/src/service-preview-model';
let root:Root,host:HTMLDivElement,model:ServicePreviewModel;
const c=()=>state.lang==='ar'?ar.whatsappDiagnosticUx:en.whatsappDiagnosticUx;
beforeEach(()=>{vi.stubGlobal('React',React);vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);state.lang='en';history.replaceState(null,'','/?path=/merchant/whatsapp-test');host=document.createElement('div');document.body.append(host);root=createRoot(host);model=new ServicePreviewModel(269);});
afterEach(async()=>{await act(async()=>root.unmount());model.dispose();host.remove();vi.restoreAllMocks();vi.unstubAllGlobals();});
const render=()=>act(async()=>root.render(<ServicePreviewContext.Provider value={model}><Page/></ServicePreviewContext.Provider>));
const mode=(v:ServiceMode)=>{model.dispose();model=new ServicePreviewModel(269,v);};
const set=(key:string,value:string)=>act(async()=>{const el=document.getElementById('wd-'+key) as HTMLInputElement|HTMLTextAreaElement;Object.getOwnPropertyDescriptor(el.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));});
const select=()=>act(async()=>{const e=document.getElementById('wd-saved') as HTMLSelectElement;e.value='1';e.dispatchEvent(new Event('change',{bubbles:true}));});
const click=(text:string)=>act(async()=>{const b=Array.from(document.querySelectorAll<HTMLButtonElement>('button')).find(b=>b.textContent===text);expect(b).toBeTruthy();b!.click();});
const prepare=async()=>{await render();await select();await set('token','local-demo-token');};
const prepareSend=async(kind:'text'|'image'='text')=>{await prepare();await click(c()[`tab_${kind}`]);await set('phoneNumber','99900000001');if(kind==='text')await set('message','Hello local test');else{await set('imageUrl','https://cdn.example.com/test.png');await set('caption','Local image');}};
it.each(['ar','en'])('shows the actual page and translated scoped guidance in %s without a default recipient or token',async lang=>{state.lang=lang;await render();expect(host.querySelector('h1')?.textContent).toBe(c().title);expect(host.textContent).toContain(c().scope);expect((document.getElementById('wd-token') as HTMLInputElement).value).toBe('');await click(c().tab_text);expect((document.getElementById('wd-phoneNumber') as HTMLInputElement).value).toBe('');expect(host.textContent).not.toMatch(/whatsappDiagnosticUx\.|966501898700/);expect(model.operations).toBe(0);});
it('links validation to the fields and focuses the first invalid field before any request',async()=>{await render();await click(c().check);expect(document.getElementById('wd-instanceId')?.getAttribute('aria-invalid')).toBe('true');expect(document.getElementById('wd-instanceId')?.getAttribute('aria-describedby')).toBe('wd-error-instanceId');expect(document.activeElement?.id).toBe('wd-instanceId');expect(host.textContent).toContain(c().error_token);expect(model.operations).toBe(0);});
it('clears connection proof when credentials change and never renders the entered secret in results',async()=>{await prepare();await click(c().check);expect(host.textContent).toContain(c().connected);expect(host.textContent).not.toContain('local-demo-token');await set('token','changed-token');expect(host.textContent).not.toContain(c().connected);expect(Array.from(host.querySelectorAll('button')).find(b=>b.textContent===c().save)?.disabled).toBe(true);});
it.each(['text','image'] as const)('reviews the exact %s message, permits cancellation and projects acceptance rather than delivery',async kind=>{
 await prepareSend(kind);await click(c().reviewSend);expect(document.querySelector('[role=dialog]')?.textContent).toContain('99900000001');expect(document.querySelector('[role=dialog]')?.textContent).toContain(kind==='text'?'Hello local test':'https://cdn.example.com/test.png');expect(document.querySelector('[role=dialog] img')).toBeNull();expect(model.operations).toBe(0);
 await click(c().cancel);expect(document.querySelector('[role=dialog]')).toBeNull();await click(c().reviewSend);await click(c().confirm);expect(model.operations).toBe(1);expect(host.textContent).toContain(c().accepted);expect(host.textContent).toContain('local-preview-receipt');expect(Array.from(host.querySelectorAll('button')).find(b=>b.textContent===c().reviewSend)?.disabled).toBe(true);
});
it('keeps an uncertain send from being automatically repeated and requires a deliberate new test',async()=>{mode('uncertain-save');await prepareSend();await click(c().reviewSend);await click(c().confirm);expect(host.textContent).toContain(c().uncertainSend);expect(host.textContent).not.toContain(c().accepted);expect(model.operations).toBe(1);await click(c().reviewSend);expect(document.querySelector('[role=dialog]')).toBeNull();await click(c().newTest);await click(c().reviewSend);expect(document.querySelector('[role=dialog]')).not.toBeNull();expect(model.operations).toBe(1);});
it('blocks invalid content before review and keeps the entered text',async()=>{await prepareSend();await set('phoneNumber','bad');await click(c().reviewSend);expect(document.querySelector('[role=dialog]')).toBeNull();expect(host.textContent).toContain(c().error_phoneNumber);expect((document.getElementById('wd-message') as HTMLTextAreaElement).value).toBe('Hello local test');expect(model.operations).toBe(0);});
it('requires a saved active connection to send and does not mislabel a failed read as empty',async()=>{mode('empty');await render();expect(host.textContent).toContain(c().empty);await set('instanceId','7103123456');await set('token','local-demo-token');await click(c().tab_text);await set('phoneNumber','99900000001');await set('message','test');await click(c().reviewSend);expect(document.querySelector('[role=dialog]')).toBeNull();expect(host.textContent).toContain(c().savedRequired);expect(model.operations).toBe(0);});
it.each(['loading','failure','stale-error','foreign','forbidden','session','readonly'] as ServiceMode[])('hides connections and credentials on %s',async v=>{mode(v);await render();expect(host.querySelector('input')).toBeNull();expect(host.textContent).not.toContain('7103000269');expect(host.textContent).not.toContain(c().empty);expect(model.operations).toBe(0);});
it('reviews saving only after a successful current check and verifies the refreshed record',async()=>{await prepare();await click(c().check);await click(c().save);expect(document.querySelector('[role=dialog]')?.textContent).toContain(c().saveHint);await click(c().confirm);expect(host.textContent).toContain(c().saved);expect((document.getElementById('wd-token') as HTMLInputElement).value).toBe('');expect(model.operations).toBe(2);});
it('requires deletion review and checks the record is absent after refresh',async()=>{await prepare();await click(c().delete);expect(document.querySelector('[role=dialog]')?.textContent).toContain(c().deleteHint);expect(model.read('whatsapp.diagnosticWorkspace',{merchantId:269}).data.connections).toHaveLength(2);await click(c().confirm);expect(host.textContent).toContain(c().deleted);expect(model.read('whatsapp.diagnosticWorkspace',{merchantId:269}).data.connections).toHaveLength(1);});
it('does not claim save success when the acknowledgement cannot be verified',async()=>{await prepare();await click(c().check);const original=model.mutate.bind(model);vi.spyOn(model,'mutate').mockImplementation((name,input)=>name==='whatsapp.saveInstance'?Promise.resolve({success:true}):original(name,input));await click(c().save);await click(c().confirm);expect(document.querySelector('[role=dialog]')?.textContent).toContain(c().verifySaved);expect(host.textContent).not.toContain(c().saved);});
it('does not display foreign workspace evidence after identity changes',async()=>{await prepare();model.dispose();model=new ServicePreviewModel(270);await render();expect((document.getElementById('wd-token') as HTMLInputElement).value).toBe('');expect(host.textContent).not.toContain('99900000269');expect(host.textContent).toContain('99900000270');});
it('keeps a pending send in review and prevents a second confirmation until the local response',async()=>{mode('pending-save');await prepareSend();await click(c().reviewSend);await click(c().confirm);expect(model.pending).toBe(1);expect(document.querySelector('[role=dialog]')).not.toBeNull();expect(Array.from(document.querySelectorAll<HTMLButtonElement>('[role=dialog] button')).every(b=>b.disabled)).toBe(true);expect(model.operations).toBe(0);await act(async()=>model.finishPending());expect(host.textContent).toContain(c().accepted);expect(model.operations).toBe(1);});

it('keeps credential input out of login password autofill and offers a numeric instance keyboard',async()=>{await render();expect(document.getElementById('wd-token')?.getAttribute('autocomplete')).toBe('new-password');expect(document.getElementById('wd-token')?.getAttribute('type')).toBe('password');expect(document.getElementById('wd-instanceId')?.getAttribute('inputmode')).toBe('numeric');});

it('keeps a stale deletion review from removing a changed record in the shared preview',async()=>{await prepare();await click(c().delete);await act(async()=>{await model.mutate('whatsapp.saveInstance',{instanceId:'7103000269',token:'local-demo-token',phoneNumber:'99900000999'});});await click(c().confirm);expect(document.querySelector('[role=dialog]')?.textContent).toContain(c().verifySaved);expect(model.read('whatsapp.diagnosticWorkspace',{merchantId:269}).data.connections).toHaveLength(2);expect(model.operations).toBe(1);});
it('rejects a deletion acknowledgement from another actor or store without claiming success',async()=>{await prepare();vi.spyOn(model,'mutate').mockResolvedValue({success:true,actorId:999,merchantId:270,instanceId:1});await click(c().delete);await click(c().confirm);expect(document.querySelector('[role=dialog]')?.textContent).toContain(c().verifySaved);expect(host.textContent).not.toContain(c().deleted);expect(model.read('whatsapp.diagnosticWorkspace',{merchantId:269}).data.connections).toHaveLength(2);});
