// @vitest-environment jsdom
import React,{act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {Router} from 'wouter';
import {memoryLocation} from 'wouter/memory-location';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import en from '../client/src/locales/merchant-ux.en';
import ar from '../client/src/locales/merchant-ux.ar';
const m=vi.hoisted(()=>({actor:7,merchant:20,language:'en',view:'settings',orders:{} as any,details:{} as any,orderAction:{} as any,orderSelection:{} as any,detailsSelection:{} as any,actionEnabled:true,update:vi.fn(),notify:vi.fn(),products:{} as any,analytics:{} as any,productSelection:{} as any,analyticsSelection:{} as any,access:{} as any,query:{} as any,logs:{} as any,incidents:{} as any,blocker:{} as any,selection:{} as any,refresh:vi.fn(),blockerRefresh:vi.fn(),connect:vi.fn(),sync:vi.fn(),reconcile:vi.fn(),lookup:vi.fn(),ack:vi.fn(),invalidate:vi.fn()}));
vi.mock('@/lib/trpc',()=>({trpc:{auth:{me:{useQuery:()=>({data:m.actor?{id:m.actor}:null})}},merchants:{workspaceIdentity:{useQuery:()=>({data:{id:m.merchant, actorId:m.actor}})}},useUtils:()=>({woocommerce:{getOperation:{fetch:m.lookup},invalidate:m.invalidate}}),woocommerce:{getOrdersWorkspace:{useQuery:(input:any)=>{m.orderSelection=input;return m.orders;}},getOrderDetailsWorkspace:{useQuery:(input:any)=>{m.detailsSelection=input;return m.details;}},getOrderActionWorkspace:{useQuery:(_input:any,options:any)=>{m.actionEnabled=options.enabled;return m.orderAction;}},requestReviewedOrderStatus:{useMutation:()=>({mutateAsync:m.update})},requestReviewedNotification:{useMutation:()=>({mutateAsync:m.notify})},getProductsWorkspace:{useQuery:(input:any)=>{m.productSelection=input;return m.products;}},getAnalyticsWorkspace:{useQuery:(input:any)=>{m.analyticsSelection=input;return m.analytics;}},getAccess:{useQuery:()=>m.access},getWorkspace:{useQuery:()=>m.query},getLogsWorkspace:{useQuery:(input:any)=>{m.selection=input;return m.logs;}},getIncidentsWorkspace:{useQuery:(input:any)=>{m.selection=input;return m.incidents;}},getBlockingOperation:{useQuery:()=>m.blocker},acknowledgeOperation:{useMutation:()=>({mutateAsync:m.ack})},requestReviewedConnection:{useMutation:()=>({mutateAsync:m.connect})},requestReviewedSync:{useMutation:()=>({mutateAsync:m.sync})},requestReviewedReconciliation:{useMutation:()=>({mutateAsync:m.reconcile})}}}}));
vi.mock('react-i18next',()=>({useTranslation:()=>({i18n:{language:m.language},t:(key:string)=>{let value:any=m.language==='ar'?ar:en;for(const k of key.split('.').slice(1))value=value?.[k];return typeof value==='string'?value:key;}})}));
import Page from '../client/src/pages/merchant/WooCommerceSettings';
import OrdersPage from '../client/src/pages/WooCommerceOrders';
import ProductsPage from '../client/src/pages/WooCommerceProducts';
import AnalyticsPage from '../client/src/pages/merchant/WooCommerceAnalytics';
import {readWooTracking,saveWooTracking,clearWooTracking,scopedWooOperation,scopedWooLogs,scopedWooIncidents,wooStoreDestination,validateWooConnection,wooMoneyLabel,wooDefaultPeriod,wooRevenuePoints} from '../client/src/lib/woocommerce-workspace';
const c=en.wooWorkspace,revision='a'.repeat(64),requestId='5b9890df-e322-42e7-9767-56d1231ba7fd',stamp='2026-10-02T12:00:00Z';
const sample=()=>({actorId:7,merchantId:20,checkedAt:stamp,revision,present:true,state:'configured',connectionStatus:'connected',storeUrl:'https://sample.example.test',storeName:'Sample store',storeVersion:'9',storeCurrency:'SAR',hasConsumerKey:true,hasConsumerSecret:true,createdAt:stamp,lastTestAt:null,lastSyncAt:null,counts:{storedProducts:601,storedOrders:501,syncLogs:502},syncSummary:{running:0,success:500,partial:1,failed:1,unknown:0},webhooks:{ready:false,identityStored:false,registeredTopics:0,registrationsValid:false,stored:3,recentTotal:3,recentCompleted:1,awaiting:1,needsReview:1,suppressed:0,unknown:0,oldestPendingAt:stamp}});
const logs=()=>({actorId:7,merchantId:20,checkedAt:stamp,selection:{search:'',state:'all',kind:'all',direction:'all',page:1},summary:{stored:1,matched:1,groups:['running','success','partial','failed','unknown'].map(key=>({key,count:key==='success'?1:0}))},pagination:{page:1,pageSize:25,pages:1,total:1},rows:[{id:3,merchantId:20,kind:'products',state:'success',direction:'import',processed:1,succeeded:1,failed:0,durationSeconds:2,hasErrors:false,createdAt:stamp,startedAt:stamp,completedAt:stamp,invalidData:false}]});
const incidents=()=>({actorId:7,merchantId:20,checkedAt:stamp,selection:{search:'',state:'manual_review',resource:'all',page:1},summary:{stored:1,matched:1,groups:['pending','processing','completed','failed','manual_review','suppressed','unknown'].map(key=>({key,count:key==='manual_review'?1:0}))},pagination:{page:1,pageSize:25,pages:1,total:1},rows:[{id:8,merchantId:20,revision,topic:'product.updated',resourceId:9001,state:'manual_review',attempts:3,createdAt:stamp,processedAt:null,hasError:true,invalidData:false,reviewable:true}]});
const receipt=(input:any,kind='sync_products',outcome='pending')=>({actorId:7,merchantId:20,requestId:input.requestId,revision:input.revision,kind,outcome,started:outcome!=='rejected',reviewRequired:outcome==='unknown',result:outcome==='success'?{type:'sync',products:601,orders:null,reconciled:0}:null,createdAt:stamp,checkedAt:stamp,replayed:false});
let root:Root,container:HTMLDivElement;
beforeEach(()=>{Object.assign(globalThis,{React,IS_REACT_ACT_ENVIRONMENT:true});vi.resetAllMocks();sessionStorage.clear();m.actor=7;m.merchant=20;m.language='en';m.view='settings';m.orders={data:ordersSample(),refetch:vi.fn()};m.details={data:detailsSample(),refetch:vi.fn()};m.orderAction={data:actionSample(),refetch:vi.fn()};m.products={data:productsSample(),refetch:vi.fn()};m.analytics={data:analyticsSample(),refetch:vi.fn()};m.access={data:{actorId:7,merchantId:20,integrationsManage:true,ordersManage:true,analyticsRead:true},refetch:vi.fn()};m.query={data:sample(),refetch:m.refresh};m.logs={data:logs(),refetch:vi.fn()};m.incidents={data:incidents(),refetch:vi.fn()};m.blocker={data:{actorId:7,merchantId:20,operation:null},refetch:m.blockerRefresh};m.blockerRefresh.mockImplementation(async()=>({data:m.blocker.data}));m.refresh.mockImplementation(async()=>({data:m.query.data}));container=document.createElement('div');document.body.append(container);root=createRoot(container);});
afterEach(async()=>{await act(async()=>root.unmount());container.remove();vi.restoreAllMocks();});
const render=()=>act(async()=>root.render(<Router hook={memoryLocation({path:'/merchant/woocommerce/settings'}).hook}>{m.view==='orders'?<OrdersPage/>:m.view==='products'?<ProductsPage/>:m.view==='analytics'?<AnalyticsPage/>:<Page/>}</Router>));
const buttons=(text:string)=>Array.from(document.querySelectorAll('button')).filter(el=>el.textContent===text);
const click=(text:string)=>act(async()=>{const list=buttons(text);expect(list.length).toBeGreaterThan(0);list[0].click();});
const fill=(selector:string,value:string)=>act(async()=>{const input=document.querySelector(selector)!;Object.getOwnPropertyDescriptor(input instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));});
const check=(selector:string)=>act(async()=>{(document.querySelector(selector) as HTMLInputElement).click();});
it.each(['ar','en'])('renders all counts, history and translated incidents in %s',async lang=>{m.language=lang;await render();const copy=(lang==='ar'?ar:en).wooWorkspace;expect(container.querySelectorAll('h1')).toHaveLength(1);expect(container.querySelectorAll('.sc-summary>div')).toHaveLength(3);expect(container.textContent).toContain(copy.savedHint);await click(copy.history);expect(container.querySelectorAll('.wc-records>li')).toHaveLength(1);await click(copy.incidents+' · 1');expect(container.textContent).toContain(copy.productUpdated);expect(container.textContent).not.toContain('merchantUx.');expect(container.textContent).not.toContain('product.updated');expect(m.sync).not.toHaveBeenCalled();});
it.each(['actorId','merchantId'])('rejects a foreign %s in the page access or source',async key=>{m.access.data[key]=999;await render();expect(container.querySelector('[data-woo-workspace]')).toBeNull();m.access.data[key]=key==='actorId'?7:20;m.query.data[key]=999;await render();expect(container.textContent).not.toContain('Sample store');});
it.each(['FORBIDDEN','UNAUTHORIZED','INTERNAL_SERVER_ERROR'])('hides stale data and private errors for %s',async code=>{m.query.error={data:{code},message:'PRIVATE'};await render();expect(container.textContent).not.toContain('Sample store');expect(container.textContent).not.toContain('PRIVATE');});
it('shows missing session and permission states without the connection form',async()=>{m.actor=0;await render();expect(container.querySelector('form')).toBeNull();m.actor=7;m.access.data.integrationsManage=false;await render();expect(container.querySelector('form')).toBeNull();});
it('keeps unsafe saved destinations as text, never a link',async()=>{m.query.data.storeUrl='javascript:unsafe()';await render();expect(container.querySelector('a[target]')).toBeNull();});
it('validates destination and each credential inline before review',async()=>{await render();await fill('#wc-storeUrl','http://localhost');await fill('#wc-consumerKey','short');await fill('#wc-consumerSecret','short');await click(c.review);expect(document.querySelectorAll('[aria-invalid=true]')).toHaveLength(3);expect(document.activeElement?.id).toBe('wc-storeUrl');expect(document.querySelector('[role=dialog]')).toBeNull();expect(m.connect).not.toHaveBeenCalled();});
it('requires both new credentials and local-copy consent to change the store',async()=>{await render();await fill('#wc-storeUrl','https://different.example.test');await click(c.review);expect(document.querySelectorAll('[aria-invalid=true]')).toHaveLength(2);await fill('#wc-consumerKey','ck_'+'a'.repeat(40));await fill('#wc-consumerSecret','cs_'+'b'.repeat(40));await click(c.review);expect(buttons(c.confirm)[0].disabled).toBe(true);await check('[role=dialog] input[type=checkbox]');m.connect.mockImplementation(async input=>{expect(readWooTracking(sessionStorage,7,20)?.requestId).toBe(input.requestId);return receipt(input,'connect');});await click(c.confirm);expect(m.connect).toHaveBeenCalledWith(expect.objectContaining({revision,action:'connect',storeUrl:'https://different.example.test',replaceLocalCopies:true}));expect((document.querySelector('#wc-consumerKey') as HTMLInputElement).value).toBe('');expect(JSON.stringify(sessionStorage)).not.toMatch(/consumerKey|consumerSecret|different/);});
it('uses saved credentials only for the same canonical root',async()=>{await render();await fill('#wc-storeUrl','https://SAMPLE.example.test///');await click(c.review);expect(document.querySelector('[role=dialog] input[type=checkbox]')).toBeNull();m.connect.mockImplementation(async input=>receipt(input,'connect'));await click(c.confirm);expect(m.connect).toHaveBeenCalledWith(expect.objectContaining({storeUrl:'https://sample.example.test',consumerKey:undefined,consumerSecret:undefined,replaceLocalCopies:false}));});
it('does not execute an obsolete connection review',async()=>{await render();await click(c.verify);m.query.data={...sample(),revision:'b'.repeat(64)};await render();expect(buttons(c.confirm)[0].disabled).toBe(true);await click(c.confirm);expect(m.connect).not.toHaveBeenCalled();});
it('requires explicit local-copy consent to disconnect',async()=>{await render();await click(c.disconnect);expect(buttons(c.confirm)[0].disabled).toBe(true);await check('[role=dialog] input');m.connect.mockImplementation(async input=>receipt(input,'disconnect'));await click(c.confirm);expect(m.connect).toHaveBeenCalledWith({requestId:expect.any(String),revision,action:'disconnect',clearLocalCopies:true});});
it('stores metadata before sync, then recovers a successful result without another mutation',async()=>{m.sync.mockImplementation(async input=>{expect(readWooTracking(sessionStorage,7,20)).toEqual({requestId:input.requestId,revision,kind:'sync_products'});return receipt(input);});await render();await click(c.syncProducts);expect(m.sync).not.toHaveBeenCalled();await click(c.confirm);const input=m.sync.mock.calls[0][0];m.lookup.mockResolvedValue(receipt(input,'sync_products','success'));await click(c.recover);expect(container.textContent).toContain(c.opSuccess);expect(m.sync).toHaveBeenCalledOnce();expect(m.invalidate).toHaveBeenCalled();});
it('retains an ambiguous request and never re-sends it when recovering',async()=>{m.sync.mockRejectedValue(Error('PRIVATE'));await render();await click(c.syncProducts);await click(c.confirm);const intent=readWooTracking(sessionStorage,7,20)!;expect(container.textContent).toContain(c.requestUnknown);m.lookup.mockResolvedValue(receipt(intent,'sync_products','unknown'));await click(c.recover);expect(container.textContent).toContain(c.opUnknown);expect(buttons(c.syncProducts)[0].disabled).toBe(true);expect(m.sync).toHaveBeenCalledOnce();expect(container.textContent).not.toContain('PRIVATE');});
it('restores a stored request on reload with read-only recovery',async()=>{saveWooTracking(sessionStorage,7,20,{requestId,revision,kind:'sync_products'});m.lookup.mockResolvedValue(receipt({requestId,revision},'sync_products','success'));await render();expect(m.lookup).toHaveBeenCalledWith({requestId});expect(container.textContent).toContain(c.opSuccess);expect(m.sync).not.toHaveBeenCalled();});
it('does not dispatch when recovery storage cannot be written',async()=>{vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error('blocked');});await render();await click(c.syncProducts);await click(c.confirm);expect(container.textContent).toContain(c.storage);expect(m.sync).not.toHaveBeenCalled();});
it('does not accept a response for another request',async()=>{m.sync.mockImplementation(async input=>receipt({...input,requestId}));await render();await click(c.syncProducts);await click(c.confirm);expect(container.textContent).toContain(c.requestUnknown);expect(container.textContent).not.toContain(c.opSuccess);});
it('blocks foreign-member operations and acknowledges only the reviewed unknown ID',async()=>{m.blocker.data.operation={...receipt({requestId,revision},'sync_products','unknown'),actorId:8};await render();expect(buttons(c.syncProducts)[0].disabled).toBe(true);expect(container.textContent).toContain(c.otherActor);await click(c.acknowledge);m.ack.mockResolvedValue({actorId:7,merchantId:20,operation:{...m.blocker.data.operation,reviewRequired:false}});await act(async()=>buttons(c.acknowledge).at(-1)!.click());expect(m.ack).toHaveBeenCalledWith({requestId});expect(m.sync).not.toHaveBeenCalled();});
it('submits only reviewed incidents and rejects changed rows before submission',async()=>{await render();await click(c.incidents+' · 1');await check('.wc-records input');await click(c.reconcile+' · 1');m.incidents.data.rows[0].revision='b'.repeat(64);await render();expect(buttons(c.confirm)[0].disabled).toBe(true);expect(m.reconcile).not.toHaveBeenCalled();});
it('reconciles the selected row without adding newly arrived incidents',async()=>{await render();await click(c.incidents+' · 1');await check('.wc-records input');await click(c.reconcile+' · 1');m.reconcile.mockImplementation(async input=>receipt(input,'reconcile'));await click(c.confirm);expect(m.reconcile).toHaveBeenCalledWith({requestId:expect.any(String),revision,incidents:[{id:8,revision}]});});
it('hides rows from different filters, pages or tenants',()=>{expect(scopedWooLogs(logs(),7,20,{page:2})).toBeNull();expect(scopedWooIncidents(incidents(),7,999,{})).toBeNull();expect(scopedWooIncidents(incidents(),7,20,{resource:'order'})).toBeNull();});
it('keeps storage isolated and rejects secret-bearing records',()=>{const intent={requestId,revision,kind:'verify'};saveWooTracking(sessionStorage,7,20,intent);expect(readWooTracking(sessionStorage,8,20)).toBeNull();expect(readWooTracking(sessionStorage,7,21)).toBeNull();expect(()=>saveWooTracking(sessionStorage,7,20,{...intent,consumerSecret:'PRIVATE'})).toThrow();clearWooTracking(sessionStorage,7,20,'other');expect(readWooTracking(sessionStorage,7,20)).toEqual(intent);clearWooTracking(sessionStorage,7,20,requestId);expect(readWooTracking(sessionStorage,7,20)).toBeNull();});
it.each(['http://shop.example.test','https://user:secret@shop.example.test','https://127.0.0.1','https://shop.internal','https://shop.example.test?a=b','https://shop.example.test#x','https://shop.example.test:444','https://shop.example.test/wp-json/wc','https://bad_host.example.test'])('rejects unsafe destination %s',value=>expect(wooStoreDestination(value)).toBeNull());
it('does not guess currency or coerce large money into floating-point numbers',()=>{expect(wooMoneyLabel('9999999999999999.99','SAR',c.none)).toBe('9999999999999999.99 SAR');expect(wooMoneyLabel('1.00',null,c.none)).toBe('1.00');expect(wooMoneyLabel(null,'SAR',c.none)).toBe(c.none);});
it('rejects operation revisions or actors from another scope',()=>{const intent={requestId,revision,kind:'sync_products' as const};expect(scopedWooOperation(receipt(intent),7,20,{...intent,revision:'b'.repeat(64)})).toBeNull();expect(scopedWooOperation(receipt(intent),8,20,intent)).toBeNull();expect(validateWooConnection({storeUrl:'https://sample.example.test',consumerKey:'',consumerSecret:''},sample()).valid).toBe(true);});

function productsSample(){return {actorId:7,merchantId:20,checkedAt:stamp,selection:{search:'',state:'all',page:1},currency:'SAR',summary:{stored:2003,matched:1,groups:['instock','outofstock','onbackorder','unknown'].map(key=>({key,count:key==='instock'?1:0}))},pagination:{page:1,pageSize:25,total:1,pages:1},rows:[{id:3,merchantId:20,providerId:9001,name:'Sample product',slug:'sample',sku:'SKU-1',price:'9999999999999999.99',regularPrice:'9999999999999999.99',salePrice:null,state:'instock',manageStock:false,stockQuantity:null,imageUrl:null,syncState:'synced',lastSyncAt:stamp,providerUpdatedAt:stamp,invalidData:false}]};}
function analyticsSample(){const selection=wooDefaultPeriod();return {actorId:7,merchantId:20,checkedAt:stamp,timezone:'UTC',selection,summary:{storedOrders:2003,orders:4,statuses:['pending','processing','on-hold','completed','cancelled','refunded','failed','unknown'].map(key=>({key,count:key==='completed'?3:key==='pending'?1:0})),completed:3,completionRate:75,eligibleCompleted:2,excludedCompleted:1},currencies:['SAR','USD'].map((currency,i)=>({currency,orders:1,revenue:i?'10.00':'9999999999999999.99',averageOrderValue:i?'10.00':'9999999999999999.99',timeline:[{date:selection.startDate,orders:1,revenue:i?'10.00':'9999999999999999.99'}],products:{distinct:1,limit:10,validLines:1,excludedLines:0,invalidArrays:0,fallbackIdentityLines:0,rows:[{key:'a'.repeat(64),name:'Sample product',identity:'provider',quantity:1,revenue:'10.00'}]}})),customers:{definition:'email_first_phone_fallback',identifiedOrders:3,unidentifiedOrders:1,identities:2,singleOrder:1,repeat:1,repeatRate:50},conversations:{createdInRange:8,attributionAvailable:false,conversionRate:null,whatsappOrders:null,whatsappRevenue:null}};}
it.each(['ar','en'])('renders products and analytics with complete translations in %s',async language=>{m.language=language;m.view='products';await render();expect(container.querySelectorAll('[data-woo-product]')).toHaveLength(1);expect(container.textContent).not.toContain('merchantUx.');m.view='analytics';await render();expect(container.querySelectorAll('[data-woo-currency]')).toHaveLength(2);expect(container.textContent).not.toContain('merchantUx.');});
it('preserves viewer catalog access without offering integration writes',async()=>{m.view='products';m.access.data.integrationsManage=false;await render();expect(container.querySelector('[data-woo-product]')).not.toBeNull();expect(buttons(c.syncProducts)).toHaveLength(0);expect(container.querySelector('a[href="/merchant/woocommerce/settings"]')).toBeNull();expect(container.textContent).toContain(c.readOnly);});
it('keeps exact large product prices and explicit untracked stock',async()=>{m.view='products';await render();expect(container.textContent).toContain('9999999999999999.99 SAR');expect(container.textContent).toContain(c.stockUnmanaged);m.products.data.currency=null;await render();expect(container.textContent).toContain(c.currencyUnknown);expect(container.textContent).not.toContain('9999999999999999.99 SAR');});
it('searches a one-character query server-side and hides the old selection',async()=>{m.view='products';await render();await fill('input[type=search]','p');await click(c.apply);expect(m.productSelection).toEqual({page:1,state:'all',search:'p'});expect(container.querySelector('[data-woo-product]')).toBeNull();m.products.data={...productsSample(),selection:m.productSelection};await render();expect(container.querySelector('[data-woo-product]')).not.toBeNull();});
it('preserves catalog pagination independently from complete summary counts',async()=>{m.view='products';m.products.data.summary.matched=26;m.products.data.summary.groups[0].count=26;m.products.data.pagination={page:1,pageSize:25,total:26,pages:2};m.products.data.rows=Array.from({length:25},(_,i)=>({...productsSample().rows[0],id:100-i}));await render();expect(container.querySelectorAll('[data-woo-product]')).toHaveLength(25);await click(c.next);expect(m.productSelection.page).toBe(2);expect(container.querySelector('[data-woo-product]')).toBeNull();});
it.each(['products','analytics'])('rejects foreign and error-stale %s data',async view=>{m.view=view;const query=view==='products'?m.products:m.analytics;query.data.merchantId=999;await render();expect(container.textContent).not.toContain('Sample product');query.data.merchantId=20;query.error={message:'PRIVATE',data:{code:'INTERNAL_SERVER_ERROR'}};await render();expect(container.textContent).not.toContain('Sample product');expect(container.textContent).not.toContain('PRIVATE');});
it('reviews product sync against the current connection revision',async()=>{m.view='products';await render();await click(c.syncProducts);m.query.data={...sample(),revision:'b'.repeat(64)};await render();expect(buttons(c.confirm)[0].disabled).toBe(true);expect(m.sync).not.toHaveBeenCalled();});
it('separates revenue currencies and exposes source exclusions without claiming conversion',async()=>{m.view='analytics';await render();expect(container.querySelector('[data-woo-currency=SAR]')?.textContent).toContain('9999999999999999.99 SAR');expect(container.querySelector('[data-woo-currency=USD]')?.textContent).toContain('10.00 USD');expect(container.textContent).toContain(c.excludedCompleted+': 1');expect(container.textContent).toContain(c.attributionUnavailable);expect(container.textContent).toContain(c.customerHint);expect(container.querySelectorAll('.wc-sparkline')).toHaveLength(2);expect(m.sync).not.toHaveBeenCalled();});
it('keeps the applied report visible while editing dates and rejects invalid spans',async()=>{m.view='analytics';await render();const original={...m.analyticsSelection};await fill('input[type=date]','2020-01-01');expect(m.analyticsSelection).toEqual(original);await click(c.apply);expect(container.textContent).toContain(c.invalidRange);expect(m.analyticsSelection).toEqual(original);expect(document.activeElement?.getAttribute('type')).toBe('date');await fill('input[type=date]',original.endDate);await click(c.apply);expect(m.analyticsSelection.startDate).toBe(original.endDate);expect(container.querySelector('[data-woo-currency]')).toBeNull();});
it('does not claim zero rates for an empty period',async()=>{m.view='analytics';const s=m.analytics.data;s.summary={storedOrders:2003,orders:0,statuses:s.summary.statuses.map((g:any)=>({...g,count:0})),completed:0,completionRate:null,eligibleCompleted:0,excludedCompleted:0};s.currencies=[];s.customers={definition:'email_first_phone_fallback',identifiedOrders:0,unidentifiedOrders:0,identities:0,singleOrder:0,repeat:0,repeatRate:null};await render();expect(container.textContent).toContain(c.noSales);expect(container.querySelector('.sc-summary>div:last-child dd')?.textContent).toBe(c.none);});
it('uses an inclusive thirty-day UTC period across calendar boundaries',()=>{expect(wooDefaultPeriod(new Date('2026-03-01T00:20:00Z'))).toEqual({startDate:'2026-01-31',endDate:'2026-03-01',period:'daily'});});
it('computes only relative chart geometry without rounding monetary labels',()=>{expect(wooRevenuePoints(['0.00','9999999999999999.99','4999999999999999.99'])).toEqual([[0,170],[500,10],[1000,91]]);expect(wooRevenuePoints(['0.00'])).toEqual([[500,170]]);});

function orderRow(){return {id:4,merchantId:20,providerId:91001,orderNumber:'WOO-1001',state:'pending',rawStatus:'pending',currency:'SAR',total:'125.00',customerName:'Sample customer',customerPhone:'+966 50 000 0001',orderDate:stamp,syncState:'synced',lastSyncAt:stamp,providerUpdatedAt:stamp,invalidData:false};}
function ordersSample(){return {actorId:7,merchantId:20,checkedAt:stamp,selection:{search:'',state:'all',page:1},summary:{stored:2003,matched:1,groups:['pending','processing','on-hold','completed','cancelled','refunded','failed','unknown'].map(key=>({key,count:key==='pending'?1:0}))},pagination:{page:1,pageSize:25,total:1,pages:1},rows:[orderRow()]};}
function detailsSample(){return {actorId:7,merchantId:20,checkedAt:stamp,selection:{id:4,itemsPage:1},order:{...orderRow(),revision:'b'.repeat(64),customerEmail:'synthetic@example.test',subtotal:'100.00',shippingTotal:'10.00',totalTax:'15.00',discountTotal:'0.00',paymentMethod:'cod',paymentMethodTitle:'Cash',customerNote:'Original note',paidAt:null,completedAt:null,createdAt:stamp,updatedAt:stamp,items:{validArray:true,invalidItems:0,total:2,page:1,pageSize:25,pages:1,rows:[1,2].map(position=>({position,providerId:position,productId:position,variationId:0,name:'Item '+position,sku:'SKU-'+position,quantity:1,subtotal:'50.00',total:'50.00',invalidData:false}))}}};}
function actionSample(){return {actorId:7,merchantId:20,checkedAt:stamp,revision,configured:true,order:detailsSample().order,canChangeStatus:true,recipient:'966500000001',notificationChannelReady:true,canNotify:true};}
const select=(selector:string,value:string)=>act(async()=>{const input=document.querySelector(selector) as HTMLSelectElement;input.value=value;input.dispatchEvent(new Event('change',{bubbles:true}));});
const inDialog=(text:string)=>act(async()=>{const button=Array.from(document.querySelectorAll('[role=dialog] button')).find(el=>el.textContent===text) as HTMLButtonElement;expect(button).toBeTruthy();button.click();});
it.each(['ar','en'])('renders complete order details and both action forms in %s',async language=>{m.view='orders';m.language=language;const copy=(language==='ar'?ar:en).wooWorkspace;await render();expect(container.querySelectorAll('[data-woo-order]')).toHaveLength(1);await click(copy.details);expect(document.querySelectorAll('.wc-order-items>li')).toHaveLength(2);expect(document.querySelector('[role=dialog]')?.textContent).toContain('synthetic@example.test');await inDialog(copy.changeStatus);expect(document.querySelector('[role=dialog] select')).not.toBeNull();await inDialog(copy.notify);expect(document.querySelector('[role=dialog] input[readonly]')?.getAttribute('value')).toBe('966500000001');expect(document.body.textContent).not.toContain('merchantUx.');expect(m.update).not.toHaveBeenCalled();expect(m.notify).not.toHaveBeenCalled();});
it('keeps viewer order details while omitting every writer form',async()=>{m.view='orders';m.access.data.ordersManage=false;m.access.data.integrationsManage=false;await render();expect(buttons(c.changeStatus)).toHaveLength(0);expect(buttons(c.notify)).toHaveLength(0);expect(buttons(c.syncOrders)).toHaveLength(0);await click(c.details);expect(m.actionEnabled).toBe(false);expect(document.querySelectorAll('.wc-order-items>li')).toHaveLength(2);expect(buttons(c.changeStatus)).toHaveLength(0);});
it('sends order searches and valid paired dates to the server instead of filtering the current page',async()=>{m.view='orders';await render();await fill('input[type=search]','91001');await fill('input[type=date]','2026-10-01');await click(c.apply);expect(container.textContent).toContain(c.invalidRange);expect(m.orderSelection.search).toBe('');await fill('.sc-filters label:nth-of-type(4) input','2026-10-02');await click(c.apply);expect(m.orderSelection).toEqual({search:'91001',state:'all',page:1,startDate:'2026-10-01',endDate:'2026-10-02'});expect(container.querySelector('[data-woo-order]')).toBeNull();});
it('requires an actual status or note change before reviewing',async()=>{m.view='orders';await render();await click(c.changeStatus);expect(buttons(c.review)[0].disabled).toBe(true);await select('[role=dialog] select','completed');expect(buttons(c.review)[0].disabled).toBe(false);await inDialog(c.review);expect(m.update).not.toHaveBeenCalled();expect(document.querySelector('[role=dialog]')?.textContent).toContain(c.completed);m.update.mockImplementation(async input=>receipt(input,'order_status'));await inDialog(c.confirm);expect(m.update).toHaveBeenCalledWith({requestId:expect.any(String),revision,orderId:4,orderRevision:'b'.repeat(64),status:'completed'});});
it('distinguishes explicitly clearing the customer note from leaving it unchanged',async()=>{m.view='orders';await render();await click(c.changeStatus);await check('[role=dialog] input[type=checkbox]');await fill('[role=dialog] textarea','');await inDialog(c.review);expect(document.querySelector('[role=dialog]')?.textContent).toContain(c.clearNote);m.update.mockImplementation(async input=>receipt(input,'order_status'));await inDialog(c.confirm);expect(m.update.mock.calls[0][0]).toMatchObject({status:'pending',note:''});});
it.each(['connection','order'])('blocks an action review when the %s revision changes',async kind=>{m.view='orders';await render();await click(c.changeStatus);await select('[role=dialog] select','completed');await inDialog(c.review);if(kind==='connection')m.orderAction.data={...actionSample(),revision:'c'.repeat(64)};else{m.details.data={...detailsSample(),order:{...detailsSample().order,revision:'c'.repeat(64)}};m.orderAction.data={...actionSample(),order:m.details.data.order};}await render();expect(buttons(c.confirm)[0].disabled).toBe(true);expect(m.update).not.toHaveBeenCalled();});
it('refuses status changes without a known provider version',async()=>{m.view='orders';m.details.data.order.providerUpdatedAt=null;m.orderAction.data.order.providerUpdatedAt=null;m.orderAction.data.canChangeStatus=false;await render();await click(c.changeStatus);expect(document.querySelector('[role=dialog]')?.textContent).toContain(c.statusUnavailable);expect(buttons(c.review)[0].disabled).toBe(true);});
it('keeps messaging unavailable without a ready channel or a usable recipient',async()=>{m.view='orders';m.orderAction.data.notificationChannelReady=false;m.orderAction.data.canNotify=false;await render();await click(c.notify);expect(document.querySelector('[role=dialog]')?.textContent).toContain(c.notificationUnavailable);expect(buttons(c.review)[0].disabled).toBe(true);expect(m.notify).not.toHaveBeenCalled();});
it('validates message text beside the field and focuses it before review',async()=>{m.view='orders';await render();await click(c.notify);await fill('[role=dialog] textarea','   ');await inDialog(c.review);expect(document.querySelector('[role=dialog] textarea')?.getAttribute('aria-invalid')).toBe('true');expect(document.activeElement?.tagName).toBe('TEXTAREA');expect(m.notify).not.toHaveBeenCalled();});
it('sends the exact reviewed recipient and message and persists metadata only',async()=>{m.view='orders';await render();await click(c.notify);await fill('[role=dialog] textarea','  Reviewed customer message\nNext line  ');await inDialog(c.review);expect(document.querySelector('[role=dialog]')?.textContent).toContain('Reviewed customer message\nNext line');expect(m.notify).not.toHaveBeenCalled();m.notify.mockImplementation(async input=>{const raw=JSON.stringify(sessionStorage);expect(raw).not.toMatch(/Reviewed customer message|966500000001|orderRevision/);return receipt(input,'order_notify');});await inDialog(c.confirm);expect(m.notify).toHaveBeenCalledWith({requestId:expect.any(String),revision,orderId:4,orderRevision:'b'.repeat(64),recipient:'966500000001',message:'Reviewed customer message\nNext line'});});
it('shows provider acceptance without a delivery claim and never auto-notifies from status changes',async()=>{m.view='orders';m.notify.mockImplementation(async input=>({...receipt(input,'order_notify'),outcome:'success',result:{type:'notification',orderId:4,accepted:true,duplicate:false}}));await render();await click(c.notify);await inDialog(c.review);await inDialog(c.confirm);expect(container.textContent).toContain(c.accepted);expect(m.update).not.toHaveBeenCalled();});
it('retains an ambiguous notification for read-only recovery without sending it again',async()=>{m.view='orders';m.notify.mockRejectedValue(Error('PRIVATE'));await render();await click(c.notify);await inDialog(c.review);await inDialog(c.confirm);const intent=readWooTracking(sessionStorage,7,20)!;m.lookup.mockResolvedValue(receipt(intent,'order_notify','unknown'));await click(c.recover);expect(m.notify).toHaveBeenCalledOnce();expect(container.textContent).toContain(c.opUnknown);expect(container.textContent).not.toContain('PRIVATE');});
it('requests every order-item page and rejects stale items from the previous page',async()=>{m.view='orders';const base=m.details.data.order.items.rows[0];m.details.data.order.items={validArray:true,invalidItems:0,total:26,page:1,pageSize:25,pages:2,rows:Array.from({length:25},(_,i)=>({...base,position:i+1,name:'Item '+(i+1)}))};await render();await click(c.details);expect(document.querySelectorAll('.wc-order-items>li')).toHaveLength(25);await inDialog(c.next);expect(m.detailsSelection).toEqual({id:4,itemsPage:2});expect(document.querySelector('.wc-order-items')).toBeNull();m.details.data={...m.details.data,selection:{id:4,itemsPage:2},order:{...m.details.data.order,items:{...m.details.data.order.items,page:2,rows:[{...base,position:26,name:'Last item'}]}}};await render();expect(document.querySelectorAll('.wc-order-items>li')).toHaveLength(1);expect(document.body.textContent).toContain('Last item');});
it('hides a foreign order detail and never offers a mutation for it',async()=>{m.view='orders';m.details.data.order.merchantId=999;await render();await click(c.details);expect(document.querySelector('[role=dialog]')?.textContent).not.toContain('synthetic@example.test');expect(document.querySelector('[role=dialog] form')).toBeNull();});
it('ignores an old notification receipt after switching tenant',async()=>{m.view='orders';let finish!:(value:any)=>void;m.notify.mockImplementation(()=>new Promise(resolve=>finish=resolve));await render();await click(c.notify);await inDialog(c.review);await inDialog(c.confirm);const input=m.notify.mock.calls[0][0];m.merchant=21;m.access.data={...m.access.data,merchantId:21};m.orders.data={...ordersSample(),merchantId:21};await render();await act(async()=>finish({...receipt(input,'order_notify'),outcome:'success',result:{type:'notification',orderId:4,accepted:true,duplicate:false}}));expect(container.textContent).not.toContain(c.accepted);expect(readWooTracking(sessionStorage,7,21)).toBeNull();expect(m.invalidate).not.toHaveBeenCalled();});

it('rejects a saved receipt for a different order on recovery',()=>{const intent={requestId,revision,kind:'order_notify' as const,targetOrderId:4};const result={...receipt(intent,'order_notify'),outcome:'success',result:{type:'notification',orderId:5,accepted:true,duplicate:false}};expect(scopedWooOperation(result,7,20,intent)).toBeNull();expect(scopedWooOperation({...result,result:{...result.result,orderId:4}},7,20,intent)).not.toBeNull();});

it('returns keyboard focus to the page after clearing the last recovered receipt',async()=>{
 saveWooTracking(sessionStorage,7,20,{requestId,revision,kind:'sync_products'});m.lookup.mockResolvedValue(receipt({requestId,revision},'sync_products','success'));
 await render();const forget=buttons(c.forget)[0];forget.closest('details')!.open=true;forget.focus();await click(c.forget);
 expect(container.querySelector('.wc-operation')).toBeNull();expect(document.activeElement).toBe(container.querySelector('h1'));expect(readWooTracking(sessionStorage,7,20)).toBeNull();expect(m.sync).not.toHaveBeenCalled();
});
it('keeps focus and the receipt when clearing recovery storage fails',async()=>{
 saveWooTracking(sessionStorage,7,20,{requestId,revision,kind:'sync_products'});m.lookup.mockResolvedValue(receipt({requestId,revision},'sync_products','success'));await render();
 vi.spyOn(Storage.prototype,'removeItem').mockImplementation(()=>{throw Error('blocked');});const forget=buttons(c.forget)[0];forget.closest('details')!.open=true;forget.focus();await click(c.forget);
 expect(container.querySelector('.wc-operation')).not.toBeNull();expect(container.textContent).toContain(c.storage);expect(document.activeElement).toBe(forget);expect(m.sync).not.toHaveBeenCalled();
});
it('returns focus to the page when acknowledging the last other-member operation removes the panel',async()=>{
 m.blocker.data.operation={...receipt({requestId,revision},'sync_products','unknown'),actorId:8};await render();buttons(c.acknowledge)[0].focus();await click(c.acknowledge);
 m.ack.mockResolvedValue({actorId:7,merchantId:20,operation:{...m.blocker.data.operation,reviewRequired:false}});
 m.blockerRefresh.mockImplementation(async()=>{m.blocker.data.operation=null;return {data:m.blocker.data};});
 await act(async()=>buttons(c.acknowledge).at(-1)!.click());await act(async()=>{await new Promise(resolve=>setTimeout(resolve,5));});
 expect(container.querySelector('.wc-operation')).toBeNull();expect(document.querySelector('[role=dialog]')).toBeNull();expect(document.activeElement).toBe(container.querySelector('h1'));expect(m.ack).toHaveBeenCalledWith({requestId});expect(m.sync).not.toHaveBeenCalled();
});
