import {randomUUID} from 'node:crypto';
import {afterAll,afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({dns:vi.fn(),request:vi.fn()}));
vi.mock('axios',()=>({default:{request:m.request}}));
vi.mock('node:dns/promises',()=>({default:{lookup:m.dns}}));
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {requestReviewedWooSync} from './integrations/woocommerce-sync-request';
import {readWooWorkspace} from './integrations/woocommerce-workspace';
import {readWooOperation} from './integrations/woocommerce-operation';
import {encryptSecret} from './security/secrets';

describe.skipIf(!process.env.DATABASE_URL)('reviewed WooCommerce synchronization MySQL',()=>{
 let own:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof own,runs:Array<()=>Promise<void>>;
 const q=async(sql:string,args:any[]=[]) => (await(await getPool())!.execute<any>(sql,args))[0];
 const product=(id=1)=>({id,name:'Synthetic product '+id,price:'12.50',date_modified_gmt:'2026-09-30T12:00:00',stock_status:'instock'});
 const order={id:1,number:'W-1',status:'completed',currency:'SAR',total:'12.50',date_created_gmt:'2026-09-29T12:00:00',date_modified_gmt:'2026-09-30T12:00:00',billing:{first_name:'Synthetic'},line_items:[{name:'Sample',quantity:1,total:'12.50',subtotal:'12.50'}]};
 const response=(items:any[],total=items.length,pages=1)=>({status:200,headers:{'x-wp-total':String(total),'x-wp-totalpages':String(pages)},data:Buffer.from(JSON.stringify(items))});
 const input=async(resource='products')=>({requestId:randomUUID(),revision:(await readWooWorkspace(own.userId,own.merchantId)).revision,resource});
 const admit=(value:unknown,actor=own.userId)=>requestReviewedWooSync(actor,own.merchantId,value,run=>{runs.push(run);});
 const read=(requestId:string)=>readWooOperation(own.userId,own.merchantId,{requestId});
 const logs=()=>q('SELECT status,items_processed,last_sync_at FROM woocommerce_sync_logs l JOIN woocommerce_settings s ON s.merchant_id=l.merchant_id WHERE l.merchant_id=?',[own.merchantId]);
 beforeEach(async()=>{
  vi.resetAllMocks();runs=[];own=await createDisposableMerchant('woo-reviewed-sync');other=await createDisposableMerchant('woo-sync-other');
  await q("INSERT INTO woocommerce_settings(merchant_id,store_url,consumer_key,consumer_secret,is_active,connectionStatus) VALUES (?,'https://shop.example.com',?,?,1,'connected')",[own.merchantId,encryptSecret('ck_'+'a'.repeat(40)),encryptSecret('cs_'+'b'.repeat(40))]);
  await q("INSERT INTO woocommerce_products(merchant_id,woo_product_id,name,slug,price) VALUES (?,99,'Historical','history','5.00'),(?,99,'Foreign','foreign','6.00')",[own.merchantId,other.merchantId]);
  m.dns.mockResolvedValue([{address:'8.8.8.8',family:4}]);m.request.mockResolvedValue(response([product()]));
 });
 afterEach(async()=>{vi.restoreAllMocks();await cleanupDisposableMerchants([own.userId,other.userId]);});afterAll(closeDb);
 it.each(['products','orders'])('commits %s, log, timestamp and result together and only launches once',async resource=>{
  m.request.mockResolvedValue(response(resource==='products'?[product()]:[order]));const value=await input(resource);
  const results=await Promise.all([admit(value),admit(value)]);expect(results.every(r=>r.outcome==='pending')).toBe(true);expect(runs).toHaveLength(1);await runs[0]();
  expect(await read(value.requestId)).toMatchObject({outcome:'success',result:{type:'sync',[resource]:1,reconciled:0}});expect(await logs()).toEqual([expect.objectContaining({status:'success',items_processed:1,last_sync_at:expect.any(Date)})]);
  expect((await admit(value)).outcome).toBe('success');expect(runs).toHaveLength(1);expect(m.request).toHaveBeenCalledOnce();expect(await q('SELECT name FROM woocommerce_products WHERE merchant_id=?',[other.merchantId])).toEqual([{name:'Foreign'}]);
  if(resource==='products')expect(await q('SELECT woo_product_id FROM woocommerce_products WHERE merchant_id=?',[own.merchantId])).toEqual([{woo_product_id:1}]);
 });
 it('rejects stale reviews, payload changes, foreign actors and disabled connections before launch',async()=>{
  const value=await input();await expect(admit({...value,revision:'f'.repeat(64)})).rejects.toMatchObject({reason:'changed'});await expect(admit(value,other.userId)).rejects.toMatchObject({reason:'forbidden'});expect(runs).toHaveLength(0);
  await q('UPDATE woocommerce_settings SET is_active=0 WHERE merchant_id=?',[own.merchantId]);await expect(admit(await input())).rejects.toMatchObject({reason:'changed'});expect(m.dns).not.toHaveBeenCalled();
 });
 it('rejects connection changes while queued, before reading credentials or creating a running log',async()=>{const value=await input();await admit(value);await q("UPDATE woocommerce_settings SET consumer_secret=? WHERE merchant_id=?",[encryptSecret('cs_'+'z'.repeat(40)),own.merchantId]);await runs[0]();expect(await read(value.requestId)).toMatchObject({outcome:'rejected',started:false});expect(m.dns).not.toHaveBeenCalled();expect(await logs()).toHaveLength(0);});
 it('checks the connection again after DNS and transmits no revoked credentials',async()=>{m.dns.mockImplementation(async()=>{await q('UPDATE woocommerce_settings SET is_active=0 WHERE merchant_id=?',[own.merchantId]);return [{address:'8.8.8.8',family:4}];});const value=await input();await admit(value);await runs[0]();expect(m.request).not.toHaveBeenCalled();expect(await read(value.requestId)).toMatchObject({outcome:'unknown',reviewRequired:true});expect((await logs())[0]).toMatchObject({status:'failed',last_sync_at:null});});
 it('checks membership after a provider response and preserves all old data',async()=>{m.request.mockImplementation(async()=>{await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'owner',0)",[own.merchantId,own.userId]);return response([product()]);});const value=await input();await admit(value);await runs[0]();expect((await q('SELECT state FROM woocommerce_operations WHERE merchant_id=?',[own.merchantId]))[0].state).toBe('unknown');expect(await q('SELECT woo_product_id FROM woocommerce_products WHERE merchant_id=?',[own.merchantId])).toEqual([{woo_product_id:99}]);expect((await logs())[0].status).toBe('failed');});
 it('will not continue after its lease expires during a request',async()=>{m.request.mockImplementation(async()=>{await q('UPDATE woocommerce_operations SET lease_until=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE merchant_id=?',[own.merchantId]);return response([product()]);});const value=await input();await admit(value);await runs[0]();expect((await read(value.requestId)).outcome).toBe('unknown');expect((await logs())[0]).toMatchObject({status:'failed',last_sync_at:null});});
 it('fetches every page before replacement and refuses an incomplete provider snapshot',async()=>{m.request.mockResolvedValueOnce(response([product(1)],2,2)).mockResolvedValueOnce(response([product(2)],3,2));const value=await input();await admit(value);await runs[0]();expect(m.request).toHaveBeenCalledTimes(2);expect((await read(value.requestId)).outcome).toBe('unknown');expect(await q('SELECT woo_product_id FROM woocommerce_products WHERE merchant_id=?',[own.merchantId])).toEqual([{woo_product_id:99}]);});
 it('rolls back the snapshot and timestamp if saving the success log fails',async()=>{const value=await input();await admit(value);const pool=(await getPool())!,get=pool.getConnection.bind(pool);let failed=false;vi.spyOn(pool,'getConnection').mockImplementation(async()=>{const tx=await get(),execute=tx.execute.bind(tx);vi.spyOn(tx,'execute').mockImplementation((async(sql:any,args:any)=>{if(typeof sql==='string'&&sql.startsWith("UPDATE woocommerce_sync_logs SET status='success'")&&!failed){failed=true;throw Error('PRIVATE storage failure');}return execute(sql,args);}) as any);return tx;});await runs[0]();expect(failed).toBe(true);expect(await q('SELECT woo_product_id FROM woocommerce_products WHERE merchant_id=?',[own.merchantId])).toEqual([{woo_product_id:99}]);expect((await logs())[0]).toMatchObject({status:'failed',last_sync_at:null});expect((await read(value.requestId)).outcome).toBe('unknown');});
 it('recovers a committed result when its acknowledgement is lost, without downgrading its log',async()=>{const value=await input();await admit(value);const pool=(await getPool())!,get=pool.getConnection.bind(pool);let lost=false;vi.spyOn(pool,'getConnection').mockImplementation(async()=>{const tx=await get(),execute=tx.execute.bind(tx),commit=tx.commit.bind(tx);let completing=false;vi.spyOn(tx,'execute').mockImplementation((async(sql:any,args:any)=>{if(typeof sql==='string'&&sql.startsWith("UPDATE woocommerce_operations SET state='success'"))completing=true;return execute(sql,args);}) as any);vi.spyOn(tx,'commit').mockImplementation(async()=>{await commit();if(completing&&!lost){lost=true;throw Error('PRIVATE acknowledgement lost');}});return tx;});await runs[0]();expect(lost).toBe(true);expect((await read(value.requestId)).outcome).toBe('success');expect((await logs())[0].status).toBe('success');expect((await admit(value)).outcome).toBe('success');expect(runs).toHaveLength(1);});
 it('does not launch after a lost admission acknowledgement and never dispatches on replay',async()=>{const value=await input(),pool=(await getPool())!,get=pool.getConnection.bind(pool);let lost=false;vi.spyOn(pool,'getConnection').mockImplementation(async()=>{const tx=await get(),commit=tx.commit.bind(tx);vi.spyOn(tx,'commit').mockImplementation(async()=>{await commit();if(!lost){lost=true;throw Error('PRIVATE acknowledgement lost');}});return tx;});await expect(admit(value)).rejects.toMatchObject({reason:'unavailable'});expect(runs).toHaveLength(0);expect((await admit(value)).outcome).toBe('pending');expect(runs).toHaveLength(0);expect(m.request).not.toHaveBeenCalled();});
 it('rejects an admission cleanly when the launcher fails',async()=>{const value=await input();await expect(requestReviewedWooSync(own.userId,own.merchantId,value,()=>{throw Error('PRIVATE launch failed');})).rejects.toMatchObject({reason:'unavailable'});expect(await read(value.requestId)).toMatchObject({outcome:'rejected',started:false});expect(m.request).not.toHaveBeenCalled();});
});
