import {randomUUID} from 'node:crypto';
import {afterAll,afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({request:vi.fn(),dns:vi.fn()}));
vi.mock('axios',()=>({default:{request:m.request}}));vi.mock('node:dns/promises',()=>({default:{lookup:m.dns}}));
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {readWooWorkspace} from './integrations/woocommerce-workspace';
import {requestReviewedWooConnection} from './integrations/woocommerce-connection';
import {readWooOperation} from './integrations/woocommerce-operation';
import {encryptSecret,decryptSecret} from './security/secrets';
import {WOOCOMMERCE_WEBHOOK_TOPICS} from './webhooks/woocommerce-security';
describe.skipIf(!process.env.DATABASE_URL)('reviewed WooCommerce connection MySQL',()=>{
 let own:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof own,runs:Array<()=>Promise<void>>,remote:Map<string,any>,nextId:number;
 const keys={consumerKey:'ck_'+'a'.repeat(40),consumerSecret:'cs_'+'b'.repeat(40)},storeUrl='https://shop.example.com',endpoint='E'.repeat(43);
 const q=async(sql:string,args:any[]=[]) => (await(await getPool())!.execute<any>(sql,args))[0];
 const body=(value:unknown,status=200)=>({status,headers:{},data:Buffer.from(JSON.stringify(value))});
 const network=async(config:any)=>{
  if(config.url.endsWith('/system_status'))return body({environment:{version:'9.1'}});
  if(config.method==='POST'){const id=++nextId,hook={id,...config.data};remote.set(String(id),hook);return body(hook);}
  const id=config.url.split('/').at(-1);
  if(config.method==='DELETE'){if(!remote.has(id))return body({},404);const previous=remote.get(id);remote.delete(id);return body(previous);}
  return remote.has(id)?body(remote.get(id)):body({},404);
 };
 const define=async(withHooks=true)=>{
  await q("INSERT INTO woocommerce_settings(merchant_id,store_url,consumer_key,consumer_secret,is_active,connectionStatus,webhook_endpoint_id,webhook_signing_secret,store_currency) VALUES (?,?,?,?,1,'connected',?,?,'SAR')",[own.merchantId,storeUrl,encryptSecret(keys.consumerKey),encryptSecret(keys.consumerSecret),endpoint,encryptSecret('SYNTHETIC_SIGNING_SECRET'.repeat(3))]);
  if(withHooks)for(let i=0;i<6;i++){const id=String(i+1),topic=WOOCOMMERCE_WEBHOOK_TOPICS[i];await q('INSERT INTO woocommerce_webhook_registrations(merchant_id,topic,webhook_id) VALUES (?,?,?)',[own.merchantId,topic,id]);remote.set(id,{id:Number(id),topic,status:'active',delivery_url:'https://sary.example.test/api/webhooks/woocommerce/'+endpoint});}
  await q("INSERT INTO woocommerce_products(merchant_id,woo_product_id,name,slug,price) VALUES (?,55,'Keep','keep','1.00'),(?,55,'Foreign','foreign','2.00')",[own.merchantId,other.merchantId]);
  await q("UPDATE merchants SET integration_source='woocommerce' WHERE id=?",[own.merchantId]);
 };
 const input=async(extra:any={action:'connect',storeUrl,...keys})=>({requestId:randomUUID(),revision:(await readWooWorkspace(own.userId,own.merchantId)).revision,...extra});
 const admit=(value:unknown,actor=own.userId)=>requestReviewedWooConnection(actor,own.merchantId,value,run=>{runs.push(run);});
 const read=(requestId:string)=>readWooOperation(own.userId,own.merchantId,{requestId});
 const saved=()=>q('SELECT store_url,consumer_key,consumer_secret FROM woocommerce_settings WHERE merchant_id=?',[own.merchantId]);
 beforeEach(async()=>{vi.resetAllMocks();vi.stubEnv('PUBLIC_APP_URL','https://sary.example.test');vi.stubEnv('FIELD_ENCRYPTION_KEY','synthetic-phase326-field-encryption-key');runs=[];remote=new Map();nextId=100;own=await createDisposableMerchant('woo-reviewed-connection');other=await createDisposableMerchant('woo-connection-other');m.dns.mockResolvedValue([{address:'8.8.8.8',family:4}]);m.request.mockImplementation(network);});
 afterEach(async()=>{vi.restoreAllMocks();vi.unstubAllEnvs();await cleanupDisposableMerchants([own.userId,other.userId]);});afterAll(closeDb);
 it('connects once with encrypted credentials, six registrations and atomic result evidence',async()=>{const value=await input();await Promise.all([admit(value),admit(value)]);expect(runs).toHaveLength(1);await runs[0]();expect(await read(value.requestId)).toMatchObject({outcome:'success',result:{type:'connection',configured:true,verification:'api_and_webhooks',remoteCleanup:'not_needed',localCopies:'retained'}});const row=(await saved())[0];expect(row.consumer_key).not.toBe(keys.consumerKey);expect(decryptSecret(row.consumer_secret)).toBe(keys.consumerSecret);expect((await readWooWorkspace(own.userId,own.merchantId)).webhooks.ready).toBe(true);expect(remote.size).toBe(6);expect((await admit(value)).outcome).toBe('success');expect(runs).toHaveLength(1);const evidence=await q('SELECT * FROM woocommerce_operations WHERE merchant_id=?',[own.merchantId]);expect(JSON.stringify(evidence)).not.toContain(keys.consumerSecret);expect(m.request).toHaveBeenCalledTimes(7);});
 it('requires explicit new credentials and local-copy replacement for a changed root',async()=>{await define();for(const extra of [{},{...keys},{replaceLocalCopies:true},{replaceLocalCopies:true,consumerKey:keys.consumerKey}])await expect(admit(await input({action:'connect',storeUrl:'https://different.example.com',...extra}))).rejects.toMatchObject({reason:'changed'});expect(m.request).not.toHaveBeenCalled();const value=await input({action:'connect',storeUrl:'https://different.example.com',...keys,replaceLocalCopies:true});await admit(value);await runs[0]();expect(await read(value.requestId)).toMatchObject({outcome:'success',result:{localCopies:'cleared',remoteCleanup:'confirmed'}});expect(await q('SELECT id FROM woocommerce_products WHERE merchant_id=?',[own.merchantId])).toHaveLength(0);expect(await q('SELECT name FROM woocommerce_products WHERE merchant_id=?',[other.merchantId])).toEqual([{name:'Foreign'}]);expect((await saved())[0].store_url).toBe('https://different.example.com');});
 it('preserves local products for a canonically identical URL and allows stored credential reuse',async()=>{await define();await q("UPDATE woocommerce_settings SET store_url='https://SHOP.example.com///' WHERE merchant_id=?",[own.merchantId]);const value=await input({action:'connect',storeUrl:'https://shop.example.com/'});await admit(value);await runs[0]();expect(await read(value.requestId)).toMatchObject({outcome:'success',result:{localCopies:'retained'}});expect(await q('SELECT name FROM woocommerce_products WHERE merchant_id=?',[own.merchantId])).toEqual([{name:'Keep'}]);});
 it('verifies the API and existing hooks without posting or deleting anything',async()=>{await define();const before=await readWooWorkspace(own.userId,own.merchantId),value=await input({action:'verify'});await admit(value);await runs[0]();expect(await read(value.requestId)).toMatchObject({outcome:'success',result:{verification:'api_and_webhooks',remoteCleanup:'not_needed'}});expect(m.request.mock.calls.every(([r])=>r.method==='GET')).toBe(true);expect((await readWooWorkspace(own.userId,own.merchantId)).webhooks).toEqual(before.webhooks);expect(remote.size).toBe(6);});
 it('reports API-only verification when hooks are absent and never silently registers them',async()=>{await define(false);const value=await input({action:'verify'});await admit(value);await runs[0]();expect(await read(value.requestId)).toMatchObject({outcome:'success',result:{verification:'api'}});expect(m.request).toHaveBeenCalledOnce();expect(remote.size).toBe(0);expect((await readWooWorkspace(own.userId,own.merchantId)).webhooks.ready).toBe(false);});
 it('keeps remote cleanup uncertainty separate from confirmed local disconnection',async()=>{await define();m.request.mockImplementation(async c=>c.method==='DELETE'?body({},503):network(c));const value=await input({action:'disconnect',clearLocalCopies:true});await admit(value);await runs[0]();expect(await read(value.requestId)).toMatchObject({outcome:'success',result:{configured:false,remoteCleanup:'unconfirmed',localCopies:'cleared',verification:'not_checked'}});expect(await saved()).toHaveLength(0);expect(remote.size).toBe(6);expect((await q('SELECT integration_source FROM merchants WHERE id=?',[own.merchantId]))[0].integration_source).toBe('none');expect(await q('SELECT name FROM woocommerce_products WHERE merchant_id=?',[other.merchantId])).toEqual([{name:'Foreign'}]);});
 it('accepts authenticated missing hooks as already cleaned and preserves operation receipts after clear',async()=>{await define();remote.clear();const value=await input({action:'disconnect',clearLocalCopies:true});await admit(value);await runs[0]();expect(await read(value.requestId)).toMatchObject({outcome:'success',result:{remoteCleanup:'confirmed'}});expect((await admit(value)).outcome).toBe('success');expect(runs).toHaveLength(1);});
 it('checks platform competition before networking and again after the provider creates hooks',async()=>{const value=await input();await q("INSERT INTO platform_integrations(merchant_id,platform_type,access_token,is_active) VALUES (?,'zid','SYNTHETIC',1)",[own.merchantId]);await expect(admit(value)).rejects.toMatchObject({reason:'changed'});expect(m.request).not.toHaveBeenCalled();await q('DELETE FROM platform_integrations WHERE merchant_id=?',[own.merchantId]);await admit(value);m.request.mockImplementation(async c=>{const r=await network(c);if(c.method==='POST'&&remote.size===6)await q("INSERT INTO platform_integrations(merchant_id,platform_type,access_token,is_active) VALUES (?,'zid','SYNTHETIC',1)",[own.merchantId]);return r;});await runs[0]();expect((await read(value.requestId)).outcome).toBe('unknown');expect(await saved()).toHaveLength(0);expect(m.request.mock.calls.filter(([r])=>r.method==='DELETE')).toHaveLength(0);});
 it('stops a stale connection change while queued and denies a foreign actor',async()=>{await define();const value=await input({action:'verify'});await expect(admit(value,other.userId)).rejects.toMatchObject({reason:'forbidden'});await admit(value);await q('UPDATE woocommerce_settings SET is_active=0 WHERE merchant_id=?',[own.merchantId]);await runs[0]();expect(await read(value.requestId)).toMatchObject({outcome:'rejected',started:false});expect(m.request).not.toHaveBeenCalled();});
 it('stops after revocation during provider work and never replaces local credentials',async()=>{await define();const value=await input();await admit(value);m.request.mockImplementationOnce(async c=>{await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'owner',0)",[own.merchantId,own.userId]);return network(c);});await runs[0]();expect((await q('SELECT state FROM woocommerce_operations WHERE merchant_id=?',[own.merchantId]))[0].state).toBe('unknown');expect(m.request).toHaveBeenCalledOnce();expect(remote.size).toBe(6);expect(decryptSecret((await saved())[0].consumer_secret)).toBe(keys.consumerSecret);});
 it('preserves the successful connection and new remote hooks after a lost final acknowledgement',async()=>{const value=await input();await admit(value);const pool=(await getPool())!,get=pool.getConnection.bind(pool);let lost=false;vi.spyOn(pool,'getConnection').mockImplementation(async()=>{const tx=await get(),execute=tx.execute.bind(tx),commit=tx.commit.bind(tx);let completing=false;vi.spyOn(tx,'execute').mockImplementation((async(sql:any,args:any)=>{if(typeof sql==='string'&&sql.startsWith("UPDATE woocommerce_operations SET state='success'"))completing=true;return execute(sql,args);}) as any);vi.spyOn(tx,'commit').mockImplementation(async()=>{await commit();if(completing&&!lost){lost=true;throw Error('PRIVATE acknowledgement lost');}});return tx;});await runs[0]();expect(lost).toBe(true);expect((await read(value.requestId)).outcome).toBe('success');expect(await saved()).toHaveLength(1);expect(remote.size).toBe(6);expect(m.request.mock.calls.filter(([r])=>r.method==='DELETE')).toHaveLength(0);});
 it('rolls back destructive local clearing when final operation evidence fails',async()=>{await define();const value=await input({action:'disconnect',clearLocalCopies:true});await admit(value);const pool=(await getPool())!,get=pool.getConnection.bind(pool);let failed=false;vi.spyOn(pool,'getConnection').mockImplementation(async()=>{const tx=await get(),execute=tx.execute.bind(tx);vi.spyOn(tx,'execute').mockImplementation((async(sql:any,args:any)=>{if(typeof sql==='string'&&sql.startsWith("UPDATE woocommerce_operations SET state='success'")&&!failed){failed=true;throw Error('PRIVATE persistence failed');}return execute(sql,args);}) as any);return tx;});await runs[0]();expect(failed).toBe(true);expect((await read(value.requestId)).outcome).toBe('unknown');expect(await saved()).toHaveLength(1);expect(await q('SELECT name FROM woocommerce_products WHERE merchant_id=?',[own.merchantId])).toEqual([{name:'Keep'}]);expect(remote.size).toBe(0);});
 it.each(['connect','disconnect'])('allows explicit %s when old credentials are corrupt, with cleanup marked unconfirmed',async action=>{await define();await q("UPDATE woocommerce_settings SET consumer_secret='enc:v1:invalid' WHERE merchant_id=?",[own.merchantId]);const value=await input(action==='connect'?{action,storeUrl,...keys}:{action,clearLocalCopies:true});await admit(value);await runs[0]();expect(await read(value.requestId)).toMatchObject({outcome:'success',result:{configured:action==='connect',remoteCleanup:'unconfirmed'}});expect(m.request.mock.calls.filter(([r])=>r.method==='DELETE')).toHaveLength(0);if(action==='connect')expect(decryptSecret((await saved())[0].consumer_secret)).toBe(keys.consumerSecret);else expect(await saved()).toHaveLength(0);});
});

