import {randomUUID} from 'node:crypto';
import {afterAll,afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({send:vi.fn(),afterRead:vi.fn()}));
vi.mock('./channels/whatsapp/providers',()=>({getWhatsAppProvider:()=>({send:m.send})}));
vi.mock('./db',async original=>{const db=await original<typeof import('./db')>();return {...db,getPrimaryWhatsAppInstance:async(id:number)=>{const value=await db.getPrimaryWhatsAppInstance(id);await m.afterRead();return value;}};});
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {readWooOrderActionWorkspace} from './integrations/woocommerce-order-action';
import {requestReviewedWooNotification} from './integrations/woocommerce-order-notification';
import {readWooOperation,reserveWooOperation,startWooOperation} from './integrations/woocommerce-operation';
import {sendMerchantWhatsApp} from './channels/whatsapp/service';
import {privacyHashExact} from './accounts/privacy-hash';
import type {SendMerchantWhatsAppInput} from './channels/whatsapp/types';
describe.skipIf(!process.env.DATABASE_URL)('reviewed WooCommerce notification transport MySQL',()=>{
 let own:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof own,runs:Array<()=>Promise<void>>,id:number,instanceId:number;
 const q=async(sql:string,args:any[]=[]) => (await(await getPool())!.execute<any>(sql,args))[0];
 const workspace=()=>readWooOrderActionWorkspace(own.userId,own.merchantId,{orderId:id});
 const input=async()=>{const review=await workspace();return {requestId:randomUUID(),revision:review.revision,orderId:id,orderRevision:review.order!.revision,recipient:'966500000001',message:'Synthetic reviewed notification'};};
 const admit=(value:unknown)=>requestReviewedWooNotification(own.userId,own.merchantId,value,run=>{runs.push(run);});
 const read=(requestId:string)=>readWooOperation(own.userId,own.merchantId,{requestId});
 const deliveries=()=>q('SELECT status,provider_message_id,request_json FROM whatsapp_message_deliveries WHERE merchant_id=?',[own.merchantId]);
 beforeEach(async()=>{vi.resetAllMocks();runs=[];own=await createDisposableMerchant('woo-reviewed-notice');other=await createDisposableMerchant('woo-notice-other');await q("INSERT INTO woocommerce_settings(merchant_id,store_url,consumer_key,consumer_secret,is_active,connectionStatus) VALUES (?,'https://shop.example.com','ck_synthetic_not_used','cs_synthetic_not_used',1,'connected')",[own.merchantId]);id=Number((await q("INSERT INTO woocommerce_orders(merchant_id,woo_order_id,order_number,status,currency,total,subtotal,order_date,provider_updated_at,line_items,customer_phone) VALUES (?,71,'W-71','pending','SAR','12.50','12.50','2026-09-29 12:00:00','2026-09-30 12:00:00','[]','+966 (50) 000-0001')",[own.merchantId])).insertId);instanceId=Number((await q("INSERT INTO whatsapp_instances(merchant_id,instance_id,token,provider,status,is_primary) VALUES (?,?,'SYNTHETIC_CHANNEL_TOKEN','mock','active',1)",[own.merchantId,'fixture-'+randomUUID()])).insertId);m.send.mockResolvedValue({accepted:true,status:'sent',outcome:'accepted',providerMessageId:'synthetic-accepted'});});
 afterEach(async()=>{vi.restoreAllMocks();await cleanupDisposableMerchants([own.userId,other.userId]);});afterAll(closeDb);
 it('reviews normalized destination and active primary channel without exposing channel credentials',async()=>{expect(await workspace()).toMatchObject({recipient:'966500000001',notificationChannelReady:true,canNotify:true});expect(JSON.stringify(await workspace())).not.toContain('SYNTHETIC_CHANNEL_TOKEN');await q("UPDATE whatsapp_instances SET status='inactive',is_primary=0 WHERE id=?",[instanceId]);expect(await workspace()).toMatchObject({notificationChannelReady:false,canNotify:false});});
 it('sends once and commits channel acceptance with operation evidence; replay only reads',async()=>{const value=await input();await Promise.all([admit(value),admit(value)]);expect(runs).toHaveLength(1);await runs[0]();expect(await read(value.requestId)).toMatchObject({outcome:'success',result:{type:'notification',orderId:id,accepted:true,duplicate:false}});expect(m.send).toHaveBeenCalledOnce();expect(m.send.mock.calls[0][1]).toMatchObject({to:value.recipient,text:value.message,kind:'text'});expect((await deliveries())[0]).toMatchObject({status:'sent',provider_message_id:'synthetic-accepted'});expect((await admit(value)).outcome).toBe('success');expect(runs).toHaveLength(1);});
 it('rejects a different recipient and a stale order before admission, and refuses altered replay text',async()=>{const value=await input();for(const change of [{recipient:'966500000002'},{orderRevision:'a'.repeat(64)}])await expect(admit({...value,...change})).rejects.toMatchObject({reason:'changed'});await admit(value);await expect(admit({...value,message:'Altered'})).rejects.toMatchObject({reason:'changed'});expect(m.send).not.toHaveBeenCalled();});
 it('does not send after the reviewed phone changes while queued',async()=>{const value=await input();await admit(value);await q("UPDATE woocommerce_orders SET customer_phone='966500000002' WHERE id=?",[id]);await runs[0]();expect(await read(value.requestId)).toMatchObject({outcome:'rejected',started:false});expect(m.send).not.toHaveBeenCalled();});
 it.each(['permission','phone','channel','connection','lease'])('checks %s again after channel lookup and before the actual provider call',async mode=>{const value=await input();await admit(value);m.afterRead.mockImplementationOnce(async()=>{if(mode==='permission')await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'owner',0)",[own.merchantId,own.userId]);if(mode==='phone')await q("UPDATE woocommerce_orders SET customer_phone='966500000002' WHERE id=?",[id]);if(mode==='channel')await q("UPDATE whatsapp_instances SET token='CHANGED_TOKEN' WHERE id=?",[instanceId]);if(mode==='connection')await q('UPDATE woocommerce_settings SET is_active=0 WHERE merchant_id=?',[own.merchantId]);if(mode==='lease')await q('UPDATE woocommerce_operations SET lease_until=DATE_SUB(UTC_TIMESTAMP(3),INTERVAL 1 SECOND) WHERE merchant_id=?',[own.merchantId]);});await runs[0]();expect(m.send).not.toHaveBeenCalled();expect((await q('SELECT state FROM woocommerce_operations WHERE merchant_id=?',[own.merchantId]))[0].state).toBe('unknown');expect((await deliveries())[0].status).toBe('failed');});
 it.each(['text','recipient','token','foreign_actor','guard_removed','retry'])('rejects tampered transport %s despite a durable admission',async mode=>{const value=await input();const digest=privacyHashExact(JSON.stringify({orderId:id,orderRevision:value.orderRevision,recipient:value.recipient,message:value.message}));const admitted=await reserveWooOperation(own.userId,own.merchantId,{requestId:value.requestId,revision:value.revision,kind:'order_notify',payloadDigest:digest},async()=>{});await startWooOperation(admitted.lease!,async()=>{});const transport:SendMerchantWhatsAppInput={merchantId:own.merchantId,idempotencyKey:`woo-reviewed-notice:${own.merchantId}:${value.requestId}`,kind:'text',to:value.recipient,text:value.message,retryFailed:false,wooOrderGuard:{lease:admitted.lease!,requestId:value.requestId,revision:value.revision,orderId:id,orderRevision:value.orderRevision}};if(mode==='text')transport.text='Altered';if(mode==='recipient')transport.to='966500000002';if(mode==='token')transport.wooOrderGuard={...transport.wooOrderGuard!,lease:{...admitted.lease!,token:randomUUID()}};if(mode==='foreign_actor')transport.wooOrderGuard={...transport.wooOrderGuard!,lease:{...admitted.lease!,actorId:other.userId}};if(mode==='guard_removed')transport.wooOrderGuard=undefined;if(mode==='retry')transport.retryFailed=true;expect((await sendMerchantWhatsApp(transport)).accepted).toBe(false);expect(m.send).not.toHaveBeenCalled();});
 it.each(['unknown','rejected'])('never resends a %s channel result through operation replay or guard stripping',async mode=>{m.send.mockResolvedValue({accepted:false,status:'failed',outcome:mode,errorCode:mode==='unknown'?'provider_unreachable':'http_400'});const value=await input();await admit(value);await runs[0]();expect((await read(value.requestId)).outcome).toBe('unknown');await admit(value);expect(runs).toHaveLength(1);expect(m.send).toHaveBeenCalledOnce();const original=m.send.mock.calls[0][1];expect((await sendMerchantWhatsApp({...original,wooOrderGuard:undefined,retryFailed:true})).accepted).toBe(false);expect(m.send).toHaveBeenCalledOnce();expect((await deliveries())[0].status).toBe(mode==='unknown'?'queued':'failed');});
 it('holds account and order authority through provider dispatch and both receipt writes',async()=>{const value=await input();await admit(value);let enter!:()=>void,finish!:()=>void;const entered=new Promise<void>(r=>enter=r),gate=new Promise<void>(r=>finish=r);m.send.mockImplementation(async()=>{enter();await gate;return {accepted:true,status:'sent',providerMessageId:'synthetic-accepted'};});const running=runs[0]();await entered;let revoked=false;const revoking=q("UPDATE users SET account_status='deletion_pending' WHERE id=?",[own.userId]).then(()=>{revoked=true;});try{await new Promise(r=>setTimeout(r,40));expect(revoked).toBe(false);}finally{finish();await running;await revoking;}expect((await q('SELECT state FROM woocommerce_operations WHERE merchant_id=?',[own.merchantId]))[0].state).toBe('success');expect((await deliveries())[0].status).toBe('sent');});
 it.each([false,true])('keeps channel and operation evidence atomic when final acknowledgement loss is %s',async lost=>{const value=await input();await admit(value);const pool=(await getPool())!,get=pool.getConnection.bind(pool);let hit=false;vi.spyOn(pool,'getConnection').mockImplementation(async()=>{const tx=await get(),execute=tx.execute.bind(tx),commit=tx.commit.bind(tx);let completing=false;vi.spyOn(tx,'execute').mockImplementation((async(sql:any,args:any)=>{if(typeof sql==='string'&&sql.startsWith("UPDATE woocommerce_operations SET state='success'")){completing=true;if(!lost&&!hit){hit=true;throw Error('PRIVATE failed evidence');}}return execute(sql,args);}) as any);vi.spyOn(tx,'commit').mockImplementation(async()=>{await commit();if(lost&&completing&&!hit){hit=true;throw Error('PRIVATE lost acknowledgement');}});return tx;});await runs[0]();expect(hit).toBe(true);expect((await read(value.requestId)).outcome).toBe(lost?'success':'unknown');expect((await deliveries())[0].status).toBe(lost?'sent':'queued');expect(m.send).toHaveBeenCalledOnce();await admit(value);expect(runs).toHaveLength(1);});
});


