import {randomUUID} from 'node:crypto';
import {afterAll,afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({request:vi.fn(),dns:vi.fn()}));
vi.mock('axios',()=>({default:{request:m.request}}));vi.mock('node:dns/promises',()=>({default:{lookup:m.dns}}));
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {readWooIncidentsWorkspace} from './integrations/woocommerce-incidents';
import {readWooWorkspace} from './integrations/woocommerce-workspace';
import {requestReviewedWooReconciliation} from './integrations/woocommerce-sync-request';
import {readWooOperation} from './integrations/woocommerce-operation';
import {encryptSecret} from './security/secrets';

describe.skipIf(!process.env.DATABASE_URL)('WooCommerce selected incident reconciliation MySQL',()=>{
 let own:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof own,runs:Array<()=>Promise<void>>;
 const q=async(sql:string,args:any[]=[]) => (await(await getPool())!.execute<any>(sql,args))[0];
 const incident=async(merchantId=own.merchantId,status='manual_review',resourceId=71,topic='product.updated')=>{const r=await q('INSERT INTO woocommerce_webhook_receipts(merchant_id,delivery_id,webhook_id,topic,resource_id,status,last_error) VALUES (?,?,?,?,?,?,?)',[merchantId,randomUUID().replaceAll('-',''),'991',topic,resourceId,status,'PRIVATE_PROVIDER_ERROR']);return Number(r.insertId);};
 const list=(raw:unknown={})=>readWooIncidentsWorkspace(own.userId,own.merchantId,raw);
 const input=async()=>({requestId:randomUUID(),revision:(await readWooWorkspace(own.userId,own.merchantId)).revision,incidents:(await list()).rows.map(({id,revision})=>({id,revision}))});
 const admit=(value:unknown)=>requestReviewedWooReconciliation(own.userId,own.merchantId,value,run=>{runs.push(run);});
 const read=(requestId:string)=>readWooOperation(own.userId,own.merchantId,{requestId});
 const response=(items:any[],total=items.length)=>({status:200,headers:{'x-wp-total':String(total),'x-wp-totalpages':'1'},data:Buffer.from(JSON.stringify(items))});
 beforeEach(async()=>{vi.resetAllMocks();runs=[];own=await createDisposableMerchant('woo-incidents');other=await createDisposableMerchant('woo-incidents-other');await q("INSERT INTO woocommerce_settings(merchant_id,store_url,consumer_key,consumer_secret,is_active,connectionStatus) VALUES (?,'https://shop.example.com',?,?,1,'connected')",[own.merchantId,encryptSecret('ck_'+'a'.repeat(40)),encryptSecret('cs_'+'b'.repeat(40))]);m.dns.mockResolvedValue([{address:'8.8.8.8',family:4}]);m.request.mockResolvedValue(response([]));});
 afterEach(async()=>{vi.restoreAllMocks();await cleanupDisposableMerchants([own.userId,other.userId]);});afterAll(closeDb);
 it('reads complete pages, literal search, filter counts and safe review data across more than one thousand receipts',async()=>{
  const first=await incident();const values=Array.from({length:1002},(_,i)=>[own.merchantId,randomUUID().replaceAll('-',''),'991',i%2?'order.updated':'product.updated',8000+i,i%3?'completed':'manual_review','PRIVATE']);
  const pool=(await getPool())!;await pool.query('INSERT INTO woocommerce_webhook_receipts(merchant_id,delivery_id,webhook_id,topic,resource_id,status,last_error) VALUES ?',[values]);await incident(other.merchantId);
  const all=await list({state:'all'});expect(all.summary.stored).toBe(1003);expect(all.pagination).toMatchObject({total:1003,pages:41});expect(all.rows).toHaveLength(25);
  expect((await list({state:'all',page:41})).rows.at(-1)?.id).toBe(first);expect((await list({state:'all',page:42})).rows).toHaveLength(0);
  const filtered=await list({search:'71',resource:'product'});expect(filtered.rows.some(r=>r.id===first)).toBe(true);expect(filtered.rows.every(r=>r.topic.startsWith('product.'))).toBe(true);
  expect((await list({search:'%',state:'all'})).pagination.total).toBe(0);expect(JSON.stringify(all)).not.toMatch(/PRIVATE|deliveryId|webhookId|token/);expect(all.rows.every(r=>r.merchantId===own.merchantId)).toBe(true);
 });
 it('keeps pending, failed, suppressed and malformed rows distinct from reviewable incidents',async()=>{for(const state of ['pending','failed','suppressed','manual_review'])await incident(own.merchantId,state);await incident(own.merchantId,'manual_review',0);const page=await list({state:'all'});expect(page.rows.filter(r=>r.reviewable)).toHaveLength(1);expect(page.rows.find(r=>r.resourceId===null)).toMatchObject({invalidData:true,reviewable:false});expect(page.summary.groups.find(g=>g.key==='manual_review')?.count).toBe(2);});
 it('commits both snapshots and only explicitly selected incidents, leaving arrivals and foreign rows untouched',async()=>{
  const one=await incident(),unselected=await incident(),foreign=await incident(other.merchantId);await q("INSERT INTO woocommerce_products(merchant_id,woo_product_id,name,slug,price) VALUES (?,55,'Old','old','1.00')",[own.merchantId]);
  const value=await input();value.incidents=value.incidents.filter(r=>r.id===one);await admit(value);let arrival=0;m.request.mockImplementationOnce(async()=>{arrival=await incident();return response([]);});await runs[0]();
  expect(await read(value.requestId)).toMatchObject({outcome:'success',result:{type:'sync',products:0,orders:0,reconciled:1}});expect(m.request).toHaveBeenCalledTimes(2);
  expect((await q('SELECT status FROM woocommerce_webhook_receipts WHERE id=?',[one]))[0].status).toBe('suppressed');for(const id of [unselected,arrival,foreign])expect((await q('SELECT status FROM woocommerce_webhook_receipts WHERE id=?',[id]))[0].status).toBe('manual_review');
  expect(await q('SELECT id FROM woocommerce_products WHERE merchant_id=?',[own.merchantId])).toHaveLength(0);expect((await admit(value)).outcome).toBe('success');expect(runs).toHaveLength(1);
 });
 it('rejects foreign, unreviewable and stale selections before admission',async()=>{const ownId=await incident(),foreign=await incident(other.merchantId),pending=await incident(own.merchantId,'pending');const value=await input();for(const id of [foreign,pending])await expect(admit({...value,incidents:[{...value.incidents[0],id}]})).rejects.toMatchObject({reason:'changed'});await q('UPDATE woocommerce_webhook_receipts SET attempt_count=attempt_count+1 WHERE id=?',[ownId]);await expect(admit(value)).rejects.toMatchObject({reason:'changed'});expect(runs).toHaveLength(0);expect(m.request).not.toHaveBeenCalled();});
 it('does not widen a replay to other incidents and canonicalizes the original selection order',async()=>{await incident();await incident();const value=await input();await admit(value);await admit({...value,incidents:[...value.incidents].reverse()});expect(runs).toHaveLength(1);await expect(admit({...value,incidents:value.incidents.slice(0,1)})).rejects.toMatchObject({reason:'changed'});});
 it('stops before provider work if an incident changes while queued',async()=>{const id=await incident(),value=await input();await admit(value);await q("UPDATE woocommerce_webhook_receipts SET status='suppressed' WHERE id=?",[id]);await runs[0]();expect(await read(value.requestId)).toMatchObject({outcome:'rejected',started:false});expect(m.request).not.toHaveBeenCalled();});
 it('checks reviewed incidents again after the provider response',async()=>{const id=await incident(),value=await input();await admit(value);m.request.mockImplementationOnce(async()=>{await q('UPDATE woocommerce_webhook_receipts SET attempt_count=attempt_count+1 WHERE id=?',[id]);return response([]);});await runs[0]();expect((await read(value.requestId)).outcome).toBe('unknown');expect(m.request).toHaveBeenCalledOnce();expect((await q('SELECT status FROM woocommerce_webhook_receipts WHERE id=?',[id]))[0].status).toBe('manual_review');});
 it('keeps reviewed incidents open and historical products intact when the second snapshot is incomplete',async()=>{const id=await incident();await q("INSERT INTO woocommerce_products(merchant_id,woo_product_id,name,slug,price) VALUES (?,55,'Old','old','1.00')",[own.merchantId]);const value=await input();await admit(value);m.request.mockResolvedValueOnce(response([])).mockResolvedValueOnce(response([],1));await runs[0]();expect((await read(value.requestId)).outcome).toBe('unknown');expect((await q('SELECT status FROM woocommerce_webhook_receipts WHERE id=?',[id]))[0].status).toBe('manual_review');expect(await q('SELECT woo_product_id FROM woocommerce_products WHERE merchant_id=?',[own.merchantId])).toEqual([{woo_product_id:55}]);});
 it('rolls back incident completion and both snapshots when final evidence cannot be saved',async()=>{const id=await incident(),value=await input();await admit(value);const pool=(await getPool())!,get=pool.getConnection.bind(pool);let failed=false;vi.spyOn(pool,'getConnection').mockImplementation(async()=>{const tx=await get(),execute=tx.execute.bind(tx);vi.spyOn(tx,'execute').mockImplementation((async(sql:any,args:any)=>{if(typeof sql==='string'&&sql.startsWith("UPDATE woocommerce_operations SET state='success'")&&!failed){failed=true;throw Error('PRIVATE failed commit');}return execute(sql,args);}) as any);return tx;});await runs[0]();expect(failed).toBe(true);expect((await q('SELECT status FROM woocommerce_webhook_receipts WHERE id=?',[id]))[0].status).toBe('manual_review');expect((await read(value.requestId)).outcome).toBe('unknown');expect((await q('SELECT last_sync_at FROM woocommerce_settings WHERE merchant_id=?',[own.merchantId]))[0].last_sync_at).toBeNull();});
});

