import {afterAll,afterEach,beforeEach,describe,it,expect} from 'vitest';
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {woocommerceRouter} from './woocommerce_router';
describe.skipIf(!process.env.DATABASE_URL)('WooCommerce dashboard selected merchant MySQL',()=>{
 let own:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof own;
 const q=async(sql:string,args:any[]=[]) => (await(await getPool())!.execute<any>(sql,args))[0];
 beforeEach(async()=>{own=await createDisposableMerchant('woo-dashboard');other=await createDisposableMerchant('woo-other');});
 afterEach(async()=>cleanupDisposableMerchants([own.userId,other.userId]));afterAll(closeDb);
 const caller=(userId=own.userId,merchantId:number|null=own.merchantId)=>woocommerceRouter.createCaller({user:{id:userId,role:'user'},merchantId:999,merchantRole:'owner',req:{headers:merchantId?{'x-merchant-id':String(merchantId)}:{}},res:{}} as any);
 const product=(merchantId:number,name:string)=>q("INSERT INTO woocommerce_products(merchant_id,woo_product_id,name,slug,price) VALUES (?,1,?,'sample','15.00')",[merchantId,name]);
 const order=(merchantId:number)=>q("INSERT INTO woocommerce_orders(merchant_id,woo_order_id,order_number,status,currency,total,subtotal,line_items,order_date) VALUES (?,1,'LOCAL-1','pending','SAR','15.00','15.00','[]',UTC_TIMESTAMP())",[merchantId]);
 it('reads only selected tenant data for a manager with two memberships',async()=>{await product(own.merchantId,'Selected');await product(other.merchantId,'Foreign');await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'manager',1)",[own.merchantId,other.userId]);expect((await caller(other.userId).getProducts({})).products.map(p=>p.name)).toEqual(['Selected']);expect((await caller(other.userId,other.merchantId).getProducts({})).products.map(p=>p.name)).toEqual(['Foreign']);expect(await caller(other.userId).getSettings()).toBeNull();expect(await caller(other.userId).getWorkspace()).toMatchObject({actorId:other.userId,merchantId:own.merchantId,counts:{storedProducts:1}});expect(await caller(other.userId).getLogsWorkspace({})).toMatchObject({actorId:other.userId,merchantId:own.merchantId,summary:{stored:0}});await expect(caller(other.userId,null).getProducts({})).rejects.toMatchObject({code:'PRECONDITION_FAILED'});});
 it.each(['viewer','sales_supervisor'])('preserves %s catalog/order reads and blocks integration metadata',async role=>{await product(own.merchantId,'Selected');await order(own.merchantId);await q('INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,?,1)',[own.merchantId,other.userId,role]);expect((await caller(other.userId).getProducts({})).products).toHaveLength(1);expect((await caller(other.userId).getOrders({})).orders).toHaveLength(1);expect((await caller(other.userId).getProductsWorkspace({})).rows).toHaveLength(1);const fresh=await caller(other.userId).getOrdersWorkspace({});expect(fresh.rows).toHaveLength(1);expect((await caller(other.userId).getOrderDetailsWorkspace({id:fresh.rows[0].id})).order?.merchantId).toBe(own.merchantId);await expect(caller(other.userId).getSettings()).rejects.toMatchObject({code:'FORBIDDEN'});await expect(caller(other.userId).getWorkspace()).rejects.toMatchObject({code:'FORBIDDEN'});await expect(caller(other.userId).getLogsWorkspace({})).rejects.toMatchObject({code:'FORBIDDEN'});await expect(caller(other.userId).getSyncLogs({})).rejects.toMatchObject({code:'FORBIDDEN'});await expect(caller(other.userId).getLatestSync({syncType:'products'})).rejects.toMatchObject({code:'FORBIDDEN'});});
 it('does not read or mutate another tenant using a forged context or record ID',async()=>{const row=await order(other.merchantId);await expect(caller().getOrder({id:Number(row.insertId)})).rejects.toMatchObject({code:'NOT_FOUND'});await expect(caller(own.userId,other.merchantId).getSettings()).rejects.toMatchObject({code:'FORBIDDEN'});await expect(caller(own.userId,other.merchantId).disconnect()).rejects.toMatchObject({code:'FORBIDDEN'});expect((await caller(other.userId,other.merchantId).getOrders({})).orders).toHaveLength(1);});
 it('honors explicit owner revocation, downgrade and suspension',async()=>{await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'owner',1)",[own.merchantId,own.userId]);await q("UPDATE merchant_members SET role='viewer' WHERE merchant_id=? AND user_id=?",[own.merchantId,own.userId]);await expect(caller().getSettings()).rejects.toMatchObject({code:'FORBIDDEN'});await q('UPDATE merchant_members SET is_active=0 WHERE merchant_id=? AND user_id=?',[own.merchantId,own.userId]);await expect(caller().getProducts({})).rejects.toMatchObject({code:'FORBIDDEN'});await q('UPDATE merchant_members SET is_active=1 WHERE merchant_id=? AND user_id=?',[own.merchantId,own.userId]);await q("UPDATE merchants SET status='suspended' WHERE id=?",[own.merchantId]);await expect(caller().getOrders({})).rejects.toMatchObject({code:'FORBIDDEN'});});
});
