import {afterAll,afterEach,beforeEach,describe,it,expect} from 'vitest';
import {getPool,closeDb,getDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {withWooDashboardAuthority,assertWooDashboardAuthority,assertWooDashboardWrite} from './integrations/woocommerce-dashboard-authority';
import {sql} from 'drizzle-orm';
import {saveVerifiedWooCommerceSettings,deleteWooCommerceIntegration,upsertWooCommerceProductsSnapshot,upsertWooCommerceOrdersSnapshot,updateWooCommerceConnectionStatus,createWooCommerceSyncLog,updateWooCommerceSyncLog,updateWooCommerceSettings,reconcileWooCommerceSnapshotAndWebhookIncidents} from './db';
describe.skipIf(!process.env.DATABASE_URL)('WooCommerce transactional dashboard authority MySQL',()=>{
 let own:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof own;
 const q=async(query:string,args:any[]=[]) => (await(await getPool())!.execute<any>(query,args))[0];
 const scope=()=>({actorId:own.userId,merchantId:own.merchantId,permission:'integrations.manage' as const});
 beforeEach(async()=>{await getDb();own=await createDisposableMerchant('woo-authority');other=await createDisposableMerchant('woo-foreign');await q("INSERT INTO woocommerce_settings(merchant_id,store_url,consumer_key,consumer_secret,connectionStatus) VALUES (?,'https://sample.example.com','LOCAL_ONLY','LOCAL_ONLY','connected')",[own.merchantId]);await q("INSERT INTO woocommerce_products(merchant_id,woo_product_id,name,slug,price) VALUES (?,1,'Retained','sample','15.00')",[own.merchantId]);});
 afterEach(async()=>cleanupDisposableMerchants([own.userId,other.userId]));afterAll(closeDb);
 const revoke=()=>q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'owner',0)",[own.merchantId,own.userId]);
 it('checks the same selected actor after asynchronous work and retains records on denial',async()=>{await withWooDashboardAuthority(scope(),async()=>{await assertWooDashboardAuthority();await revoke();await expect(assertWooDashboardAuthority()).rejects.toMatchObject({code:'FORBIDDEN'});await expect(deleteWooCommerceIntegration(own.merchantId)).rejects.toMatchObject({code:'FORBIDDEN'});});expect(await q('SELECT id FROM woocommerce_settings WHERE merchant_id=?',[own.merchantId])).toHaveLength(1);expect(await q('SELECT id FROM woocommerce_products WHERE merchant_id=?',[own.merchantId])).toHaveLength(1);});
 it.each(['products','orders','settings','status','log','reconcile'])('rejects revoked %s persistence before changing stored data',async kind=>{await revoke();const work=()=>kind==='products'?upsertWooCommerceProductsSnapshot(own.merchantId,[]):kind==='orders'?upsertWooCommerceOrdersSnapshot(own.merchantId,[]):kind==='settings'?updateWooCommerceSettings(own.merchantId,{autoSyncProducts:1}):kind==='status'?updateWooCommerceConnectionStatus(own.merchantId,'error'):kind==='log'?createWooCommerceSyncLog({merchantId:own.merchantId,syncType:'products',direction:'import',status:'running',startedAt:'2026-10-02 00:00:00'}):reconcileWooCommerceSnapshotAndWebhookIncidents({merchantId:own.merchantId,products:[],orders:[],observedAt:'2026-10-02 00:00:00.000'});await expect(withWooDashboardAuthority(scope(),work)).rejects.toMatchObject({code:'FORBIDDEN'});expect(await q('SELECT id FROM woocommerce_products WHERE merchant_id=?',[own.merchantId])).toHaveLength(1);expect(await q('SELECT id FROM woocommerce_sync_logs WHERE merchant_id=?',[own.merchantId])).toHaveLength(0);});
 it('does not finalize a previously admitted log after revocation',async()=>{const id=await withWooDashboardAuthority(scope(),()=>createWooCommerceSyncLog({merchantId:own.merchantId,syncType:'products',direction:'import',status:'running',startedAt:'2026-10-02 00:00:00'}));await revoke();await expect(withWooDashboardAuthority(scope(),()=>updateWooCommerceSyncLog(id,{status:'success',itemsSuccess:20}))).rejects.toMatchObject({code:'FORBIDDEN'});expect((await q('SELECT status FROM woocommerce_sync_logs WHERE id=?',[id]))[0].status).toBe('running');});
 it('rejects foreign persistence and inactive actor accounts',async()=>{await expect(withWooDashboardAuthority(scope(),()=>upsertWooCommerceProductsSnapshot(other.merchantId,[]))).rejects.toMatchObject({code:'FORBIDDEN'});await q("UPDATE users SET account_status='deletion_pending' WHERE id=?",[own.userId]);await expect(withWooDashboardAuthority(scope(),()=>deleteWooCommerceIntegration(own.merchantId))).rejects.toMatchObject({code:'FORBIDDEN'});});
 it('serializes revocation against an in-flight local transaction, then rejects the next write',async()=>{
  let entered!:()=>void,release!:()=>void;const started=new Promise<void>(r=>entered=r),held=new Promise<void>(r=>release=r);
  const write=withWooDashboardAuthority(scope(),async()=> (await getDb())!.transaction(async tx=>{await assertWooDashboardWrite(tx,own.merchantId);entered();await held;await tx.execute(sql`UPDATE woocommerce_settings SET auto_sync_products=1 WHERE merchant_id=${own.merchantId}`);}));
  await started;let revoked=false;const revocation=q('UPDATE merchants SET status=? WHERE id=?',['suspended',own.merchantId]).then(()=>revoked=true);
  try{await new Promise(r=>setTimeout(r,40));expect(revoked).toBe(false);}finally{release();await write;await revocation;}
  expect((await q('SELECT auto_sync_products AS autoSyncProducts FROM woocommerce_settings WHERE merchant_id=?',[own.merchantId]))[0].autoSyncProducts).toBe(1);await expect(withWooDashboardAuthority(scope(),()=>updateWooCommerceSettings(own.merchantId,{autoSyncProducts:0}))).rejects.toMatchObject({code:'FORBIDDEN'});
 });
 it('preserves trusted background writes outside dashboard authority',async()=>{await revoke();await upsertWooCommerceProductsSnapshot(own.merchantId,[]);expect(await q('SELECT id FROM woocommerce_products WHERE merchant_id=?',[own.merchantId])).toHaveLength(0);});
 it('does not replace a verified store or its credentials after permission is revoked',async()=>{await revoke();const topics=['product.created','product.updated','product.deleted','order.created','order.updated','order.deleted'] as const;await expect(withWooDashboardAuthority(scope(),()=>saveVerifiedWooCommerceSettings({merchantId:own.merchantId,storeUrl:'https://new.example.com',consumerKey:'LOCAL_NEW',consumerSecret:'LOCAL_NEW',webhookEndpointId:'a'.repeat(43),webhookSigningSecret:'LOCAL_NEW_SIGNING_SECRET'.repeat(2)},topics.map((topic,index)=>({topic,webhookId:String(index+1)}))))).rejects.toMatchObject({code:'FORBIDDEN'});expect((await q('SELECT store_url FROM woocommerce_settings WHERE merchant_id=?',[own.merchantId]))[0].store_url).toBe('https://sample.example.com');});
});
