import {afterAll,afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {readWooAnalyticsWorkspace} from './integrations/woocommerce-analytics-workspace';
describe.skipIf(!process.env.DATABASE_URL)('WooCommerce complete analytics MySQL',()=>{
 let own:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof own;
 const range={startDate:'2026-09-01',endDate:'2026-09-30'},q=async(sql:string,args:unknown[]=[]) => (await(await getPool())!.execute<any>(sql,args))[0];
 beforeEach(async()=>{own=await createDisposableMerchant('woo-analytics');other=await createDisposableMerchant('woo-foreign');});
 afterEach(async()=>{vi.restoreAllMocks();await cleanupDisposableMerchants([own.userId,other.userId]);});afterAll(closeDb);
 const read=(input:unknown=range)=>readWooAnalyticsWorkspace(own.userId,own.merchantId,input);
 const order=async(id:number,options:{merchantId?:number;status?:string;currency?:string;total?:string;date?:string;email?:string|null;phone?:string|null;items?:string}={})=>q("INSERT INTO woocommerce_orders(merchant_id,woo_order_id,order_number,status,currency,total,subtotal,line_items,order_date,customer_email,customer_phone) VALUES (?,?,'LOCAL',?,?,?,0,?,?,?,?)",[options.merchantId??own.merchantId,id,options.status??'completed',options.currency??'SAR',options.total??'0.10',options.items??'[]',options.date??'2026-09-01 00:00:00',options.email??null,options.phone??null]);
 it('counts and sums all 2003 orders across scan batches without mixing currencies or tenants',async()=>{const entries=Array.from({length:2003},(_,i)=>[own.merchantId,i+1,i%2?'SAR':'USD']);await q('INSERT INTO woocommerce_orders(merchant_id,woo_order_id,currency,order_number,status,total,subtotal,line_items,order_date) VALUES '+entries.map(()=>"(?,?,?,'LOCAL','completed',0.10,0,'[]','2026-09-01 00:00:00')").join(','),entries.flat());await order(1,{merchantId:other.merchantId,total:'999999.99'});await order(2004,{date:'2026-10-01 00:00:00'});const value=await read();expect(value.summary).toMatchObject({storedOrders:2004,orders:2003,completed:2003,eligibleCompleted:2003,excludedCompleted:0,completionRate:100});expect(value.currencies.map(({currency,orders,revenue,averageOrderValue})=>({currency,orders,revenue,averageOrderValue}))).toEqual([{currency:'SAR',orders:1001,revenue:'100.10',averageOrderValue:'0.10'},{currency:'USD',orders:1002,revenue:'100.20',averageOrderValue:'0.10'}]);expect(value.currencies[0].timeline).toHaveLength(30);expect(value.currencies[0].timeline[29]).toEqual({date:'2026-09-30',orders:0,revenue:'0.00'});});
 it('includes only exact completed status in revenue and reports every invalid monetary exclusion',async()=>{await order(1,{total:'0.01'});await order(2,{total:'0.02'});await order(3,{total:'-1'});await order(4,{currency:'invalid'});await order(5,{status:'COMPLETED',total:'900'});await order(6,{status:'refunded',total:'900'});await order(7,{status:'pending'});const value=await read();expect(value.summary).toMatchObject({orders:7,completed:4,eligibleCompleted:2,excludedCompleted:2,completionRate:57.14});expect(value.summary.statuses.find(s=>s.key==='unknown')?.count).toBe(1);expect(value.currencies[0]).toMatchObject({orders:2,revenue:'0.03',averageOrderValue:'0.02'});});
 it('groups full item arrays by provider/variation identity, keeps top ten explicit and counts exclusions',async()=>{const items=Array.from({length:503},(_,i)=>({product_id:i<502?1:2,variation_id:i<502?0:4,name:i<502?'Same':'Other',quantity:1,total:'0.10'}));await order(1,{items:JSON.stringify([...items,null,{name:'Invalid',quantity:0,total:'1.00'},{name:'Fallback',quantity:1,total:'0.25'}])});await order(2,{items:'broken'});const value=await read(),products=value.currencies[0].products;expect(products).toMatchObject({distinct:3,validLines:504,excludedLines:2,invalidArrays:1,fallbackIdentityLines:1});expect(products.rows[0]).toMatchObject({name:'Same',quantity:502,revenue:'50.20',identity:'provider'});expect(products.rows.some(r=>r.name==='Other')).toBe(true);expect(products.rows.some(r=>r.identity==='name')).toBe(true);await order(3,{items:JSON.stringify(Array.from({length:12},(_,i)=>({product_id:100+i,variation_id:0,name:'Extra '+i,quantity:1,total:'1'})))});const next=(await read()).currencies[0].products;expect(next.distinct).toBe(15);expect(next.rows).toHaveLength(10);expect(next.limit).toBe(10);});
 it('keeps customer contact identities within the period and does not claim new customers or attribution',async()=>{await order(1,{email:' Client@Example.test ',phone:'+966 500 000 001'});await order(2,{email:'client@example.test',phone:'966500000002'});await order(3,{email:'bad',phone:'+966 (500) 000-003'});await order(4,{phone:'966500000003'});await order(5,{phone:'invalid'});await order(6,{email:'single@example.test'});await order(7,{email:'single@example.test',date:'2026-08-31 23:59:59'});await q("INSERT INTO conversations(merchantId,customerPhone,createdAt) VALUES (?,'local-1','2026-09-01 00:00:00'),(?,'local-2','2026-09-30 23:59:59'),(?,'outside','2026-10-01 00:00:00'),(?,'foreign','2026-09-01 00:00:00')",[own.merchantId,own.merchantId,own.merchantId,other.merchantId]);const value=await read();expect(value.customers).toEqual({definition:'email_first_phone_fallback',identifiedOrders:5,unidentifiedOrders:1,identities:3,singleOrder:1,repeat:2,repeatRate:66.67});expect(value.conversations).toEqual({createdInRange:2,attributionAvailable:false,conversionRate:null,whatsappOrders:null,whatsappRevenue:null});expect(JSON.stringify(value)).not.toMatch(/example.test|966500/);});
 it('uses real UTC date edges and includes partial weekly/monthly bins with no outside orders',async()=>{await order(1,{date:'2026-09-01 00:00:00'});await order(2,{date:'2026-09-30 23:59:59'});await order(3,{date:'2026-10-01 00:00:00'});const weekly=await read({...range,period:'weekly'}),monthly=await read({...range,period:'monthly'});expect(weekly.currencies[0].timeline).toHaveLength(5);expect(weekly.currencies[0].timeline[0]).toEqual({date:'2026-08-30',orders:1,revenue:'0.10'});expect(monthly.currencies[0].timeline).toEqual([{date:'2026-09-01',orders:2,revenue:'0.20'}]);});
 it('returns empty rates as unavailable with valid independent conversation counts',async()=>{const value=await read();expect(value.summary).toMatchObject({orders:0,completed:0,completionRate:null});expect(value.customers.repeatRate).toBeNull();expect(value.conversations.createdInRange).toBe(0);});
 it('retains the snapshot across an insert between counts and the first batch',async()=>{await order(1);const pool=(await getPool())!,get=pool.getConnection.bind(pool);let inserted=false;vi.spyOn(pool,'getConnection').mockImplementation(async()=>{const c=await get(),execute=c.execute.bind(c);vi.spyOn(c,'execute').mockImplementation(async(sql:any,args:any)=>{const result=await execute(sql,args);if(!inserted&&String(sql).includes('AS storedOrders')){inserted=true;await order(2);}return result;});return c;});expect((await read()).summary.orders).toBe(1);expect((await q('SELECT COUNT(*) AS n FROM woocommerce_orders WHERE merchant_id=?',[own.merchantId]))[0].n).toBe(2);});
});
