import {afterAll,afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {readZidWorkspace,readZidLogsWorkspace} from './integrations/zid-workspace';
import {parseZidSettings} from './integrations/zid-settings';
describe.skipIf(!process.env.DATABASE_URL)('Zid complete workspace MySQL',()=>{
 let own:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof own;
 const q=async(sql:string,args:unknown[]=[]) => (await(await getPool())!.execute<any>(sql,args))[0];
 beforeEach(async()=>{own=await createDisposableMerchant('zid-complete');other=await createDisposableMerchant('zid-foreign');});
 afterEach(async()=>{vi.restoreAllMocks();await cleanupDisposableMerchants([own.userId,other.userId]);});afterAll(closeDb);
 const read=()=>readZidWorkspace(own.userId,own.merchantId),logs=(input:unknown={})=>readZidLogsWorkspace(own.userId,own.merchantId,input);
 const connect=async(merchantId=own.merchantId)=>q("INSERT INTO platform_integrations(merchant_id,platform_type,is_active,store_name,store_url,access_token,settings) VALUES (?,'zid',1,'Sample','https://sample.example.test/?SECRET','PRIVATE',?)",[merchantId,JSON.stringify({storeId:String(merchantId),managerToken:'PRIVATE'})]);
 const log=async(merchantId=own.merchantId)=>q("INSERT INTO zid_sync_logs(merchant_id,sync_type,status,total_items,processed_items,success_count,completed_at,error_message) VALUES (?,'products','completed',3,3,3,UTC_TIMESTAMP(),'PRIVATE')",[merchantId]);
 it('retains history while unlinked and excludes a different tenant',async()=>{await connect(other.merchantId);await log();await log(other.merchantId);const result=await read();expect(result).toMatchObject({present:false,state:'unlinked',source:null,counts:{catalog:0,linkedProducts:0,sourceOrders:0,syncLogs:1},syncSummary:{completed:1}});expect(JSON.stringify(result)).not.toContain('PRIVATE');});
 it('separates credential presence, malformed settings and disabled canonical authority from legacy fallback',async()=>{await q("INSERT INTO zid_settings(merchant_id,store_id,access_token,manager_token) VALUES (?,'123','PRIVATE','PRIVATE')",[own.merchantId]);expect(await read()).toMatchObject({source:'legacy',state:'configured',storeId:'123',credentialsStored:true,settings:{syncCustomers:false}});await connect();await q("UPDATE platform_integrations SET is_active=0,settings='broken' WHERE merchant_id=?",[own.merchantId]);expect(await read()).toMatchObject({source:'canonical',state:'disabled',storeId:null,credentialsStored:false,settingsValid:false,settings:{autoSync:false}});await q('DELETE FROM platform_integrations WHERE merchant_id=?',[own.merchantId]);expect((await read()).source).toBe('legacy');});
 it.each([null,'','{}','[]','null','broken','{"syncProducts":null}','{"autoSync":1}','{"notifyMerchantOrders":true,"syncOrders":false}'])('matches runtime settings semantics for %s without reading secrets',async settings=>{await connect();await q('UPDATE platform_integrations SET settings=? WHERE merchant_id=?',[settings,own.merchantId]);const result=await read(),expected=parseZidSettings(settings);expect(result.settingsValid).toBe(expected.valid);for(const key of ['autoSync','syncProducts','syncOrders','syncCustomers','notifyMerchantOrders'] as const)expect(result.settings[key]).toBe(expected[key]);expect(JSON.stringify(result)).not.toMatch(/SECRET|PRIVATE/);});
 it('changes review revision for settings, status or credential replacement, but not progress',async()=>{await connect();const first=await read();await q('UPDATE platform_integrations SET last_sync_at=UTC_TIMESTAMP() WHERE merchant_id=?',[own.merchantId]);expect((await read()).revision).toBe(first.revision);await q("UPDATE platform_integrations SET access_token='CHANGED' WHERE merchant_id=?",[own.merchantId]);const second=await read();expect(second.revision).not.toBe(first.revision);await q('UPDATE platform_integrations SET is_active=0 WHERE merchant_id=?',[own.merchantId]);expect((await read()).revision).not.toBe(second.revision);expect(first.storeUrl).toBe('https://sample.example.test/');});
 it('traverses more than a thousand logs with full counts, filters and literal reference search',async()=>{const entries=Array.from({length:1003},(_,i)=>[own.merchantId,i%2?'failed':'completed',i%3?'orders':'products',i,i,i%2?0:i,i%2?i:0]);await q('INSERT INTO zid_sync_logs(merchant_id,status,sync_type,total_items,processed_items,success_count,failed_count,completed_at) VALUES '+entries.map(()=>'(?,?,?,?,?,?,?,UTC_TIMESTAMP())').join(','),entries.flat());await log(other.merchantId);const first=await logs(),last=await logs({page:41});expect(first.summary.stored).toBe(1003);expect(first.rows).toHaveLength(25);expect(last.rows).toHaveLength(3);expect(last.rows[2].totalItems).toBe(0);expect(first.rows.every(row=>!row.invalidData)).toBe(true);expect((await logs({state:'failed'})).pagination.total).toBe(501);expect((await logs({kind:'products',state:'failed'})).rows.every(row=>row.kind==='products'&&row.state==='failed')).toBe(true);expect((await logs({search:String(first.rows[0].id)})).rows.some(row=>row.id===first.rows[0].id)).toBe(true);expect((await logs({search:'%_!'})).pagination.total).toBe(0);expect((await logs({page:42})).rows).toHaveLength(0);expect(await read()).toMatchObject({counts:{syncLogs:1003},syncSummary:{completed:502,failed:501}});});
 it('marks bad historical counts explicitly and retains logs after disconnect',async()=>{await connect();const record=await log();await q('UPDATE zid_sync_logs SET total_items=-1,completed_at=NULL WHERE id=?',[record.insertId]);expect((await logs()).rows[0]).toMatchObject({totalItems:null,invalidData:true,hasErrors:true});await q('DELETE FROM platform_integrations WHERE merchant_id=?',[own.merchantId]);expect((await logs()).summary.stored).toBe(1);expect((await read()).counts.syncLogs).toBe(1);});
 it('scopes source rows to the stored store identity and labels retained tenant customers independently',async()=>{await connect();await q("INSERT INTO products(merchantId,name,sallaProductId,price) VALUES (?,'Local','local-item',0)",[own.merchantId]);for(const [storeId,externalId,active] of [[String(own.merchantId),'101',1],[String(own.merchantId)+'9','102',1],[String(own.merchantId),'103',0]] as const){const product=await q("INSERT INTO products(merchantId,name,sallaProductId,price) VALUES (?,'Sample',?,0)",[own.merchantId,`zid:${storeId}:${externalId}`]);await q('INSERT INTO zid_products(merchant_id,zid_store_id,zid_product_id,sari_product_id,price,is_active) VALUES (?,?,?,?,0,?)',[own.merchantId,storeId,externalId,product.insertId,active]);}
  const foreign=await q("INSERT INTO products(merchantId,name,sallaProductId,price) VALUES (?,'Foreign','foreign-local',0)",[other.merchantId]);await q("INSERT INTO zid_products(merchant_id,zid_store_id,zid_product_id,sari_product_id,price) VALUES (?,?,'foreign-link',?,0)",[own.merchantId,String(own.merchantId),foreign.insertId]);
  for(const store of [String(own.merchantId),'999999',''])await q("INSERT INTO zid_orders(merchant_id,zid_store_id,zid_order_id,total_amount,items) VALUES (?,?,'1',0,'[]')",[own.merchantId,store]);for(const [merchant,active] of [[own.merchantId,1],[own.merchantId,0],[other.merchantId,1]])await q("INSERT INTO zid_customers(merchant_id,zid_customer_id,is_active,last_synced_at) VALUES (?,?,?,UTC_TIMESTAMP())",[merchant,String(active),active]);
  expect((await read()).counts).toMatchObject({catalog:3,linkedProducts:1,sourceOrders:1,storedCustomers:2,activeCustomers:1});await q('UPDATE platform_integrations SET is_active=0 WHERE merchant_id=?',[own.merchantId]);expect((await read()).counts).toMatchObject({catalog:1,linkedProducts:1,sourceOrders:1});await q('DELETE FROM platform_integrations WHERE merchant_id=?',[own.merchantId]);expect((await read()).counts).toMatchObject({catalog:1,linkedProducts:0,sourceOrders:0,storedCustomers:2});
 });
 it('keeps all outstanding webhooks and notifications separate from recent completion',async()=>{for(const [i,status,age,merchant] of [[1,'processed',0,own.merchantId],[2,'pending',9,own.merchantId],[3,'failed',0,own.merchantId],[4,'pending',0,other.merchantId]] as const)await q("INSERT INTO zid_webhooks(merchant_id,event_type,payload,status,created_at) VALUES (?,'product.updated','PRIVATE',?,DATE_SUB(UTC_TIMESTAMP(),INTERVAL ? DAY))",[merchant,status,age]);for(const [i,status,age,merchant] of [[1,'delivered',0,own.merchantId],[2,'pending',9,own.merchantId],[3,'manual_review',9,own.merchantId],[4,'suppressed',0,own.merchantId],[5,'failed',0,own.merchantId],[6,'manual_review',0,other.merchantId]] as const)await q('INSERT INTO zid_order_notification_outbox(merchant_id,zid_order_id,event_key,status,created_at) VALUES (?,?,?,?,DATE_SUB(UTC_TIMESTAMP(3),INTERVAL ? DAY))',[merchant,String(i),`phase306-${merchant}-${i}`,status,age]);expect(await read()).toMatchObject({webhooks:{recentTotal:2,recentProcessed:1,awaiting:1,failed:1},notifications:{recentTotal:3,recentDelivered:1,recentSuppressed:1,awaiting:2,needsReview:1}});});
 it('keeps totals and rows in one snapshot during concurrent inserts',async()=>{await log();const pool=(await getPool())!,get=pool.getConnection.bind(pool);let intercepted=false;vi.spyOn(pool,'getConnection').mockImplementation(async()=>{const connection=await get(),execute=connection.execute.bind(connection);vi.spyOn(connection,'execute').mockImplementation(async(sql:any,args:any)=>{const value=await execute(sql,args);if(!intercepted&&String(sql).startsWith('SELECT COUNT(*) AS count FROM zid_sync_logs')){intercepted=true;await log();}return value;});return connection;});const result=await logs();expect(result.summary.stored).toBe(1);expect(result.rows).toHaveLength(1);expect((await q('SELECT COUNT(*) AS n FROM zid_sync_logs WHERE merchant_id=?',[own.merchantId]))[0].n).toBe(2);});
});
