import {afterAll,afterEach,beforeEach,describe,it,expect} from 'vitest';
import {getPool,closeDb} from './db/connection';
import {createDisposableMerchant,cleanupDisposableMerchants} from './tests/helpers/disposable-merchant';
import {zidRouter} from './integrations/zid';
describe.skipIf(!process.env.DATABASE_URL)('Zid dashboard selected merchant MySQL',()=>{
 let own:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof own;
 const q=async(sql:string,args:any[]=[]) => (await(await getPool())!.execute<any>(sql,args))[0];
 beforeEach(async()=>{own=await createDisposableMerchant('zid-dashboard');other=await createDisposableMerchant('zid-other');});
 afterEach(async()=>cleanupDisposableMerchants([own.userId,other.userId]));afterAll(closeDb);
 const caller=(userId=own.userId,merchantId:number|undefined=own.merchantId)=>zidRouter.createCaller({user:{id:userId,role:'user'},merchantId:999,merchantRole:'owner',req:{headers:merchantId?{'x-merchant-id':String(merchantId)}:{}},res:{}} as any);
 const seed=(merchantId:number,name:string)=>q("INSERT INTO platform_integrations(merchant_id,platform_type,is_active,store_name,store_url,settings) VALUES (?,'zid',1,?,'https://sample.example.test/?token=PRIVATE',?)",[merchantId,name,JSON.stringify({autoSync:false,syncProducts:false,syncOrders:false,syncCustomers:false,notifyMerchantOrders:false})]);
 it('reads only the selected tenant and admits its authorized manager',async()=>{await seed(own.merchantId,'Selected');await seed(other.merchantId,'Foreign');await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'manager',1)",[own.merchantId,other.userId]);expect(await caller(other.userId).getConnection()).toMatchObject({storeName:'Selected',storeUrl:'https://sample.example.test/'});expect(await caller(other.userId,other.merchantId).getConnection()).toMatchObject({storeName:'Foreign'});expect(await caller().getSyncLogs({limit:10})).toEqual([]);});
 it('honors downgrade, explicit owner revocation and suspension before reads or writes',async()=>{await seed(own.merchantId,'Selected');await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'owner',1)",[own.merchantId,own.userId]);await q("UPDATE merchant_members SET role='viewer' WHERE merchant_id=? AND user_id=?",[own.merchantId,own.userId]);await expect(caller().getConnection()).rejects.toMatchObject({code:'FORBIDDEN'});await expect(caller().updateSettings({autoSync:true,syncProducts:true,syncOrders:true,syncCustomers:true,notifyMerchantOrders:true})).rejects.toMatchObject({code:'FORBIDDEN'});await q("UPDATE merchant_members SET role='owner',is_active=0 WHERE merchant_id=? AND user_id=?",[own.merchantId,own.userId]);await expect(caller().getSyncLogs({limit:10})).rejects.toMatchObject({code:'FORBIDDEN'});await q("UPDATE merchant_members SET is_active=1 WHERE merchant_id=? AND user_id=?",[own.merchantId,own.userId]);await q("UPDATE merchants SET status='suspended' WHERE id=?",[own.merchantId]);await expect(caller().getConnection()).rejects.toMatchObject({code:'FORBIDDEN'});});
 it('rejects another tenant and leaves that connection untouched',async()=>{await seed(other.merchantId,'Private');await expect(caller(own.userId,other.merchantId).disconnect()).rejects.toMatchObject({code:'FORBIDDEN'});expect(await caller(other.userId,other.merchantId).getConnection()).toMatchObject({storeName:'Private'});expect(await caller().getConnection()).toEqual({connected:false});});
 it('saves selected tenant settings without modifying a different owned connection',async()=>{await seed(own.merchantId,'Selected');await seed(other.merchantId,'Other');await q("INSERT INTO merchant_members(merchant_id,user_id,role,is_active) VALUES (?,?,'manager',1)",[own.merchantId,other.userId]);await caller(other.userId).updateSettings({autoSync:true,syncProducts:true,syncOrders:false,syncCustomers:false,notifyMerchantOrders:false});expect(await caller().getConnection()).toMatchObject({settings:{autoSync:true,syncProducts:true}});expect(await caller(other.userId,other.merchantId).getConnection()).toMatchObject({settings:{autoSync:false,syncProducts:false}});});
});
