import { discountCreateInput, discountUpdateInput, discountDeleteInput } from '../../../shared/discount-dashboard';
import { discountPageSize, discountWorkspaceInput, discountWorkspaceSchema, type DiscountWorkspaceRow } from '../../../shared/discount-workspace';
import type { ServiceMode } from './service-preview-model';
export const discountPreviewQueries = ['discounts.workspace'] as const;
export const discountPreviewMutations = ['discounts.create', 'discounts.update', 'discounts.delete'] as const;
const fault = (code: string) => ({ message: 'Local discount simulation', data: { code } });
type Stored = Omit<DiscountWorkspaceRow, 'state' | 'revision'> & { version: number };
/** In-memory examples only; version markers are not server SHA-256 evidence. */
export class DiscountPreviewStore {
  writes = 0; private nextId = 32; private rows = new Map<number, Stored>();
  constructor(readonly actorId: number, readonly merchantId: number, readonly now: string, private mode: () => ServiceMode) {
    if (mode() !== 'empty') for (let id = 1; id <= 31; id++) this.rows.set(id, {
      id, code: `DEMO-${merchantId}-${String(id).padStart(2, '0')}`, type: id % 3 ? 'percentage' : 'fixed', value: id % 3 ? 15 : 50,
      minOrderAmount: id % 2 ? 100 : null, maxUses: id % 5 === 1 ? 5 : null, usedCount: id % 5 === 1 ? 5 : 0,
      isActive: id % 5 !== 0, isAutoGenerated: id % 4 === 0, customerPhone: id % 4 === 0 ? '+966500000000' : null,
      expiresAt: id % 5 === 3 ? new Date(Date.parse(now) - 86400000).toISOString() : null,
      createdAt: now, updatedAt: now, issues: [], version: 0,
    });
  }
  private row(value: Stored): DiscountWorkspaceRow {
    const { version, ...row } = structuredClone(value);
    if (this.mode() === 'legacy' && row.id % 5 === 2) { row.usedCount = null; row.issues = ['usage']; }
    const state = row.issues.length ? 'invalid' : !row.isActive ? 'inactive' : row.expiresAt && row.expiresAt <= this.now ? 'expired' : row.maxUses !== null && row.usedCount! >= row.maxUses ? 'exhausted' : 'available';
    const revision = [this.actorId, this.merchantId, row.id, version, this.mode() === 'legacy' ? 1 : 0, 0, 0, 0].map(n => n.toString(16).padStart(8, '0')).join('');
    return { ...row, state, revision };
  }
  read(name: string, input: unknown = {}) {
    if (name !== 'discounts.workspace') throw fault('NOT_FOUND');
    const selection = discountWorkspaceInput.parse(input), all = Array.from(this.rows.values()).sort((a, b) => b.id - a.id).map(row => this.row(row));
    const counts = { available: 0, inactive: 0, expired: 0, exhausted: 0, invalid: 0 }, usage = { recorded: 0, invalidRows: 0 };
    for (const row of all) { counts[row.state]++; if (row.usedCount === null) usage.invalidRows++; else usage.recorded += row.usedCount; }
    const query = selection.query.toLowerCase(), matches = all.filter(row => (selection.status === 'all' || row.state === selection.status) && (selection.origin === 'all' || row.isAutoGenerated === (selection.origin === 'automatic')) && (!query || row.code.toLowerCase().includes(query) || String(row.id) === query));
    return discountWorkspaceSchema.parse({ actorId: this.actorId, merchantId: this.merchantId, checkedAt: this.now, canManage: this.mode() !== 'readonly', selection, pageSize: discountPageSize, total: all.length, matched: matches.length, pages: Math.ceil(matches.length / discountPageSize), counts, usage, rows: matches.slice((selection.page - 1) * discountPageSize, selection.page * discountPageSize) });
  }
  mutate(name: string, input: unknown) {
    if (name === 'discounts.create') {
      const value = discountCreateInput.parse(input);
      if (Array.from(this.rows.values()).some(row => row.code.toUpperCase() === value.code)) throw fault('CONFLICT');
      const id = this.nextId++;
      this.rows.set(id, { ...value, id, minOrderAmount: value.minOrderAmount ?? null, maxUses: value.maxUses ?? null, expiresAt: value.expiresAt ? value.expiresAt + 'T00:00:00.000Z' : null, usedCount: 0, isActive: true, isAutoGenerated: false, customerPhone: null, createdAt: this.now, updatedAt: this.now, issues: [], version: 0 });
      this.writes++; return { success: true, discountCode: { id, merchantId: this.merchantId } };
    }
    const value = name === 'discounts.update' ? discountUpdateInput.parse(input) : name === 'discounts.delete' ? discountDeleteInput.parse(input) : null;
    if (!value) throw fault('NOT_FOUND'); const row = this.rows.get(value.id);
    if (!row) throw fault('NOT_FOUND'); if (this.row(row).revision !== value.expectedRevision) throw fault('CONFLICT');
    if (name === 'discounts.delete') this.rows.delete(row.id);
    else { const update = discountUpdateInput.parse(input); if (update.isActive !== undefined) row.isActive = update.isActive; if (update.maxUses !== undefined) row.maxUses = update.maxUses; if (update.expiresAt !== undefined) row.expiresAt = update.expiresAt ? update.expiresAt + 'T00:00:00.000Z' : null; row.version++; row.updatedAt = this.now; }
    this.writes++; return { success: true };
  }
}
