import {pendingAppointmentRequest,clearAppointmentRequest} from '../../../client/src/lib/appointment-create';
import CalendarPage from '../../../client/src/pages/CalendarPage';
import CalendarSettings from '../../../client/src/pages/CalendarSettings';
import BookingsManagement from '../../../client/src/pages/BookingsManagement';
import StaffManagement from '../../../client/src/pages/StaffManagement';
import {useEffect,useMemo,useState,useSyncExternalStore} from 'react';
import {createRoot} from 'react-dom/client';import {createPortal} from 'react-dom';import {Toaster,toast} from 'sonner';
import ServicesManagement from '../../../client/src/pages/merchant/ServicesManagement';
import ServiceForm from '../../../client/src/pages/merchant/ServiceForm';
import ServiceCategories from '../../../client/src/pages/merchant/ServiceCategories';
import ServicePackages from '../../../client/src/pages/merchant/ServicePackages';
import ServiceDetails from '../../../client/src/pages/ServiceDetails';
import {WorkspaceState} from '../../../client/src/components/merchant/WorkspaceState';
import {useMerchantViewport} from '../../../client/src/lib/merchant-viewport';
import {ServicePreviewModel,serviceModes,type ServiceMode} from './service-preview-model';
import {ServicePreviewContext} from './service-preview-api';import {ServicePreviewLanguage} from './service-preview-i18n';
import {usePreviewSearch,previewNavigation,updateServiceSearch,validServicePath,Link} from './service-preview-router';
const labels={ar:['عادية','فارغة','تحميل','تعذر القراءة','دون صلاحية','جلسة منتهية','بيانات متجر آخر','فشل مع بيانات قديمة','قراءة فقط','بيانات قديمة غير صالحة','علاقات غير متاحة','تعذر قراءة الاختيارات','فشل الإجراء','تعارض النسخة','حفظ معلق','حفظ بنتيجة غير مؤكدة','تقويم غير مربوط','تفويض غير مهيأ','وجهة التقويم مفقودة','بيانات الربط غير صالحة'],en:['Normal','Empty','Loading','Read failed','Forbidden','Session expired','Another store snapshot','Error with stale data','Read only','Invalid legacy data','Unavailable references','Choices unavailable','Action failed','Save conflict','Pending save','Uncertain save','Calendar unlinked','OAuth unavailable','Calendar destination missing','Invalid credentials']};
function PendingControl({model,ar}:{model:ServicePreviewModel;ar:boolean}){
 const [target,setTarget]=useState<Element|null>(null);useEffect(()=>{setTarget(model.pending?document.querySelector('[role="dialog"]')??document.querySelector('.service-preview-controls'):null);},[model,model.pending]);
 return model.pending&&target?createPortal(<div className="service-preview-controls"><p>{ar?'أداة محاكاة التأخير فقط':'Local delay simulation control'}</p><button type="button" onClick={model.finishPending}>{ar?'أكمل الحفظ المحلي':'Complete local save'}</button></div>,target):null;
}
function Preview(){
 const [connectionVisit,setConnectionVisit]=useState(0);useEffect(()=>{const returned=()=>setConnectionVisit(n=>n+1);window.addEventListener('calendar-preview-authorization',returned);return()=>window.removeEventListener('calendar-preview-authorization',returned);},[]);
 useMerchantViewport();const search=usePreviewSearch(),{path,params}=previewNavigation(search),language=params.get('lang')==='en'?'en':'ar',ar=language==='ar';
 const merchantId=params.get('tenant')==='270'?270:269,raw=params.get('scenario'),mode:ServiceMode=serviceModes.includes(raw as ServiceMode)?raw as ServiceMode:'normal';
 const [generation,setGeneration]=useState(0),model=useMemo(()=>new ServicePreviewModel(merchantId,mode),[merchantId,mode,generation]);useSyncExternalStore(model.subscribe,model.snapshot);useEffect(()=>()=>model.dispose(),[model]);
 useEffect(()=>{document.documentElement.lang=language;document.documentElement.dir=ar?'rtl':'ltr';},[language,ar]);
 const change=(key:string,value:string)=>{const next=new URLSearchParams(search);next.set(key,value);updateServiceSearch(next);};
 const page=!validServicePath(path)?<WorkspaceState kind="missing"/>:path==='/merchant/calendar'?<CalendarPage/>:path==='/merchant/calendar/settings'?<CalendarSettings/>:path==='/merchant/bookings'?<BookingsManagement/>:path==='/merchant/staff'?<StaffManagement/>:path==='/merchant/services'?<ServicesManagement/>:path==='/merchant/service-categories'?<ServiceCategories/>:path==='/merchant/service-packages'?<ServicePackages/>:path.endsWith('/new')||path.endsWith('/edit')?<ServiceForm/>:<ServiceDetails/>;
 return <ServicePreviewLanguage.Provider value={language}><ServicePreviewContext.Provider value={model}><main className="mw-main service-preview-main" onClickCapture={event=>{const anchor=(event.target as HTMLElement).closest?.('a[href="/login"],a[href="/support"]');if(anchor){event.preventDefault();if(anchor.getAttribute('href')==='/login')model.complete();else toast.info(ar?'معاينة محلية؛ لم يُرسل طلب دعم.':'Local preview; no support request was sent.');}}}>
  <aside className="service-preview-controls" aria-label={ar?'خيارات الموك أب':'Preview controls'}><h2>{ar?'موك أب الخدمات والحجوزات والتقويم':'Actual services, bookings and calendar preview'}</h2><p>{ar?'شاشات التطبيق ببيانات توضيحية في الذاكرة. الإضافة والتعديل والتعطيل محاكاة محلية؛ لا إنشاء لحجوزات أو تعديل لبيانات متجرك، ولا تفويض Google أو إرسال تذكيرات. تغيير التيننت أو الحالة أو إعادة التحميل يعيد بيانات المثال.':'Application screens with in-memory sample data. Creates, edits and deactivation are local simulations; no real bookings, Google authorization, reminders or store data changes. Switching tenant or scenario, or reloading, resets samples.'}</p>
  <div className="service-preview-options"><label>{ar?'حالة التجربة':'Scenario'}<select data-service-scenario value={mode} onChange={e=>change('scenario',e.target.value)}>{serviceModes.map((item,i)=><option key={item} value={item}>{labels[language][i]}</option>)}</select></label><label>{ar?'لغة اللوحة':'Interface language'}<select data-service-language value={language} onChange={e=>change('lang',e.target.value)}><option value="ar">العربية</option><option value="en">English</option></select></label><label>{ar?'تيننت المحاكاة':'Simulated tenant'}<select data-service-tenant value={merchantId} onChange={e=>change('tenant',e.target.value)}><option value="269">A · 269</option><option value="270">B · 270</option></select></label><button type="button" onClick={()=>{try{const id=pendingAppointmentRequest(sessionStorage,model.actorId,merchantId);if(id)clearAppointmentRequest(sessionStorage,model.actorId,merchantId,id);setGeneration(n=>n+1);}catch{toast.error(ar?'تعذر إعادة بيانات المثال في هذا المتصفح.':'Could not reset the sample in this browser.');}}}>{ar?'إعادة بيانات المثال':'Reset sample data'}</button><button type="button" onClick={model.complete}>{ar?'استعادة الحالة محليًا':'Recover local state'}</button></div>
  <nav aria-label={ar?'صفحات الخدمات':'Service pages'}><Link href="/merchant/services">{ar?'الخدمات':'Services'}</Link><Link href="/merchant/services/new">{ar?'إضافة خدمة':'Create service'}</Link><Link href="/merchant/services/1/edit">{ar?'تعديل المثال':'Edit sample'}</Link><Link href="/merchant/services/1">{ar?'تفاصيل المثال':'Sample details'}</Link><Link href="/merchant/service-categories">{ar?'التصنيفات':'Categories'}</Link><Link href="/merchant/bookings">{ar?'الحجوزات':'Bookings'}</Link><Link href="/merchant/bookings?booking=new">{ar?'حجز جديد':'New booking'}</Link><Link href="/merchant/calendar">{ar?'التقويم':'Calendar'}</Link><Link href="/merchant/calendar?create=1">{ar?'موعد جديد':'New appointment'}</Link><Link href="/merchant/calendar/settings">{ar?'ربط التقويم':'Calendar connection'}</Link><Link href="/merchant/staff">{ar?'مقدمو الخدمات':'Providers'}</Link><Link href="/merchant/service-packages">{ar?'الباقات':'Packages'}</Link></nav>{path==='/merchant/bookings'&&<nav aria-label={ar?'أمثلة خصائص الحجز':'Booking feature examples'}>{[[1,'حجز يدوي','Manual booking'],[2,'موافقة العميل','Customer consent'],[3,'ربط التقويم','Calendar sync'],[4,'طلب إلغاء','Cancellation request'],[5,'تغيير موعد','Reschedule request'],[6,'مراجعة الدفع','Payment review'],[7,'تجديد الرابط','Link renewal'],[8,'مراجعة إشعار','Notice review'],[9,'التحقق من المزامنة','Verify calendar'],[10,'التحقق من الإلغاء','Verify cancellation'],[11,'التحقق من النقل','Verify reschedule']].map(([id,arabic,english])=><Link key={id} href={'/merchant/bookings?booking='+id}>{ar?arabic:english}</Link>)}</nav>}{path==='/merchant/calendar'&&<nav aria-label={ar?'أمثلة خصائص التقويم':'Calendar feature examples'}>{[[1,'موعد محلي','Local appointment'],[2,'موعد متزامن','Synced appointment'],[3,'تحقق من الإنشاء','Verify creation'],[4,'تحقق من الإلغاء','Verify cancellation'],[5,'ربط سجل قديم','Bind legacy event'],[6,'تذكير مقبول','Accepted reminder'],[7,'تذكير غير مؤكد','Unknown reminder'],[8,'موعد ملغى','Cancelled appointment'],[9,'موعد مكتمل','Completed appointment'],[10,'لم يحضر','No show'],[11,'إنشاء جارٍ','Creation in flight'],[12,'إلغاء جارٍ','Cancellation in flight']].map(([id,arabic,english])=><Link key={id} href={'/merchant/calendar?appointment='+id}>{ar?arabic:english}</Link>)}</nav>}<p role="status">{ar?'عمليات محلية: ':'Local operations: '}{model.operations} · {ar?'محاولات الاستعادة: ':'Recovery attempts: '}{model.retries}</p></aside>
  <Toaster richColors position="bottom-center"/><div key={`${merchantId}:${mode}:${generation}:${path}`} className="service-preview-workspace"><div key={path==="/merchant/calendar/settings"?connectionVisit:0}>{page}</div></div><PendingControl model={model} ar={ar}/>
 </main></ServicePreviewContext.Provider></ServicePreviewLanguage.Provider>;
}
createRoot(document.getElementById('service-preview')!).render(<Preview/>);
