import { z } from 'zod';
import { discountRecordId } from './discount-dashboard';
export const discountPageSize = 25;
export const discountStates = ['available', 'inactive', 'expired', 'exhausted', 'invalid'] as const;
export const discountWorkspaceInput = z.object({
  query: z.string().trim().max(80).default(''),
  status: z.enum(['all', ...discountStates]).default('all'),
  origin: z.enum(['all', 'manual', 'automatic']).default('all'),
  page: z.number().int().min(1).max(1000000).default(1),
}).strict();
export type DiscountSelection = z.infer<typeof discountWorkspaceInput>;
const count = z.number().int().nonnegative().safe();
const stamp = z.string().datetime().nullable();
export const discountWorkspaceRow = z.object({
  id: discountRecordId, code: z.string().max(50), type: z.enum(['percentage', 'fixed']).nullable(),
  value: count.nullable(), minOrderAmount: count.nullable(), maxUses: count.nullable(), usedCount: count.nullable(),
  isActive: z.boolean().nullable(), isAutoGenerated: z.boolean().nullable(), customerPhone: z.string().max(50).nullable(),
  expiresAt: stamp, createdAt: stamp, updatedAt: stamp,
  state: z.enum(discountStates), revision: z.string().regex(/^[a-f0-9]{64}$/),
  issues: z.array(z.enum(['code', 'type', 'value', 'minimum', 'limit', 'usage', 'activation', 'origin', 'expiry', 'created', 'updated'])),
}).strict();
export const discountWorkspaceSchema = z.object({
  actorId: discountRecordId, merchantId: discountRecordId, checkedAt: z.string().datetime(), canManage: z.boolean(),
  selection: discountWorkspaceInput, pageSize: z.literal(discountPageSize), total: count, matched: count, pages: count,
  counts: z.object({ available: count, inactive: count, expired: count, exhausted: count, invalid: count }).strict(),
  usage: z.object({ recorded: count, invalidRows: count }).strict(), rows: z.array(discountWorkspaceRow).max(discountPageSize),
}).strict();
export type DiscountWorkspaceRow = z.infer<typeof discountWorkspaceRow>;
export type DiscountWorkspace = z.infer<typeof discountWorkspaceSchema>;
