import {beforeEach,afterEach,afterAll,describe,it,expect,vi} from 'vitest';
const calls=vi.hoisted(()=>({llm:vi.fn()}));
vi.mock('../_core/llm',()=>({invokeLLM:calls.llm}));
import {getPool,closeDb} from '../db/connection';
import {getPromotionById} from '../db';
import {createDisposableMerchant,cleanupDisposableMerchants} from '../tests/helpers/disposable-merchant';
import {parseAICommands,generateAIResponse} from '../ai';
describe.skipIf(!process.env.DATABASE_URL)('promotion context and media boundaries on local MySQL',()=>{
 let owner:Awaited<ReturnType<typeof createDisposableMerchant>>,other:typeof owner;
 const q=async(sql:string,args:any[]=[]) => (await (await getPool())!.execute<any>(sql,args))[0];
 const create=async(merchantId=owner.merchantId)=>{const r=await q("INSERT INTO promotions (merchant_id,title,description,type,value,scope,min_order_amount,min_quantity,banner_image_url,view_count,click_count) VALUES (?,'Stored offer','Exact conditions','percentage',15,'all',0,1,'https://example.com/banner.png',7,3)",[merchantId]);return Number(r.insertId);};
 beforeEach(async()=>{calls.llm.mockReset();calls.llm.mockResolvedValue({choices:[{message:{content:'fixture reply'}}]});owner=await createDisposableMerchant('promo-evidence');other=await createDisposableMerchant('promo-evidence-other');});
 afterEach(async()=>{await cleanupDisposableMerchants([owner?.userId,other?.userId].filter(Boolean));});afterAll(closeDb);
 it('scopes the database lookup and refuses another store banner',async()=>{const id=await create(other.merchantId);expect(await getPromotionById(id,owner.merchantId)).toBeUndefined();const parsed=await parseAICommands('Hello [SEND_PROMO_IMAGE:'+id+']',owner.merchantId);expect(parsed).toMatchObject({text:'Hello',media:[]});});
 it('prepares only one current banner with its conditions and changes no counters',async()=>{const id=await create(),text='Offer [SEND_PROMO_IMAGE:'+id+'] [SEND_PROMO_IMAGE:'+id+']';const parsed=await parseAICommands(text,owner.merchantId);expect(parsed.media).toHaveLength(1);expect(parsed.media[0].caption).toContain('Exact conditions');expect(parsed.media[0].caption).toContain('15%');expect(parsed.media[0].caption).not.toMatch(/ريال|SAR/);expect(await q('SELECT view_count,click_count FROM promotions WHERE id=?',[id])).toEqual([{view_count:7,click_count:3}]);});
 it.each(["is_active=0","starts_at=DATE_ADD(UTC_TIMESTAMP(),INTERVAL 1 DAY)","expires_at=UTC_TIMESTAMP()","scope='products',product_ids='[1]'","scope='categories',category_ids='[1]'","banner_image_url='https://127.0.0.1/private'","description=REPEAT('x',1500)"])( 'rechecks source before preparing media: %s',async patch=>{const id=await create();await q('UPDATE promotions SET '+patch+' WHERE id=?',[id]);expect((await parseAICommands('[SEND_PROMO_IMAGE:'+id+']',owner.merchantId)).media).toEqual([]);});
 it('caps distinct banners and strips rejected/invalid markers',async()=>{const ids=await Promise.all(Array.from({length:4},()=>create()));const result=await parseAICommands(ids.map(id=>'[SEND_PROMO_IMAGE:'+id+']').join(' ')+' [SEND_PROMO_IMAGE:99999999999999999999999]',owner.merchantId);expect(result.media).toHaveLength(3);expect(result.text).toBe('');});
 it('uses bounded structured context with scope and no counter writes or inferred currency',async()=>{const id=await create();await q("UPDATE promotions SET type='fixed',value=25,scope='products',product_ids='[1,2]',min_order_amount=100 WHERE id=?",[id]);await create(other.merchantId);expect(await generateAIResponse(owner.merchantId,'ما العرض المتاح؟')).toBe('fixture reply');const prompt=String(calls.llm.mock.calls[0][0].messages[0].content),section=prompt.slice(prompt.indexOf('## تعريفات العروض الحالية'));expect(section).toContain('"scope":"products"');expect(section).toContain('"currency":null');expect(section).toContain('"minOrderAmount":100');expect(section).not.toMatch(/25 ريال|100 ريال/);expect(section).not.toContain('"merchantId":'+other.merchantId);expect(await q('SELECT view_count,click_count FROM promotions WHERE id=?',[id])).toEqual([{view_count:7,click_count:3}]);});
});
